project_id = "szbnqeydhhlpyevqkydr"

[functions.generate-part-image]
verify_jwt = false

[functions.admin-create-user]
verify_jwt = false

[functions.admin-update-user-permissions]
verify_jwt = false

[functions.admin-list-users]
verify_jwt = false

[functions.external-api]
verify_jwt = false

[functions.send-quote-request]
verify_jwt = false

[functions.submit-quote-response]
verify_jwt = false

[functions.send-purchase-order]
verify_jwt = false

[functions.confirm-purchase-order]
verify_jwt = false
