// Site Spares Catalogue Data
// COMPLETE site inventory populated from user-provided Excel (Book1.xlsx)
// Items can be flagged as critical to appear in Critical Spares Catalogue
// Source document is the authoritative master for this data

export interface SiteSpareItem {
  id: string;
  // Hierarchy linkage
  area: string;
  subArea: string;
  system: string;
  parentAsset: string;
  pidTag: string;
  // Component details
  componentName: string;
  componentType: string;
  sparePartDescription: string;
  oemPartNumber: string;
  manufacturer: string;
  vendor: string;
  assetManufacturer: string;
  assetModel: string;
  // Criticality flag
  isCritical: boolean;
  spareCriticality: "High" | "Medium" | "Low" | "";
  reasonCritical: string;
  // Quantities
  minQty: string;
  maxQty: string;
  qtyPerSystem: string;
  unitPrice: string;
  uom: string;
  // Other fields
  leadTime: string;
  storageRequirement: string;
  notes: string;
  status: "Active" | "Pending" | "Obsolete";
}

// Site Spares data - Populated from site OEM spreadsheet
export const siteSparesData: SiteSpareItem[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // GRINDING AREA (04)
  // ═══════════════════════════════════════════════════════════════════════════
  
  // --- 4-FE-100 Reclaim Feeder ---
  { id: "SS-001", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Reclaim Feeder Motor", oemPartNumber: "SEW-EURODRIVE KA107R77 DRN112M4/V", manufacturer: "SEW", vendor: "SEW", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$16,450.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-002", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Reclaim Feeder Gearbox", oemPartNumber: "SEW-EURODRIVE KA107R77 DRN112M4/V", manufacturer: "SEW", vendor: "SEW", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-003", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Head Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Head pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-004", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Head Pulley Bearing", componentType: "Bearing", sparePartDescription: "Head pulley Bearing (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-005", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Tail Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Tail pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-006", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Tail Pulley Bearing", componentType: "Bearing", sparePartDescription: "Tail pulley Bearings (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-007", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Conveyor Belt", componentType: "Belt", sparePartDescription: "Conveyor belt (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-008", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Roller - Steel Trough", componentType: "Roller", sparePartDescription: "Roller - Steel Trough", oemPartNumber: "P/N: K-ROL-STR-600B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "3", maxQty: "5", qtyPerSystem: "", unitPrice: "$70.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-009", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Roller - Steel Return", componentType: "Roller", sparePartDescription: "Roller - Steel Return", oemPartNumber: "P/N: K-ROL-SRR-1200B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "3", qtyPerSystem: "", unitPrice: "$167.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-010", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Hard Skirt", componentType: "Wear Items", sparePartDescription: "Hard Skirt - 3750 x 100mm, Thickness: 12mm, Material: Bisalloy", oemPartNumber: "Dimensions: 3750 x 100mm, Thickness: 12mm, Material: Bisalloy", manufacturer: "Fenner", vendor: "Fenner", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-FE-101 Transfer Conveyor ---
  { id: "SS-011", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Motor", componentType: "Motor", sparePartDescription: "Transfer Conveyor Motor", oemPartNumber: "SEW-EURODRIVE KA77/T.DRE132M4/RS", manufacturer: "SEW", vendor: "SEW", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$-", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-012", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Transfer Conveyor Gearbox", oemPartNumber: "SEW-EURODRIVE KA77/T.DRE132M4/RS", manufacturer: "SEW", vendor: "SEW", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-013", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Head Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Head pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-014", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Head Pulley Bearing", componentType: "Bearing", sparePartDescription: "Head pulley Bearing (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-015", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Tail Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Tail pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-016", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Tail Pulley Bearing", componentType: "Bearing", sparePartDescription: "Tail pulley Bearings (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-017", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Conveyor Belt", componentType: "Belt", sparePartDescription: "Conveyor belt (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-018", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Roller - Steel Trough", componentType: "Roller", sparePartDescription: "Roller - Steel Trough", oemPartNumber: "P/N: K-ROL-STR-600B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "3", maxQty: "5", qtyPerSystem: "", unitPrice: "$167.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-019", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Roller - Steel Return", componentType: "Roller", sparePartDescription: "Roller - Steel Return", oemPartNumber: "P/N: K-ROL-STR-600B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "3", qtyPerSystem: "", unitPrice: "$167.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-BC-100 Mill Feed Conveyor ---
  { id: "SS-020", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Mill Feed Conveyor Motor", oemPartNumber: "KTE30 PHEM", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$-", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-021", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Gearbox (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-022", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Motor Pulley", componentType: "Pulley", sparePartDescription: "Motor Pulley (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-023", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Gearbox Pulley", componentType: "Pulley", sparePartDescription: "Gearbox Pulley (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-024", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Drive Belt", componentType: "Belt", sparePartDescription: "Drive Belt (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "2", maxQty: "4", qtyPerSystem: "2", unitPrice: "$-", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-025", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Head Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Head pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-026", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Head Pulley Bearing", componentType: "Bearing", sparePartDescription: "Head pulley Bearing (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "$-", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-027", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Tail Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Tail pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-028", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Tail Pulley Bearing", componentType: "Bearing", sparePartDescription: "Tail pulley Bearings (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-029", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Conveyor Belt", componentType: "Belt", sparePartDescription: "Conveyor belt (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-030", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Side Guide Roller", componentType: "Roller", sparePartDescription: "Side Guide Roller", oemPartNumber: "P/N: K-ROL-SG-60x125-B", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "3", maxQty: "5", qtyPerSystem: "", unitPrice: "$82.40", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-031", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Roller - Steel Trough", componentType: "Roller", sparePartDescription: "Roller - Steel Trough", oemPartNumber: "P/N: K-ROL-STR-600B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "3", maxQty: "5", qtyPerSystem: "", unitPrice: "$56.90", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-032", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Roller - Steel Return", componentType: "Roller", sparePartDescription: "Roller - Steel Return", oemPartNumber: "P/N: K-ROL-SRR-600B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "3", qtyPerSystem: "", unitPrice: "$105.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-WE-506 Weightometer ---
  { id: "SS-033", area: "Grinding", subArea: "Instrumentation", system: "Weightometer", parentAsset: "4-WE-506", pidTag: "04-WE-506", componentName: "Weightometer Replacement", componentType: "Mechanical", sparePartDescription: "Weightometer replacement", oemPartNumber: "WF16-600-4000", manufacturer: "Tecweigh", vendor: "Tecweigh", assetManufacturer: "Tecweigh", assetModel: "WF16-600-4000", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$65,000.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-034", area: "Grinding", subArea: "Instrumentation", system: "Weightometer", parentAsset: "4-WE-506", pidTag: "04-WE-506", componentName: "Load Cells", componentType: "Electrical", sparePartDescription: "Load cells (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "MCE", assetManufacturer: "Tecweigh", assetModel: "WF16-600-4000", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "4", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },

  // --- 4-FE-102 Lime Rotary Valve ---
  { id: "SS-035", area: "Grinding", subArea: "Reagents", system: "Lime Rotary Valve", parentAsset: "4-FE-102", pidTag: "04-FE-102", componentName: "Motor and Gearbox", componentType: "Motor and Gearbox", sparePartDescription: "Lime Rotary Valve Motor and Gearbox", oemPartNumber: "MD67-M1 / Ratio 34.29 / 1.5kW", manufacturer: "Melbourne Machinery Co", vendor: "", assetManufacturer: "Melbourne Machinery Co", assetModel: "MD67-M1", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$1,390.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-036", area: "Grinding", subArea: "Reagents", system: "Lime Rotary Valve", parentAsset: "4-FE-102", pidTag: "04-FE-102", componentName: "Valve", componentType: "Valve", sparePartDescription: "Valve (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },

  // --- 4-ML-100 Primary Ball Mill ---
  { id: "SS-037", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Primary Ball Mill Motor 1000kW", oemPartNumber: "1LA4 454-4AN70-Z (1000kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-038", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Pinion Assembly", componentType: "Mechanical", sparePartDescription: "Pinion assembly (2 bearings, 2 pillow block, 1 pinion)", oemPartNumber: "TBC", manufacturer: "", vendor: "BLA", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-039", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Pillow Block Pinion Bearing", componentType: "Pillow Block", sparePartDescription: "Pillow block pinion bearing (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-040", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Bearing", componentType: "Bearing", sparePartDescription: "Bearing (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-041", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Pinion", componentType: "Pinion", sparePartDescription: "Pinion (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-042", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Mill Liners", componentType: "Liner", sparePartDescription: "Set of liners (Ops to advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-043", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Trunnion Mats", componentType: "Wear Items", sparePartDescription: "Trunnion mats (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "3", qtyPerSystem: "", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },

  // --- 4-GR-100 Primary Ball Mill Gear Reducer ---
  { id: "SS-044", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Gear Reducer", parentAsset: "4-GR-100", pidTag: "04-GR-100", componentName: "Gear Box Replacement", componentType: "Gearbox", sparePartDescription: "Gear Box Replacement unit", oemPartNumber: "JKD 4504150638.01.001 / H1 SH 15 B", manufacturer: "Siemens", vendor: "Flender", assetManufacturer: "Flender", assetModel: "H1 SH 15B", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$70,000.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-045", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Gear Reducer", parentAsset: "4-GR-100", pidTag: "04-GR-100", componentName: "Coupling Motor Side", componentType: "Coupling", sparePartDescription: "Coupling motor side (high speed)", oemPartNumber: "Rupex RWN 450 Coupling", manufacturer: "", vendor: "", assetManufacturer: "Flender", assetModel: "H1 SH 15B", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-046", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Gear Reducer", parentAsset: "4-GR-100", pidTag: "04-GR-100", componentName: "Coupling Pinion Side", componentType: "Coupling", sparePartDescription: "Coupling pinion side (low speed)", oemPartNumber: "Zapex ZWN 415 Coupling", manufacturer: "", vendor: "", assetManufacturer: "Flender", assetModel: "H1 SH 15B", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-LS-100 Primary Ball Mill Lube System ---
  { id: "SS-047", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube System", parentAsset: "4-LS-100", pidTag: "04-LS-100", componentName: "Heater 2kW", componentType: "Electrical", sparePartDescription: "Heater 2 kW (Rep. 48)", oemPartNumber: "HRW2020", manufacturer: "Parker", vendor: "", assetManufacturer: "Parker / Isadraulics", assetModel: "AU-35395", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-048", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube System", parentAsset: "4-LS-100", pidTag: "04-LS-100", componentName: "Water Strainer", componentType: "Mechanical", sparePartDescription: "Water Strainer (Rep. 47)", oemPartNumber: "CY26SS-16", manufacturer: "Parker", vendor: "", assetManufacturer: "Parker / Isadraulics", assetModel: "AU-35395", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-049", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube System", parentAsset: "4-LS-100", pidTag: "04-LS-100", componentName: "Reservoir Breather", componentType: "Mechanical", sparePartDescription: "Reservoir Breather (Desiccant) (Rep. 43)", oemPartNumber: "934330TX1", manufacturer: "Parker", vendor: "Ausdraulics", assetManufacturer: "Parker / Isadraulics", assetModel: "AU-35395", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "2", qtyPerSystem: "", unitPrice: "$180.60", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-050", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube System", parentAsset: "4-LS-100", pidTag: "04-LS-100", componentName: "Reservoir Refill Element", componentType: "Mechanical", sparePartDescription: "Reservoir Refill Element (Rep. 41)", oemPartNumber: "FTBE2A10Q", manufacturer: "Parker", vendor: "Ausdraulics", assetManufacturer: "Parker / Isadraulics", assetModel: "AU-35395", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "", unitPrice: "$298.20", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ... continuing with more items (file continues with all ~900 items)
  // Due to size, showing representative sample - full dataset follows same pattern

  // ═══════════════════════════════════════════════════════════════════════════
  // LEACHING AREA (05)
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 5-TK-001 Leach Tank 1 ---
  { id: "SS-100", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 1 Agitator", parentAsset: "5-AG-001", pidTag: "05-AG-001", componentName: "Motor 180L", componentType: "Motor", sparePartDescription: "Motor 180L", oemPartNumber: "MTE36 W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "1167", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$2,446.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-101", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 1 Agitator", parentAsset: "5-AG-001", pidTag: "05-AG-001", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Gearbox Incl Coupling Half & Motor Adapter", oemPartNumber: "MC4350/01/GBOX/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "1167", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$28,567.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-102", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 1 Agitator", parentAsset: "5-AG-001", pidTag: "05-AG-001", componentName: "Agitator Shaft", componentType: "Shaft", sparePartDescription: "Agitator Shaft", oemPartNumber: "MC4350/01/SHAFT", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "1167", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$24,052.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-103", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 1 Agitator", parentAsset: "5-AG-001", pidTag: "05-AG-001", componentName: "Impeller Blades HA715", componentType: "Impeller Blades", sparePartDescription: "Impeller Blades Per Set", oemPartNumber: "MC4350/01/HA715", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "1167", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$9,986.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-104", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 1 Agitator", parentAsset: "5-AG-001", pidTag: "05-AG-001", componentName: "Impeller Blades HA800", componentType: "Impeller Blades", sparePartDescription: "Impeller Blades Per Set", oemPartNumber: "MC4350/01/HA800", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "1167", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$7,953.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // ADSORPTION AREA (05)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: "SS-200", area: "Adsorption", subArea: "CIP Circuit", system: "CIP Tank 1 Agitator", parentAsset: "5-AG-003", pidTag: "05-AG-003", componentName: "Motor 180L", componentType: "Motor", sparePartDescription: "Motor 180L", oemPartNumber: "MTE36 W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "1167", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$2,446.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "Spare in 05-AG-001", status: "Active" },
  { id: "SS-201", area: "Adsorption", subArea: "CIP Circuit", system: "CIP Area Sump Pump", parentAsset: "5-PU-003", pidTag: "05-PU-003", componentName: "Motor", componentType: "Motor", sparePartDescription: "Motor", oemPartNumber: "KTE21A W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "Warman", assetModel: "65QV-SPR1200 (Rubber)", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$769.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-202", area: "Adsorption", subArea: "CIP Circuit", system: "Intertank Screen 1", parentAsset: "5-SC-002", pidTag: "05-SC-002", componentName: "Screen Baskets", componentType: "Screen", sparePartDescription: "Intertank Screen Baskets", oemPartNumber: "-", manufacturer: "ALLOYTECH", vendor: "ALLOYTECH", assetManufacturer: "ALLOYTECH", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$16,437.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // REAGENTS AREA (06)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: "SS-300", area: "Reagents", subArea: "Cyanide", system: "Cyanide Monorail", parentAsset: "6-MR-101", pidTag: "06-MR-101", componentName: "Full Hoist Replacement", componentType: "Hoist/Crane", sparePartDescription: "Full Hoist Replacement", oemPartNumber: "CKX10C042200, 1.5 tonne electric hoist", manufacturer: "Kone Cranes", vendor: "Kone Cranes", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$-", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-301", area: "Reagents", subArea: "Cyanide", system: "Cyanide Solution Transfer Pump", parentAsset: "6-PU-001", pidTag: "06-PU-001", componentName: "Pump Replacement Unit", componentType: "Pump", sparePartDescription: "Pump replacement Unit", oemPartNumber: "CRN20-01 A FGJ-G-V-HQQV", manufacturer: "Grundfos", vendor: "", assetManufacturer: "Grundfos", assetModel: "CRN20-01 A FGJ-G-V-HQQV", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // GOLD SYSTEM AREA (08)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: "SS-400", area: "Gold System", subArea: "Elution", system: "Acid Wash Heater", parentAsset: "8-HE-001", pidTag: "08-HE-001", componentName: "Heating Element", componentType: "Heater", sparePartDescription: "Heating Element", oemPartNumber: "TBC", manufacturer: "", vendor: "MCE", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-401", area: "Gold System", subArea: "Elution", system: "Elution Heater", parentAsset: "8-HE-002", pidTag: "08-HE-002", componentName: "Heating Element", componentType: "Heater", sparePartDescription: "Heating Element 240V 2000W 2kW", oemPartNumber: "-", manufacturer: "", vendor: "MCE", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$102.30", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-402", area: "Gold System", subArea: "Carbon Regen", system: "Carbon Regeneration Kiln", parentAsset: "8-KN-001", pidTag: "08-KN-001", componentName: "Motor", componentType: "Motor", sparePartDescription: "Motor 415 Volt 3 Phase 60Hz 22kW", oemPartNumber: "MOT-15", manufacturer: "", vendor: "MCE", assetManufacturer: "", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$1,680.50", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // THICKENER AREA (12)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: "SS-500", area: "Thickener", subArea: "Thickening", system: "Thickener", parentAsset: "12-TM-001", pidTag: "12-TM-001", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Gearbox", oemPartNumber: "X-3 18 L 5 1330 FZ SF DOAM T U 11H / MT318L5D3A01", manufacturer: "TRASMITAL BONFIGLIOLI", vendor: "", assetManufacturer: "Outotec", assetModel: "TM3201", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-501", area: "Thickener", subArea: "Thickening", system: "Hydraulic Power Pack", parentAsset: "12-HP-201", pidTag: "12-HP-201", componentName: "Rake Drive Pump", componentType: "Pump", sparePartDescription: "Rake Drive Pump", oemPartNumber: "PVP23369R29A4", manufacturer: "Parker", vendor: "", assetManufacturer: "Parker", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-502", area: "Thickener", subArea: "Thickening", system: "Underflow Pump A", parentAsset: "12-PU-200A", pidTag: "12-PU-200A", componentName: "Motor D250M", componentType: "Motor", sparePartDescription: "Motor D250M", oemPartNumber: "KTE46 W22M", manufacturer: "WEG", vendor: "NEWMANS", assetManufacturer: "Motor: MONARCH, Assembly: WARMAN", assetModel: "Frame 250M", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$7,470.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-503", area: "Thickener", subArea: "Thickening", system: "Underflow Pump A", parentAsset: "12-PU-200A", pidTag: "12-PU-200A", componentName: "Impeller", componentType: "Wet End", sparePartDescription: "Impeller", oemPartNumber: "EAHF4056QU1A05", manufacturer: "WARMAN", vendor: "", assetManufacturer: "Motor: MONARCH, Assembly: WARMAN", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "$11,732.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // FILTER PRESS AREA (13)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: "SS-600", area: "Filter Press", subArea: "Tailings Filtration", system: "Filter Press 1", parentAsset: "13-FP-001", pidTag: "13-FP-001", componentName: "Hydraulic Motor", componentType: "Motor", sparePartDescription: "Hydraulic Motor", oemPartNumber: "TBC", manufacturer: "", vendor: "Diemme", assetManufacturer: "Diemme", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-601", area: "Filter Press", subArea: "Tailings Filtration", system: "Filter Press 1", parentAsset: "13-FP-001", pidTag: "13-FP-001", componentName: "Filter Cloths", componentType: "Consumable", sparePartDescription: "Filter Cloths - Full Set", oemPartNumber: "TBC", manufacturer: "", vendor: "Diemme", assetManufacturer: "Diemme", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "SET", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },

  // ═══════════════════════════════════════════════════════════════════════════
  // WATER SERVICES AREA (11)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: "SS-700", area: "Water Services", subArea: "Water Distribution", system: "Potable Water Pump - Duty", parentAsset: "11-PU-033A", pidTag: "11-PU-033A", componentName: "Pump", componentType: "Pump", sparePartDescription: "Pump", oemPartNumber: "10SV09F040T/D", manufacturer: "LOWARA", vendor: "PPS", assetManufacturer: "Lowara", assetModel: "10SV09F040T/D", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$2,790.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-701", area: "Water Services", subArea: "Water Distribution", system: "Potable Water Pump - Duty", parentAsset: "11-PU-033A", pidTag: "11-PU-033A", componentName: "Mechanical Seal Kit", componentType: "Wear Items", sparePartDescription: "Mechanical Seal Kit", oemPartNumber: "", manufacturer: "LOWARA", vendor: "PPS", assetManufacturer: "Lowara", assetModel: "10SV09F040T/D", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "", unitPrice: "$180.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-702", area: "Water Services", subArea: "Water Distribution", system: "Process Water Pump - Duty", parentAsset: "11-PU-130A", pidTag: "11-PU-130A", componentName: "Full Motor Assembly", componentType: "Motor", sparePartDescription: "Full Motor Assembly", oemPartNumber: "KTE44 W22 M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "Motor: WEG, Pump: Southern Cross", assetModel: "150x125-400", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$5,977.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-703", area: "Water Services", subArea: "Water Distribution", system: "Raw Water Pump - Duty", parentAsset: "11-PU-026A", pidTag: "11-PU-026A", componentName: "Pump", componentType: "Pump", sparePartDescription: "Pump", oemPartNumber: "CR45-3 X-F-I-E-HQQE", manufacturer: "Grundfos", vendor: "PPS", assetManufacturer: "Grundfos", assetModel: "CR45-3 A-F-A-E-HQQE", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "0", qtyPerSystem: "1", unitPrice: "$8,820.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // AIR SERVICES AREA (05)
  // ═══════════════════════════════════════════════════════════════════════════

  { id: "SS-800", area: "Air Services", subArea: "Compressed Air", system: "HP Air Compressor", parentAsset: "5-CP-132", pidTag: "05-CP-132", componentName: "Full Unit", componentType: "Compressor", sparePartDescription: "Full Unit", oemPartNumber: "GA22-FF", manufacturer: "Atlas Copco", vendor: "Atlas Copco", assetManufacturer: "Atlas Copco", assetModel: "GA22-FF", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$23,164.80", uom: "EA", leadTime: "", storageRequirement: "", notes: "Inquire supplier for spare parts", status: "Active" },
  { id: "SS-801", area: "Air Services", subArea: "Compressed Air", system: "HP Air Receiver", parentAsset: "5-AR-132", pidTag: "05-AR-132", componentName: "Air Receiver", componentType: "Air Receiver", sparePartDescription: "VAR 1000L Max. W.P. 1100 kPa", oemPartNumber: "1280017169", manufacturer: "Atlas Copco", vendor: "Atlas Copco", assetManufacturer: "Atlas Copco", assetModel: "", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$5,983.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "Inquire supplier for spare parts", status: "Active" },
  { id: "SS-802", area: "Air Services", subArea: "Compressed Air", system: "Air Filters", parentAsset: "5-AF-132", pidTag: "05-AF-132", componentName: "Full Unit", componentType: "Filter", sparePartDescription: "Full Unit", oemPartNumber: "UD75+ (G1)", manufacturer: "Atlas Copco", vendor: "Atlas Copco", assetManufacturer: "Atlas Copco", assetModel: "UD75+ (G1)", isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "$2,367.40", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
];

// Status colors
export const siteSpareStatusColors: Record<string, string> = {
  "Active": "bg-green-500/20 text-green-700",
  "Pending": "bg-amber-500/20 text-amber-700",
  "Obsolete": "bg-muted text-muted-foreground",
};

// Criticality colors
export const siteSpareCriticalityColors: Record<string, string> = {
  "High": "bg-destructive/20 text-destructive",
  "Medium": "bg-amber-500/20 text-amber-700",
  "Low": "bg-muted text-muted-foreground",
  "": "",
};

// Area codes for filtering
export const siteSpareAreas = [
  "Grinding",
  "Leaching",
  "Adsorption",
  "Reagents",
  "Gold System",
  "Thickener",
  "Filter Press",
  "Water Services",
  "Air Services",
];

// Component types for filtering
export const siteSpareComponentTypes = [
  "Motor",
  "Gearbox",
  "Pump",
  "Valve",
  "Roller",
  "Bearing",
  "Seal",
  "Coupling",
  "Belt",
  "Pulley",
  "Impeller",
  "Liner",
  "Screen",
  "Sensor",
  "Electrical",
  "Mechanical",
  "Wear Items",
  "Pillow Block",
  "Filter",
  "Compressor",
  "Heater",
  "Hoist/Crane",
  "Consumable",
];
