// Site Spares Catalogue Data
// MASTER INVENTORY for the entire site - ALL spare parts (HIGH, MEDIUM, LOW priority)
// Critical Spares Catalogue filters from this master list (HIGH + MEDIUM only)
// Populated from site catalogue document - September 2022 version

export interface SiteSpareItem {
  id: string;
  // Hierarchy linkage - aligned with Critical Spares structure
  area: string;           // Area code e.g., "COM", "REC", "TAIL"
  areaLabel: string;      // Full area name e.g., "Comminution / Process"
  subArea: string;        // e.g., "Feed / Reclaim", "Grinding"
  system: string;         // e.g., "APN01 Apron Feeder"
  parentAsset: string;    // Legacy P&ID reference e.g., "4-FE-100"
  assetNumber: string;    // Modern asset number e.g., "APN01-GMR01"
  pidTag: string;         // P&ID tag e.g., "04-FE-100"
  // Component details
  componentName: string;
  componentType: string;
  sparePartDescription: string;
  oemPartNumber: string;
  manufacturer: string;
  vendor: string;
  assetManufacturer: string;
  assetModel: string;
  // Priority & Criticality
  priority: "HIGH" | "MEDIUM" | "LOW";
  priorityReason: string;
  reviewFlag: boolean;
  spareCriticality: "High" | "Medium" | "Low" | "";
  criticalitySource: "Confirmed" | "Assumed" | "";
  reasonCritical: string;
  // Quantities
  minQty: string;
  maxQty: string;
  qtyPerSystem: string;
  unitPrice: string;
  uom: string;
  // Other fields
  leadTime: string;
  storageRequirement: string;
  notes: string;
  confidence: "Low" | "Medium" | "High";
  status: "Provisional" | "Confirmed" | "TBC" | "Active" | "Pending" | "Obsolete";
}

// Priority colors for UI
export const priorityColors: Record<string, string> = {
  HIGH: "bg-destructive/20 text-destructive",
  MEDIUM: "bg-amber-500/20 text-amber-700",
  LOW: "bg-muted text-muted-foreground",
};

// Status colors
export const siteSpareStatusColors: Record<string, string> = {
  Active: "bg-green-500/20 text-green-700",
  Provisional: "bg-blue-500/20 text-blue-700",
  Confirmed: "bg-green-500/20 text-green-700",
  Pending: "bg-amber-500/20 text-amber-700",
  TBC: "bg-amber-500/20 text-amber-700",
  Obsolete: "bg-muted text-muted-foreground",
};

// Criticality source colors
export const criticalitySourceColors: Record<string, string> = {
  Confirmed: "bg-green-500/20 text-green-700",
  Assumed: "bg-amber-500/20 text-amber-700",
};

// Import critical spares data and transform to site spares format
import { sparesData } from "../critical-spares/sparesData";

// Transform critical spares to site spares format
const transformedCriticalSpares: SiteSpareItem[] = sparesData.map((item, index) => ({
  id: `SS-${String(index + 1).padStart(4, "0")}`,
  area: item.area,
  areaLabel: item.areaLabel,
  subArea: item.subArea,
  system: item.system,
  parentAsset: item.parentAsset,
  assetNumber: item.assetNumber,
  pidTag: item.pidTag,
  componentName: item.componentName,
  componentType: item.componentType,
  sparePartDescription: item.sparePartDescription,
  oemPartNumber: item.oemPartNumber,
  manufacturer: item.manufacturer,
  vendor: item.vendor,
  assetManufacturer: item.assetManufacturer,
  assetModel: item.assetModel,
  priority: item.spareCriticality === "High" ? "HIGH" as const : item.spareCriticality === "Medium" ? "MEDIUM" as const : "LOW" as const,
  priorityReason: item.reasonCritical,
  reviewFlag: false,
  spareCriticality: item.spareCriticality,
  criticalitySource: item.criticalitySource,
  reasonCritical: item.reasonCritical,
  minQty: item.minQty,
  maxQty: item.maxQty,
  qtyPerSystem: item.qtyPerSystem,
  unitPrice: item.unitPrice,
  uom: item.uom,
  leadTime: "",
  storageRequirement: "",
  notes: item.notes,
  confidence: item.confidence || "Medium",
  status: item.status,
}));

// ═══════════════════════════════════════════════════════════════════════════════════════
// SITE CATALOGUE DATA - Imported from Catalogue_Template_TCMG_220925-2.xlsx
// Priority assigned per criticality hierarchy definitions
// ═══════════════════════════════════════════════════════════════════════════════════════

const catalogueData: SiteSpareItem[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // SENSORS & INSTRUMENTATION (MEDIUM - reliability/throughput impact)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0001", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "30-LSH-0510", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "BC100 discharge chute blocked", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - process monitoring", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - process monitoring", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0002", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "30-FCV-0545", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Ball Mill Discharge Pump Box Water Addition Flow Control Valve Positioner", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - flow control", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - flow control", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0003", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "30-FIT-0521", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Ball Mill LP Lube Oil Flow", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Lube system monitoring - mill protection", reviewFlag: false, spareCriticality: "High", criticalitySource: "Assumed", reasonCritical: "Lube system monitoring - mill protection", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0004", area: "COM", areaLabel: "Comminution / Process", subArea: "Classification", system: "CYC01 Cyclone Cluster", parentAsset: "", assetNumber: "", pidTag: "30-PIT-0552", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Ball Mill cyclone pressure transmitter", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - pressure monitoring", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - pressure monitoring", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0005", area: "COM", areaLabel: "Comminution / Process", subArea: "Classification", system: "CYC01 Cyclone Cluster", parentAsset: "", assetNumber: "", pidTag: "30-FIT-0551", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Cyclone inlet flow", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - flow monitoring", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - flow monitoring", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0006", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "", assetNumber: "", pidTag: "60-AE-0933", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Leach tank 1 pH probe", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - pH monitoring", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - pH monitoring", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0007", area: "REC", areaLabel: "Gold Recovery", subArea: "Reagents", system: "REA01 Cyanide Mixing", parentAsset: "", assetNumber: "", pidTag: "60-LIT-0938", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Cyanide mixing tank level transmitter", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - level monitoring", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - level monitoring", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0008", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "ELU01 Elution Circuit", parentAsset: "", assetNumber: "", pidTag: "70-FSH-7528", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Elution heater flow high switch", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - safety switch", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - safety switch", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0009", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "ELU01 Elution Circuit", parentAsset: "", assetNumber: "", pidTag: "70-TT-7522", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Elution heater outlet temp tx", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - temperature monitoring", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - temperature monitoring", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0010", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "ELU01 Elution Circuit", parentAsset: "", assetNumber: "", pidTag: "70-TSHH-7523", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Elution heater outlet temp high switch", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - safety switch", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - safety switch", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0011", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "ELU01 Elution Circuit", parentAsset: "", assetNumber: "", pidTag: "70-PI-7510", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Acid wash column pressure indicator", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - pressure monitoring", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - pressure monitoring", minQty: "4", maxQty: "6", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0012", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "ELU01 Elution Circuit", parentAsset: "", assetNumber: "", pidTag: "70-TIC-7521", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Elution heater temperature controller", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - temperature control", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - temperature control", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0013", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "ELU01 Elution Circuit", parentAsset: "", assetNumber: "", pidTag: "70-PSHH-7501", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Eluate pump press high switch", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - safety switch", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - safety switch", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0014", area: "REC", areaLabel: "Gold Recovery", subArea: "Regeneration", system: "REG01 Regen Kiln", parentAsset: "", assetNumber: "", pidTag: "70-ZA-7565", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Regen kiln drum rotation switch", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - rotation monitoring", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - rotation monitoring", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0015", area: "REC", areaLabel: "Gold Recovery", subArea: "Regeneration", system: "REG01 Regen Kiln", parentAsset: "", assetNumber: "", pidTag: "70-LSLL-7576", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Regen carbon quench hopper LLS", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - level monitoring", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - level monitoring", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0016", area: "UTIL", areaLabel: "Utilities", subArea: "Water Services", system: "WSV01 Raw Water", parentAsset: "", assetNumber: "", pidTag: "xx-LIT-0716", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Water tank level TX", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - level monitoring", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - level monitoring", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0017", area: "TAIL", areaLabel: "Tailings", subArea: "Thickener", system: "THK01 Tailings Thickener", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Tailings Thickener Bed Mass", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Instrumentation - bed mass monitoring", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Instrumentation - bed mass monitoring", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0018", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "30-TIT-0537", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Ball Mill DE Trunnion Oil Reservoir Temperature", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Lube system monitoring - mill protection", reviewFlag: false, spareCriticality: "High", criticalitySource: "Assumed", reasonCritical: "Lube system monitoring - mill protection", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0019", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "30-WT-0506", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "Mill feed conveyor weightometer. Entire System.", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Instrumentation - production monitoring", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Instrumentation - production monitoring", minQty: "TBC", maxQty: "TBC", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // GEARBOXES (HIGH - long lead time, plant stoppage)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0020", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Gearbox Incl Coupling Half & Motor Adapter. Part No- MC4350/01/1167. Model- 1167 Design Speed- 28 rpm. Motor Adaptor- AM180. Coupling OD- 318mm", oemPartNumber: "MC4350/01/1167", manufacturer: "Mixtec", vendor: "Mixtec", assetManufacturer: "Mixtec", assetModel: "1167", priority: "HIGH", priorityReason: "Gearbox - long lead time, plant impact", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "1 is currently on its way to Mixtec for rebuild.", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // PLC & CONTROL SYSTEMS (HIGH - critical control modules)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0021", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE01 Main Switchboard", parentAsset: "", assetNumber: "", pidTag: "", componentName: "PLC", componentType: "PLC", sparePartDescription: "WEI1550550000. # UR20-FBC-EIP-V2 With DLR Support", oemPartNumber: "WEI1550550000", manufacturer: "Weidmuller", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "PLC - critical control module", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "PLC - critical control module", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0022", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE01 Main Switchboard", parentAsset: "", assetNumber: "", pidTag: "", componentName: "PLC", componentType: "PLC", sparePartDescription: "WEI2682170000. Unmanaged Ethernet Switch IE-SW-EL08-6TX-2SC, 6TX+2SC", oemPartNumber: "WEI2682170000", manufacturer: "Weidmuller", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Network switch - critical control", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Network switch - critical control", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0023", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE01 Main Switchboard", parentAsset: "", assetNumber: "", pidTag: "", componentName: "PLC", componentType: "PLC", sparePartDescription: "WEI1315200000. UR20-16DI-P Remote I/O 16DI", oemPartNumber: "WEI1315200000", manufacturer: "Weidmuller", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "PLC I/O - critical control module", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "PLC I/O - critical control module", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0024", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE01 Main Switchboard", parentAsset: "", assetNumber: "", pidTag: "", componentName: "PLC", componentType: "PLC", sparePartDescription: "WEI1315250000. Weidmuller UR20-16DO-P 16 point digital Output", oemPartNumber: "WEI1315250000", manufacturer: "Weidmuller", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "PLC I/O - critical control module", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "PLC I/O - critical control module", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0025", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE01 Main Switchboard", parentAsset: "", assetNumber: "", pidTag: "", componentName: "PLC", componentType: "PLC", sparePartDescription: "WEI1315620000. # UR20-4AI-UI-16 4 point analog input", oemPartNumber: "WEI1315620000", manufacturer: "Weidmuller", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "PLC I/O - critical control module", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "PLC I/O - critical control module", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0026", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE01 Main Switchboard", parentAsset: "", assetNumber: "", pidTag: "", componentName: "PLC", componentType: "PLC", sparePartDescription: "WEI1315680000.UR20-4AO-UI-16 4 point analog output", oemPartNumber: "WEI1315680000", manufacturer: "Weidmuller", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "PLC I/O - critical control module", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "PLC I/O - critical control module", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0027", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE01 Main Switchboard", parentAsset: "", assetNumber: "", pidTag: "", componentName: "PLC", componentType: "PLC", sparePartDescription: "WEI1315700000. UR20-4AI-RTD-DIAG", oemPartNumber: "WEI1315700000", manufacturer: "Weidmuller", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "PLC I/O - critical control module", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "PLC I/O - critical control module", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0028", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE01 Main Switchboard", parentAsset: "", assetNumber: "", pidTag: "", componentName: "PLC", componentType: "PLC", sparePartDescription: "WEI2466880000. Power Supply PRO TOP1 Switch-Mode 24V 10A 240W 1PH", oemPartNumber: "WEI2466880000", manufacturer: "Weidmuller", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Power supply - critical control", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Power supply - critical control", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // RELAYS & ELECTRICAL (MEDIUM - reliability impact)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0029", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "MCC01 Motor Control Centre", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Relay", componentType: "Relay", sparePartDescription: "PHO2900299. PLC-RPT- 24DC/21, Relay Module", oemPartNumber: "PHO2900299", manufacturer: "Phoenix", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Relay - electrical component", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Relay - electrical component", minQty: "2", maxQty: "6", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0030", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "MCC01 Motor Control Centre", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Relay", componentType: "Relay", sparePartDescription: "#NHP55340074110VDC. MINIATURE GP RELAY 7A 4CO 110VDC COIL W/PB+LED+MI", oemPartNumber: "NHP55340074110VDC", manufacturer: "NHP", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Relay - electrical component", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Relay - electrical component", minQty: "2", maxQty: "4", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // CIRCUIT BREAKERS & MOTOR STARTERS (MEDIUM)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0031", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "MCC01 Motor Control Centre", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Circuit Breaker", componentType: "Circuit Breaker", sparePartDescription: "SHNA9D11810. RCBO 240V 10A 10kA 1P DIN Rail 30mA IP20", oemPartNumber: "SHNA9D11810", manufacturer: "Schneider", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Circuit breaker - electrical protection", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Circuit breaker - electrical protection", minQty: "2", maxQty: "4", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0032", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "MCC01 Motor Control Centre", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Motor Starter", componentType: "Motor Starter", sparePartDescription: "SHNGV4P115B. Motor Circuit breaker TeSys GV4, TeSys GV4, 3P, 115A, Icu", oemPartNumber: "SHNGV4P115B", manufacturer: "Schneider", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Motor starter - motor protection", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Motor starter - motor protection", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0033", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "MCC01 Motor Control Centre", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Contactor", componentType: "Contactor", sparePartDescription: "SHNLC1D115BD. Contactor TeSys Deca 115A 3P 24VDC Screw", oemPartNumber: "SHNLC1D115BD", manufacturer: "Schneider", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Contactor - motor control", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Contactor - motor control", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // MILL LUBE SYSTEM (HIGH - critical for mill operation)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0034", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Breather", componentType: "Filter", sparePartDescription: "BREATHER TRICEPTOR SINGLE 934330TX1", oemPartNumber: "934330TX1", manufacturer: "Ausdraulics", vendor: "Ausdraulics", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Filter - lube system", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Filter - lube system", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0035", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "OIL LEVEL/ TEMPERATURE CONTROLLER SCLTSD-520-10-05", oemPartNumber: "SCLTSD-520-10-05", manufacturer: "Ausdraulics", vendor: "Ausdraulics", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Lube system controller - mill protection", reviewFlag: false, spareCriticality: "High", criticalitySource: "Assumed", reasonCritical: "Lube system controller - mill protection", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0036", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Sensor", componentType: "Sensor", sparePartDescription: "PRESSURE SENSOR AND SWITCH SCPSD-400-14-25", oemPartNumber: "SCPSD-400-14-25", manufacturer: "Ausdraulics", vendor: "Ausdraulics", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Lube system sensor - mill protection", reviewFlag: false, spareCriticality: "High", criticalitySource: "Assumed", reasonCritical: "Lube system sensor - mill protection", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0037", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump", sparePartDescription: "Gear Pump 28 cc/rev 3339111192", oemPartNumber: "3339111192", manufacturer: "Ausdraulics", vendor: "Ausdraulics", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Pump - lube system critical", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - lube system critical", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0038", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump", sparePartDescription: "Gear Pump 44 cc/rev 3339111486", oemPartNumber: "3339111486", manufacturer: "Ausdraulics", vendor: "Ausdraulics", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Pump - lube system critical", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - lube system critical", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0039", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump", sparePartDescription: "PUMP HP 3706030", oemPartNumber: "3706030", manufacturer: "Ausdraulics", vendor: "Ausdraulics", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Pump - HP lube system critical", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - HP lube system critical", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0040", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Filter", componentType: "Filter", sparePartDescription: "FILTER MEDIUM PRESSURE FILTREC D761G10AV", oemPartNumber: "D761G10AV", manufacturer: "Filtrec", vendor: "Ausdraulics", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Filter - lube system", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Filter - lube system", minQty: "4", maxQty: "6", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0041", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Filter", componentType: "Filter", sparePartDescription: "FILTER ELEMENT LP 937399Q", oemPartNumber: "937399Q", manufacturer: "Ausdraulics", vendor: "Ausdraulics", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Filter - lube system", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Filter - lube system", minQty: "4", maxQty: "6", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0042", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Valve", componentType: "Valve", sparePartDescription: "RELIEF VALVE HP RAH101S50V", oemPartNumber: "RAH101S50V", manufacturer: "Ausdraulics", vendor: "Ausdraulics", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Valve - lube system", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Valve - lube system", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // COMPRESSOR (MEDIUM - reliability impact)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0043", area: "UTIL", areaLabel: "Utilities", subArea: "Compressed Air", system: "CMP01 Main Compressor", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Kit", componentType: "Service Kit", sparePartDescription: "2901990815 KIT OIL SEPERATOR 18-30KW", oemPartNumber: "2901990815", manufacturer: "Atlas Copco", vendor: "Atlas Copco", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Service kit - compressor maintenance", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Service kit - compressor maintenance", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0044", area: "UTIL", areaLabel: "Utilities", subArea: "Compressed Air", system: "CMP01 Main Compressor", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Kit", componentType: "Service Kit", sparePartDescription: "2901990816 KIT FILTER AIR/OIL RIF", oemPartNumber: "2901990816", manufacturer: "Atlas Copco", vendor: "Atlas Copco", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Filter kit - compressor maintenance", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Filter kit - compressor maintenance", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0045", area: "UTIL", areaLabel: "Utilities", subArea: "Compressed Air", system: "CMP01 Main Compressor", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Kit", componentType: "Service Kit", sparePartDescription: "3002602191 PREVENTIVE MAINTENANCE KIT", oemPartNumber: "3002602191", manufacturer: "Atlas Copco", vendor: "Atlas Copco", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "PM kit - compressor maintenance", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "PM kit - compressor maintenance", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // BEARINGS (MEDIUM - reliability/throughput impact)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0046", area: "COM", areaLabel: "Comminution / Process", subArea: "Feed / Reclaim", system: "MFC01 Mill Feed Conveyor", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Bearing", componentType: "Bearing", sparePartDescription: "071004DOD BRG ROLLER PILLOW BLOCK UNIT COMPLETE DODGE 50MM", oemPartNumber: "071004DOD", manufacturer: "Dodge", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing - reliability component", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Bearing - reliability component", minQty: "2", maxQty: "4", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0047", area: "COM", areaLabel: "Comminution / Process", subArea: "Feed / Reclaim", system: "MFC01 Mill Feed Conveyor", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Bearing", componentType: "Bearing", sparePartDescription: "SNG517NTN BRG HSG NTN 2 BOLT SNG517 CORE D BASE ITEM NO: 10939566", oemPartNumber: "SNG517NTN", manufacturer: "NTN", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing - reliability component", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Bearing - reliability component", minQty: "2", maxQty: "4", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0048", area: "COM", areaLabel: "Comminution / Process", subArea: "Feed / Reclaim", system: "MFC01 Mill Feed Conveyor", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Bearing", componentType: "Bearing", sparePartDescription: "22217EAKD1C3NTN BRG SPH ROLLER TAPER 85X150X36MM C3 ITEM NO: 10651732", oemPartNumber: "22217EAKD1C3NTN", manufacturer: "NTN", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing - reliability component", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Bearing - reliability component", minQty: "2", maxQty: "4", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0049", area: "TAIL", areaLabel: "Tailings", subArea: "Filtration", system: "FLT01 Filter Press", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Bearing", componentType: "Bearing", sparePartDescription: "UC214NTN INSERT BALL BRG 70X125X74.6MM WIR ITEM NO: 10638008", oemPartNumber: "UC214NTN", manufacturer: "NTN", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing - reliability component", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Bearing - reliability component", minQty: "2", maxQty: "4", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // FLOC SYSTEM (MEDIUM)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0050", area: "TAIL", areaLabel: "Tailings", subArea: "Thickener", system: "THK01 Tailings Thickener", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Floc", componentType: "Floc Component", sparePartDescription: "#226000 100NB Dispersion Cylinder", oemPartNumber: "226000", manufacturer: "Delcad", vendor: "Delcad", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Floc system - thickener performance", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Floc system - thickener performance", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0051", area: "TAIL", areaLabel: "Tailings", subArea: "Thickener", system: "THK01 Tailings Thickener", parentAsset: "", assetNumber: "", pidTag: "", componentName: "PLC", componentType: "PLC", sparePartDescription: "#950140 Allen-Bradley Micrologix 1400 PLC", oemPartNumber: "950140", manufacturer: "Allen-Bradley", vendor: "Delcad", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "PLC - critical control module", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "PLC - critical control module", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // POWER STATION GENERATORS (HIGH)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0052", area: "UTIL", areaLabel: "Utilities", subArea: "Power", system: "GEN01 Power Station", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Circuit Breaker", componentType: "Circuit Breaker", sparePartDescription: "NS800 N 4P FIXED BASIC BREAKER with Micrologic 5.0", oemPartNumber: "NS800", manufacturer: "Schneider", vendor: "Cummings", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Main breaker - power critical", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Main breaker - power critical", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // GIRTH GEAR GREASE SYSTEM (HIGH)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0053", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "PLC", componentType: "PLC", sparePartDescription: "Micrologix 1400 Processor", oemPartNumber: "", manufacturer: "Allen-Bradley", vendor: "Fuchs", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "PLC - girth gear grease control", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "PLC - girth gear grease control", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0054", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Valve", componentType: "Valve", sparePartDescription: "R900561272 / 4WE6C6X/EG24N9K4 Directional Spool Valve", oemPartNumber: "R900561272", manufacturer: "Bosch Rexroth", vendor: "Ausdraulics", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Valve - girth gear grease system", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Valve - girth gear grease system", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // PUMPS - CYCLONE FEED (HIGH - plant stoppage)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0055", area: "COM", areaLabel: "Comminution / Process", subArea: "Classification", system: "CYC01 Cyclone Cluster", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump Wear Parts", sparePartDescription: "Impeller 8/6E-AH", oemPartNumber: "", manufacturer: "Warman", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Pump impeller - wear part", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Pump impeller - wear part", minQty: "2", maxQty: "4", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0056", area: "COM", areaLabel: "Comminution / Process", subArea: "Classification", system: "CYC01 Cyclone Cluster", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump Wear Parts", sparePartDescription: "Frame Plate Liner 8/6E-AH", oemPartNumber: "", manufacturer: "Warman", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Pump liner - wear part", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Pump liner - wear part", minQty: "2", maxQty: "4", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0057", area: "COM", areaLabel: "Comminution / Process", subArea: "Classification", system: "CYC01 Cyclone Cluster", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump Wear Parts", sparePartDescription: "Cover Plate Liner", oemPartNumber: "", manufacturer: "Warman", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Pump liner - wear part", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Pump liner - wear part", minQty: "2", maxQty: "4", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0058", area: "COM", areaLabel: "Comminution / Process", subArea: "Classification", system: "CYC01 Cyclone Cluster", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump Wear Parts", sparePartDescription: "Throat Bush", oemPartNumber: "", manufacturer: "Warman", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Pump throat bush - wear part", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Pump throat bush - wear part", minQty: "2", maxQty: "4", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // PUMPS - THICKENER UNDERFLOW (MEDIUM)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0059", area: "TAIL", areaLabel: "Tailings", subArea: "Thickener", system: "THK01 Tailings Thickener", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump Wear Parts", sparePartDescription: "KCPL-4ESRTL.NL56 KETO COVER PLATE LINER MULTIFIT 4E RUBBER", oemPartNumber: "KCPL-4ESRTL.NL56", manufacturer: "Keto", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Pump liner - wear part", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Pump liner - wear part", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0060", area: "TAIL", areaLabel: "Tailings", subArea: "Thickener", system: "THK01 Tailings Thickener", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump Wear Parts", sparePartDescription: "MISC KHEE-4E.UR01. IMP, HI EFF, 5VC, 4E, URETHANE", oemPartNumber: "KHEE-4E.UR01", manufacturer: "Keto", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Pump impeller - wear part", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Pump impeller - wear part", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // WATER SERVICES PUMPS (HIGH - process water critical)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0061", area: "UTIL", areaLabel: "Utilities", subArea: "Water Services", system: "WSV01 Raw Water", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump", sparePartDescription: "96500530 GRUNDFOS PUMP MULTISTAGE CRI20-7", oemPartNumber: "96500530", manufacturer: "Grundfos", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Pump - process water critical", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - process water critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0062", area: "UTIL", areaLabel: "Utilities", subArea: "Water Services", system: "WSV01 Raw Water", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Mech Seal", componentType: "Seal", sparePartDescription: "LWSPKL01AAE LOWARA MECH SEAL SV8-SV16", oemPartNumber: "LWSPKL01AAE", manufacturer: "Lowara", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Mechanical seal - pump maintenance", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Mechanical seal - pump maintenance", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // LUBRICANTS (MEDIUM - maintenance consumables)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0063", area: "UTIL", areaLabel: "Utilities", subArea: "Stores", system: "STR01 Lubricants", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Lube", componentType: "Lubricant", sparePartDescription: "RENOLIN CLP 220 1000L IBC", oemPartNumber: "", manufacturer: "Fuchs", vendor: "Fuchs", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Lubricant - maintenance consumable", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Lubricant - maintenance consumable", minQty: "1", maxQty: "2", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0064", area: "UTIL", areaLabel: "Utilities", subArea: "Stores", system: "STR01 Lubricants", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Lube", componentType: "Lubricant", sparePartDescription: "RENOLIN CLP 320 1000L IBC", oemPartNumber: "", manufacturer: "Fuchs", vendor: "Fuchs", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Lubricant - maintenance consumable", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Lubricant - maintenance consumable", minQty: "1", maxQty: "2", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0065", area: "UTIL", areaLabel: "Utilities", subArea: "Stores", system: "STR01 Lubricants", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Lube", componentType: "Lubricant", sparePartDescription: "RENOLIT XTB 2 450G CRT", oemPartNumber: "", manufacturer: "Fuchs", vendor: "Fuchs", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Grease - maintenance consumable", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Grease - maintenance consumable", minQty: "24", maxQty: "48", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // V-BELTS (MEDIUM - reliability components)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0066", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Belt", componentType: "Belt", sparePartDescription: "SPA1250GAT GATES SUPER HC WEDGE BELT ITEM NO: 10641194", oemPartNumber: "SPA1250GAT", manufacturer: "Gates", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "V-belt - reliability component", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "V-belt - reliability component", minQty: "4", maxQty: "8", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0067", area: "COM", areaLabel: "Comminution / Process", subArea: "Classification", system: "CYC01 Cyclone Cluster", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Belt", componentType: "Belt", sparePartDescription: "SPC2360GAT GATES SUPER HC WEDGE BELT ITEM NO: 10641442", oemPartNumber: "SPC2360GAT", manufacturer: "Gates", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "V-belt - cyclone pump drive", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "V-belt - cyclone pump drive", minQty: "8", maxQty: "16", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0068", area: "TAIL", areaLabel: "Tailings", subArea: "Pumping", system: "TLP01 Tails Pump", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Belt", componentType: "Belt", sparePartDescription: "SPC2650PGAT GATES-PREDATOR BELT ITEM NO: 10089770", oemPartNumber: "SPC2650PGAT", manufacturer: "Gates", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "V-belt - tails pump drive", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "V-belt - tails pump drive", minQty: "3", maxQty: "6", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // FILTER PRESS (HIGH - major equipment)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0069", area: "TAIL", areaLabel: "Tailings", subArea: "Filtration", system: "FLT01 Filter Press", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump", sparePartDescription: "PUMP DLT 1050-2H BARE SHAFT (Complete replacement Pump Excl Motor)", oemPartNumber: "", manufacturer: "Matec", vendor: "Matec", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Pump - filter press feed critical", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - filter press feed critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0070", area: "TAIL", areaLabel: "Tailings", subArea: "Filtration", system: "FLT01 Filter Press", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump", sparePartDescription: "IMPELLER ØF60 -100 Part No. CDA000151.02", oemPartNumber: "CDA000151.02", manufacturer: "Matec", vendor: "Matec", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Impeller - pump wear part", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Impeller - pump wear part", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0071", area: "TAIL", areaLabel: "Tailings", subArea: "Filtration", system: "FLT01 Filter Press", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Mech Seal", componentType: "Seal", sparePartDescription: "MECH. SEAL EMG1 G6 Ø70 SILICON CARBIDE Part No. TENUEMG1G6D70CSCS", oemPartNumber: "TENUEMG1G6D70CSCS", manufacturer: "Matec", vendor: "Matec", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Mechanical seal - pump maintenance", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Mechanical seal - pump maintenance", minQty: "2", maxQty: "4", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0072", area: "TAIL", areaLabel: "Tailings", subArea: "Filtration", system: "FLT01 Filter Press", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Filter", componentType: "Filter Cloth", sparePartDescription: "NS002-Filtration cloth 1500x2000", oemPartNumber: "NS002", manufacturer: "Matec", vendor: "Matec", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Filter cloth - consumable", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Filter cloth - consumable", minQty: "200", maxQty: "400", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0073", area: "TAIL", areaLabel: "Tailings", subArea: "Filtration", system: "FLT01 Filter Press", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Filter", componentType: "Filter Plate", sparePartDescription: "PIASMT152050TTFCROP -TT FC Plate CH 50 1500x2000", oemPartNumber: "", manufacturer: "Matec", vendor: "Matec", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Filter plate - critical component", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Filter plate - critical component", minQty: "2", maxQty: "5", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // MOTORS (HIGH - plant stoppage risk)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0074", area: "TAIL", areaLabel: "Tailings", subArea: "Thickener", system: "THK01 Tailings Thickener", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Motor", componentType: "Motor", sparePartDescription: "Monarch Motor, 75kW, 1485rpm, Frame- D250M 125.2A, Foot Mount. PN-KTE46 W22M", oemPartNumber: "KTE46 W22M", manufacturer: "Monarch", vendor: "Newmans Rewinding", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - thickener pump drive", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - thickener pump drive", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0075", area: "TAIL", areaLabel: "Tailings", subArea: "Filtration", system: "FLT01 Filter Press", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Motor", componentType: "Motor", sparePartDescription: "WEG motor, 200kW, 1485rpm, Frame- D315/SM, Foot Mount. PN- KTE204 W22M>VSD", oemPartNumber: "KTE204 W22M", manufacturer: "WEG", vendor: "Newmans Rewinding", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - filter press feed pump", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - filter press feed pump", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0076", area: "COM", areaLabel: "Comminution / Process", subArea: "Classification", system: "CYC01 Cyclone Cluster", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Motor", componentType: "Motor", sparePartDescription: "Weg Motor, 110kW, 1485rpm, Frame- 280S/M, 183A, Foot Mount. PN- KTE50 W22M.DOL", oemPartNumber: "KTE50 W22M", manufacturer: "WEG", vendor: "Newmans Rewinding", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - cyclone feed pump", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - cyclone feed pump", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0077", area: "UTIL", areaLabel: "Utilities", subArea: "Water Services", system: "WSV01 Raw Water", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Motor", componentType: "Motor", sparePartDescription: "WEG Motor, 55kW, 1480rpm, Frame- 250S/M, 93.4A, Foot Mount. PN- KTE44 W22M", oemPartNumber: "KTE44 W22M", manufacturer: "WEG", vendor: "Newmans Rewinding", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - process water pump", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - process water pump", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0078", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Motor", componentType: "Motor", sparePartDescription: "WEG Motor, 22kW, 1470rpm, Frame-180L, 38A Flange Mount. PN- MTE36 W22M", oemPartNumber: "MTE36 W22M", manufacturer: "WEG", vendor: "Newmans Rewinding", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - agitator drive", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - agitator drive", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0079", area: "TAIL", areaLabel: "Tailings", subArea: "Pumping", system: "TLP01 Tails Pump", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Motor", componentType: "Motor", sparePartDescription: "WEG Motor,110kW, 1485rpm, Frame- 280S/M, 183A, Foot Mount, KTE50 W22M.DOL", oemPartNumber: "KTE50 W22M", manufacturer: "WEG", vendor: "Newmans Rewinding", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - tails pump drive", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - tails pump drive", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // GOLD ROOM (HIGH - gold recovery critical)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0080", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "ELU01 Elution Circuit", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Gold Room", componentType: "Burner Component", sparePartDescription: "Control Box Siemens LOA24.171B2FB 230V50:60Hz", oemPartNumber: "LOA24.171B2FB", manufacturer: "Siemens", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Burner control - elution heater", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Burner control - elution heater", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0081", area: "REC", areaLabel: "Gold Recovery", subArea: "Electrowinning", system: "EW01 Electrowinning", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Gold Room", componentType: "Rectifier Component", sparePartDescription: "Regulation Board DSQ11", oemPartNumber: "DSQ11", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Rectifier board - electrowinning", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Rectifier board - electrowinning", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0082", area: "REC", areaLabel: "Gold Recovery", subArea: "Electrowinning", system: "EW01 Electrowinning", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Gold Room", componentType: "Rectifier Component", sparePartDescription: "Power Supply Board IGTR8x", oemPartNumber: "IGTR8x", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Power supply - electrowinning", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Power supply - electrowinning", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0083", area: "REC", areaLabel: "Gold Recovery", subArea: "Regeneration", system: "REG01 Regen Kiln", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Gold Room", componentType: "Motor", sparePartDescription: "DC Motors GSM750-3-24-71", oemPartNumber: "GSM750-3-24-71", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - regen kiln drive", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - regen kiln drive", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // RO PLANT (MEDIUM - water treatment)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0084", area: "UTIL", areaLabel: "Utilities", subArea: "Water Services", system: "RO01 RO Plant", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump", sparePartDescription: "96517212. PUMP GRUNDFOS CRN5-12.", oemPartNumber: "96517212", manufacturer: "Grundfos", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Pump - RO plant", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Pump - RO plant", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0085", area: "UTIL", areaLabel: "Utilities", subArea: "Water Services", system: "RO01 RO Plant", parentAsset: "", assetNumber: "", pidTag: "", componentName: "RO Plant", componentType: "Membrane", sparePartDescription: "RO Membrane Element", oemPartNumber: "", manufacturer: "Mork Water", vendor: "Mork Water", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "RO membrane - water treatment", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "RO membrane - water treatment", minQty: "2", maxQty: "4", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // VALVES (MEDIUM - process control)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0086", area: "TAIL", areaLabel: "Tailings", subArea: "Filtration", system: "FLT01 Filter Press", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Valve", componentType: "Valve", sparePartDescription: "DN200 CLARKSON SU10R KNIFE GATE VALVE with pneumatic actuator", oemPartNumber: "123330", manufacturer: "Clarkson", vendor: "KeyFlo", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Valve - filter press isolation", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Valve - filter press isolation", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0087", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "ELU01 Elution Circuit", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Valve", componentType: "Valve", sparePartDescription: "BVWNL100 100mm Lever Wafer Butterfly Valve 316 SS Disc, NBR Seat", oemPartNumber: "BVWNL100", manufacturer: "GWG", vendor: "GWG", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Valve - elution isolation", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Valve - elution isolation", minQty: "2", maxQty: "4", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0088", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "ELU01 Elution Circuit", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Valve", componentType: "Valve", sparePartDescription: "BVWNL150 150mm Lever Wafer Butterfly Valve 316 SS Disc, NBR Seat", oemPartNumber: "BVWNL150", manufacturer: "GWG", vendor: "GWG", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Valve - elution isolation", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Valve - elution isolation", minQty: "1", maxQty: "2", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // ELECTRICAL CONSUMABLES (LOW - readily available)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0089", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE02 Electrical Consumables", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Cable Tie", componentType: "Consumable", sparePartDescription: "MTLNCT-200/48B. Cable Tie Std Duty L200mmxW4.8mm Nylon 66 Black", oemPartNumber: "MTLNCT-200/48B", manufacturer: "MTL", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Consumable - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Consumable - readily available", minQty: "10", maxQty: "20", qtyPerSystem: "", unitPrice: "", uom: "PK", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0090", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE02 Electrical Consumables", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Tape", componentType: "Consumable", sparePartDescription: "WATPVCBLA. Elect Insulating Tape GP L20MxW18mmx0.18mm PVC Black", oemPartNumber: "WATPVCBLA", manufacturer: "WAT", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Consumable - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Consumable - readily available", minQty: "10", maxQty: "20", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0091", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE02 Electrical Consumables", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Gland", componentType: "Consumable", sparePartDescription: "CCG053501. Metal Cable Gland U/A GP M20 11-15mm w/L-Nut IP66/68 NPB", oemPartNumber: "CCG053501", manufacturer: "CCG", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Consumable - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Consumable - readily available", minQty: "5", maxQty: "20", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0092", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE02 Electrical Consumables", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Conduit", componentType: "Consumable", sparePartDescription: "TPRTRAABSC25. Rigid Conduit Medium Duty 25mm ABS", oemPartNumber: "TPRTRAABSC25", manufacturer: "TPR", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Consumable - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Consumable - readily available", minQty: "5", maxQty: "10", qtyPerSystem: "", unitPrice: "", uom: "LN", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0093", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE02 Electrical Consumables", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Terminal", componentType: "Consumable", sparePartDescription: "PHO3044076. Rail Terminal Block Screwed 2 Wire 0.14-4mm Grey PA", oemPartNumber: "PHO3044076", manufacturer: "Phoenix", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Consumable - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Consumable - readily available", minQty: "50", maxQty: "100", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0094", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE02 Electrical Consumables", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Crimp", componentType: "Consumable", sparePartDescription: "BOOT LACE PIN 2.5MM-GREY PKT 100", oemPartNumber: "", manufacturer: "", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Consumable - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Consumable - readily available", minQty: "1", maxQty: "4", qtyPerSystem: "", unitPrice: "", uom: "PK", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0095", area: "UTIL", areaLabel: "Utilities", subArea: "Electrical", system: "ELE02 Electrical Consumables", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Battery", componentType: "Consumable", sparePartDescription: "Industrial alkaline dry cell battery 1.5 Volt AA size", oemPartNumber: "", manufacturer: "", vendor: "MME", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Consumable - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Consumable - readily available", minQty: "1", maxQty: "2", qtyPerSystem: "", unitPrice: "", uom: "PK", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // POLY FITTINGS (LOW - readily available)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0096", area: "UTIL", areaLabel: "Utilities", subArea: "Piping", system: "PIP01 Poly Fittings", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Poly", componentType: "Fitting", sparePartDescription: "7010014 25mm Metric Coupling PlassonCompression", oemPartNumber: "7010014", manufacturer: "Plasson", vendor: "GWG", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Fitting - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Fitting - readily available", minQty: "20", maxQty: "40", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0097", area: "UTIL", areaLabel: "Utilities", subArea: "Piping", system: "PIP01 Poly Fittings", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Poly", componentType: "Fitting", sparePartDescription: "CME025 25mm Metric 90D Elbow Compression", oemPartNumber: "CME025", manufacturer: "Compression", vendor: "GWG", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Fitting - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Fitting - readily available", minQty: "10", maxQty: "20", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0098", area: "UTIL", areaLabel: "Utilities", subArea: "Piping", system: "PIP01 Poly Fittings", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Poly", componentType: "Fitting", sparePartDescription: "EFC11110 110mm SDR11 Coupling Electrofusion", oemPartNumber: "EFC11110", manufacturer: "Electrofusion", vendor: "GWG", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Fitting - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Fitting - readily available", minQty: "20", maxQty: "40", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0099", area: "UTIL", areaLabel: "Utilities", subArea: "Piping", system: "PIP01 Poly Fittings", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Flange", componentType: "Fitting", sparePartDescription: "110mm x 4\" Table E AS2129 Galvanised Backing Flange", oemPartNumber: "", manufacturer: "", vendor: "GWG", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Fitting - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Fitting - readily available", minQty: "10", maxQty: "20", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // HOSE FITTINGS (LOW - readily available)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0100", area: "UTIL", areaLabel: "Utilities", subArea: "Piping", system: "PIP02 Hose Fittings", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Minsup", componentType: "Fitting", sparePartDescription: "POWE21-000-006 COUPLING TYPE A HOSETAIL 10MM", oemPartNumber: "POWE21-000-006", manufacturer: "", vendor: "MIMS", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Fitting - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Fitting - readily available", minQty: "10", maxQty: "20", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0101", area: "UTIL", areaLabel: "Utilities", subArea: "Piping", system: "PIP02 Hose Fittings", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Minsup", componentType: "Fitting", sparePartDescription: "POWE21-008-000 TYPE A MINSUP SAFETY PIN", oemPartNumber: "POWE21-008-000", manufacturer: "", vendor: "MIMS", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Fitting - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Fitting - readily available", minQty: "50", maxQty: "100", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // POTABLE WATER (MEDIUM)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0102", area: "UTIL", areaLabel: "Utilities", subArea: "Water Services", system: "POT01 Potable Water", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Potable Water", componentType: "UV Component", sparePartDescription: "RES6 PURETEC RES6 ELECTRONIC REPLACEMENT BALLAST 240V", oemPartNumber: "RES6", manufacturer: "Puretec", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "UV system - potable water", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "UV system - potable water", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0103", area: "UTIL", areaLabel: "Utilities", subArea: "Water Services", system: "POT01 Potable Water", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Potable Water", componentType: "UV Component", sparePartDescription: "RL6 PURETEC HYBRID UV LAMP, SUITS G/P/R SERIES 520MM 4 PIN 46W", oemPartNumber: "RL6", manufacturer: "Puretec", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "UV lamp - potable water", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "UV lamp - potable water", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0104", area: "UTIL", areaLabel: "Utilities", subArea: "Water Services", system: "POT01 Potable Water", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Pump", sparePartDescription: "98507627 GRUNDFOS PUMP BOOSTER SELF-PRIMING CMB-SP 3-28", oemPartNumber: "98507627", manufacturer: "Grundfos", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Pump - potable water booster", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Pump - potable water booster", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // WEIGHTOMETER (HIGH - production monitoring)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0105", area: "COM", areaLabel: "Comminution / Process", subArea: "Feed / Reclaim", system: "MFC01 Mill Feed Conveyor", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Weightometer", componentType: "Instrumentation", sparePartDescription: "WP50 Weigh Processor (replaces WP20)", oemPartNumber: "WP50", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Instrumentation - production monitoring", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Instrumentation - production monitoring", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0106", area: "COM", areaLabel: "Comminution / Process", subArea: "Feed / Reclaim", system: "MFC01 Mill Feed Conveyor", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Weightometer", componentType: "Instrumentation", sparePartDescription: "SC500 Signal Conditioning Card", oemPartNumber: "SC500", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Instrumentation - production monitoring", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Instrumentation - production monitoring", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0107", area: "COM", areaLabel: "Comminution / Process", subArea: "Feed / Reclaim", system: "MFC01 Mill Feed Conveyor", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Weightometer", componentType: "Instrumentation", sparePartDescription: "75kg Load Cells. 30-WT-0506, WP20 (Integrator) GK2101S (Load Cells)", oemPartNumber: "", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Load cells - production monitoring", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Load cells - production monitoring", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // PUMP REBUILD KITS (MEDIUM)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0108", area: "COM", areaLabel: "Comminution / Process", subArea: "Classification", system: "CYC01 Cyclone Cluster", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Rebuild Kit", sparePartDescription: "8/6E7DKIT-PPS.8/6E REPAIR KIT CONTAINS PARTS AS PER SPREAD SHEET", oemPartNumber: "8/6E7DKIT-PPS", manufacturer: "Warman", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Pump rebuild kit - planned maintenance", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Pump rebuild kit - planned maintenance", minQty: "TBC", maxQty: "TBC", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0109", area: "TAIL", areaLabel: "Tailings", subArea: "Pumping", system: "TLP01 Tails Pump", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Rebuild Kit", sparePartDescription: "6/4D7DKIT-PPS 6/4D REPAIR KIT", oemPartNumber: "6/4D7DKIT-PPS", manufacturer: "Warman", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Pump rebuild kit - planned maintenance", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Pump rebuild kit - planned maintenance", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },
  { id: "CAT-0110", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Pump", componentType: "Rebuild Kit", sparePartDescription: "65QVR7DKIT-PPS. 65QVR REPAIR KIT", oemPartNumber: "65QVR7DKIT-PPS", manufacturer: "Warman", vendor: "PPS", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Pump rebuild kit - planned maintenance", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Pump rebuild kit - planned maintenance", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // AIR FITTINGS (LOW - readily available)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0111", area: "UTIL", areaLabel: "Utilities", subArea: "Compressed Air", system: "AIR01 Air Fittings", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Air", componentType: "Fitting", sparePartDescription: "8MM x 8MM JOINER P/N: KQ2H08-00A", oemPartNumber: "KQ2H08-00A", manufacturer: "SMC", vendor: "Keyflow", assetManufacturer: "", assetModel: "", priority: "LOW", priorityReason: "Fitting - readily available", reviewFlag: false, spareCriticality: "Low", criticalitySource: "Assumed", reasonCritical: "Fitting - readily available", minQty: "10", maxQty: "20", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0112", area: "UTIL", areaLabel: "Utilities", subArea: "Compressed Air", system: "AIR01 Air Fittings", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Regulator", componentType: "Regulator", sparePartDescription: "1/4\" SMC FILTER REGULATOR P/N: AW30K-02BDG-D", oemPartNumber: "AW30K-02BDG-D", manufacturer: "SMC", vendor: "Keyflow", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Filter regulator - pneumatic system", reviewFlag: false, spareCriticality: "Medium", criticalitySource: "Assumed", reasonCritical: "Filter regulator - pneumatic system", minQty: "1", maxQty: "2", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "Medium", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // SCREEN VIBRATING MOTORS (HIGH - process critical)
  // ═══════════════════════════════════════════════════════════════════════════
  { id: "CAT-0113", area: "TAIL", areaLabel: "Tailings", subArea: "Dewatering", system: "SCR02 Tails Screen", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Motor", componentType: "Motor", sparePartDescription: "URAS KEE 75-4 URAS Vibrator motor. 3 kW, FLA 5.7, 1445rpm", oemPartNumber: "KEE 75-4", manufacturer: "URAS", vendor: "Newmans Rewinding", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - screen vibrator", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - screen vibrator", minQty: "1", maxQty: "2", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
  { id: "CAT-0114", area: "REC", areaLabel: "Gold Recovery", subArea: "Carbon Transfer", system: "CTS01 Carbon Transfer Screen", parentAsset: "", assetNumber: "", pidTag: "", componentName: "Motor", componentType: "Motor", sparePartDescription: "URAS Motor,1.5kW. PN- KEE-34-4W", oemPartNumber: "KEE-34-4W", manufacturer: "URAS", vendor: "Newmans Rewinding", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - carbon transfer screen", reviewFlag: false, spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - carbon transfer screen", minQty: "1", maxQty: "2", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", confidence: "High", status: "Provisional" },
];

// Site Spares data - MASTER INVENTORY
// This is the source of truth for ALL site spares
// Merges Critical Spares + Site Catalogue data
export const siteSparesData: SiteSpareItem[] = [
  ...transformedCriticalSpares,
  ...catalogueData,
];

// Helper functions
export const getPriorityCounts = (): { high: number; medium: number; low: number } => {
  const high = siteSparesData.filter((item) => item.priority === "HIGH").length;
  const medium = siteSparesData.filter((item) => item.priority === "MEDIUM").length;
  const low = siteSparesData.filter((item) => item.priority === "LOW").length;
  return { high, medium, low };
};

// Get items flagged for review
export const getReviewItems = (): SiteSpareItem[] => {
  return siteSparesData.filter((item) => item.reviewFlag);
};

// Get critical items only (HIGH + MEDIUM) for Critical Spares Catalogue
export const getCriticalItems = (): SiteSpareItem[] => {
  return siteSparesData.filter((item) => item.priority === "HIGH" || item.priority === "MEDIUM");
};
