// Site Spares Catalogue Data
// COMPLETE site inventory populated from user-provided Excel (Book1-2.xlsx)
// Items classified by maintenance priority: HIGH (critical) or MEDIUM (semi-critical)
// This is a PRELIMINARY REGISTER pending updated P&IDs and plant walkdowns

export interface SiteSpareItem {
  id: string;
  // Hierarchy linkage
  area: string;
  subArea: string;
  system: string;
  parentAsset: string;
  pidTag: string;
  // Component details
  componentName: string;
  componentType: string;
  sparePartDescription: string;
  oemPartNumber: string;
  manufacturer: string;
  vendor: string;
  assetManufacturer: string;
  assetModel: string;
  // Priority classification
  priority: "HIGH" | "MEDIUM";
  priorityReason: string;
  reviewFlag: boolean; // True if criticality is unclear
  // Criticality flag (for critical spares register)
  isCritical: boolean;
  spareCriticality: "High" | "Medium" | "Low" | "";
  reasonCritical: string;
  // Quantities
  minQty: string;
  maxQty: string;
  qtyPerSystem: string;
  unitPrice: string;
  uom: string;
  // Other fields
  leadTime: string;
  storageRequirement: string;
  notes: string;
  status: "Active" | "Pending" | "Obsolete";
}

// Priority colors for UI
export const priorityColors: Record<string, string> = {
  HIGH: "bg-destructive/20 text-destructive",
  MEDIUM: "bg-amber-500/20 text-amber-700",
};

// Status colors
export const siteSpareStatusColors: Record<string, string> = {
  Active: "bg-green-500/20 text-green-700",
  Pending: "bg-amber-500/20 text-amber-700",
  Obsolete: "bg-muted text-muted-foreground",
};

// Helper function to determine priority based on component type
// HIGH: Motors, Gearboxes, Motor-gearbox assemblies, Process pumps, PLC hardware, critical instrumentation
// MEDIUM: Bearings, Seals, Rollers, Filters, Hoses, Non-process-critical valves
function determinePriority(
  type: string,
  description: string
): { priority: "HIGH" | "MEDIUM"; reason: string; reviewFlag: boolean } {
  const typeLower = type.toLowerCase();
  const descLower = description.toLowerCase();

  // HIGH PRIORITY items
  if (
    typeLower.includes("motor") ||
    typeLower === "motor and gearbox" ||
    descLower.includes("motor") && (descLower.includes("full") || descLower.includes("assembly"))
  ) {
    return { priority: "HIGH", reason: "Motor - plant stoppage risk", reviewFlag: false };
  }

  if (typeLower.includes("gearbox") || typeLower === "gear box") {
    return { priority: "HIGH", reason: "Gearbox - long lead time, plant impact", reviewFlag: false };
  }

  if (
    typeLower.includes("pump") &&
    (descLower.includes("full") ||
      descLower.includes("replacement") ||
      descLower.includes("pump unit") ||
      descLower.includes("pump and motor"))
  ) {
    return { priority: "HIGH", reason: "Process pump - critical to operations", reviewFlag: false };
  }

  if (typeLower === "pump" && !descLower.includes("seal") && !descLower.includes("kit")) {
    return { priority: "HIGH", reason: "Pump - process critical", reviewFlag: false };
  }

  if (typeLower.includes("plc") || descLower.includes("plc")) {
    return { priority: "HIGH", reason: "PLC - control system critical", reviewFlag: false };
  }

  if (typeLower.includes("rectifier") || descLower.includes("rectifier")) {
    return { priority: "HIGH", reason: "Critical instrumentation - electrowinning", reviewFlag: false };
  }

  if (typeLower.includes("burner") && descLower.includes("replacement")) {
    return { priority: "HIGH", reason: "Burner unit - elution critical", reviewFlag: false };
  }

  if (typeLower.includes("air cooler") && descLower.includes("replacement")) {
    return { priority: "HIGH", reason: "Air cooler - lube system critical", reviewFlag: false };
  }

  if (typeLower.includes("hoist") || typeLower.includes("crane")) {
    return { priority: "HIGH", reason: "Lifting equipment - safety/operations critical", reviewFlag: false };
  }

  if (descLower.includes("weightometer") && descLower.includes("replacement")) {
    return { priority: "HIGH", reason: "Instrumentation - production monitoring", reviewFlag: false };
  }

  if (typeLower.includes("agitator") && descLower.includes("shaft")) {
    return { priority: "HIGH", reason: "Agitator shaft - long lead time", reviewFlag: false };
  }

  // MEDIUM PRIORITY items (or unclear)
  if (
    typeLower.includes("bearing") ||
    typeLower.includes("pillow block")
  ) {
    return { priority: "MEDIUM", reason: "Bearing/pillow block - replaceable", reviewFlag: false };
  }

  if (typeLower.includes("seal") || descLower.includes("seal kit") || descLower.includes("o-ring")) {
    return { priority: "MEDIUM", reason: "Seal/O-ring - consumable", reviewFlag: false };
  }

  if (typeLower.includes("roller")) {
    return { priority: "MEDIUM", reason: "Roller - commonly stocked", reviewFlag: false };
  }

  if (typeLower.includes("filter") || typeLower.includes("screen")) {
    return { priority: "MEDIUM", reason: "Filter/screen - consumable/replaceable", reviewFlag: false };
  }

  if (typeLower.includes("belt") || typeLower.includes("belts")) {
    return { priority: "MEDIUM", reason: "Belt - consumable", reviewFlag: false };
  }

  if (typeLower.includes("valve") && !descLower.includes("rotary")) {
    return { priority: "MEDIUM", reason: "Valve - non-process-critical", reviewFlag: false };
  }

  if (typeLower.includes("coupling")) {
    return { priority: "MEDIUM", reason: "Coupling - replaceable", reviewFlag: false };
  }

  if (typeLower.includes("wear") || typeLower.includes("liner")) {
    return { priority: "MEDIUM", reason: "Wear item - consumable", reviewFlag: false };
  }

  if (typeLower.includes("gasket")) {
    return { priority: "MEDIUM", reason: "Gasket - consumable", reviewFlag: false };
  }

  if (typeLower.includes("impeller") && !descLower.includes("full")) {
    return { priority: "MEDIUM", reason: "Impeller - wet end component", reviewFlag: false };
  }

  if (typeLower.includes("wet end")) {
    return { priority: "MEDIUM", reason: "Wet end component - replaceable", reviewFlag: false };
  }

  if (typeLower.includes("cloth") || typeLower.includes("plates")) {
    return { priority: "MEDIUM", reason: "Filter press consumable", reviewFlag: false };
  }

  if (typeLower.includes("electrical") && !descLower.includes("plc") && !descLower.includes("rectifier")) {
    return { priority: "MEDIUM", reason: "Electrical component", reviewFlag: true };
  }

  if (typeLower.includes("mechanical") && !descLower.includes("pump") && !descLower.includes("motor")) {
    return { priority: "MEDIUM", reason: "Mechanical component", reviewFlag: true };
  }

  // Default to MEDIUM with review flag if unclear
  return { priority: "MEDIUM", reason: "Criticality unclear - flagged for review", reviewFlag: true };
}

// Site Spares data - Populated from user Excel (Book1-2.xlsx)
// All data is from the attached document - NO invented or assumed data
export const siteSparesData: SiteSpareItem[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // GRINDING AREA (04)
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 4-FE-100 Reclaim Feeder ---
  { id: "SS-001", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Reclaim Feeder Motor", oemPartNumber: "SEW-EURODRIVE KA107R77 DRN112M4/V", manufacturer: "SEW", vendor: "SEW", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$16,450.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-002", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Reclaim Feeder Gearbox", oemPartNumber: "SEW-EURODRIVE KA107R77 DRN112M4/V", manufacturer: "SEW", vendor: "SEW", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Gearbox - long lead time, plant impact", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-003", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Head Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Head pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-004", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Head Pulley Bearing", componentType: "Bearing", sparePartDescription: "Head pulley Bearing (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-005", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Tail Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Tail pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-006", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Tail Pulley Bearing", componentType: "Bearing", sparePartDescription: "Tail pulley Bearings (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-007", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Conveyor Belt", componentType: "Belt", sparePartDescription: "Conveyor belt (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Belt - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-008", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Roller - Steel Trough", componentType: "Roller", sparePartDescription: "Roller - Steel Trough", oemPartNumber: "P/N: K-ROL-STR-600B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Roller - commonly stocked", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "3", maxQty: "5", qtyPerSystem: "", unitPrice: "$70.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-009", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Roller - Steel Return", componentType: "Roller", sparePartDescription: "Roller - Steel Return", oemPartNumber: "P/N: K-ROL-SRR-1200B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Roller - commonly stocked", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "3", qtyPerSystem: "", unitPrice: "$167.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-010", area: "Grinding", subArea: "Materials Handling", system: "Reclaim Feeder", parentAsset: "4-FE-100", pidTag: "04-FE-100", componentName: "Hard Skirt", componentType: "Wear Items", sparePartDescription: "Hard Skirt - 3750 x 100mm, Thickness: 12mm, Material: Bisalloy", oemPartNumber: "Dimensions: 3750 x 100mm, Thickness: 12mm, Material: Bisalloy", manufacturer: "Fenner", vendor: "Fenner", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Wear item - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-FE-101 Transfer Conveyor ---
  { id: "SS-011", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Motor", componentType: "Motor", sparePartDescription: "Transfer Conveyor Motor", oemPartNumber: "SEW-EURODRIVE KA77/T.DRE132M4/RS", manufacturer: "SEW", vendor: "SEW", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$-", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-012", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Transfer Conveyor Gearbox", oemPartNumber: "SEW-EURODRIVE KA77/T.DRE132M4/RS", manufacturer: "SEW", vendor: "SEW", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Gearbox - long lead time, plant impact", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-013", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Head Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Head pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-014", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Head Pulley Bearing", componentType: "Bearing", sparePartDescription: "Head pulley Bearing (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-015", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Tail Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Tail pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-016", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Tail Pulley Bearing", componentType: "Bearing", sparePartDescription: "Tail pulley Bearings (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-017", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Conveyor Belt", componentType: "Belt", sparePartDescription: "Conveyor belt (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Belt - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-018", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Roller - Steel Trough", componentType: "Roller", sparePartDescription: "Roller - Steel Trough", oemPartNumber: "P/N: K-ROL-STR-600B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Roller - commonly stocked", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "3", maxQty: "5", qtyPerSystem: "", unitPrice: "$167.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-019", area: "Grinding", subArea: "Materials Handling", system: "Transfer Conveyor", parentAsset: "4-FE-101", pidTag: "04-FE-101", componentName: "Roller - Steel Return", componentType: "Roller", sparePartDescription: "Roller - Steel Return", oemPartNumber: "P/N: K-ROL-STR-600B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Roller - commonly stocked", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "3", qtyPerSystem: "", unitPrice: "$167.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-BC-100 Mill Feed Conveyor ---
  { id: "SS-020", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Mill Feed Conveyor Motor", oemPartNumber: "KTE30 PHEM", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$-", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-021", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Gearbox (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Gearbox - long lead time, plant impact", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-022", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Motor Pulley", componentType: "Pulley", sparePartDescription: "Motor Pulley (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Criticality unclear - flagged for review", reviewFlag: true, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-023", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Gearbox Pulley", componentType: "Pulley", sparePartDescription: "Gearbox Pulley (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Criticality unclear - flagged for review", reviewFlag: true, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-024", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Drive Belt", componentType: "Belt", sparePartDescription: "Drive Belt (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Belt - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "2", maxQty: "4", qtyPerSystem: "2", unitPrice: "$-", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-025", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Head Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Head pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-026", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Head Pulley Bearing", componentType: "Bearing", sparePartDescription: "Head pulley Bearing (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "$-", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-027", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Tail Pulley Pillow Block", componentType: "Pillow Block", sparePartDescription: "Tail pulley Pillow Block (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-028", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Tail Pulley Bearing", componentType: "Bearing", sparePartDescription: "Tail pulley Bearings (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "2", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-029", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Conveyor Belt", componentType: "Belt", sparePartDescription: "Conveyor belt (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Belt - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-030", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Side Guide Roller", componentType: "Roller", sparePartDescription: "Side Guide Roller", oemPartNumber: "P/N: K-ROL-SG-60x125-B", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Roller - commonly stocked", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "3", maxQty: "5", qtyPerSystem: "", unitPrice: "$82.40", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-031", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Roller - Steel Trough", componentType: "Roller", sparePartDescription: "Roller - Steel Trough", oemPartNumber: "P/N: K-ROL-STR-600B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Roller - commonly stocked", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "3", maxQty: "5", qtyPerSystem: "", unitPrice: "$56.90", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-032", area: "Grinding", subArea: "Materials Handling", system: "Mill Feed Conveyor", parentAsset: "4-BC-100", pidTag: "04-BC-100", componentName: "Roller - Steel Return", componentType: "Roller", sparePartDescription: "Roller - Steel Return", oemPartNumber: "P/N: K-ROL-SRR-600B25", manufacturer: "Britac", vendor: "Britac", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Roller - commonly stocked", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "3", qtyPerSystem: "", unitPrice: "$105.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-WE-506 Weightometer ---
  { id: "SS-033", area: "Grinding", subArea: "Instrumentation", system: "Weightometer", parentAsset: "4-WE-506", pidTag: "04-WE-506", componentName: "Weightometer Replacement", componentType: "Mechanical", sparePartDescription: "Weightometer replacement", oemPartNumber: "WF16-600-4000", manufacturer: "Tecweigh", vendor: "Tecweigh", assetManufacturer: "Tecweigh", assetModel: "WF16-600-4000", priority: "HIGH", priorityReason: "Instrumentation - production monitoring", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$65,000.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-034", area: "Grinding", subArea: "Instrumentation", system: "Weightometer", parentAsset: "4-WE-506", pidTag: "04-WE-506", componentName: "Load Cells", componentType: "Electrical", sparePartDescription: "Load cells (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "MCE", assetManufacturer: "Tecweigh", assetModel: "WF16-600-4000", priority: "MEDIUM", priorityReason: "Electrical component", reviewFlag: true, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "4", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },

  // --- 4-FE-102 Lime Rotary Valve ---
  { id: "SS-035", area: "Grinding", subArea: "Reagents", system: "Lime Rotary Valve", parentAsset: "4-FE-102", pidTag: "04-FE-102", componentName: "Motor and Gearbox", componentType: "Motor and Gearbox", sparePartDescription: "Lime Rotary Valve Motor and Gearbox", oemPartNumber: "MD67-M1 / Ratio 34.29 / 1.5kW", manufacturer: "Melbourne Machinery Co", vendor: "", assetManufacturer: "Melbourne Machinery Co", assetModel: "MD67-M1", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$1,390.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-036", area: "Grinding", subArea: "Reagents", system: "Lime Rotary Valve", parentAsset: "4-FE-102", pidTag: "04-FE-102", componentName: "Valve", componentType: "Valve", sparePartDescription: "Valve (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Valve - non-process-critical", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },

  // --- 4-ML-100 Primary Ball Mill ---
  { id: "SS-037", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Primary Ball Mill Motor 1000kW", oemPartNumber: "1LA4 454-4AN70-Z (1000kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-038", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Pinion Assembly", componentType: "Mechanical", sparePartDescription: "Pinion assembly (2 bearings, 2 pillow block, 1 pinion)", oemPartNumber: "TBC", manufacturer: "", vendor: "BLA", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Mill pinion - plant stoppage", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-039", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Pillow Block Pinion Bearing", componentType: "Pillow Block", sparePartDescription: "Pillow block pinion bearing (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-040", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Bearing", componentType: "Bearing", sparePartDescription: "Bearing (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-041", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Pinion", componentType: "Pinion", sparePartDescription: "Pinion (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Mill pinion - plant stoppage", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-042", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Mill Liners", componentType: "Liner", sparePartDescription: "Set of liners (Ops to advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Wear item - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },
  { id: "SS-043", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill", parentAsset: "4-ML-100", pidTag: "04-ML-100", componentName: "Trunnion Mats", componentType: "Wear Items", sparePartDescription: "Trunnion mats (Robbie please advise)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Wear item - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "3", qtyPerSystem: "", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Pending" },

  // --- 4-GR-100 Primary Ball Mill Gear Reducer ---
  { id: "SS-044", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Gear Reducer", parentAsset: "4-GR-100", pidTag: "04-GR-100", componentName: "Gear Box Replacement", componentType: "Gearbox", sparePartDescription: "Gear Box Replacement unit", oemPartNumber: "JKD 4504150638.01.001 / H1 SH 15 B", manufacturer: "Siemens", vendor: "Flender", assetManufacturer: "Flender", assetModel: "H1 SH 15B", priority: "HIGH", priorityReason: "Gearbox - long lead time, plant impact", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$70,000.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-045", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Gear Reducer", parentAsset: "4-GR-100", pidTag: "04-GR-100", componentName: "Coupling Motor Side", componentType: "Coupling", sparePartDescription: "Coupling motor side (high speed)", oemPartNumber: "Rupex RWN 450 Coupling", manufacturer: "", vendor: "", assetManufacturer: "Flender", assetModel: "H1 SH 15B", priority: "MEDIUM", priorityReason: "Coupling - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-046", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Gear Reducer", parentAsset: "4-GR-100", pidTag: "04-GR-100", componentName: "Coupling Pinion Side", componentType: "Coupling", sparePartDescription: "Coupling pinion side (low speed)", oemPartNumber: "Zapex ZWN 415 Coupling", manufacturer: "", vendor: "", assetManufacturer: "Flender", assetModel: "H1 SH 15B", priority: "MEDIUM", priorityReason: "Coupling - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-LS-100 Primary Ball Mill Lube System (Sample - many parts) ---
  { id: "SS-047", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube System", parentAsset: "4-LS-100", pidTag: "04-LS-100", componentName: "Heater 2kW", componentType: "Electrical", sparePartDescription: "Heater 2 kW (Rep. 48)", oemPartNumber: "HRW2020", manufacturer: "Parker", vendor: "", assetManufacturer: "Parker / Isadraulics", assetModel: "AU-35395", priority: "MEDIUM", priorityReason: "Electrical component", reviewFlag: true, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-048", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube System", parentAsset: "4-LS-100", pidTag: "04-LS-100", componentName: "Reservoir Breather", componentType: "Mechanical", sparePartDescription: "Reservoir Breather (Desiccant) (Rep. 43)", oemPartNumber: "934330TX1", manufacturer: "Parker", vendor: "Ausdraulics", assetManufacturer: "Parker / Isadraulics", assetModel: "AU-35395", priority: "MEDIUM", priorityReason: "Mechanical component", reviewFlag: true, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "2", qtyPerSystem: "", unitPrice: "$180.60", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-049", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube System", parentAsset: "4-LS-100", pidTag: "04-LS-100", componentName: "Oil Level/Temp Controller", componentType: "Electrical", sparePartDescription: "Oil Level / Temperature Controller (Rep. 40)", oemPartNumber: "SCLTSD-520-10-05", manufacturer: "Parker", vendor: "Ausdraulics", assetManufacturer: "Parker / Isadraulics", assetModel: "AU-35395", priority: "MEDIUM", priorityReason: "Electrical component", reviewFlag: true, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "", unitPrice: "$1,776.74", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-050", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube System", parentAsset: "4-LS-100", pidTag: "04-LS-100", componentName: "Pressure Sensor & Switch", componentType: "Electrical", sparePartDescription: "Pressure Sensor & Switch (Rep. 54)", oemPartNumber: "SCPSD-400-14-25", manufacturer: "Parker", vendor: "Ausdraulics", assetManufacturer: "Parker / Isadraulics", assetModel: "AU-35395", priority: "MEDIUM", priorityReason: "Electrical component", reviewFlag: true, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "", unitPrice: "$932.96", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-051", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube System", parentAsset: "4-LS-100", pidTag: "04-LS-100", componentName: "Relief Valve (Low Pressure)", componentType: "Valve", sparePartDescription: "Relief Valve (Low Pressure) (Rep. 11)", oemPartNumber: "RAH201S10", manufacturer: "Parker", vendor: "Ausdraulics", assetManufacturer: "Parker / Isadraulics", assetModel: "AU-35395", priority: "MEDIUM", priorityReason: "Valve - non-process-critical", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "", unitPrice: "$660.66", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-052", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube System", parentAsset: "4-LS-100", pidTag: "04-LS-100", componentName: "Filter Element (Medium Pressure)", componentType: "Filter", sparePartDescription: "Filter Element (Medium Pressure Filter) (Rep. 12)", oemPartNumber: "932667Q", manufacturer: "Parker", vendor: "Ausdraulics", assetManufacturer: "Parker / Isadraulics", assetModel: "AU-35395", priority: "MEDIUM", priorityReason: "Filter/screen - consumable/replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "2", maxQty: "4", qtyPerSystem: "", unitPrice: "$540.96", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-053", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube System", parentAsset: "4-LS-100", pidTag: "04-LS-100", componentName: "Filter Element (Low Pressure)", componentType: "Filter", sparePartDescription: "Filter Element (Low Pressure Filter) (Rep. 37)", oemPartNumber: "937399Q", manufacturer: "Parker", vendor: "Ausdraulics", assetManufacturer: "Parker / Isadraulics", assetModel: "AU-35395", priority: "MEDIUM", priorityReason: "Filter/screen - consumable/replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "2", maxQty: "4", qtyPerSystem: "", unitPrice: "$445.20", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-FA-006 Primary Ball Mill Lube Air Blast Oil Cooler ---
  { id: "SS-054", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube Air Blast Oil Cooler", parentAsset: "4-FA-006", pidTag: "04-FA-006", componentName: "Air Cooler Replacement Unit", componentType: "Mechanical", sparePartDescription: "AC-LN7S/1.0/F/A/BP3 Air cooler replacement unit inc. motor", oemPartNumber: "4028981", manufacturer: "HYDAC", vendor: "HYDAC", assetManufacturer: "Hydac", assetModel: "AC-LN7S/1.O/F/A/1/IBP3", priority: "HIGH", priorityReason: "Air cooler - lube system critical", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$5,664.20", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-055", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube Air Blast Oil Cooler", parentAsset: "4-FA-006", pidTag: "04-FA-006", componentName: "Motor", componentType: "Motor", sparePartDescription: "E-Motor IMB14 100M 3.0kW 4P 3Ph", oemPartNumber: "2355748", manufacturer: "HYDAC", vendor: "HYDAC", assetManufacturer: "Hydac", assetModel: "AC-LN7S/1.O/F/A/1/IBP3", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$2,187.70", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-PU-16 Primary Ball Mill Lube Cooling Recirculating Pump ---
  { id: "SS-056", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Lube Cooling Recirculating Pump", parentAsset: "4-PU-16", pidTag: "04-PU-016", componentName: "Full Pump Unit", componentType: "Pump", sparePartDescription: "Full Pump Unit", oemPartNumber: "3339111496", manufacturer: "Parker", vendor: "Powerdraulics", assetManufacturer: "Parker", assetModel: "3339111496", priority: "HIGH", priorityReason: "Pump - process critical", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$1,857.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-PU-100A/B Primary Ball Mill Low Pressure Lube Pump ---
  { id: "SS-057", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Low Pressure Lube Pump - Duty", parentAsset: "4-PU-100A", pidTag: "04-PU-100A", componentName: "Full Motor Assembly", componentType: "Motor", sparePartDescription: "Full Motor Assembly", oemPartNumber: "L194 W22", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "WEG / Parker", assetModel: "L194 W22", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$-", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-058", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Low Pressure Lube Pump - Duty", parentAsset: "4-PU-100A", pidTag: "04-PU-100A", componentName: "Pump", componentType: "Pump", sparePartDescription: "Pump", oemPartNumber: "3339111192", manufacturer: "PARKER", vendor: "Powerdraulics", assetManufacturer: "WEG / Parker", assetModel: "L194 W22", priority: "HIGH", priorityReason: "Pump - process critical", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$1,857.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-059", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill Low Pressure Lube Pump - Duty", parentAsset: "4-PU-100A", pidTag: "04-PU-100A", componentName: "Seals Kit", componentType: "Seal", sparePartDescription: "Seals Kit (Wet end)", oemPartNumber: "3911822071", manufacturer: "PARKER", vendor: "Powerdraulics", assetManufacturer: "WEG / Parker", assetModel: "L194 W22", priority: "MEDIUM", priorityReason: "Seal/O-ring - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$81.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-PU-101 Primary Ball Mill High Pressure Lube Pump ---
  { id: "SS-060", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill High Pressure Lube Pump", parentAsset: "4-PU-101", pidTag: "04-PU-101", componentName: "Motor", componentType: "Motor", sparePartDescription: "Motor", oemPartNumber: "L30 STDE2", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "WEG / Parker", assetModel: "L30 STDE2 / F11 010", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-061", area: "Grinding", subArea: "Comminution", system: "Primary Ball Mill High Pressure Lube Pump", parentAsset: "4-PU-101", pidTag: "04-PU-101", componentName: "Pump (High Pressure)", componentType: "Pump", sparePartDescription: "Pump (High Pressure) (Rep. 20)", oemPartNumber: "3706030", manufacturer: "PARKER", vendor: "Ausdraulics", assetManufacturer: "WEG / Parker", assetModel: "L30 STDE2 / F11 010", priority: "HIGH", priorityReason: "Pump - process critical", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$4,286.59", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 4-PU-102A/B Primary Mill Cyclone Feed Pump ---
  { id: "SS-062", area: "Grinding", subArea: "Comminution", system: "Primary Mill Cyclone Feed Pump - Duty", parentAsset: "4-PU-102A", pidTag: "04-PU-102A", componentName: "Full Motor Assembly", componentType: "Motor", sparePartDescription: "Full Motor Assembly", oemPartNumber: "KTE50 W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "WEG / Austral Pump", assetModel: "KTE50 W22M / 8/6 AH Metal", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$10,041.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-063", area: "Grinding", subArea: "Comminution", system: "Primary Mill Cyclone Feed Pump - Duty", parentAsset: "4-PU-102A", pidTag: "04-PU-102A", componentName: "Bearing", componentType: "Bearing", sparePartDescription: "Bearing", oemPartNumber: "EAM005M / 1811005", manufacturer: "M&Q Equipment", vendor: "CBC", assetManufacturer: "WEG / Austral Pump", assetModel: "KTE50 W22M / 8/6 AH Metal", priority: "MEDIUM", priorityReason: "Bearing/pillow block - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-064", area: "Grinding", subArea: "Comminution", system: "Primary Mill Cyclone Feed Pump - Duty", parentAsset: "4-PU-102A", pidTag: "04-PU-102A", componentName: "Belts", componentType: "Belt", sparePartDescription: "Belts", oemPartNumber: "SPC 2360", manufacturer: "", vendor: "CBC", assetManufacturer: "WEG / Austral Pump", assetModel: "KTE50 W22M / 8/6 AH Metal", priority: "MEDIUM", priorityReason: "Belt - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "2", maxQty: "4", qtyPerSystem: "4", unitPrice: "$43.40", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-065", area: "Grinding", subArea: "Comminution", system: "Primary Mill Cyclone Feed Pump - Duty", parentAsset: "4-PU-102A", pidTag: "04-PU-102A", componentName: "Impeller", componentType: "Wet End", sparePartDescription: "Impeller", oemPartNumber: "F6147A05", manufacturer: "Austral Pump", vendor: "PPS", assetManufacturer: "WEG / Austral Pump", assetModel: "KTE50 W22M / 8/6 AH Metal", priority: "MEDIUM", priorityReason: "Wet end component - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$13,459.66", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-066", area: "Grinding", subArea: "Comminution", system: "Primary Mill Cyclone Feed Pump - Duty", parentAsset: "4-PU-102A", pidTag: "04-PU-102A", componentName: "Volute Liner", componentType: "Wet End", sparePartDescription: "Volute Liner", oemPartNumber: "F6110A05", manufacturer: "Austral Pump", vendor: "PPS", assetManufacturer: "WEG / Austral Pump", assetModel: "KTE50 W22M / 8/6 AH Metal", priority: "MEDIUM", priorityReason: "Wet end component - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$14,659.66", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-067", area: "Grinding", subArea: "Comminution", system: "Primary Mill Cyclone Feed Pump - Duty", parentAsset: "4-PU-102A", pidTag: "04-PU-102A", componentName: "Throat Bush", componentType: "Wet End", sparePartDescription: "Throat Bush", oemPartNumber: "F6083A05", manufacturer: "Austral Pump", vendor: "PPS", assetManufacturer: "WEG / Austral Pump", assetModel: "KTE50 W22M / 8/6 AH Metal", priority: "MEDIUM", priorityReason: "Wet end component - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$6,893.22", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-068", area: "Grinding", subArea: "Comminution", system: "Primary Mill Cyclone Feed Pump - Duty", parentAsset: "4-PU-102A", pidTag: "04-PU-102A", componentName: "Shaft Sleeve", componentType: "Wet End", sparePartDescription: "Shaft Sleeve", oemPartNumber: "EAM076C21", manufacturer: "Austral Pump", vendor: "PPS", assetManufacturer: "WEG / Austral Pump", assetModel: "KTE50 W22M / 8/6 AH Metal", priority: "MEDIUM", priorityReason: "Wet end component - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "1", qtyPerSystem: "1", unitPrice: "$1,491.66", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // LEACHING AREA (05) - Agitators
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 5-AG-001 Leach Tank 1 Agitator ---
  { id: "SS-100", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 1 Agitator", parentAsset: "5-AG-001", pidTag: "05-AG-001", componentName: "Motor 180L", componentType: "Motor", sparePartDescription: "Motor 180L", oemPartNumber: "MTE36 W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "1167", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$2,446.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-101", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 1 Agitator", parentAsset: "5-AG-001", pidTag: "05-AG-001", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Gearbox Incl Coupling Half & Motor Adapter", oemPartNumber: "MC4350/01/GBOX/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "1167", priority: "HIGH", priorityReason: "Gearbox - long lead time, plant impact", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$28,567.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-102", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 1 Agitator", parentAsset: "5-AG-001", pidTag: "05-AG-001", componentName: "Agitator Shaft", componentType: "Shaft", sparePartDescription: "Agitator Shaft", oemPartNumber: "MC4350/01/SHAFT", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "1167", priority: "HIGH", priorityReason: "Agitator shaft - long lead time", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$24,052.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-103", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 1 Agitator", parentAsset: "5-AG-001", pidTag: "05-AG-001", componentName: "Impeller Blades HA715", componentType: "Impeller Blades", sparePartDescription: "Impeller Blades Per Set", oemPartNumber: "MC4350/01/HA715", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "1167", priority: "MEDIUM", priorityReason: "Impeller - wet end component", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$9,986.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-104", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 1 Agitator", parentAsset: "5-AG-001", pidTag: "05-AG-001", componentName: "Impeller Blades HA800", componentType: "Impeller Blades", sparePartDescription: "Impeller Blades Per Set", oemPartNumber: "MC4350/01/HA800", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "1167", priority: "MEDIUM", priorityReason: "Impeller - wet end component", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$7,953.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 5-AG-002 Leach Tank 2 Agitator (same spares as Tank 1) ---
  { id: "SS-105", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 2 Agitator", parentAsset: "5-AG-002", pidTag: "05-AG-002", componentName: "Motor 180L", componentType: "Motor", sparePartDescription: "Motor 180L", oemPartNumber: "MTE36 W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "1167", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$2,446.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "Spare in 05-AG-001", status: "Active" },
  { id: "SS-106", area: "Leaching", subArea: "CIL Circuit", system: "Leach Tank 2 Agitator", parentAsset: "5-AG-002", pidTag: "05-AG-002", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Gearbox Incl Coupling Half & Motor Adapter", oemPartNumber: "MC4350/01/GBOX/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "1167", priority: "HIGH", priorityReason: "Gearbox - long lead time, plant impact", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$28,567.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "Spare in 05-AG-001", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // ADSORPTION AREA (05) - CIP Circuit
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 5-AG-003 CIP Tank 1 Agitator ---
  { id: "SS-120", area: "Adsorption", subArea: "CIP Circuit", system: "CIP Tank 1 Agitator", parentAsset: "5-AG-003", pidTag: "05-AG-003", componentName: "Motor 180L", componentType: "Motor", sparePartDescription: "Motor 180L", oemPartNumber: "MTE36 W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "1167", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$2,446.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "Spare in 05-AG-001", status: "Active" },

  // --- 5-PU-003 CIP Area Sump Pump ---
  { id: "SS-121", area: "Adsorption", subArea: "CIP Circuit", system: "CIP Area Sump Pump", parentAsset: "5-PU-003", pidTag: "05-PU-003", componentName: "Motor", componentType: "Motor", sparePartDescription: "Motor", oemPartNumber: "KTE21A W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "Warman", assetModel: "65QV-SPR1200 (Rubber)", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$769.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-122", area: "Adsorption", subArea: "CIP Circuit", system: "CIP Area Sump Pump", parentAsset: "5-PU-003", pidTag: "05-PU-003", componentName: "Impeller/Flinger", componentType: "Wet End", sparePartDescription: "Impeller/Flinger", oemPartNumber: "QVR184S44", manufacturer: "WARMAN", vendor: "", assetManufacturer: "Warman", assetModel: "65QV-SPR1200 (Rubber)", priority: "MEDIUM", priorityReason: "Wet end component - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$384.89", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-123", area: "Adsorption", subArea: "CIP Circuit", system: "CIP Area Sump Pump", parentAsset: "5-PU-003", pidTag: "05-PU-003", componentName: "Belts", componentType: "Belt", sparePartDescription: "Belts", oemPartNumber: "SPA 1250", manufacturer: "", vendor: "CBC", assetManufacturer: "Warman", assetModel: "65QV-SPR1200 (Rubber)", priority: "MEDIUM", priorityReason: "Belt - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "2", unitPrice: "$12.90", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 5-SC-002 Intertank Screen ---
  { id: "SS-124", area: "Adsorption", subArea: "CIP Circuit", system: "Intertank Screen 1", parentAsset: "5-SC-002", pidTag: "05-SC-002", componentName: "Screen Baskets", componentType: "Screen", sparePartDescription: "Intertank Screen Baskets", oemPartNumber: "-", manufacturer: "ALLOYTECH", vendor: "ALLOYTECH", assetManufacturer: "ALLOYTECH", assetModel: "", priority: "MEDIUM", priorityReason: "Filter/screen - consumable/replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$16,437.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // REAGENTS AREA (06)
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 6-MR-101 Cyanide Monorail ---
  { id: "SS-200", area: "Reagents", subArea: "Cyanide", system: "Cyanide Monorail", parentAsset: "6-MR-101", pidTag: "06-MR-101", componentName: "Full Hoist Replacement", componentType: "Hoist/Crane", sparePartDescription: "Full Hoist Replacement", oemPartNumber: "CKX10C042200, 1.5 tonne electric hoist", manufacturer: "Kone Cranes", vendor: "Kone Cranes", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Lifting equipment - safety/operations critical", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$-", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 6-PU-001 Cyanide Solution Transfer Pump ---
  { id: "SS-201", area: "Reagents", subArea: "Cyanide", system: "Cyanide Solution Transfer Pump", parentAsset: "6-PU-001", pidTag: "06-PU-001", componentName: "Pump Replacement Unit", componentType: "Pump", sparePartDescription: "Pump replacement Unit", oemPartNumber: "CRN20-01 A FGJ-G-V-HQQV", manufacturer: "Grundfos", vendor: "", assetManufacturer: "Grundfos", assetModel: "CRN20-01 A FGJ-G-V-HQQV", priority: "HIGH", priorityReason: "Process pump - critical to operations", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "0", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-202", area: "Reagents", subArea: "Cyanide", system: "Cyanide Solution Transfer Pump", parentAsset: "6-PU-001", pidTag: "06-PU-001", componentName: "Gasket Kit", componentType: "Seal", sparePartDescription: "Gasket Kit", oemPartNumber: "6509610 (Pos# 37, 38a, 38, 60, 100, 441b)", manufacturer: "Grundfos", vendor: "", assetManufacturer: "Grundfos", assetModel: "CRN20-01 A FGJ-G-V-HQQV", priority: "MEDIUM", priorityReason: "Seal/O-ring - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$405.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-203", area: "Reagents", subArea: "Cyanide", system: "Cyanide Solution Transfer Pump", parentAsset: "6-PU-001", pidTag: "06-PU-001", componentName: "Shaft Seal Kit", componentType: "Seal", sparePartDescription: "Shaft Seal Kit", oemPartNumber: "96511845 (Pos# 105)", manufacturer: "Grundfos", vendor: "", assetManufacturer: "Grundfos", assetModel: "CRN20-01 A FGJ-G-V-HQQV", priority: "MEDIUM", priorityReason: "Seal/O-ring - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$469.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-204", area: "Reagents", subArea: "Cyanide", system: "Cyanide Solution Transfer Pump", parentAsset: "6-PU-001", pidTag: "06-PU-001", componentName: "Kit, Wear Parts", componentType: "Wear Items", sparePartDescription: "Kit, Wear Parts", oemPartNumber: "96511824", manufacturer: "Grundfos", vendor: "", assetManufacturer: "Grundfos", assetModel: "CRN20-01 A FGJ-G-V-HQQV", priority: "MEDIUM", priorityReason: "Wear item - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$682.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 6-PU-002/003 Cyanide Dosing Pumps ---
  { id: "SS-205", area: "Reagents", subArea: "Cyanide", system: "Cyanide Dosing Pump - Duty", parentAsset: "6-PU-002", pidTag: "06-PU-002", componentName: "Pump Replacement Unit", componentType: "Pump", sparePartDescription: "Pump replacement unit", oemPartNumber: "CRN5-4 A-FGJ-G-V-HQQV", manufacturer: "Grundfos", vendor: "", assetManufacturer: "Grundfos", assetModel: "CRN5-4 A-FGJ-G-V-HQQV", priority: "HIGH", priorityReason: "Process pump - critical to operations", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 6-AG-001 Cyanide Mixing Tank Agitator ---
  { id: "SS-210", area: "Reagents", subArea: "Cyanide", system: "Cyanide Mixing Tank Agitator", parentAsset: "6-AG-001", pidTag: "06-AG-001", componentName: "Motor W22M 0.75kW", componentType: "Motor", sparePartDescription: "Motor W22M 0.75kW", oemPartNumber: "MTE8 W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "1057", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$294.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-211", area: "Reagents", subArea: "Cyanide", system: "Cyanide Mixing Tank Agitator", parentAsset: "6-AG-001", pidTag: "06-AG-001", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Gearbox Incl Coupling Half & Motor Adapter", oemPartNumber: "MC4350/02/GBOX/1057", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "1057", priority: "HIGH", priorityReason: "Gearbox - long lead time, plant impact", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$1,987.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-212", area: "Reagents", subArea: "Cyanide", system: "Cyanide Mixing Tank Agitator", parentAsset: "6-AG-001", pidTag: "06-AG-001", componentName: "Agitator Shaft", componentType: "Shaft", sparePartDescription: "Agitator Shaft", oemPartNumber: "MC4350/02/SHAFT", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "1057", priority: "HIGH", priorityReason: "Agitator shaft - long lead time", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$2,760.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // GOLD SYSTEM AREA (08)
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 8-FL-001/002 Carbon Filters ---
  { id: "SS-300", area: "Gold System", subArea: "Elution", system: "Acid Wash Column Carbon Filters", parentAsset: "8-FL-001", pidTag: "08-FL-001", componentName: "Acid Column Inlet/Outlet Screen", componentType: "Filter", sparePartDescription: "Acid Column Inlet/Outlet Screen", oemPartNumber: "-", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "ALLOYTECH", assetModel: "", priority: "MEDIUM", priorityReason: "Filter/screen - consumable/replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "4", maxQty: "8", qtyPerSystem: "4", unitPrice: "$729.68", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-301", area: "Gold System", subArea: "Elution", system: "Elution Column Carbon Filters", parentAsset: "8-FL-002", pidTag: "08-FL-002", componentName: "Elution Column Inlet/Outlet Screen", componentType: "Filter", sparePartDescription: "Elution Column Inlet/Outlet Screen", oemPartNumber: "-", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "ALLOYTECH", assetModel: "", priority: "MEDIUM", priorityReason: "Filter/screen - consumable/replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "4", maxQty: "8", qtyPerSystem: "4", unitPrice: "$2,197.65", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 8-PU-003 HCL Acid Dosing Pump ---
  { id: "SS-302", area: "Gold System", subArea: "Elution", system: "HCL Acid Dosing Pump", parentAsset: "8-PU-003", pidTag: "08-PU-003", componentName: "Exchange Spare Pump", componentType: "Pump", sparePartDescription: "Exchange Spare Pump", oemPartNumber: "3376.08 AP 01", manufacturer: "Verderair", vendor: "MCE", assetManufacturer: "VerderAir", assetModel: "VA25", priority: "HIGH", priorityReason: "Process pump - critical to operations", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$6,367.55", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-303", area: "Gold System", subArea: "Elution", system: "HCL Acid Dosing Pump", parentAsset: "8-PU-003", pidTag: "08-PU-003", componentName: "Service Kit", componentType: "Seal", sparePartDescription: "Service Kit VA25 Poly/Stanoprere", oemPartNumber: "3376.08 AP 03", manufacturer: "Verderair", vendor: "MCE", assetManufacturer: "VerderAir", assetModel: "VA25", priority: "MEDIUM", priorityReason: "Seal/O-ring - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$1,481.20", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 8-PU-001 Eluate Pump ---
  { id: "SS-304", area: "Gold System", subArea: "Elution", system: "Eluate Pump", parentAsset: "8-PU-001", pidTag: "08-PU-001", componentName: "Pump Replacement Unit", componentType: "Pump", sparePartDescription: "Pump replacement unit", oemPartNumber: "Grundfos CRI20-07 A-FGJ-I-E-HQQE", manufacturer: "Grundfos", vendor: "", assetManufacturer: "Grundfos", assetModel: "CRI20-07 A-FGJ-I-E-HQQE", priority: "HIGH", priorityReason: "Process pump - critical to operations", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$5,630.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 8-BU-001 Eluate Heater Burner ---
  { id: "SS-305", area: "Gold System", subArea: "Elution", system: "Eluate Heater Burner", parentAsset: "8-BU-001", pidTag: "08-BU-001", componentName: "Burner Replacement Unit", componentType: "Burner", sparePartDescription: "Burner replacement unit", oemPartNumber: "GX 5/2 TL", manufacturer: "FBR", vendor: "BoilerTronix", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Burner unit - elution critical", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$2,554.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-306", area: "Gold System", subArea: "Elution", system: "Eluate Heater Burner", parentAsset: "8-BU-001", pidTag: "08-BU-001", componentName: "Motor Simel", componentType: "Motor", sparePartDescription: "Motor Simel XD6-208-32-2P 450W 230V-50:60Hz", oemPartNumber: "158122", manufacturer: "", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$1,509.38", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-307", area: "Gold System", subArea: "Elution", system: "Eluate Heater Burner", parentAsset: "8-BU-001", pidTag: "08-BU-001", componentName: "Control Box", componentType: "Electrical", sparePartDescription: "Control Box Siemens LOA24.171B2FB 230V50:60Hz", oemPartNumber: "101010_2", manufacturer: "", vendor: "MCE", assetManufacturer: "", assetModel: "", priority: "MEDIUM", priorityReason: "Electrical component", reviewFlag: true, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "0", qtyPerSystem: "1", unitPrice: "$959.10", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 8-RC-001 Electrowinning Cell Rectifier ---
  { id: "SS-308", area: "Gold System", subArea: "Electrowinning", system: "Electrowinning Cell Rectifier", parentAsset: "8-RC-001", pidTag: "08-RC-001", componentName: "RC Chain", componentType: "Electrical", sparePartDescription: "RC Chain 27R 15nK, 15V", oemPartNumber: "EB00000011", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "MCE", assetModel: "pe3000-6", priority: "HIGH", priorityReason: "Critical instrumentation - electrowinning", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "2", maxQty: "4", qtyPerSystem: "4", unitPrice: "$92.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm quantities with Ops", status: "Active" },
  { id: "SS-309", area: "Gold System", subArea: "Electrowinning", system: "Electrowinning Cell Rectifier", parentAsset: "8-RC-001", pidTag: "08-RC-001", componentName: "Mains Filter Board", componentType: "Electrical", sparePartDescription: "Mains Filter Board NK9-9 460V", oemPartNumber: "EB00000076", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "MCE", assetModel: "pe3000-6", priority: "HIGH", priorityReason: "Critical instrumentation - electrowinning", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$1,058.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm quantities with Ops", status: "Active" },
  { id: "SS-310", area: "Gold System", subArea: "Electrowinning", system: "Electrowinning Cell Rectifier", parentAsset: "8-RC-001", pidTag: "08-RC-001", componentName: "Regulation Board", componentType: "Electrical", sparePartDescription: "Regulation Board DSQ117", oemPartNumber: "EB00001299", manufacturer: "MCE", vendor: "MCE", assetManufacturer: "MCE", assetModel: "pe3000-6", priority: "HIGH", priorityReason: "Critical instrumentation - electrowinning", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$6,382.50", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm quantities with Ops", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // THICKENER AREA (12)
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 12-TH-101 Thickener ---
  { id: "SS-400", area: "Thickener", subArea: "Tailings", system: "Thickener", parentAsset: "12-TH-101", pidTag: "12-TH-101", componentName: "Motor 160M", componentType: "Motor", sparePartDescription: "Motor 160M", oemPartNumber: "MTE24 W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "Westech", assetModel: "12TH1C1C0000004-D22A", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$1,541.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-401", area: "Thickener", subArea: "Tailings", system: "Thickener", parentAsset: "12-TH-101", pidTag: "12-TH-101", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Thickener Gearbox", oemPartNumber: "12TH1C1C0000004-D22A", manufacturer: "Westech", vendor: "", assetManufacturer: "Westech", assetModel: "12TH1C1C0000004-D22A", priority: "HIGH", priorityReason: "Gearbox - long lead time, plant impact", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 12-PU-101A/B Thickener Underflow Pump ---
  { id: "SS-402", area: "Thickener", subArea: "Tailings", system: "Thickener Underflow Pump - Duty", parentAsset: "12-PU-101A", pidTag: "12-PU-101A", componentName: "Full Motor Assembly", componentType: "Motor", sparePartDescription: "Full Motor Assembly", oemPartNumber: "KTE36 W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "WEG / Austral Pump", assetModel: "KTE36 W22M / 6/4 DAH Metal", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$2,446.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-403", area: "Thickener", subArea: "Tailings", system: "Thickener Underflow Pump - Duty", parentAsset: "12-PU-101A", pidTag: "12-PU-101A", componentName: "Impeller", componentType: "Wet End", sparePartDescription: "Impeller", oemPartNumber: "D4147A05", manufacturer: "Austral Pump", vendor: "PPS", assetManufacturer: "WEG / Austral Pump", assetModel: "KTE36 W22M / 6/4 DAH Metal", priority: "MEDIUM", priorityReason: "Wet end component - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$5,665.11", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-404", area: "Thickener", subArea: "Tailings", system: "Thickener Underflow Pump - Duty", parentAsset: "12-PU-101A", pidTag: "12-PU-101A", componentName: "Volute Liner", componentType: "Wet End", sparePartDescription: "Volute Liner", oemPartNumber: "D4110A05", manufacturer: "Austral Pump", vendor: "PPS", assetManufacturer: "WEG / Austral Pump", assetModel: "KTE36 W22M / 6/4 DAH Metal", priority: "MEDIUM", priorityReason: "Wet end component - replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$7,379.89", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // FILTER PRESS AREA (13)
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 13-FP-101 Filter Press 1 ---
  { id: "SS-500", area: "Filter Press", subArea: "Tailings Filtration", system: "Filter Press 1", parentAsset: "13-FP-101", pidTag: "13-FP-101", componentName: "PLC - Pre Programmed", componentType: "Electrical", sparePartDescription: "PLC - PRE PROGRAMMED", oemPartNumber: "TBA", manufacturer: "MATEC", vendor: "MATEC", assetManufacturer: "MATEC INDUSTRIES", assetModel: "", priority: "HIGH", priorityReason: "PLC - control system critical", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm qty with Matec", status: "Active" },
  { id: "SS-501", area: "Filter Press", subArea: "Tailings Filtration", system: "Filter Press 1", parentAsset: "13-FP-101", pidTag: "13-FP-101", componentName: "Touchscreen Programmed", componentType: "Electrical", sparePartDescription: "TOUCHSCREEN PROGRAMED", oemPartNumber: "EMRCK2711PT12W21D8S", manufacturer: "MATEC", vendor: "MATEC", assetManufacturer: "MATEC INDUSTRIES", assetModel: "", priority: "HIGH", priorityReason: "PLC - control system critical", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm qty with Matec", status: "Active" },
  { id: "SS-502", area: "Filter Press", subArea: "Tailings Filtration", system: "Filter Press 1", parentAsset: "13-FP-101", pidTag: "13-FP-101", componentName: "Filter Plate (FAN)", componentType: "Mechanical", sparePartDescription: "PLATE MATEC 1500x2000 CH35 FAN FC REC RU", oemPartNumber: "PIASMT152035FAFCROP", manufacturer: "MATEC", vendor: "MATEC", assetManufacturer: "MATEC INDUSTRIES", assetModel: "", priority: "MEDIUM", priorityReason: "Mechanical component", reviewFlag: true, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "2", qtyPerSystem: "2", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm qty with Matec", status: "Active" },
  { id: "SS-503", area: "Filter Press", subArea: "Tailings Filtration", system: "Filter Press 1", parentAsset: "13-FP-101", pidTag: "13-FP-101", componentName: "Filter Plate (INT)", componentType: "Mechanical", sparePartDescription: "PLATE MATEC 1500x2000 CH35 INT FC REC RU", oemPartNumber: "PIASMT152035INFCROP", manufacturer: "MATEC", vendor: "MATEC", assetManufacturer: "MATEC INDUSTRIES", assetModel: "", priority: "MEDIUM", priorityReason: "Mechanical component", reviewFlag: true, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "2", maxQty: "5", qtyPerSystem: "5", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm qty with Matec", status: "Active" },
  { id: "SS-504", area: "Filter Press", subArea: "Tailings Filtration", system: "Filter Press 1", parentAsset: "13-FP-101", pidTag: "13-FP-101", componentName: "Filter Cloth", componentType: "Cloth", sparePartDescription: "MATEC CLOTH 1500X2000 FIS FC OPEN NS002", oemPartNumber: "TELAMT1500X2000FICEOPNS", manufacturer: "MATEC", vendor: "MATEC", assetManufacturer: "MATEC INDUSTRIES", assetModel: "", priority: "MEDIUM", priorityReason: "Filter press consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "4", maxQty: "8", qtyPerSystem: "8", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm qty with Matec", status: "Active" },
  { id: "SS-505", area: "Filter Press", subArea: "Tailings Filtration", system: "Filter Press 1", parentAsset: "13-FP-101", pidTag: "13-FP-101", componentName: "Overcloth", componentType: "Cloth", sparePartDescription: "MATEC OVERCLOTH 1500X2000 INT FC NS002", oemPartNumber: "TELAMT1500X2000INCEOPNS", manufacturer: "MATEC", vendor: "MATEC", assetManufacturer: "MATEC INDUSTRIES", assetModel: "", priority: "MEDIUM", priorityReason: "Filter press consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "500", maxQty: "850", qtyPerSystem: "400", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm qty with Matec", status: "Active" },
  { id: "SS-506", area: "Filter Press", subArea: "Tailings Filtration", system: "Filter Press 1", parentAsset: "13-FP-101", pidTag: "13-FP-101", componentName: "Undercloth", componentType: "Cloth", sparePartDescription: "MATEC UNDERCLOTH 1500X2000 INT FC PUNDER1", oemPartNumber: "SOTESOTMT1500XCEPUNDEO", manufacturer: "MATEC", vendor: "MATEC", assetManufacturer: "MATEC INDUSTRIES", assetModel: "", priority: "MEDIUM", priorityReason: "Filter press consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "500", maxQty: "850", qtyPerSystem: "400", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm qty with Matec", status: "Active" },
  { id: "SS-507", area: "Filter Press", subArea: "Tailings Filtration", system: "Filter Press 1", parentAsset: "13-FP-101", pidTag: "13-FP-101", componentName: "Triple Pump", componentType: "Pump", sparePartDescription: "TRIPLE PUMP XV3/90+90+15 cc", oemPartNumber: "CERIPOMPATRIPDXAF909015", manufacturer: "MATEC", vendor: "MATEC", assetManufacturer: "MATEC INDUSTRIES", assetModel: "", priority: "HIGH", priorityReason: "Pump - process critical", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "3", qtyPerSystem: "3", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm qty with Matec", status: "Active" },
  { id: "SS-508", area: "Filter Press", subArea: "Tailings Filtration", system: "Filter Press 1", parentAsset: "13-FP-101", pidTag: "13-FP-101", componentName: "Mechanical Seal Ø70", componentType: "Seal", sparePartDescription: "MECHANICAL SEAL Ø70", oemPartNumber: "PORI369006", manufacturer: "MATEC", vendor: "MATEC", assetManufacturer: "MATEC INDUSTRIES", assetModel: "", priority: "MEDIUM", priorityReason: "Seal/O-ring - consumable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "2", maxQty: "4", qtyPerSystem: "4", unitPrice: "", uom: "EA", leadTime: "", storageRequirement: "", notes: "Confirm qty with Matec", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // WATER SERVICES AREA (11)
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 11-PU-101A/B Raw Water Bore Pump ---
  { id: "SS-600", area: "Water Services", subArea: "Raw Water", system: "Raw Water Bore Pump - Duty", parentAsset: "11-PU-101A", pidTag: "11-PU-101A", componentName: "Full Motor Assembly", componentType: "Motor", sparePartDescription: "Full Motor Assembly", oemPartNumber: "MS6R45/11 11kW 6\" Sub. Motor", manufacturer: "Grundfos", vendor: "NEWMAN", assetManufacturer: "Grundfos", assetModel: "SP95-2 A", priority: "HIGH", priorityReason: "Motor - plant stoppage risk", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$4,091.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-601", area: "Water Services", subArea: "Raw Water", system: "Raw Water Bore Pump - Duty", parentAsset: "11-PU-101A", pidTag: "11-PU-101A", componentName: "Pump Replacement Unit", componentType: "Pump", sparePartDescription: "SP95-2 A Pump", oemPartNumber: "SP95-2 A", manufacturer: "Grundfos", vendor: "", assetManufacturer: "Grundfos", assetModel: "SP95-2 A", priority: "HIGH", priorityReason: "Process pump - critical to operations", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$7,000.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // --- 11-PU-107 RO Plant Feed Pump ---
  { id: "SS-602", area: "Water Services", subArea: "RO Plant", system: "RO Plant Feed Pump", parentAsset: "11-PU-107", pidTag: "11-PU-107", componentName: "Pump Replacement Unit", componentType: "Pump", sparePartDescription: "Pump replacement unit", oemPartNumber: "CRN10-09 A-FGJ-G-E-HQQE", manufacturer: "Grundfos", vendor: "", assetManufacturer: "Grundfos", assetModel: "CRN10-09 A-FGJ-G-E-HQQE", priority: "HIGH", priorityReason: "Process pump - critical to operations", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$4,396.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },

  // ═══════════════════════════════════════════════════════════════════════════
  // AIR SERVICES AREA (05)
  // ═══════════════════════════════════════════════════════════════════════════

  // --- 5-AC-001 Plant Compressor ---
  { id: "SS-700", area: "Air Services", subArea: "Compressed Air", system: "Plant Compressor", parentAsset: "5-AC-001", pidTag: "05-AC-001", componentName: "Air Filter Element", componentType: "Filter", sparePartDescription: "Air Filter Element", oemPartNumber: "2903740701", manufacturer: "Atlas Copco", vendor: "Atlas Copco", assetManufacturer: "Atlas Copco", assetModel: "GA37VSD+", priority: "MEDIUM", priorityReason: "Filter/screen - consumable/replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "$201.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-701", area: "Air Services", subArea: "Compressed Air", system: "Plant Compressor", parentAsset: "5-AC-001", pidTag: "05-AC-001", componentName: "Oil Filter Element", componentType: "Filter", sparePartDescription: "Oil Filter Element", oemPartNumber: "1625752500", manufacturer: "Atlas Copco", vendor: "Atlas Copco", assetManufacturer: "Atlas Copco", assetModel: "GA37VSD+", priority: "MEDIUM", priorityReason: "Filter/screen - consumable/replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "1", maxQty: "2", qtyPerSystem: "1", unitPrice: "$157.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
  { id: "SS-702", area: "Air Services", subArea: "Compressed Air", system: "Plant Compressor", parentAsset: "5-AC-001", pidTag: "05-AC-001", componentName: "Oil Separator Element", componentType: "Filter", sparePartDescription: "Oil Separator Element", oemPartNumber: "1625165717", manufacturer: "Atlas Copco", vendor: "Atlas Copco", assetManufacturer: "Atlas Copco", assetModel: "GA37VSD+", priority: "MEDIUM", priorityReason: "Filter/screen - consumable/replaceable", reviewFlag: false, isCritical: false, spareCriticality: "", reasonCritical: "", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$1,059.00", uom: "EA", leadTime: "", storageRequirement: "", notes: "", status: "Active" },
];

// Get all unique areas for filtering
export const getUniqueAreas = (): string[] => {
  return [...new Set(siteSparesData.map((item) => item.area))].sort();
};

// Get counts by priority
export const getPriorityCounts = (): { high: number; medium: number } => {
  const high = siteSparesData.filter((item) => item.priority === "HIGH").length;
  const medium = siteSparesData.filter((item) => item.priority === "MEDIUM").length;
  return { high, medium };
};

// Get items flagged for review
export const getReviewItems = (): SiteSpareItem[] => {
  return siteSparesData.filter((item) => item.reviewFlag);
};
