// Area Codes (Level 3)
export const areaCodes = [
  { code: "SITE", meaning: "Site Infrastructure", description: "Buildings, admin, amenities, and site-wide services" },
  { code: "UTL", meaning: "Utilities & Power", description: "Compressed air, electrical, power generation, water systems, reagents" },
  { code: "COM", meaning: "Comminution / Process", description: "Feed/reclaim, milling, grinding, classification, conveying" },
  { code: "REC", meaning: "Gold Recovery", description: "Gravity circuit, CIP, elution, gold room, carbon regeneration" },
  { code: "TAIL", meaning: "Tailings", description: "Thickening, filtration, tailings storage facility" },
  { code: "SUP", meaning: "Support Services", description: "Workshop, laboratory, maintenance infrastructure" },
];

// Equipment Type Prefixes
export const equipmentPrefixes = [
  { prefix: "APN", meaning: "Apron Feeder", example: "APN001", category: "Feed Systems" },
  { prefix: "BM", meaning: "Ball Mill", example: "BM001", category: "Milling" },
  { prefix: "COMP", meaning: "Air Compressor", example: "COMP01", category: "Utilities" },
  { prefix: "CV", meaning: "Conveyor", example: "CV01, CV02", category: "Material Handling" },
  { prefix: "CYC", meaning: "Cyclone / Cyclone Cluster", example: "CYC001", category: "Classification" },
  { prefix: "DRYR", meaning: "Air Dryer", example: "DRYR01", category: "Utilities" },
  { prefix: "FP", meaning: "Filter Press", example: "FP01, FP02", category: "Filtration" },
  { prefix: "GEN", meaning: "Generator", example: "GEN001-GEN008", category: "Power Generation" },
  { prefix: "HCMP", meaning: "High Pressure Compressor", example: "HCMP001", category: "Utilities" },
  { prefix: "KLN", meaning: "Kiln", example: "KLN001", category: "Carbon Regeneration" },
  { prefix: "KNC", meaning: "Knelson Concentrator", example: "KNC001", category: "Gravity" },
  { prefix: "MFC", meaning: "Mill Feed Conveyor", example: "MFC001", category: "Feed Systems" },
  { prefix: "RCVR", meaning: "Air Receiver", example: "RCVR01", category: "Utilities" },
  { prefix: "SCN", meaning: "Screen", example: "SCN001-SCN004", category: "Screening" },
  { prefix: "SHK", meaning: "Shaking Table", example: "SHK001", category: "Gravity" },
  { prefix: "THK", meaning: "Thickener", example: "THK001", category: "Tailings" },
  { prefix: "TRSCR", meaning: "Trash Screen", example: "TRSCR001", category: "Screening" },
  { prefix: "PMP", meaning: "Pump (Generic)", example: "PMP001-PMP016", category: "Pumps" },
  { prefix: "CYFPA/CYFPB", meaning: "Cyclone Feed Pump A/B", example: "CYFPA001", category: "Pumps" },
  { prefix: "THKUFP", meaning: "Thickener Underflow Pump", example: "THKUFP-A", category: "Pumps" },
  { prefix: "CIPPMP", meaning: "CIP Tailings Pump", example: "CIPPMP-A", category: "Pumps" },
  { prefix: "CIP-TK", meaning: "CIP Tank", example: "CIP-TK01 to CIP-TK08", category: "Tanks" },
  { prefix: "FHOP", meaning: "Feed Hopper", example: "FHOP001", category: "Feed Systems" },
  { prefix: "FSTK", meaning: "Fuel Storage Tank", example: "FSTK001", category: "Fuel" },
  { prefix: "GWTR", meaning: "Gland Water System", example: "GWTR001", category: "Water" },
  { prefix: "LSILO", meaning: "Lime Storage Silo", example: "LSILO001", category: "Reagents" },
  { prefix: "PWT", meaning: "Potable Water Tank", example: "PWT001", category: "Water" },
  { prefix: "PWP", meaning: "Process Water Pond", example: "PWP001", category: "Water" },
  { prefix: "RHOP", meaning: "Reclaim Hopper", example: "RHOP001", category: "Feed Systems" },
  { prefix: "RWT", meaning: "Raw Water Tank", example: "RWT001", category: "Water" },
  { prefix: "MDB", meaning: "Main Distribution Board", example: "MDB001", category: "Electrical" },
  { prefix: "SDB", meaning: "Sub Distribution Board", example: "SDB001", category: "Electrical" },
  { prefix: "CR", meaning: "Control Room", example: "CR001", category: "Electrical" },
  { prefix: "LTW", meaning: "Lighting Tower", example: "LTW001-LTW005", category: "Electrical" },
  { prefix: "MSUB", meaning: "Main Sub Station", example: "MSUB001", category: "Electrical" },
  { prefix: "AGT", meaning: "Agitator", example: "AGT001-AGT008", category: "Agitation" },
  { prefix: "EWCL", meaning: "Electrowinning Cell", example: "EWCL001", category: "Gold Room" },
  { prefix: "GEW", meaning: "Gravity Electrowinning", example: "GEW001", category: "Gold Room" },
  { prefix: "GR", meaning: "Gold Room", example: "GR-SCL-01, GR-FRN-01", category: "Gold Room" },
  { prefix: "RECT", meaning: "Rectifier", example: "RECT001", category: "Gold Room" },
  { prefix: "CALC", meaning: "Calcine Oven", example: "CALC001", category: "Gold Room" },
  { prefix: "CDSCR", meaning: "Carbon Dewatering Screen", example: "CDSCR001", category: "Carbon Regen" },
  { prefix: "CREG", meaning: "Carbon Regeneration", example: "CREG001", category: "Carbon Regen" },
  { prefix: "RCTR", meaning: "Regenerated Carbon Transfer", example: "RCTR001", category: "Carbon Regen" },
  { prefix: "KLNHP", meaning: "Kiln Hopper", example: "KLNHP001", category: "Carbon Regen" },
  { prefix: "CBB", meaning: "Cyanide Bag Breaker", example: "CBB001", category: "Reagents" },
  { prefix: "CABB", meaning: "Caustic Bag Breaker", example: "CABB001", category: "Reagents" },
  { prefix: "CMIX", meaning: "Cyanide Mixing", example: "CMIX001", category: "Reagents" },
  { prefix: "FLOC", meaning: "Flocculant System", example: "FLOC001", category: "Reagents" },
  { prefix: "LDOS", meaning: "Lime Dosing System", example: "LDOS001", category: "Reagents" },
  { prefix: "SINF", meaning: "Site Infrastructure", example: "SINF001-SINF008", category: "Buildings" },
  { prefix: "SVC", meaning: "Services", example: "SVC001", category: "Infrastructure" },
  { prefix: "WSHP", meaning: "Workshop", example: "WSHP001", category: "Support" },
  { prefix: "LAB", meaning: "Laboratory", example: "LAB001", category: "Support" },
];

// Component Suffixes
export const componentSuffixes = [
  { suffix: "MTR", meaning: "Motor", example: "BM001-MTR001", category: "Rotating" },
  { suffix: "GBX", meaning: "Gearbox", example: "BM001-GBX001", category: "Rotating" },
  { suffix: "GMR", meaning: "Gearmotor", example: "APN001-GMR001", category: "Rotating" },
  { suffix: "VSD", meaning: "Variable Speed Drive", example: "BM001-VSD001", category: "Electrical" },
  { suffix: "MCC", meaning: "Motor Control Centre Cell", example: "BM001-MCC001", category: "Electrical" },
  { suffix: "LCS", meaning: "Local Control Station", example: "BM001-LCS001", category: "Electrical" },
  { suffix: "PNL", meaning: "Control Panel", example: "CR001-PNL001", category: "Electrical" },
  { suffix: "DB", meaning: "Distribution Board", example: "SINF003-DB001", category: "Electrical" },
  { suffix: "LP", meaning: "Lighting & Power Board", example: "MDB001-LP001", category: "Electrical" },
  { suffix: "PMP", meaning: "Pump", example: "BM001-PMP001", category: "Pumps" },
  { suffix: "VLV", meaning: "Valve", example: "COMP01-VLV001", category: "Valves" },
  { suffix: "TK", meaning: "Tank", example: "CMIX001-TK001", category: "Vessels" },
  { suffix: "PIPE", meaning: "Piping", example: "THK001-PIPE001", category: "Piping" },
  { suffix: "CHU", meaning: "Chute", example: "FHOP001-CHU001", category: "Material Handling" },
  { suffix: "HOP", meaning: "Hopper", example: "CREG001-HOP001", category: "Material Handling" },
  { suffix: "FDR", meaning: "Feeder", example: "RKHP001-FDR001", category: "Material Handling" },
  { suffix: "EXC", meaning: "Exciter (Screen/Vibrator)", example: "TRSCR001-EXC001", category: "Screening" },
  { suffix: "ENG", meaning: "Engine", example: "GEN001-ENG001", category: "Engines" },
  { suffix: "ALT", meaning: "Alternator", example: "GEN001-ALT001", category: "Engines" },
  { suffix: "BRN", meaning: "Burner", example: "KLN001-BRN001", category: "Thermal" },
  { suffix: "HTR", meaning: "Heater", example: "DRYR01-HTR001", category: "Thermal" },
  { suffix: "FAN", meaning: "Fan", example: "KLN001-FAN001", category: "Ventilation" },
  { suffix: "VIB", meaning: "Vibrator", example: "LSILO001-VIB001", category: "Material Handling" },
  { suffix: "AGT", meaning: "Agitator", example: "CIP-TK01-AGT001", category: "Agitation" },
  { suffix: "ALF", meaning: "Air Lift", example: "CIP-ALF01", category: "Transfer" },
  { suffix: "RCVR", meaning: "Receiver", example: "HPCP001-RCVR001", category: "Vessels" },
  { suffix: "HYD", meaning: "Hydraulic System/Pack", example: "BM001-HYD001", category: "Hydraulics" },
  { suffix: "CYL", meaning: "Hydraulic Cylinder", example: "BM001-CYL001", category: "Hydraulics" },
  { suffix: "MNR", meaning: "Monorail", example: "THK001-MNR001", category: "Lifting" },
  { suffix: "HOOD", meaning: "Extraction Hood", example: "CALC001-HOOD001", category: "Ventilation" },
];

// Instrumentation Suffixes
export const instrumentationSuffixes = [
  { suffix: "SWT", meaning: "Switch", example: "RCVR01-SWT001", category: "Switches" },
  { suffix: "PWS", meaning: "Pull Wire Switch", example: "CV01-PWS001", category: "Safety" },
  { suffix: "USS", meaning: "Underspeed Switch", example: "MFC001-USS001", category: "Switches" },
  { suffix: "BAS", meaning: "Belt Alignment Drift Switch", example: "MFC001-BAS001", category: "Safety" },
  { suffix: "HLS", meaning: "High Level Switch", example: "FHOP001-HLS001", category: "Switches" },
  { suffix: "TX", meaning: "Transmitter", example: "APN001-TX001", category: "Instrumentation" },
  { suffix: "SEN", meaning: "Sensor", example: "MFC001-SEN001", category: "Instrumentation" },
  { suffix: "FM", meaning: "Flow Meter", example: "THK001-FM001", category: "Instrumentation" },
  { suffix: "DT", meaning: "Density Transmitter", example: "PCFI001-DT001", category: "Instrumentation" },
  { suffix: "LT", meaning: "Level Transmitter", example: "TAILHOP001-LT001", category: "Instrumentation" },
  { suffix: "PG", meaning: "Pressure Gauge", example: "CYC001-PG001", category: "Instrumentation" },
  { suffix: "TG", meaning: "Temperature Gauge", example: "EWCL001-TG001", category: "Instrumentation" },
  { suffix: "INS", meaning: "Instrument (General)", example: "CYC001-INS001", category: "Instrumentation" },
  { suffix: "WTM", meaning: "Weightometer", example: "MFC001-WTM001", category: "Instrumentation" },
];

// Special Naming Patterns
export const specialPatterns = [
  { pattern: "-D / -S", meaning: "Duty / Standby designation", example: "UTL-PW-PMP-D, UTL-PW-PMP-S" },
  { pattern: "-A / -B", meaning: "Parallel unit designation", example: "PCFPA001, PCFPB001" },
  { pattern: "-01 to -08", meaning: "Sequential numbering for identical units", example: "CIP-TK01 to CIP-TK08" },
  { pattern: "GEN-ADM", meaning: "Generator location prefix", example: "GEN-ADM001 (Admin)" },
  { pattern: "GEN-LAB", meaning: "Generator location prefix", example: "GEN-LAB001 (Laboratory)" },
  { pattern: "GEN-JUNO", meaning: "Generator location prefix", example: "GEN-JUNO001 (Juno Bore)" },
  { pattern: "GRD-", meaning: "Grinding auxiliary system", example: "GRD-LP-LPUMP-D (Low Pressure Lube Pump)" },
  { pattern: "CIP-", meaning: "CIP circuit identifier", example: "CIP-TK01, CIP-ALF01, CIP-SHW01" },
  { pattern: "REAG-", meaning: "Reagent area identifier", example: "REAG-SHW001 (Reagent Safety Shower)" },
  { pattern: "-SHW", meaning: "Safety Shower", example: "CIP-SHW01, GR-SHW01" },
];
