// Area Codes (Level 3)
export const areaCodes = [
  { code: "SITE", meaning: "Site Infrastructure", description: "Buildings, admin, amenities, and site-wide services" },
  { code: "UTL", meaning: "Utilities & Power", description: "Compressed air, electrical, power generation, water systems, reagents" },
  { code: "COM", meaning: "Comminution / Process", description: "Feed/reclaim, milling, grinding, classification, conveying" },
  { code: "REC", meaning: "Gold Recovery", description: "Gravity circuit, CIP, elution, gold room, carbon regeneration" },
  { code: "TAIL", meaning: "Tailings", description: "Thickening, filtration, tailings storage facility" },
  { code: "SUP", meaning: "Support Services", description: "Workshop, laboratory, maintenance infrastructure" },
];

// Equipment Type Prefixes — real asset examples from Processing Plant
export const equipmentPrefixes = [
  { prefix: "APN", meaning: "Apron Feeder", example: "APN01 – Reclaim Apron Feeder", category: "Feed Systems" },
  { prefix: "BM", meaning: "Ball Mill", example: "BM01 – Primary Ball Mill", category: "Milling" },
  { prefix: "COMP", meaning: "Air Compressor", example: "COMP01 – Plant Air Compressor (Duty)", category: "Utilities" },
  { prefix: "CV", meaning: "Conveyor", example: "MFCV01 – Mill Feed Conveyor", category: "Material Handling" },
  { prefix: "CYC", meaning: "Cyclone / Cyclone Cluster", example: "CYC01 – Primary Cyclones", category: "Classification" },
  { prefix: "DRYR", meaning: "Air Dryer", example: "DRYR01 – Compressed Air Dryer", category: "Utilities" },
  { prefix: "FP", meaning: "Filter Press", example: "FP01 – Filter Press No.1", category: "Filtration" },
  { prefix: "GEN", meaning: "Generator", example: "GEN01–GEN08 – Power Station Generators", category: "Power Generation" },
  { prefix: "HCMP", meaning: "High Pressure Compressor", example: "HCMP01 – Filter Press HP Compressor", category: "Utilities" },
  { prefix: "KLN", meaning: "Kiln", example: "KLN01 – Carbon Regeneration Kiln", category: "Carbon Regeneration" },
  { prefix: "KNC", meaning: "Knelson Concentrator", example: "KNC01 – Knelson Concentrator", category: "Gravity" },
  { prefix: "MFC", meaning: "Mill Feed Conveyor", example: "MFCV01 – Mill Feed Conveyor", category: "Feed Systems" },
  { prefix: "RCVR", meaning: "Air Receiver", example: "RCVR01 – Plant Air Receiver", category: "Utilities" },
  { prefix: "SCN", meaning: "Screen", example: "SCN01 – Gravity Screen", category: "Screening" },
  { prefix: "SHK", meaning: "Shaking Table", example: "SHK01 – Gravity Shaking Table", category: "Gravity" },
  { prefix: "THK", meaning: "Thickener", example: "THK01 – Tailings Thickener", category: "Tailings" },
  { prefix: "TRSCN", meaning: "Trash Screen", example: "TRSCN01 – Trash Screen", category: "Screening" },
  { prefix: "PMP", meaning: "Pump (Generic)", example: "ADS01-PMP01 – CIP Area Tails Sump Pump", category: "Pumps" },
  { prefix: "CFP", meaning: "Cyclone Feed Pump", example: "CFP01-PA01 – Primary Cyclone Feed Pump (Duty)", category: "Pumps" },
  { prefix: "THKUFP", meaning: "Thickener Underflow Pump", example: "THK01-UFPA – Thickener U/F Pump (Duty)", category: "Pumps" },
  { prefix: "CIP", meaning: "CIP Tank", example: "CIP01-TK03 – CIP Tank 1", category: "Tanks" },
  { prefix: "FHOP", meaning: "Feed Hopper", example: "FHOP01 – ROM Feed Hopper", category: "Feed Systems" },
  { prefix: "FSTK", meaning: "Fuel Storage Tank", example: "FSTK01 – Diesel Fuel Storage Tank", category: "Fuel" },
  { prefix: "GWTR", meaning: "Gland Water System", example: "GWTR01 – Gland Water System", category: "Water" },
  { prefix: "LSILO", meaning: "Lime Storage Silo", example: "MLA01-SILO01 – Lime Storage Silo", category: "Reagents" },
  { prefix: "PWT", meaning: "Potable Water Tank", example: "PWT01 – Potable Water Tank", category: "Water" },
  { prefix: "PWP", meaning: "Process Water Pond", example: "PWP01 – Process Water Pond", category: "Water" },
  { prefix: "RHOP", meaning: "Reclaim Hopper", example: "RHOP01 – Reclaim Hopper", category: "Feed Systems" },
  { prefix: "RWT", meaning: "Raw Water Tank", example: "RWT01 – Raw Water Tank", category: "Water" },
  { prefix: "MDB", meaning: "Main Distribution Board", example: "SB-100 – Main Switchboard", category: "Electrical" },
  { prefix: "SDB", meaning: "Sub Distribution Board", example: "DB-101 – Control Power", category: "Electrical" },
  { prefix: "CR", meaning: "Control Room", example: "CR01 – Processing Plant Control Room", category: "Electrical" },
  { prefix: "LTW", meaning: "Lighting Tower", example: "LTW01–LTW05 – Site Lighting Towers", category: "Electrical" },
  { prefix: "MSUB", meaning: "Main Sub Station", example: "MSUB01 – Main Substation", category: "Electrical" },
  { prefix: "AGT", meaning: "Agitator", example: "CIP01-TK03-AGT01 – CIP Tank 1 Agitator", category: "Agitation" },
  { prefix: "EWCL", meaning: "Electrowinning Cell", example: "EW01-CELL01 – Electrowinning Cell", category: "Gold Room" },
  { prefix: "GEW", meaning: "Gravity Electrowinning", example: "GEW01 – Gravity Electrowinning Cell", category: "Gold Room" },
  { prefix: "GR", meaning: "Gold Room", example: "GR01 – Gold Room Equipment", category: "Gold Room" },
  { prefix: "RECT", meaning: "Rectifier", example: "EW01-RECT01 – Electrowinning Rectifier", category: "Gold Room" },
  { prefix: "CALC", meaning: "Calcine Oven", example: "GR01-CALC01 – Calcine Oven", category: "Gold Room" },
  { prefix: "CDSCN", meaning: "Carbon Dewatering Screen", example: "CREG01-CDSCN01 – Carbon Dewatering Screen", category: "Carbon Regen" },
  { prefix: "CREG", meaning: "Carbon Regeneration", example: "CREG01 – Carbon Regeneration System", category: "Carbon Regen" },
  { prefix: "RCTR", meaning: "Regenerated Carbon Transfer", example: "CREG01-QTK01 – Regen Quench Tank", category: "Carbon Regen" },
  { prefix: "KLNHP", meaning: "Kiln Hopper", example: "KLN01-HOP01 – Kiln Feed Hopper", category: "Carbon Regen" },
  { prefix: "CBB", meaning: "Cyanide Bag Breaker", example: "CN01-BB01 – Cyanide Bag Breaker", category: "Reagents" },
  { prefix: "CABB", meaning: "Caustic Bag Breaker", example: "EL01-BB01 – Caustic Bag Breaker", category: "Reagents" },
  { prefix: "CMIX", meaning: "Cyanide Mixing", example: "CN01-MXT01 – Cyanide Mixing Tank", category: "Reagents" },
  { prefix: "FLOC", meaning: "Flocculant System", example: "FLOC01 – Flocculant Dosing System", category: "Reagents" },
  { prefix: "LDOS", meaning: "Lime Dosing System", example: "MLA01-SILO01 – Lime Dosing via Rotary Valve", category: "Reagents" },
  { prefix: "SINF", meaning: "Site Infrastructure", example: "SINF01–SINF08 – Site Buildings", category: "Buildings" },
  { prefix: "SVC", meaning: "Services", example: "SVC01 – Site Services", category: "Infrastructure" },
  { prefix: "WSHP", meaning: "Workshop", example: "WSHP01 – Maintenance Workshop", category: "Support" },
  { prefix: "LAB", meaning: "Laboratory", example: "LAB01 – Site Laboratory", category: "Support" },
];

// Component Suffixes — real examples from Processing Plant
export const componentSuffixes = [
  { suffix: "MTR", meaning: "Motor", example: "BM01-MTR01 – Ball Mill Drive Motor", category: "Rotating" },
  { suffix: "GBX", meaning: "Gearbox", example: "BM01-GBX01 – Ball Mill Gear Reducer", category: "Rotating" },
  { suffix: "GMR", meaning: "Gearmotor", example: "APN01-GMR01 – Apron Feeder Gearmotor", category: "Rotating" },
  { suffix: "VSD", meaning: "Variable Speed Drive", example: "BM01-VSD01 – Ball Mill VSD", category: "Electrical" },
  { suffix: "MCC", meaning: "Motor Control Centre Cell", example: "18-MCC-101 – Field MCC", category: "Electrical" },
  { suffix: "LCS", meaning: "Local Control Station", example: "BM01-LCS01 – Mill Local Control Station", category: "Electrical" },
  { suffix: "PNL", meaning: "Control Panel", example: "CR01-PNL01 – Control Room Panel", category: "Electrical" },
  { suffix: "DB", meaning: "Distribution Board", example: "DB-103 – Filter Area Substation Board", category: "Electrical" },
  { suffix: "LP", meaning: "Lighting & Power Board", example: "DB-105 – Control Room L&P Board", category: "Electrical" },
  { suffix: "PMP", meaning: "Pump", example: "MLA01-PMP01 – Grinding Area Sump Pump", category: "Pumps" },
  { suffix: "VLV", meaning: "Valve", example: "ADS01-VLV04 – Butterfly Valves (CIP tanks bypass)", category: "Valves" },
  { suffix: "TK", meaning: "Tank", example: "CN01-MXT01 – Cyanide Mixing Tank", category: "Vessels" },
  { suffix: "PIPE", meaning: "Piping", example: "MLA01-PIPE03 – Slurry Pipe 200mm (Mill Discharge)", category: "Piping" },
  { suffix: "CHU", meaning: "Chute", example: "MFCV01-CH01 – Primary Mill Feed Chute", category: "Material Handling" },
  { suffix: "HOP", meaning: "Hopper", example: "ADS01-HOP01 – CIP Tailings Hopper", category: "Material Handling" },
  { suffix: "FDR", meaning: "Feeder", example: "APN01 – Reclaim Apron Feeder", category: "Material Handling" },
  { suffix: "EXC", meaning: "Exciter (Screen/Vibrator)", example: "TRSCN01-EXC01 – Trash Screen Exciter", category: "Screening" },
  { suffix: "ENG", meaning: "Engine", example: "GEN01-ENG01 – Generator Engine", category: "Engines" },
  { suffix: "ALT", meaning: "Alternator", example: "GEN01-ALT01 – Generator Alternator", category: "Engines" },
  { suffix: "BRN", meaning: "Burner", example: "KLN01-BRN01 – Kiln Burner", category: "Thermal" },
  { suffix: "HTR", meaning: "Heater", example: "EL01-HTR01 – Elution Heater", category: "Thermal" },
  { suffix: "FAN", meaning: "Fan", example: "KLN01-FAN01 – Kiln Induced Draft Fan", category: "Ventilation" },
  { suffix: "VIB", meaning: "Vibrator", example: "MLA01-SILO01-VIB01 – Lime Silo Vibrator", category: "Material Handling" },
  { suffix: "AGT", meaning: "Agitator", example: "CIP01-TK03-AGT01 – CIP Tank 1 Agitator", category: "Agitation" },
  { suffix: "ALF", meaning: "Air Lift", example: "CIP01-ALF01 – CIP Air Lift", category: "Transfer" },
  { suffix: "RCVR", meaning: "Receiver", example: "RCVR01 – Plant Air Receiver", category: "Vessels" },
  { suffix: "HYD", meaning: "Hydraulic System/Pack", example: "BM01-HYD01 – Ball Mill Hydraulic Pack", category: "Hydraulics" },
  { suffix: "CYL", meaning: "Hydraulic Cylinder", example: "FP01-CYL01 – Filter Press Cylinder", category: "Hydraulics" },
  { suffix: "MNR", meaning: "Monorail", example: "CN01-MR01 – Cyanide Monorail", category: "Lifting" },
  { suffix: "HOOD", meaning: "Extraction Hood", example: "GR01-CALC01-HOOD01 – Calcine Oven Hood", category: "Ventilation" },
];

// Instrumentation Suffixes — real examples from Processing Plant
export const instrumentationSuffixes = [
  { suffix: "SWT", meaning: "Switch", example: "RCVR01-SWT01 – Air Receiver Pressure Switch", category: "Switches" },
  { suffix: "PWS", meaning: "Pull Wire Switch", example: "MFCV01-PWS01 – Mill Feed Conveyor Pull Wire", category: "Safety" },
  { suffix: "USS", meaning: "Underspeed Switch", example: "MFCV01-USS01 – Conveyor Underspeed Switch", category: "Switches" },
  { suffix: "BAS", meaning: "Belt Alignment Drift Switch", example: "MFCV01-BAS01 – Conveyor Belt Drift Switch", category: "Safety" },
  { suffix: "HLS", meaning: "High Level Switch", example: "FHOP01-HLS01 – Feed Hopper High Level Switch", category: "Switches" },
  { suffix: "TX", meaning: "Transmitter", example: "THK01-TX01 – Thickener Bed Level Transmitter", category: "Instrumentation" },
  { suffix: "SEN", meaning: "Sensor", example: "BM01-SEN01 – Mill Bearing Temperature Sensor", category: "Instrumentation" },
  { suffix: "FM", meaning: "Flow Meter", example: "THK01-FM01 – Thickener Feed Flow Meter", category: "Instrumentation" },
  { suffix: "DT", meaning: "Density Transmitter", example: "CFP01-DT01 – Cyclone Feed Density Transmitter", category: "Instrumentation" },
  { suffix: "LT", meaning: "Level Transmitter", example: "THK01-LT01 – Thickener Level Transmitter", category: "Instrumentation" },
  { suffix: "PG", meaning: "Pressure Gauge", example: "CYC01-PG01 – Cyclone Feed Pressure Gauge", category: "Instrumentation" },
  { suffix: "TG", meaning: "Temperature Gauge", example: "EL01-TG01 – Elution Column Temperature Gauge", category: "Instrumentation" },
  { suffix: "INS", meaning: "Instrument (General)", example: "CYC01-INS01 – Cyclone Instrument", category: "Instrumentation" },
  { suffix: "WTM", meaning: "Weightometer", example: "MFCV01-WTM01 – Mill Feed Belt Weightometer", category: "Instrumentation" },
];

// Special Naming Patterns — real examples from Processing Plant
export const specialPatterns = [
  { pattern: "-D / -S", meaning: "Duty / Standby designation", example: "CFP01-PA01 (Duty), CFP01-PB01 (Standby)" },
  { pattern: "-A / -B", meaning: "Parallel unit designation", example: "THK01-UFPA (Duty), THK01-UFPB (Standby)" },
  { pattern: "-01 to -08", meaning: "Sequential numbering for identical units", example: "CIP01-TK03 to CIP01-TK08 (CIP Tanks 1–6)" },
  { pattern: "GEN-ADM", meaning: "Generator location prefix", example: "GEN-ADM01 – Admin Generator" },
  { pattern: "GEN-LAB", meaning: "Generator location prefix", example: "GEN-LAB01 – Laboratory Generator" },
  { pattern: "GEN-JUNO", meaning: "Generator location prefix", example: "GEN-JUNO01 – Juno Bore Generator" },
  { pattern: "GRD-", meaning: "Grinding auxiliary system", example: "GRD-LP-LPUMP-D – Low Pressure Lube Pump (Duty)" },
  { pattern: "CIP-", meaning: "CIP circuit identifier", example: "CIP01-TK03, CIP01-ALF01, CIP01-SHW01" },
  { pattern: "REAG-", meaning: "Reagent area identifier", example: "REAG01-SHW01 – Reagent Safety Shower" },
  { pattern: "-SHW", meaning: "Safety Shower", example: "MLA01-SHW01 – Lime Area Safety Shower" },
];
