// Area Codes (Level 3)
export const areaCodes = [
  { code: "SITE", meaning: "Site Infrastructure", description: "Buildings, admin, amenities, and site-wide services" },
  { code: "UTL", meaning: "Utilities & Power", description: "Compressed air, electrical, power generation, water systems, reagents" },
  { code: "COM", meaning: "Comminution / Process", description: "Feed/reclaim, milling, grinding, classification, conveying" },
  { code: "REC", meaning: "Gold Recovery", description: "Gravity circuit, CIP, elution, gold room, carbon regeneration" },
  { code: "TAIL", meaning: "Tailings", description: "Thickening, filtration, tailings storage facility" },
  { code: "SUP", meaning: "Support Services", description: "Workshop, laboratory, maintenance infrastructure" },
];

// Equipment Type Prefixes — real asset examples from Processing Plant
export const equipmentPrefixes = [
  
  { prefix: "BM", meaning: "Ball Mill", example: "BM01", category: "Milling" },
  { prefix: "COMP", meaning: "Air Compressor", example: "COMP01", category: "Utilities" },
  { prefix: "CV", meaning: "Conveyor", example: "MFCV01", category: "Material Handling" },
  { prefix: "CYC", meaning: "Cyclone / Cyclone Cluster", example: "CYC01", category: "Classification" },
  { prefix: "DRYR", meaning: "Air Dryer", example: "DRYR01", category: "Utilities" },
  { prefix: "FP", meaning: "Filter Press", example: "FP01", category: "Filtration" },
  { prefix: "GEN", meaning: "Generator", example: "GEN01–GEN08", category: "Power Generation" },
  { prefix: "HCMP", meaning: "High Pressure Compressor", example: "HCMP01", category: "Utilities" },
  { prefix: "KLN", meaning: "Kiln", example: "KLN01", category: "Carbon Regeneration" },
  { prefix: "KNC", meaning: "Knelson Concentrator", example: "KNC01", category: "Gravity" },
  { prefix: "MFC", meaning: "Mill Feed Conveyor", example: "MFCV01", category: "Feed Systems" },
  { prefix: "RCVR", meaning: "Air Receiver", example: "RCVR01", category: "Utilities" },
  { prefix: "SCN", meaning: "Screen", example: "SCN01", category: "Screening" },
  { prefix: "SHK", meaning: "Shaking Table", example: "SHK01", category: "Gravity" },
  { prefix: "THK", meaning: "Thickener", example: "THK01", category: "Tailings" },
  { prefix: "TRSCN", meaning: "Trash Screen", example: "TRSCN01", category: "Screening" },
  { prefix: "PMP", meaning: "Pump (Generic)", example: "ADS01-PMP01", category: "Pumps" },
  { prefix: "CFP", meaning: "Cyclone Feed Pump", example: "CFP01-PA01", category: "Pumps" },
  { prefix: "THKUFP", meaning: "Thickener Underflow Pump", example: "THK01-UFPA", category: "Pumps" },
  { prefix: "CIP", meaning: "CIP Tank", example: "CIP01-TK03", category: "Tanks" },
  { prefix: "FHOP", meaning: "Feed Hopper", example: "FHOP01", category: "Feed Systems" },
  { prefix: "FSTK", meaning: "Fuel Storage Tank", example: "FSTK01", category: "Fuel" },
  { prefix: "GWTR", meaning: "Gland Water System", example: "GWTR01", category: "Water" },
  { prefix: "LSILO", meaning: "Lime Storage Silo", example: "MLA01-SILO01", category: "Reagents" },
  { prefix: "PWT", meaning: "Potable Water Tank", example: "PWT01", category: "Water" },
  { prefix: "PWP", meaning: "Process Water Pond", example: "PWP01", category: "Water" },
  { prefix: "RHOP", meaning: "Reclaim Hopper", example: "RHOP01", category: "Feed Systems" },
  { prefix: "RWT", meaning: "Raw Water Tank", example: "RWT01", category: "Water" },
  { prefix: "MDB", meaning: "Main Distribution Board", example: "SB-100", category: "Electrical" },
  { prefix: "SDB", meaning: "Sub Distribution Board", example: "DB-101", category: "Electrical" },
  { prefix: "CR", meaning: "Control Room", example: "CR01", category: "Electrical" },
  { prefix: "LTW", meaning: "Lighting Tower", example: "LTW01–LTW05", category: "Electrical" },
  { prefix: "MSUB", meaning: "Main Sub Station", example: "MSUB01", category: "Electrical" },
  { prefix: "AGT", meaning: "Agitator", example: "CIP01-TK03-AGT01", category: "Agitation" },
  { prefix: "EWCL", meaning: "Electrowinning Cell", example: "EW01-CELL01", category: "Gold Room" },
  { prefix: "GEW", meaning: "Gravity Electrowinning", example: "GEW01", category: "Gold Room" },
  { prefix: "GR", meaning: "Gold Room", example: "GR01", category: "Gold Room" },
  { prefix: "RECT", meaning: "Rectifier", example: "EW01-RECT01", category: "Gold Room" },
  { prefix: "CALC", meaning: "Calcine Oven", example: "GR01-CALC01", category: "Gold Room" },
  { prefix: "CDSCN", meaning: "Carbon Dewatering Screen", example: "CREG01-CDSCN01", category: "Carbon Regen" },
  { prefix: "CREG", meaning: "Carbon Regeneration", example: "CREG01", category: "Carbon Regen" },
  { prefix: "RCTR", meaning: "Regenerated Carbon Transfer", example: "CREG01-QTK01", category: "Carbon Regen" },
  { prefix: "KLNHP", meaning: "Kiln Hopper", example: "KLN01-HOP01", category: "Carbon Regen" },
  { prefix: "CBB", meaning: "Cyanide Bag Breaker", example: "CN01-BB01", category: "Reagents" },
  { prefix: "CABB", meaning: "Caustic Bag Breaker", example: "EL01-BB01", category: "Reagents" },
  { prefix: "CMIX", meaning: "Cyanide Mixing", example: "CN01-MXT01", category: "Reagents" },
  { prefix: "FLOC", meaning: "Flocculant System", example: "FLOC01", category: "Reagents" },
  { prefix: "LDOS", meaning: "Lime Dosing System", example: "MLA01-SILO01", category: "Reagents" },
  { prefix: "SINF", meaning: "Site Infrastructure", example: "SINF01–SINF08", category: "Buildings" },
  { prefix: "SVC", meaning: "Services", example: "SVC01", category: "Infrastructure" },
  { prefix: "WSHP", meaning: "Workshop", example: "WSHP01", category: "Support" },
  { prefix: "LAB", meaning: "Laboratory", example: "LAB01", category: "Support" },
];

// Component Suffixes — real examples from Processing Plant
export const componentSuffixes = [
  { suffix: "MTR", meaning: "Motor", example: "BM01-MTR01", category: "Rotating" },
  { suffix: "GBX", meaning: "Gearbox", example: "BM01-GBX01", category: "Rotating" },
  { suffix: "GMR", meaning: "Gearmotor", example: "APN01-GMR01", category: "Rotating" },
  { suffix: "VSD", meaning: "Variable Speed Drive", example: "BM01-VSD01", category: "Electrical" },
  { suffix: "MCC", meaning: "Motor Control Centre Cell", example: "18-MCC-101", category: "Electrical" },
  { suffix: "LCS", meaning: "Local Control Station", example: "BM01-LCS01", category: "Electrical" },
  { suffix: "PNL", meaning: "Control Panel", example: "CR01-PNL01", category: "Electrical" },
  { suffix: "DB", meaning: "Distribution Board", example: "DB-103", category: "Electrical" },
  { suffix: "LP", meaning: "Lighting & Power Board", example: "DB-105", category: "Electrical" },
  { suffix: "PMP", meaning: "Pump", example: "MLA01-PMP01", category: "Pumps" },
  { suffix: "VLV", meaning: "Valve", example: "ADS01-VLV04", category: "Valves" },
  { suffix: "TK", meaning: "Tank", example: "CN01-MXT01", category: "Vessels" },
  { suffix: "PIPE", meaning: "Piping", example: "MLA01-PIPE03", category: "Piping" },
  { suffix: "CHU", meaning: "Chute", example: "MFCV01-CH01", category: "Material Handling" },
  { suffix: "HOP", meaning: "Hopper", example: "ADS01-HOP01", category: "Material Handling" },
  { suffix: "FDR", meaning: "Feeder", example: "APN01", category: "Material Handling" },
  { suffix: "EXC", meaning: "Exciter (Screen/Vibrator)", example: "TRSCN01-EXC01", category: "Screening" },
  { suffix: "ENG", meaning: "Engine", example: "GEN01-ENG01", category: "Engines" },
  { suffix: "ALT", meaning: "Alternator", example: "GEN01-ALT01", category: "Engines" },
  { suffix: "BRN", meaning: "Burner", example: "KLN01-BRN01", category: "Thermal" },
  { suffix: "HTR", meaning: "Heater", example: "EL01-HTR01", category: "Thermal" },
  { suffix: "FAN", meaning: "Fan", example: "KLN01-FAN01", category: "Ventilation" },
  { suffix: "VIB", meaning: "Vibrator", example: "MLA01-SILO01-VIB01", category: "Material Handling" },
  { suffix: "AGT", meaning: "Agitator", example: "CIP01-TK03-AGT01", category: "Agitation" },
  { suffix: "ALF", meaning: "Air Lift", example: "CIP01-ALF01", category: "Transfer" },
  { suffix: "RCVR", meaning: "Receiver", example: "RCVR01", category: "Vessels" },
  { suffix: "HYD", meaning: "Hydraulic System/Pack", example: "BM01-HYD01", category: "Hydraulics" },
  { suffix: "CYL", meaning: "Hydraulic Cylinder", example: "FP01-CYL01", category: "Hydraulics" },
  { suffix: "MNR", meaning: "Monorail", example: "CN01-MR01", category: "Lifting" },
  { suffix: "HOOD", meaning: "Extraction Hood", example: "GR01-CALC01-HOOD01", category: "Ventilation" },
];

// Instrumentation Suffixes — real examples from Processing Plant
export const instrumentationSuffixes = [
  { suffix: "SWT", meaning: "Switch", example: "RCVR01-SWT01", category: "Switches" },
  { suffix: "PWS", meaning: "Pull Wire Switch", example: "MFCV01-PWS01", category: "Safety" },
  { suffix: "USS", meaning: "Underspeed Switch", example: "MFCV01-USS01", category: "Switches" },
  { suffix: "BAS", meaning: "Belt Alignment Drift Switch", example: "MFCV01-BAS01", category: "Safety" },
  { suffix: "HLS", meaning: "High Level Switch", example: "FHOP01-HLS01", category: "Switches" },
  { suffix: "TX", meaning: "Transmitter", example: "THK01-TX01", category: "Instrumentation" },
  { suffix: "SEN", meaning: "Sensor", example: "BM01-SEN01", category: "Instrumentation" },
  { suffix: "FM", meaning: "Flow Meter", example: "THK01-FM01", category: "Instrumentation" },
  { suffix: "DT", meaning: "Density Transmitter", example: "CFP01-DT01", category: "Instrumentation" },
  { suffix: "LT", meaning: "Level Transmitter", example: "THK01-LT01", category: "Instrumentation" },
  { suffix: "PG", meaning: "Pressure Gauge", example: "CYC01-PG01", category: "Instrumentation" },
  { suffix: "TG", meaning: "Temperature Gauge", example: "EL01-TG01", category: "Instrumentation" },
  { suffix: "INS", meaning: "Instrument (General)", example: "CYC01-INS01", category: "Instrumentation" },
  { suffix: "WTM", meaning: "Weightometer", example: "MFCV01-WTM01", category: "Instrumentation" },
];

// Special Naming Patterns — real examples from Processing Plant
export const specialPatterns = [
  { pattern: "-D / -S", meaning: "Duty / Standby designation", example: "CFP01-PA01, CFP01-PB01" },
  { pattern: "-A / -B", meaning: "Parallel unit designation", example: "THK01-UFPA, THK01-UFPB" },
  { pattern: "-01 to -08", meaning: "Sequential numbering for identical units", example: "CIP01-TK03 to CIP01-TK08" },
  { pattern: "GEN-ADM", meaning: "Generator location prefix", example: "GEN-ADM01" },
  { pattern: "GEN-LAB", meaning: "Generator location prefix", example: "GEN-LAB01" },
  { pattern: "GEN-JUNO", meaning: "Generator location prefix", example: "GEN-JUNO01" },
  { pattern: "GRD-", meaning: "Grinding auxiliary system", example: "GRD-LP-LPUMP-D" },
  { pattern: "CIP-", meaning: "CIP circuit identifier", example: "CIP01-TK03, CIP01-ALF01" },
  { pattern: "REAG-", meaning: "Reagent area identifier", example: "REAG01-SHW01" },
  { pattern: "-SHW", meaning: "Safety Shower", example: "MLA01-SHW01" },
];
