// Legacy P&ID Tag to Asset Number Mappings
// These tags are stored as searchable metadata only - they do not appear in asset names/numbers

export interface PidTagMapping {
  pidTag: string;
  assetNumber: string;
  description: string;
  status: "mapped" | "unmapped";
}

// Comprehensive P&ID tag mappings organized by area
export const pidTagMappings: PidTagMapping[] = [
  // ============ GRINDING / COMMINUTION ============
  // Reclaim / Feed System
  { pidTag: "04-FE-100", assetNumber: "APN01", description: "Reclaim Feeder", status: "mapped" },
  { pidTag: "04-PB-099", assetNumber: "RHOP01", description: "Reclaim Hopper", status: "mapped" },
  { pidTag: "04-FE-100LCS", assetNumber: "APN01-LCS01", description: "Reclaim Feeder LCS", status: "mapped" },
  { pidTag: "04-FE-100M", assetNumber: "APN01-MTR01", description: "Reclaim Feeder Motor", status: "mapped" },
  { pidTag: "04-FE-100MC", assetNumber: "APN01-MCC01", description: "Reclaim Feeder MCC Cell", status: "mapped" },
  { pidTag: "04-FE-100GB", assetNumber: "APN01-GMR01", description: "Reclaim Feeder Gearmotor", status: "mapped" },
  { pidTag: "04-FE-100-PWS", assetNumber: "APN01-PWS01", description: "Reclaim Feeder Pullwire switch", status: "mapped" },
  { pidTag: "04-SIT-500", assetNumber: "APN01-TX01", description: "Reclaim Feeder Speed Transmitter", status: "mapped" },
  
  // Transfer Conveyor
  { pidTag: "04-FE-101", assetNumber: "CV01", description: "Transfer Conveyor", status: "mapped" },
  { pidTag: "04-CH-100", assetNumber: "CV01-CHU01", description: "Transfer Conveyor Discharge Chute", status: "mapped" },
  { pidTag: "04-FE-101LCS", assetNumber: "CV01-LCS01", description: "Transfer Conveyor Local Control Station", status: "mapped" },
  { pidTag: "04-FE-101M", assetNumber: "CV01-MTR01", description: "Transfer Conveyor Motor", status: "mapped" },
  { pidTag: "04-FE-101MC", assetNumber: "CV01-MCC01", description: "Transfer Conveyor MCC Cell", status: "mapped" },
  { pidTag: "04-FE-101GB", assetNumber: "CV01-GBX01", description: "Transfer Conveyor Gearbox", status: "mapped" },
  { pidTag: "04-FE-101PWS", assetNumber: "CV01-PWS01", description: "Transfer Conveyor Pull Wire Switch", status: "mapped" },
  
  // Mill Feed Conveyor
  { pidTag: "04-BC-100", assetNumber: "MFC01", description: "Mill Feed Conveyor", status: "mapped" },
  { pidTag: "04-BC-100LCS", assetNumber: "MFC01-LCS01", description: "Mill Feed Conveyor Local Control station", status: "mapped" },
  { pidTag: "04-BC-100M", assetNumber: "MFC01-MTR01", description: "Mill Feed Conveyor Motor", status: "mapped" },
  { pidTag: "04-BC-100MC", assetNumber: "MFC01-MCC01", description: "Mill Feed Conveyor MCC Cell", status: "mapped" },
  { pidTag: "04-BC-100GB", assetNumber: "MFC01-GBX01", description: "Mill Feed Conveyor Gearbox", status: "mapped" },
  { pidTag: "04-SS-506", assetNumber: "MFC01-USS01", description: "Feed Conveyor Underspeed Switch", status: "mapped" },
  { pidTag: "04-WE-506", assetNumber: "MFC01-WTM01", description: "Ball Mill Feed Conveyor Weightometer Loadcells", status: "mapped" },
  { pidTag: "04-WQIT-506", assetNumber: "MFC01-WTM02", description: "Ball Mill Feed Conveyor Weightometer Transmitter", status: "mapped" },
  { pidTag: "04-XS-507A", assetNumber: "MFC01-PWS01", description: "Feed Conveyor Pull Wire Switch 1", status: "mapped" },
  { pidTag: "04-XS-507B", assetNumber: "MFC01-PWS02", description: "Feed Conveyor Pull Wire Switch 2", status: "mapped" },
  { pidTag: "04-XS-507C", assetNumber: "MFC01-PWS03", description: "Feed Conveyor Pull Wire Switch 3", status: "mapped" },
  { pidTag: "04-XS-507D", assetNumber: "MFC01-PWS04", description: "Feed Conveyor Pull Wire Switch 4", status: "mapped" },
  { pidTag: "04-ZS-508A", assetNumber: "MFC01-BAS01", description: "Feed Conveyor Belt Alignment Switch 1", status: "mapped" },
  { pidTag: "04-ZS-508B", assetNumber: "MFC01-BAS02", description: "Feed Conveyor Belt Alignment Switch 2", status: "mapped" },
  { pidTag: "04-ZS-508C", assetNumber: "MFC01-BAS03", description: "Feed Conveyor Belt Alignment Switch 3", status: "mapped" },
  { pidTag: "04-ZS-508D", assetNumber: "MFC01-BAS04", description: "Feed Conveyor Belt Alignment Switch 4", status: "mapped" },
  { pidTag: "04-LSH-510", assetNumber: "FHOP01-HLS01", description: "Ball Mill Feed Chute High Level Switch", status: "mapped" },
  { pidTag: "04-CH-101", assetNumber: "MFC01-CHU01", description: "Mill Feed Conveyor Discharge Chute", status: "mapped" },
  { pidTag: "04-CH-102", assetNumber: "FHOP01-CHU01", description: "Mill Feed Chute", status: "mapped" },
  { pidTag: "04-CH-010", assetNumber: "FHOP01-CHU02", description: "Ball Loading Chute", status: "mapped" },
  
  // Lime System
  { pidTag: "04-TK-100", assetNumber: "LSILO01", description: "Lime Storage Silo", status: "mapped" },
  { pidTag: "04-FE-102", assetNumber: "APN01-VLV01", description: "Lime Feeder Rotary Valve", status: "mapped" },
  { pidTag: "-BA-103", assetNumber: "LSILO01-VIB01", description: "Lime Silo Vibrator", status: "mapped" },
  
  // Primary Ball Mill
  { pidTag: "04-ML-100", assetNumber: "BM01", description: "Primary Ball Mill", status: "mapped" },
  { pidTag: "04-ML-100M", assetNumber: "BM01-MTR01", description: "Primary Ball Mill Motor", status: "mapped" },
  { pidTag: "04-ML-100GB", assetNumber: "BM01-GBX01", description: "Primary Ball Mill Gearbox", status: "mapped" },
  { pidTag: "04-ML-100P", assetNumber: "BM01-PIN01", description: "Primary Ball Mill Pinion", status: "mapped" },
  { pidTag: "04-ML-100MC", assetNumber: "BM01-MCC01", description: "Primary Ball Mill MCC Cell", status: "mapped" },
  { pidTag: "04-ML-100VSD", assetNumber: "BM01-VSD01", description: "Primary Ball Mill VSD", status: "mapped" },
  { pidTag: "04-ML-100I", assetNumber: "BM01-INS01", description: "Primary Ball mill Instruments", status: "mapped" },
  { pidTag: "04-TIT-536", assetNumber: "BM01-TX01", description: "Feed End Trunnion Bearing Temperature Transmitter", status: "mapped" },
  { pidTag: "04-TE-536X", assetNumber: "BM01-SEN01", description: "Feed End Trunnion Bearing Temperature Sensor 1", status: "mapped" },
  { pidTag: "04-TE-536Y", assetNumber: "BM01-SEN02", description: "Feed End Trunnion Bearing Temperature Sensor 2", status: "mapped" },
  { pidTag: "04-TE-536Z", assetNumber: "BM01-SEN03", description: "Feed End Trunnion Bearing Temperature Sensor 3", status: "mapped" },
  { pidTag: "04-TIT-537", assetNumber: "BM01-TX02", description: "Dis End Trunnion Bearing Temperature Transmitter", status: "mapped" },
  { pidTag: "04-TE-537X", assetNumber: "BM01-SEN04", description: "Dis End Trunnion Bearing Temperature Sensor 1", status: "mapped" },
  { pidTag: "04-TE-537Y", assetNumber: "BM01-SEN05", description: "Dis End Trunnion Bearing Temperature Sensor 2", status: "mapped" },
  { pidTag: "04-TE-537Z", assetNumber: "BM01-SEN06", description: "Dis End Trunnion Bearing Temperature Sensor 3", status: "mapped" },
  { pidTag: "04-TE-538", assetNumber: "BM01-SEN07", description: "Mill Gear Reducer Temperature", status: "mapped" },
  { pidTag: "04-FCV-545", assetNumber: "BM01-VLV01", description: "Mill Discharge End Water Addition Control Valve", status: "mapped" },
  { pidTag: "04-FIT-545", assetNumber: "BM01-TX03", description: "Mill Discharge End Water Addition Flow Transmitter", status: "mapped" },
  { pidTag: "-LE-550", assetNumber: "BM01-TX04", description: "Mill Discharge Hopper Level Transmitter", status: "mapped" },
  { pidTag: "04-PB-105", assetNumber: "FHOP01-BOX01", description: "Primary Mill Feed Boiler Box", status: "mapped" },
  { pidTag: "04-GR-100", assetNumber: "BM01-GBX01", description: "Primary Ball Mill Gear Reducer", status: "mapped" },
  { pidTag: "04-MR-100", assetNumber: "BM01-MNR01", description: "Ball Mill Loading Monorail", status: "mapped" },
  { pidTag: "04-CV-011", assetNumber: "CV02", description: "Ball Mill Scatts Conveyor", status: "mapped" },
  { pidTag: "04-SS-01", assetNumber: "MILL-SHW01", description: "Mill Area Safety Shower 1", status: "mapped" },
  { pidTag: "04-SS-02", assetNumber: "MILL-SHW02", description: "Mill Area Safety Shower 2", status: "mapped" },
  
  // Ball Mill Lube System
  { pidTag: "04-PU-016", assetNumber: "BM01-PMP01", description: "Primary Ball Mill Lube Recirculating Pump", status: "mapped" },
  { pidTag: "04-PU-016M", assetNumber: "BM01-PMP01-MTR01", description: "Primary Ball Mill Lube Recirculating Pump Motor", status: "mapped" },
  { pidTag: "04-PU-016MC", assetNumber: "BM01-PMP01-MCC01", description: "Primary Ball Mill Lube Recirculating Pump MCC Cell", status: "mapped" },
  { pidTag: "04-PU-016LCS", assetNumber: "BM01-PMP01-LCS01", description: "Primary Ball Mill Lube Recirculating Pump LCS", status: "mapped" },
  { pidTag: "04-LS-100", assetNumber: "BM01-LUB01", description: "Primary Ball Mill Lube System", status: "mapped" },
  { pidTag: "04-FA-006", assetNumber: "BM01-CLR01", description: "Primary Ball Mill Lube Air Blast Oil Cooler", status: "mapped" },
  { pidTag: "04-FA-006M", assetNumber: "BM01-CLR01-MTR01", description: "Primary Ball Mill Lube Air Blast Oil Cooler Motor", status: "mapped" },
  { pidTag: "04-FA-006MC", assetNumber: "BM01-CLR01-MCC01", description: "Primary Ball Mill Lube Air Blast Oil Cooler MCC Cell", status: "mapped" },
  { pidTag: "04-FA-06LCS", assetNumber: "BM01-CLR01-LCS01", description: "Primary Ball Mill Lube Air Blast Oil Cooler LCS", status: "mapped" },
  { pidTag: "04-PU-100A", assetNumber: "BM01-PMP02", description: "Primary Ball Mill Low Pressure Lube Pump A", status: "mapped" },
  { pidTag: "04-PU-100AM", assetNumber: "BM01-PMP02-MTR01", description: "Primary Ball Mill Low Pressure Lube Pump A Motor", status: "mapped" },
  { pidTag: "04-PU-100AMC", assetNumber: "BM01-PMP02-MCC01", description: "Primary Ball Mill Low Pressure Lube Pump A MCC Cell", status: "mapped" },
  { pidTag: "04-PU-100ALCS", assetNumber: "BM01-PMP02-LCS01", description: "Primary Ball Mill Low Pressure Lube Pump A LCS", status: "mapped" },
  { pidTag: "04-PU-100B", assetNumber: "BM01-PMP03", description: "Primary Ball Mill Low Pressure Lube Pump B", status: "mapped" },
  { pidTag: "04-PU-100BM", assetNumber: "BM01-PMP03-MTR01", description: "Primary Ball Mill Low Pressure Lube Pump B Motor", status: "mapped" },
  { pidTag: "04-PU-100BMC", assetNumber: "BM01-PMP03-MCC01", description: "Primary Ball Mill Low Pressure Lube Pump B MCC Cell", status: "mapped" },
  { pidTag: "04-PU-100BLCS", assetNumber: "BM01-PMP03-LCS01", description: "Primary Ball Mill Low Pressure Lube Pump B LCS", status: "mapped" },
  
  // Grinding Sump
  { pidTag: "04-PU-120", assetNumber: "GSPMP01", description: "Grinding Area Sump Pump", status: "mapped" },
  { pidTag: "04-PU-120M", assetNumber: "GSPMP01-MTR01", description: "Grinding Area Sump Pump Motor", status: "mapped" },
  { pidTag: "04-PU-120MC", assetNumber: "GSPMP01-MCC01", description: "Grinding Area Sump Pump MCC Cell", status: "mapped" },
  { pidTag: "04-PU-120LCS", assetNumber: "GSPMP01-LCS01", description: "Grinding Area Sump Pump LCS", status: "mapped" },
  
  // High Pressure Lube
  { pidTag: "04-PU-101", assetNumber: "BM01-PMP04", description: "Primary Ball Mill High Pressure Lube Pump", status: "mapped" },
  { pidTag: "04-PU-101M", assetNumber: "BM01-PMP04-MTR01", description: "Primary Ball Mill High Pressure Lube Pump Motor", status: "mapped" },
  { pidTag: "04-PU-101MC", assetNumber: "BM01-PMP04-MCC01", description: "Primary Ball Mill High Pressure Lube Pump MCC Cell", status: "mapped" },
  { pidTag: "04-LS-100I", assetNumber: "BM01-INS02", description: "Primary Mill Lube System Instruments", status: "mapped" },
  { pidTag: "04-PIT-520", assetNumber: "BM01-TX05", description: "Mill Low Pressure Lube Oil Pressure Transmitter", status: "mapped" },
  { pidTag: "04-FIT-521", assetNumber: "BM01-TX06", description: "Mill Low Pressure Lube Oil Flow Transmitter", status: "mapped" },
  { pidTag: "04-PIT-525", assetNumber: "BM01-TX07", description: "Mill High Pressure Lift Lube Oil Pressure Transmitter", status: "mapped" },
  { pidTag: "04-FE-526", assetNumber: "BM01-LUB04", description: "Mill High Pressure Lift Lube Oil Flow", status: "mapped" },
  { pidTag: "04-FIT-526", assetNumber: "BM01-TX08", description: "Mill High Pressure Lift Lube Oil Flow Transmitter", status: "mapped" },
  { pidTag: "04-LIT-528", assetNumber: "BM01-TX09", description: "Mill Lube System Oil Level", status: "mapped" },
  { pidTag: "04-TIT-529", assetNumber: "BM01-TX10", description: "Mill Lube System Oil Temperature", status: "mapped" },
  { pidTag: "04-PU-101LCS", assetNumber: "BM01-PMP04-LCS01", description: "Primary Ball Mill High Pressure Lube Pump LCS", status: "mapped" },
  { pidTag: "04-LS-101", assetNumber: "BM01-LUB02", description: "Primary Ball Mill Girth Gear Lube System", status: "mapped" },
  { pidTag: "04-LS-101P", assetNumber: "BM01-LUB02-PMP01", description: "Primary Ball Mill Girth Gear Lube System Pump", status: "mapped" },
  { pidTag: "04-LS-101CP", assetNumber: "BM01-LUB02-PNL01", description: "Primary Ball Mill Girth Gear Lube System Control Panel", status: "mapped" },
  { pidTag: "04-FL-100A", assetNumber: "BM01-FLT01", description: "Primary Ball Mill Lube System Filter A", status: "mapped" },
  { pidTag: "04-FL-100B", assetNumber: "BM01-FLT02", description: "Primary Ball Mill Lube System Filter B", status: "mapped" },
  { pidTag: "04-PB-100", assetNumber: "BM01-HOP01", description: "Primary Mill Discharge Hopper", status: "mapped" },
  
  // Primary Cyclone Feed Pumps
  { pidTag: "04-PU-102A", assetNumber: "PCFPA01", description: "Primary Cyclone Feed Pump A", status: "mapped" },
  { pidTag: "04-PU-102AM", assetNumber: "PCFPA01-MTR01", description: "Primary Cyclone Feed Pump A Motor", status: "mapped" },
  { pidTag: "04-PU-102AMC", assetNumber: "PCFPA01-MCC01", description: "Primary Cyclone Feed Pump A MCC Cell", status: "mapped" },
  { pidTag: "04-PU-102ALCS", assetNumber: "PCFPA01-LCS01", description: "Primary Cyclone Feed Pump A LCS", status: "mapped" },
  { pidTag: "04-PU-102B", assetNumber: "PCFPB01", description: "Primary Cyclone Feed Pump B", status: "mapped" },
  { pidTag: "04-PU-102BM", assetNumber: "PCFPB01-MTR01", description: "Primary Cyclone Feed Pump B Motor", status: "mapped" },
  { pidTag: "04-PU-102BMC", assetNumber: "PCFPB01-MCC01", description: "Primary Cyclone Feed Pump B MCC Cell", status: "mapped" },
  { pidTag: "04-PU-102BLCS", assetNumber: "PCFPB01-LCS01", description: "Primary Cyclone Feed Pump B LCS", status: "mapped" },
  { pidTag: "04-XV-", assetNumber: "PCFI01-VLV01", description: "Primary Cyclone Feed TechTaylor Valve", status: "mapped" },
  
  // Primary Cyclone Cluster
  { pidTag: "04-CY-100", assetNumber: "CYC01", description: "Primary Cyclone Cluster", status: "mapped" },
  { pidTag: "04-CY-100I", assetNumber: "CYC01-INS01", description: "Primary Cyclone Cluster Instruments", status: "mapped" },
  { pidTag: "04-FIT-551", assetNumber: "PCFI01-TX01", description: "Primary Cyclone Feed Flow Transmitter", status: "mapped" },
  { pidTag: "04-PIT-552", assetNumber: "CYC01-TX01", description: "Primary Cyclone Pressure Transmitter", status: "mapped" },
  { pidTag: "04-PI-552A", assetNumber: "CYC01-PG01", description: "Primary Cyclone Pressure Gauge", status: "mapped" },
  { pidTag: "04-PB-101", assetNumber: "CYC01-SPL01", description: "Primary Cyclone Underflow Splitter Box", status: "mapped" },
  
  // ============ CIP AREA ============
  { pidTag: "05-CIP-01", assetNumber: "CIP-TK01", description: "CIP Area", status: "mapped" },
  { pidTag: "05-CH-001", assetNumber: "CPTS01-FBX01", description: "CIP Trash Screen Feed Box", status: "mapped" },
  { pidTag: "05-SC-001", assetNumber: "CPTS01", description: "CIP Feed Trash Screen", status: "mapped" },
  { pidTag: "05-SC-001EXA", assetNumber: "CPTS01-EXC01", description: "CIP Feed Trash Screen Exciter A", status: "mapped" },
  { pidTag: "05-SC-001EXALCS", assetNumber: "CPTS01-LCS01", description: "CIP Feed Trash Screen Exciter A LCS", status: "mapped" },
  { pidTag: "05-SC-001EXAMC", assetNumber: "CPTS01-MCC01", description: "CIP Feed Trash Screen Exciter A MCC Cell", status: "mapped" },
  { pidTag: "05-SC-001EXB", assetNumber: "CPTS01-EXC02", description: "CIP Feed Trash Screen Exciter B", status: "mapped" },
  { pidTag: "05-SC-001EXBLCS", assetNumber: "CPTS01-LCS02", description: "CIP Feed Trash Screen Exciter B LCS", status: "mapped" },
  { pidTag: "05-SC-001EXBMC", assetNumber: "CPTS01-MCC02", description: "CIP Feed Trash Screen Exciter B MCC Cell", status: "mapped" },
  { pidTag: "05-SC-001SB", assetNumber: "CPTS01-SPR01", description: "CIP Feed Trash Screen Spray Bars", status: "mapped" },
  { pidTag: "05-CH-002", assetNumber: "CPTS01-CHU01", description: "CIP Trash Screen Oversize Chute", status: "mapped" },
  
  // CIP Sump
  { pidTag: "05-PU-005", assetNumber: "CIP-PMP01", description: "CIP Leach Area Sump Pump", status: "mapped" },
  { pidTag: "05-PU-005M", assetNumber: "CIP-PMP01-MTR01", description: "CIP Leach Area Sump Pump Motor", status: "mapped" },
  { pidTag: "05-PU-005MC", assetNumber: "CIP-PMP01-MCC01", description: "CIP Leach Area Sump Pump MCC Cell", status: "mapped" },
  { pidTag: "05-PU-005LCS", assetNumber: "CIP-PMP01-LCS01", description: "CIP Leach Area Sump Pump LCS", status: "mapped" },
  
  // CIP Safety Showers
  { pidTag: "05-SS", assetNumber: "CIP-SHW01", description: "CIP Area Safety Showers", status: "mapped" },
  { pidTag: "05-SS-001", assetNumber: "CIP-SHW01", description: "CIP Area Safety Shower 1", status: "mapped" },
  { pidTag: "05-SS-002", assetNumber: "CIP-SHW02", description: "CIP Area Safety Shower 2", status: "mapped" },
  { pidTag: "05-SS-003", assetNumber: "CIP-SHW04", description: "CIP Tails Area Safety Shower", status: "mapped" },
  
  // CIP Tank 1
  { pidTag: "05-TK-001", assetNumber: "CIP-TK01", description: "CIP Leach Tank 1", status: "mapped" },
  { pidTag: "05-AG-001", assetNumber: "CIP-TK01-AGT01", description: "CIP Leach Tank 1 Agitator", status: "mapped" },
  { pidTag: "05-AG-001M", assetNumber: "CIP-TK01-AGT01-MTR01", description: "CIP Leach Tank 1 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-001MC", assetNumber: "CIP-TK01-AGT01-MCC01", description: "CIP Leach Tank 1 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-001GB", assetNumber: "CIP-TK01-AGT01-GBX01", description: "CIP Leach Tank 1 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-001LCS", assetNumber: "CIP-TK01-AGT01-LCS01", description: "CIP Leach Tank 1 Agitator LCS", status: "mapped" },
  { pidTag: "05-AIT-933", assetNumber: "CIP-TK01-PH01", description: "CIP Leach Tank 1 PH Probe", status: "mapped" },
  { pidTag: "05-XM-001", assetNumber: "CIP-TK01-NZL01", description: "Leach Tank 1 Air Sparge Nozzles", status: "mapped" },
  
  // CIP Tank 2
  { pidTag: "05-TK-002", assetNumber: "CIP-TK02", description: "CIP Leach Tank 2", status: "mapped" },
  { pidTag: "05-AG-002", assetNumber: "CIP-TK02-AGT01", description: "CIP Leach Tank 2 Agitator", status: "mapped" },
  { pidTag: "05-AG-002M", assetNumber: "CIP-TK02-AGT01-MTR01", description: "CIP Leach Tank 2 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-002MC", assetNumber: "CIP-TK02-AGT01-MCC01", description: "CIP Leach Tank 2 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-00GB", assetNumber: "CIP-TK02-AGT01-GBX01", description: "CIP Leach Tank 2 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-002LCS", assetNumber: "CIP-TK02-AGT01-LCS01", description: "CIP Leach Tank 2 Agitator LCS", status: "mapped" },
  { pidTag: "05-XM-002", assetNumber: "CIP-TK02-NZL01", description: "Leach Tank 2 Air Sparge Nozzles", status: "mapped" },
  
  // Loaded Carbon Screen
  { pidTag: "05-CH-7", assetNumber: "LCS01-FBX01", description: "Loaded Carbon Screen Feedbox", status: "mapped" },
  { pidTag: "05-SC-010", assetNumber: "LCS01", description: "Loaded Carbon Screen", status: "mapped" },
  { pidTag: "05-SC-010EX", assetNumber: "LCS01-EXC01", description: "Loaded Carbon Screen Exciter A", status: "mapped" },
  { pidTag: "05-SC-010EXALCS", assetNumber: "LCS01-EXC01-LCS01", description: "Loaded Carbon Screen Exciter A LCS", status: "mapped" },
  { pidTag: "05-SC-010EXAMC", assetNumber: "LCS01-EXC01-MCC01", description: "Loaded Carbon Screen Exciter A MCC Cell", status: "mapped" },
  { pidTag: "05-SC-010EXB", assetNumber: "LCS01-EXC02", description: "Loaded Carbon Screen Exciter B", status: "mapped" },
  { pidTag: "05-SC-010EXBLCS", assetNumber: "LCS01-EXC02-LCS01", description: "Loaded Carbon Screen Exciter B LCS", status: "mapped" },
  { pidTag: "05-SC-010EXBMC", assetNumber: "LCS01-EXC02-MCC01", description: "Loaded Carbon Screen Exciter B MCC Cell", status: "mapped" },
  { pidTag: "05-SC-010EXSB", assetNumber: "LCS01-SPR01", description: "Loaded Carbon Screen Spray Bars", status: "mapped" },
  { pidTag: "05-CH-009", assetNumber: "LCS01-UPN01", description: "Loaded Carbon Screen Underpan", status: "mapped" },
  { pidTag: "05-CH-008", assetNumber: "LCS01-CHU01", description: "Loaded Carbon Screen Oversize Chute", status: "mapped" },
  
  // CIP Tank 3
  { pidTag: "05-TK-003", assetNumber: "CIP-TK03", description: "CIP Tank 3", status: "mapped" },
  { pidTag: "05-AG-003", assetNumber: "CIP-TK03-AGT01", description: "CIP Tank 3 Agitator", status: "mapped" },
  { pidTag: "05-AG-003M", assetNumber: "CIP-TK03-AGT01-MTR01", description: "CIP Tank 3 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-003MC", assetNumber: "CIP-TK03-AGT01-MCC01", description: "CIP Tank 3 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-003GB", assetNumber: "CIP-TK03-AGT01-GBX01", description: "CIP Tank 3 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-003LCS", assetNumber: "CIP-TK03-AGT01-LCS01", description: "CIP Tank 3 Agitator LCS", status: "mapped" },
  { pidTag: "05-SC-002", assetNumber: "CIP-SCR01", description: "CIP Inter Tank Screen 1", status: "mapped" },
  { pidTag: "05-SC-002M", assetNumber: "CIP-SCR01-MTR01", description: "CIP Inter Tank Screen 1 Motor", status: "mapped" },
  { pidTag: "05-SC-002MC", assetNumber: "CIP-SCR01-MCC01", description: "CIP Inter Tank Screen 1 MCC Cell", status: "mapped" },
  { pidTag: "05-SC-00GB", assetNumber: "CIP-SCR01-GBX01", description: "CIP Inter Tank Screen 1 Gearbox", status: "mapped" },
  { pidTag: "05-SC-002LCS", assetNumber: "CIP-SCR01-LCS01", description: "CIP Inter Tank Screen 1 LCS", status: "mapped" },
  { pidTag: "05-AL-002", assetNumber: "CIP-AL02", description: "Carbon Transfer Air Lift 2", status: "mapped" },
  
  // CIP Tank 4
  { pidTag: "05-TK-004", assetNumber: "CIP-TK04", description: "CIP Tank 4", status: "mapped" },
  { pidTag: "05-AG-004", assetNumber: "CIP-TK04-AGT01", description: "CIP Tank 4 Agitator", status: "mapped" },
  { pidTag: "05-AG-004M", assetNumber: "CIP-TK04-AGT01-MTR01", description: "CIP Tank 4 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-004MC", assetNumber: "CIP-TK04-AGT01-MCC01", description: "CIP Tank 4 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-004GB", assetNumber: "CIP-TK04-AGT01-GBX01", description: "CIP Tank 4 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-004LCS", assetNumber: "CIP-TK04-AGT01-LCS01", description: "CIP Tank 4 Agitator LCS", status: "mapped" },
  { pidTag: "05-AL-003", assetNumber: "CIP-AL03", description: "Carbon Transfer Air Lift 3", status: "mapped" },
  { pidTag: "05-SC-003", assetNumber: "CIP-SCR02", description: "CIP Inter Tank Screen 2", status: "mapped" },
  
  // CIP Tank 5
  { pidTag: "05-TK-005", assetNumber: "CIP-TK05", description: "CIP Tank 5", status: "mapped" },
  { pidTag: "05-AG-005", assetNumber: "CIP-TK05-AGT01", description: "CIP Tank 5 Agitator", status: "mapped" },
  { pidTag: "05-AG-005M", assetNumber: "CIP-TK05-AGT01-MTR01", description: "CIP Tank 5 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-005MC", assetNumber: "CIP-TK05-AGT01-MCC01", description: "CIP Tank 5 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-005GB", assetNumber: "CIP-TK05-AGT01-GBX01", description: "CIP Tank 5 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-005LCS", assetNumber: "CIP-TK05-AGT01-LCS01", description: "CIP Tank 5 Agitator LCS", status: "mapped" },
  { pidTag: "05-AL-004", assetNumber: "CIP-AL04", description: "Carbon Transfer Air Lift 4", status: "mapped" },
  
  // CIP Tank 6
  { pidTag: "05-TK-006", assetNumber: "CIP-TK06", description: "CIP Tank 6", status: "mapped" },
  { pidTag: "05-AG-006", assetNumber: "CIP-TK06-AGT01", description: "CIP Tank 6 Agitator", status: "mapped" },
  { pidTag: "05-AG-006M", assetNumber: "CIP-TK06-AGT01-MTR01", description: "CIP Tank 6 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-006MC", assetNumber: "CIP-TK06-AGT01-MCC01", description: "CIP Tank 6 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-006GB", assetNumber: "CIP-TK06-AGT01-GBX01", description: "CIP Tank 6 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-006LCS", assetNumber: "CIP-TK06-AGT01-LCS01", description: "CIP Tank 6 Agitator LCS", status: "mapped" },
  { pidTag: "05-AL-005", assetNumber: "CIP-AL05", description: "Carbon Transfer Air Lift 5", status: "mapped" },
  
  // CIP Tank 7
  { pidTag: "05-TK-007", assetNumber: "CIP-TK07", description: "CIP Tank 7", status: "mapped" },
  { pidTag: "05-AG-007", assetNumber: "CIP-TK07-AGT01", description: "CIP Tank 7 Agitator", status: "mapped" },
  { pidTag: "05-AG-007M", assetNumber: "CIP-TK07-AGT01-MTR01", description: "CIP Tank 7 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-007MC", assetNumber: "CIP-TK07-AGT01-MCC01", description: "CIP Tank 7 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-007GB", assetNumber: "CIP-TK07-AGT01-GBX01", description: "CIP Tank 7 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-007LCS", assetNumber: "CIP-TK07-AGT01-LCS01", description: "CIP Tank 7 Agitator LCS", status: "mapped" },
  { pidTag: "05-AL-006", assetNumber: "CIP-AL06", description: "Carbon Transfer Air Lift 6", status: "mapped" },
  { pidTag: "05-SC-004", assetNumber: "CIP-SCR05", description: "CIP Inter Tank Screen 5", status: "mapped" },
  
  // CIP Tank 8
  { pidTag: "05-TK-008", assetNumber: "CIP-TK08", description: "CIP Tank 8", status: "mapped" },
  { pidTag: "05-AG-008", assetNumber: "CIP-TK08-AGT01", description: "CIP Tank 8 Agitator", status: "mapped" },
  { pidTag: "05-AG-008M", assetNumber: "CIP-TK08-AGT01-MTR01", description: "CIP Tank 8 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-008MC", assetNumber: "CIP-TK08-AGT01-MCC01", description: "CIP Tank 8 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-008GB", assetNumber: "CIP-TK08-AGT01-GBX01", description: "CIP Tank 8 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-008LCS", assetNumber: "CIP-TK08-AGT01-LCS01", description: "CIP Tank 8 Agitator LCS", status: "mapped" },
  { pidTag: "05-SC-007", assetNumber: "CIP-SCR06", description: "CIP Inter Tank Screen 6", status: "mapped" },
  
  // CIP Tails
  { pidTag: "05-PU-004", assetNumber: "CIP-SPMP01", description: "CIP Tails Area Sump Pump", status: "mapped" },
  { pidTag: "05-PU-004M", assetNumber: "CIP-SPMP01-MTR01", description: "CIP Tails Area Sump Pump Motor", status: "mapped" },
  { pidTag: "05-PU-004MC", assetNumber: "CIP-SPMP01-MCC01", description: "CIP Tails Area Sump Pump MCC Cell", status: "mapped" },
  { pidTag: "05-PU-004LCS", assetNumber: "CIP-SPMP01-LCS01", description: "CIP Tails Area Sump Pump LCS", status: "mapped" },
  { pidTag: "05-HP-001", assetNumber: "CIP-HOP01", description: "CIP Tailings Hopper", status: "mapped" },
  { pidTag: "05-CH-004", assetNumber: "CSS01-FBX01", description: "Carbon Safety Screen Feed Box", status: "mapped" },
  { pidTag: "05-SC-005", assetNumber: "CSS01", description: "Carbon Safety Screen", status: "mapped" },
  { pidTag: "05-CH-005", assetNumber: "CSS01-UPN01", description: "Carbon Safety Screen Underpan Chute", status: "mapped" },
  { pidTag: "05-CH-006", assetNumber: "CSS01-CHU01", description: "Carbon Safety Screen Oversize Chute", status: "mapped" },
  
  // CIP Tailings Pumps
  { pidTag: "05-PU-108A", assetNumber: "CIP-PMP-A", description: "CIP Tailings Pump A", status: "mapped" },
  { pidTag: "05-PU-108AM", assetNumber: "CIP-PMP-A-MTR01", description: "CIP Tailings Pump A Motor", status: "mapped" },
  { pidTag: "05-PU-108AMC", assetNumber: "CIP-PMP-A-MCC01", description: "CIP Tailings Pump A MCC Cell", status: "mapped" },
  { pidTag: "05-PU-108ALCS", assetNumber: "CIP-PMP-A-LCS01", description: "CIP Tailings Pump A LCS", status: "mapped" },
  { pidTag: "05-PU-108AVFD", assetNumber: "CIP-PMP-A-VFD01", description: "CIP Tailings Pump A VFD", status: "mapped" },
  { pidTag: "05-FIT-930", assetNumber: "CIP-TX01", description: "Tails Flow Meter", status: "mapped" },
  { pidTag: "05-LIT-925", assetNumber: "CIP-HOP01-TX01", description: "CIP Tailings Hopper Level Transmitter", status: "mapped" },
  { pidTag: "05-PU-108B", assetNumber: "CIP-PMP-B", description: "CIP Tailings Pump B", status: "mapped" },
  { pidTag: "05-PU-108BM", assetNumber: "CIP-PMP-B-MTR01", description: "CIP Tailings Pump B Motor", status: "mapped" },
  { pidTag: "05-PU-108BMC", assetNumber: "CIP-PMP-B-MCC01", description: "CIP Tailings Pump B MCC Cell", status: "mapped" },
  { pidTag: "05-PU-108BLCS", assetNumber: "CIP-PMP-B-LCS01", description: "CIP Tailings Pump B LCS", status: "mapped" },
  { pidTag: "05-PU-108BVFD", assetNumber: "CIP-PMP-B-VFD01", description: "CIP Tailings Pump B VFD", status: "mapped" },
  { pidTag: "05-HT-001", assetNumber: "CIP-CRN01", description: "CIP Area Gantry Crane", status: "mapped" },
  
  // ============ REAGENTS ============
  { pidTag: "06-MR-101", assetNumber: "RGT-MNR01", description: "Cyanide Monorail", status: "mapped" },
  { pidTag: "06-XM-001", assetNumber: "RGT-BBR01", description: "Cyanide Bag Breaker", status: "mapped" },
  { pidTag: "06-XM-002", assetNumber: "RGT-BBR02", description: "Caustic Bag Breaker", status: "mapped" },
  { pidTag: "06-TK-001", assetNumber: "RGT-TK01", description: "Cyanide Mixing Tank", status: "mapped" },
  { pidTag: "06-AG-001", assetNumber: "RGT-TK01-AGT01", description: "Cyanide Mixing Tank Agitator", status: "mapped" },
  { pidTag: "06-AG-001M", assetNumber: "RGT-TK01-AGT01-MTR01", description: "Cyanide Mixing Tank Agitator Motor", status: "mapped" },
  { pidTag: "06-AG-001MC", assetNumber: "RGT-TK01-AGT01-MCC01", description: "Cyanide Mixing Tank Agitator MCC Cell", status: "mapped" },
  { pidTag: "06-AG-001GB", assetNumber: "RGT-TK01-AGT01-GBX01", description: "Cyanide Mixing Tank Agitator Gearbox", status: "mapped" },
  { pidTag: "06-AG-001LCS", assetNumber: "RGT-TK01-AGT01-LCS01", description: "Cyanide Mixing Tank Agitator LCS", status: "mapped" },
  { pidTag: "06-LT-938", assetNumber: "RGT-TK01-TX01", description: "Cyanide Mixing Tank Level Transmitter", status: "mapped" },
  { pidTag: "06-LT-940", assetNumber: "RGT-TK02-TX01", description: "Cyanide Storage Tank Level Transmitter", status: "mapped" },
  { pidTag: "06-PU-001", assetNumber: "RGT-PMP01", description: "Cyanide Transfer Pump", status: "mapped" },
  { pidTag: "06-PU-001M", assetNumber: "RGT-PMP01-MTR01", description: "Cyanide Transfer Pump Motor", status: "mapped" },
  { pidTag: "06-PU-001MC", assetNumber: "RGT-PMP01-MCC01", description: "Cyanide Transfer Pump MCC", status: "mapped" },
  { pidTag: "06-PU-001LCS", assetNumber: "RGT-PMP01-LCS01", description: "Cyanide Transfer Pump LCS", status: "mapped" },
  { pidTag: "06-TK-002", assetNumber: "RGT-TK02", description: "Cyanide Solution Storage Tank", status: "mapped" },
  { pidTag: "06-PU-002A", assetNumber: "RGT-PMP02A", description: "Cyanide Dosing Pump Duty", status: "mapped" },
  { pidTag: "06-PU-002AM", assetNumber: "RGT-PMP02A-MTR01", description: "Cyanide Dosing Pump Duty Motor", status: "mapped" },
  { pidTag: "06-PU-002AMC", assetNumber: "RGT-PMP02A-MCC01", description: "Cyanide Dosing Pump Duty MCC", status: "mapped" },
  { pidTag: "06-PU-002ALCS", assetNumber: "RGT-PMP02A-LCS01", description: "Cyanide Dosing Pump Duty LCS", status: "mapped" },
  { pidTag: "06-PU-002B", assetNumber: "RGT-PMP02B", description: "Cyanide Dosing Pump Stand-by", status: "mapped" },
  { pidTag: "06-PU-002BM", assetNumber: "RGT-PMP02B-MTR01", description: "Cyanide Dosing Pump Stand-by Motor", status: "mapped" },
  { pidTag: "06-PU-002BMC", assetNumber: "RGT-PMP02B-MCC01", description: "Cyanide Dosing Pump Stand-by MCC Cell", status: "mapped" },
  { pidTag: "06-PU-002BLCS", assetNumber: "RGT-PMP02B-LCS01", description: "Cyanide Dosing Pump Stand-by LCS", status: "mapped" },
  { pidTag: "06-PU-003", assetNumber: "RGT-SPMP01", description: "Cyanide Area Sump Pump", status: "mapped" },
  { pidTag: "06-PU-003M", assetNumber: "RGT-SPMP01-MTR01", description: "Cyanide Area Sump Pump Motor", status: "mapped" },
  { pidTag: "06-PU-003MC", assetNumber: "RGT-SPMP01-MCC01", description: "Cyanide Area Sump Pump MCC Cell", status: "mapped" },
  { pidTag: "06-PU-003MLCS", assetNumber: "RGT-SPMP01-LCS01", description: "Cyanide Area Sump Pump LCS", status: "mapped" },
  { pidTag: "06-SS-001", assetNumber: "RGT-SHW01", description: "Reagent Area Safety Shower 1", status: "mapped" },
  { pidTag: "06-SS-002", assetNumber: "RGT-SHW02", description: "Reagent Area Safety Shower 2", status: "mapped" },
  { pidTag: "06-PU-006", assetNumber: "RGT-PMP03", description: "Caustic Dosing Pump", status: "mapped" },
  { pidTag: "06-PU-004M", assetNumber: "RGT-PMP03-MTR01", description: "Caustic Dosing Pump Motor", status: "mapped" },
  { pidTag: "06-PU-004MC", assetNumber: "RGT-PMP03-MCC01", description: "Caustic Dosing Pump MCC Cell", status: "mapped" },
  { pidTag: "06-PU-004LCS", assetNumber: "RGT-PMP03-LCS01", description: "Caustic Dosing Pump LCS", status: "mapped" },
  
  // ============ ELUTION ============
  { pidTag: "08-PU-003", assetNumber: "ELU-PMP01", description: "Diesel Pump", status: "mapped" },
  { pidTag: "08-TK-002", assetNumber: "ELU-TK01", description: "Diesel Day Tank", status: "mapped" },
  { pidTag: "08-PU-003", assetNumber: "ELU-PMP02", description: "HCL Acid Dosing Pump", status: "mapped" },
  { pidTag: "08-PU-004", assetNumber: "ELU-SPMP01", description: "HCL Area Sump Pump", status: "mapped" },
  { pidTag: "08-HX-001", assetNumber: "ELU-HX01", description: "Elution Recovery Heat Exchange", status: "mapped" },
  { pidTag: "08-CM-002", assetNumber: "ELU-COL01", description: "Elution Column", status: "mapped" },
  { pidTag: "08-FL-02", assetNumber: "ELU-COL01-FLT01", description: "Elution Column Filters", status: "mapped" },
  
  // Elution Instruments
  { pidTag: "08-PSHH-7501", assetNumber: "ELU-INS01", description: "Eluate Pump Discharge High High Pressure Switch", status: "mapped" },
  { pidTag: "08-DPSH-7502", assetNumber: "ELU-INS02", description: "Elution Heater Differential Pressure High Switch", status: "mapped" },
  { pidTag: "08-PI-7503", assetNumber: "ELU-PG01", description: "Eluate Pump Discharge Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7504", assetNumber: "ELU-PG02", description: "Elution Heater Inlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7505", assetNumber: "ELU-PG03", description: "Elution Heater Outlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7506", assetNumber: "ELU-PG04", description: "Elution Column Outlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7507", assetNumber: "ELU-PG05", description: "Elution Column Inlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7509", assetNumber: "ELU-PG06", description: "Acid Wash Column Inlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7510", assetNumber: "ELU-PG07", description: "Acid Wash Column Discharge Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7511", assetNumber: "ELU-PG08", description: "Elution Heater Inlet Pressure Gauge 2", status: "mapped" },
  { pidTag: "08-TI-7512", assetNumber: "ELU-TG01", description: "Elution Heat Exchange Inlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-PI-7513", assetNumber: "ELU-PG09", description: "Elution Heat Exchange Outlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-TI-7514", assetNumber: "ELU-TG02", description: "Elution Heat Exchange Outlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-TI-7515", assetNumber: "ELU-TG03", description: "Eluate Pump Discharge Temperature Gauge", status: "mapped" },
  { pidTag: "08-TI-7516", assetNumber: "ELU-TG04", description: "Elution Heater Inlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-TI-7517", assetNumber: "ELU-TG05", description: "Elution Heater Outlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-TI-7518", assetNumber: "ELU-TG06", description: "Elution Column Outlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-TI-7519", assetNumber: "ELU-TG07", description: "Elution Column Inlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-TIC-7521", assetNumber: "ELU-HTR01-CTRL01", description: "Elution Heater Burner Controller", status: "mapped" },
  { pidTag: "08-TE-7522", assetNumber: "ELU-HTR01-SEN01", description: "Elution Heater Outlet Temperature Sensor", status: "mapped" },
  { pidTag: "08-TE-7524", assetNumber: "ELU-HTR01-SEN02", description: "Elution Heater Flue Temperature Sensor", status: "mapped" },
  { pidTag: "08-FE-7529", assetNumber: "ELU-HTR01-SEN03", description: "Elution Heater Inlet Flow Sensor", status: "mapped" },
  { pidTag: "08-FE-7531", assetNumber: "ELU-AWC01-SEN01", description: "Acid Wash Column HCL Flow Sensor", status: "mapped" },
  { pidTag: "08-FE-7532", assetNumber: "ELU-TK02-SEN01", description: "Eluate Tank Cyanide Feed Flow Sensor", status: "mapped" },
  { pidTag: "08-SV-7533", assetNumber: "ELU-TK02-VLV01", description: "Eluate Tank Cyanide Feed Solenoid Valve", status: "mapped" },
  { pidTag: "08-LE-7541", assetNumber: "ELU-TK02-SEN02", description: "Eluate Tank Level Sensor", status: "mapped" },
  { pidTag: "08-LSHH-7542", assetNumber: "ELU-AWC01-LSH01", description: "Acid Wash Column High High Level Switch", status: "mapped" },
  { pidTag: "06-SV-7554", assetNumber: "ELU-VLV01", description: "HCL Dosing Pump Solenoid Valve", status: "mapped" },
  { pidTag: "08-SS-001", assetNumber: "ELU-SHW01", description: "Elution Area Safety Shower", status: "mapped" },
  { pidTag: "08-PU-005", assetNumber: "ELU-SPMP02", description: "Elution Area Sump Pump", status: "mapped" },
  { pidTag: "08-PU-005M", assetNumber: "ELU-SPMP02-MTR01", description: "Elution Area Sump Pump Motor", status: "mapped" },
  { pidTag: "08-PU-005MC", assetNumber: "ELU-SPMP02-MCC01", description: "Elution Area Sump Pump MCC Cell", status: "mapped" },
  { pidTag: "08-PU-005LCS", assetNumber: "ELU-SPMP02-LCS01", description: "Elution Area Sump Pump LCS", status: "mapped" },
  { pidTag: "08-CM-001", assetNumber: "ELU-AWC01", description: "Acid Wash Column", status: "mapped" },
  { pidTag: "100-FL-001", assetNumber: "ELU-AWC01-FLT01", description: "Acid Column Filters", status: "mapped" },
  { pidTag: "08-HE-001", assetNumber: "ELU-HTR01", description: "Elution Heater", status: "mapped" },
  { pidTag: "08-BU-001", assetNumber: "ELU-HTR01-BRN01", description: "Elution Heater Burner", status: "mapped" },
  { pidTag: "08-SS-002", assetNumber: "ELU-SHW02", description: "Elution Area Safety Shower 2", status: "mapped" },
  { pidTag: "08-SS-003", assetNumber: "ELU-SHW03", description: "Gold Room Safety Shower", status: "mapped" },
  { pidTag: "08-MR-001", assetNumber: "ELU-MNR01", description: "Electrowinning Monorail", status: "mapped" },
  { pidTag: "08-TK-001", assetNumber: "ELU-TK02", description: "Eluate Tank", status: "mapped" },
  { pidTag: "08-EW-001", assetNumber: "ELU-EW01", description: "Electrowinning Cell", status: "mapped" },
  { pidTag: "08-FA-001", assetNumber: "ELU-EW01-FAN01", description: "Electrowinning Fan", status: "mapped" },
  { pidTag: "08-FA-004", assetNumber: "ELU-EW02-FAN01", description: "Gravity Electrowinning Fan", status: "mapped" },
  { pidTag: "08-EW-002", assetNumber: "ELU-EW02", description: "Gravity Electrowinning", status: "mapped" },
  { pidTag: "08-TK-004", assetNumber: "ELU-TK03", description: "Electrowinning Solution Tank", status: "mapped" },
  { pidTag: "08-PU-015", assetNumber: "ELU-PMP03", description: "Electrowinning Feed Pump", status: "mapped" },
  { pidTag: "08-PU-015M", assetNumber: "ELU-PMP03-MTR01", description: "Electrowinning Feed Pump Motor", status: "mapped" },
  { pidTag: "08-PU-015MC", assetNumber: "ELU-PMP03-MCC01", description: "Electrowinning Feed Pump MCC Cell", status: "mapped" },
  { pidTag: "08-PU-015LCS", assetNumber: "ELU-PMP03-LCS01", description: "Electrowinning Feed Pump LCS", status: "mapped" },
  { pidTag: "08-PU-001", assetNumber: "ELU-PMP04", description: "Eluate Pump", status: "mapped" },
  { pidTag: "08-PU-001M", assetNumber: "ELU-PMP04-MTR01", description: "Eluate Pump Motor", status: "mapped" },
  { pidTag: "08-PU-001MC", assetNumber: "ELU-PMP04-MCC01", description: "Eluate Pump MCC Cell", status: "mapped" },
  { pidTag: "08-PU-001LCS", assetNumber: "ELU-PMP04-LCS01", description: "Eluate Pump LCS", status: "mapped" },
  { pidTag: "08-SC-001", assetNumber: "ELU-SCR01", description: "Barron Carbon Dewatering Screen", status: "mapped" },
  { pidTag: "08-SC-001EX", assetNumber: "ELU-SCR01-EXC01", description: "Barron Carbon Dewatering Screen Excitor", status: "mapped" },
  { pidTag: "08-SC-001MC", assetNumber: "ELU-SCR01-MCC01", description: "Barron Carbon Dewatering Screen MCC Cell", status: "mapped" },
  { pidTag: "08-SC-001LCS", assetNumber: "ELU-SCR01-LCS01", description: "Barron Carbon Dewatering Screen LCS", status: "mapped" },
  { pidTag: "08-HP-001", assetNumber: "ELU-HOP01", description: "Regen Kiln Feed Hopper", status: "mapped" },
  { pidTag: "08-KN-001", assetNumber: "ELU-KLN01", description: "Carbon Regen Kiln", status: "mapped" },
  { pidTag: "08-FE-001", assetNumber: "ELU-KLN01-FDR01", description: "Regen Kiln Screw Feeder", status: "mapped" },
  { pidTag: "08-BU-003", assetNumber: "ELU-KLN01-BRN01", description: "Regen Kiln Burners", status: "mapped" },
  { pidTag: "08-HP-002", assetNumber: "ELU-HOP02", description: "Regenerated Carbon Quench Hopper", status: "mapped" },
  { pidTag: "08-PU-006", assetNumber: "ELU-PMP05", description: "Carbon Transfer Pump", status: "mapped" },
  { pidTag: "08-PU-006M", assetNumber: "ELU-PMP05-MTR01", description: "Carbon Transfer Pump Motor", status: "mapped" },
  { pidTag: "08-PU-006MC", assetNumber: "ELU-PMP05-MCC01", description: "Carbon Transfer Pump MCC Cell", status: "mapped" },
  { pidTag: "08-PU-006LCS", assetNumber: "ELU-PMP05-LCS01", description: "Carbon Transfer Pump LCS", status: "mapped" },
  
  // Regen Instruments
  { pidTag: "08-LE-7550", assetNumber: "ELU-KLN01-SEN01", description: "Regen Kiln Feed Screw Inlet Level Sensor", status: "mapped" },
  { pidTag: "08-TE-7561A", assetNumber: "ELU-KLN01-TG01", description: "Regen Kiln Zone 2 Temperature Gauge A", status: "mapped" },
  { pidTag: "08-TE-7561B", assetNumber: "ELU-KLN01-TG02", description: "Regen Kiln Zone 2 Temperature Gauge B", status: "mapped" },
  { pidTag: "08-TE-7562A", assetNumber: "ELU-KLN01-TG03", description: "Regen Kiln Zone 3 Temperature Gauge A", status: "mapped" },
  { pidTag: "08-TE-7562B", assetNumber: "ELU-KLN01-TG04", description: "Regen Kiln Zone 3 Temperature Gauge B", status: "mapped" },
  { pidTag: "08-TE-7563", assetNumber: "ELU-KLN01-SEN02", description: "Regen Kiln Discharge Temperature Sensor", status: "mapped" },
  { pidTag: "08-TE-7575A", assetNumber: "ELU-KLN01-TG05", description: "Regen Kiln Zone 1 Temperature Gauge A", status: "mapped" },
  { pidTag: "08-TE-7575B", assetNumber: "ELU-KLN01-TG06", description: "Regen Kiln Zone 1 Temperature Gauge B", status: "mapped" },
  { pidTag: "08-TE-7575C", assetNumber: "ELU-KLN01-TG07", description: "Regen Kiln Feed End Temperature Gauge", status: "mapped" },
  { pidTag: "08-LSLL-7576", assetNumber: "ELU-HOP02-LSL01", description: "Regenerated Carbon Quench Hopper Low Low Level Switch", status: "mapped" },
  { pidTag: "08-PU-011", assetNumber: "ELU-WSH01", description: "High Pressure Cathode Washer", status: "mapped" },
  { pidTag: "08-TK-003", assetNumber: "ELU-TK04", description: "Cathode Wash Box", status: "mapped" },
  { pidTag: "08-PU-009", assetNumber: "ELU-PMP06", description: "Cathode Wash Sludge Pump", status: "mapped" },
  { pidTag: "08-PU-009M", assetNumber: "ELU-PMP06-MTR01", description: "Cathode Wash Sludge Pump Motor", status: "mapped" },
  { pidTag: "08-PU-009MC", assetNumber: "ELU-PMP06-MCC01", description: "Cathode Wash Sludge Pump MCC Cell", status: "mapped" },
  { pidTag: "08-PU-009LCS", assetNumber: "ELU-PMP06-LCS01", description: "Cathode Wash Sludge Pump LCS", status: "mapped" },
  { pidTag: "08-CW-001", assetNumber: "ELU-CW01", description: "Cathode Winder", status: "mapped" },
  { pidTag: "08-FL-003", assetNumber: "ELU-FP01", description: "Cathode Sludge Filter Press", status: "mapped" },
  { pidTag: "08-CO-001", assetNumber: "ELU-OVN01", description: "Calcine Oven", status: "mapped" },
  { pidTag: "08-HD-002", assetNumber: "ELU-OVN01-HD01", description: "Calcine Oven Hood", status: "mapped" },
  { pidTag: "08-FA-002", assetNumber: "ELU-OVN01-FAN01", description: "Calcine Oven Extraction Fan", status: "mapped" },
  { pidTag: "08-BF-001", assetNumber: "ELU-FUR01", description: "Gold Room Barring Furnace", status: "mapped" },
  
  // Gold Room Instruments
  { pidTag: "08-TI-7520", assetNumber: "ELU-EW01-TG01", description: "Electrowinning Flashpot Inlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-LSHH-7539", assetNumber: "ELU-EW01-LSH01", description: "Electrowinning Flashpot High High Level Switch", status: "mapped" },
  { pidTag: "08-BU-002", assetNumber: "ELU-FUR01-FAN01", description: "Barring Furnace Extraction Fan", status: "mapped" },
  { pidTag: "08-HD-001", assetNumber: "ELU-FUR01-HD01", description: "Barring Furnace Hood", status: "mapped" },
  { pidTag: "08-XM-007", assetNumber: "ELU-WBN01", description: "Gold Room Work Bench", status: "mapped" },
  { pidTag: "08-XM-004", assetNumber: "ELU-SCL01", description: "Gold Bullion Scale", status: "mapped" },
  { pidTag: "08-XM-003", assetNumber: "ELU-SCL01-BEN01", description: "Gold Bullion Scale Bench", status: "mapped" },
  { pidTag: "08-XM-005", assetNumber: "ELU-SAF01", description: "Gold Room Bullion Safe", status: "mapped" },
  
  // ============ GRAVITY ============
  { pidTag: "04-SC-100", assetNumber: "GRV-SCR01", description: "Gravity Screen", status: "mapped" },
  { pidTag: "04-CH-103", assetNumber: "GRV-SCR01-CHU01", description: "Gravity Screen Feed Chute", status: "mapped" },
  { pidTag: "04-CH-104", assetNumber: "GRV-SCR01-UPN01", description: "Gravity Screen Under Pan", status: "mapped" },
  { pidTag: "04-CH-105", assetNumber: "GRV-SCR01-CHU02", description: "Gravity Screen Discharge Chute", status: "mapped" },
  { pidTag: "04-GC-100", assetNumber: "GRV-KNC01", description: "Knelson Concentrator", status: "mapped" },
  { pidTag: "04-GC-100CP", assetNumber: "GRV-KNC01-PNL01", description: "Knelson Concentrator Control Panel", status: "mapped" },
  { pidTag: "04-PB-112", assetNumber: "GRV-CON01", description: "Concentrate Collection Cone", status: "mapped" },
  { pidTag: "04-ST-100", assetNumber: "GRV-TBL01", description: "Concentrate Shaking Table", status: "mapped" },
  { pidTag: "04-ST-100M", assetNumber: "GRV-TBL01-MTR01", description: "Concentrate Shaking Table Motor", status: "mapped" },
  { pidTag: "04-ST-100MC", assetNumber: "GRV-TBL01-MCC01", description: "Concentrate Shaking Table MCC Cell", status: "mapped" },
  { pidTag: "04-ST-100LCS", assetNumber: "GRV-TBL01-LCS01", description: "Concentrate Shaking Table LCS", status: "mapped" },
  { pidTag: "04-ST-100GB", assetNumber: "GRV-TBL01-GBX01", description: "Concentrate Shaking Table Gearbox", status: "mapped" },
  { pidTag: "04-PU-111", assetNumber: "GRV-PMP01", description: "Gravity Tails Pump", status: "mapped" },
  { pidTag: "04-PU-111M", assetNumber: "GRV-PMP01-MTR01", description: "Gravity Tails Pump Motor", status: "mapped" },
  { pidTag: "04-PU-111MC", assetNumber: "GRV-PMP01-MCC01", description: "Gravity Tails Pump MCC Cell", status: "mapped" },
  { pidTag: "04-PU-111LCS", assetNumber: "GRV-PMP01-LCS01", description: "Gravity Tails Pump LCS", status: "mapped" },
  { pidTag: "04-MR-101", assetNumber: "GRV-HST01", description: "Knelson Area Hoist", status: "mapped" },
  { pidTag: "04-MR-101CP", assetNumber: "GRV-HST01-PNL01", description: "Knelson Area Hoist Control Panel", status: "mapped" },
  
  // ============ SERVICES ============
  { pidTag: "11-TK-202", assetNumber: "SVC-TK01", description: "Potable Water Tank", status: "mapped" },
  { pidTag: "11-TK-202P", assetNumber: "SVC-TK01-PIP01", description: "Potable Water Pipework", status: "mapped" },
  { pidTag: "11-PU-033B", assetNumber: "SVC-PMP01B", description: "Potable Water Pump Standby", status: "mapped" },
  { pidTag: "11-PU-33BMC", assetNumber: "SVC-PMP01B-MCC01", description: "Potable Water Pump Standby MCC Cell", status: "mapped" },
  { pidTag: "11-PU-33BLCS", assetNumber: "SVC-PMP01B-LCS01", description: "Potable Water Pump Standby LCS", status: "mapped" },
  { pidTag: "11-PU-033A", assetNumber: "SVC-PMP01A", description: "Potable Water Pump Duty", status: "mapped" },
  { pidTag: "11-TK-205", assetNumber: "SVC-TK02", description: "Safety Shower Water Tank", status: "mapped" },
  { pidTag: "11-TK-205P", assetNumber: "SVC-TK02-PIP01", description: "Safety Shower Water Tank Pipe Work", status: "mapped" },
  { pidTag: "11-PU-205A", assetNumber: "SVC-PMP02A", description: "Safety Shower Water Pump Duty", status: "mapped" },
  { pidTag: "11-PU-205AM", assetNumber: "SVC-PMP02A-MTR01", description: "Safety Shower Water Pump Duty Motor", status: "mapped" },
  { pidTag: "11-PU-205AMC", assetNumber: "SVC-PMP02A-MCC01", description: "Safety Shower Water Pump Duty MCC Cell", status: "mapped" },
  { pidTag: "11-PU-205ALCS", assetNumber: "SVC-PMP02A-LCS01", description: "Safety Shower Water Pump Duty LCS", status: "mapped" },
  { pidTag: "11-PU-205B", assetNumber: "SVC-PMP02B", description: "Safety Shower Water Pump Standby", status: "mapped" },
  { pidTag: "11-PU-205BM", assetNumber: "SVC-PMP02B-MTR01", description: "Safety Shower Water Pump Standby Motor", status: "mapped" },
  { pidTag: "11-PU-205BMC", assetNumber: "SVC-PMP02B-MCC01", description: "Safety Shower Water Pump Standby MCC Cell", status: "mapped" },
  { pidTag: "11-PU-205BLCS", assetNumber: "SVC-PMP02B-LCS01", description: "Safety Shower Water Pump Standby LCS", status: "mapped" },
  { pidTag: "11-TK-001", assetNumber: "SVC-TK03", description: "Raw Water Storage Tank", status: "mapped" },
  { pidTag: "11-PU-26A", assetNumber: "SVC-PMP03A", description: "Raw Water Pump Duty", status: "mapped" },
  { pidTag: "11-PU-26AM", assetNumber: "SVC-PMP03A-MTR01", description: "Raw Water Pump Duty Motor", status: "mapped" },
  { pidTag: "11-PU-26AMC", assetNumber: "SVC-PMP03A-MCC01", description: "Raw Water Pump Duty MCC Cell", status: "mapped" },
  { pidTag: "11-PU-26ALCS", assetNumber: "SVC-PMP03A-LCS01", description: "Raw Water Pump Duty LCS", status: "mapped" },
  { pidTag: "11-PU-26B", assetNumber: "SVC-PMP03B", description: "Raw Water Pump Stand-By", status: "mapped" },
  { pidTag: "11-PU-26BM", assetNumber: "SVC-PMP03B-MTR01", description: "Raw Water Pump Stand-By Motor", status: "mapped" },
  { pidTag: "11-PU-26BMC", assetNumber: "SVC-PMP03B-MCC01", description: "Raw Water Pump Stand-By MCC Cell", status: "mapped" },
  { pidTag: "11-PU-26BLCS", assetNumber: "SVC-PMP03B-LCS01", description: "Raw Water Pump Stand-By LCS", status: "mapped" },
  { pidTag: "11-TK-212", assetNumber: "SVC-TK04", description: "Gland Water Tank", status: "mapped" },
  { pidTag: "11-TK-212P", assetNumber: "SVC-TK04-PIP01", description: "Gland Water Piping", status: "mapped" },
  { pidTag: "11-PU-135A", assetNumber: "SVC-PMP04A", description: "Gland Water Pump Duty", status: "mapped" },
  { pidTag: "11-PU-135AM", assetNumber: "SVC-PMP04A-MTR01", description: "Gland Water Pump Duty Motor", status: "mapped" },
  { pidTag: "11-PU-135AMC", assetNumber: "SVC-PMP04A-MCC01", description: "Gland Water Pump Duty MCC Cell", status: "mapped" },
  { pidTag: "11-PU-135ALCS", assetNumber: "SVC-PMP04A-LCS01", description: "Gland Water Pump Duty LCS", status: "mapped" },
  { pidTag: "11-PU-135B", assetNumber: "SVC-PMP04B", description: "Gland Water Pump Stand-By", status: "mapped" },
  { pidTag: "11-PU-135BM", assetNumber: "SVC-PMP04B-MTR01", description: "Gland Water Pump Stand-By Motor", status: "mapped" },
  { pidTag: "11-PU-135BMC", assetNumber: "SVC-PMP04B-MCC01", description: "Gland Water Pump Stand-By MCC Cell", status: "mapped" },
  { pidTag: "11-PU-135BLCS", assetNumber: "SVC-PMP04B-LCS01", description: "Gland Water Pump Stand-By LCS", status: "mapped" },
  { pidTag: "11-PD-004", assetNumber: "SVC-DAM01", description: "Andys Dam", status: "mapped" },
  { pidTag: "11-PD-03", assetNumber: "SVC-PND01", description: "Process Water Pond", status: "mapped" },
  { pidTag: "11-PD-03P", assetNumber: "SVC-PND01-PIP01", description: "Process Water Piping", status: "mapped" },
  { pidTag: "11-PU-130A", assetNumber: "SVC-PMP05A", description: "Process Water Pump Duty", status: "mapped" },
  { pidTag: "11-PU-130AM", assetNumber: "SVC-PMP05A-MTR01", description: "Process Water Pump Duty Motor", status: "mapped" },
  { pidTag: "11-PU-130AMC", assetNumber: "SVC-PMP05A-MCC01", description: "Process Water Pump Duty MCC Cell", status: "mapped" },
  { pidTag: "11-PU-130ALCS", assetNumber: "SVC-PMP05A-LCS01", description: "Process Water Pump Duty LCS", status: "mapped" },
  { pidTag: "11-PU-130AVFD", assetNumber: "SVC-PMP05A-VFD01", description: "Process Water Pump Duty VFD", status: "mapped" },
  { pidTag: "11-PU-130B", assetNumber: "SVC-PMP05B", description: "Process Water Pump Stand-By", status: "mapped" },
  { pidTag: "11-PU-130BM", assetNumber: "SVC-PMP05B-MTR01", description: "Process Water Pump Stand-By Motor", status: "mapped" },
  { pidTag: "11-PU-130BMC", assetNumber: "SVC-PMP05B-MCC01", description: "Process Water Pump Stand-By MCC Cell", status: "mapped" },
  { pidTag: "11-PU-130BLCS", assetNumber: "SVC-PMP05B-LCS01", description: "Process Water Pump Stand-By LCS", status: "mapped" },
  { pidTag: "11-PU-130BVFD", assetNumber: "SVC-PMP05B-VFD01", description: "Process Water Pump Stand-By VFD", status: "mapped" },
  { pidTag: "05-CP-132", assetNumber: "SVC-CMP01", description: "HP Air Compressor 1", status: "mapped" },
  { pidTag: "05-CP-132P", assetNumber: "SVC-CMP01-PIP01", description: "HP Air Compressor 1 Piping", status: "mapped" },
  { pidTag: "05-CP-132MC", assetNumber: "SVC-CMP01-MCC01", description: "HP Air Compressor 1 MCC Cell", status: "mapped" },
  { pidTag: "05-AR-137", assetNumber: "SVC-AR01", description: "HP Air Receiver 1", status: "mapped" },
  { pidTag: "05-CP-133", assetNumber: "SVC-CMP02", description: "HP Air Compressor 2", status: "mapped" },
  { pidTag: "05-CP-133P", assetNumber: "SVC-CMP02-PIP01", description: "HP Air Compressor 2 Piping", status: "mapped" },
  { pidTag: "05-CP-133MC", assetNumber: "SVC-CMP02-MCC01", description: "HP Air Compressor 2 MCC Cell", status: "mapped" },
  { pidTag: "05-AR-138", assetNumber: "SVC-AR02", description: "HP Air Receiver 2", status: "mapped" },
  
  // ============ TAILS ============
  { pidTag: "12-TM-001", assetNumber: "TAL-THK01", description: "Tails Thickener", status: "mapped" },
  { pidTag: "12-TM-001P", assetNumber: "TAL-THK01-PIP01", description: "Tails Thickener Piping and Valves", status: "mapped" },
  { pidTag: "PU-200A", assetNumber: "TAL-PMP01A", description: "Thickener Underflow Pump A", status: "mapped" },
  { pidTag: "PU-200AM", assetNumber: "TAL-PMP01A-MTR01", description: "Thickener Underflow Pump A Motor", status: "mapped" },
  { pidTag: "PU-200AMC", assetNumber: "TAL-PMP01A-MCC01", description: "Thickener Underflow Pump A MCC Cell", status: "mapped" },
  { pidTag: "PU-200ALCS", assetNumber: "TAL-PMP01A-LCS01", description: "Thickener Underflow Pump A LCS", status: "mapped" },
  { pidTag: "PU-200AVFD", assetNumber: "TAL-PMP01A-VFD01", description: "Thickener Underflow Pump A VFD", status: "mapped" },
  { pidTag: "12-PU-200B", assetNumber: "TAL-PMP01B", description: "Thickener Underflow Pump B", status: "mapped" },
  { pidTag: "12-PU-200BM", assetNumber: "TAL-PMP01B-MTR01", description: "Thickener Underflow Pump B Motor", status: "mapped" },
  { pidTag: "12-PU-200BMC", assetNumber: "TAL-PMP01B-MCC01", description: "Thickener Underflow Pump B MCC", status: "mapped" },
  { pidTag: "12-PU-200BLCS", assetNumber: "TAL-PMP01B-LCS01", description: "Thickener Underflow Pump B LCS", status: "mapped" },
  { pidTag: "12-PU-200BVFD", assetNumber: "TAL-PMP01B-VFD01", description: "Thickener Underflow Pump B VFD", status: "mapped" },
  { pidTag: "12-PU-210", assetNumber: "TAL-SPMP01", description: "Tails Area Sump Pump", status: "mapped" },
  { pidTag: "12-PU-210M", assetNumber: "TAL-SPMP01-MTR01", description: "Tails Area Sump Pump Motor", status: "mapped" },
  { pidTag: "12-PU-210MC", assetNumber: "TAL-SPMP01-MCC01", description: "Tails Area Sump Pump MCC", status: "mapped" },
  { pidTag: "12-PU-210LCS", assetNumber: "TAL-SPMP01-LCS01", description: "Tails Area Sump Pump LCS", status: "mapped" },
  { pidTag: "12-HY-201", assetNumber: "TAL-THK01-HPU01", description: "Thickener Hydraulic Pack", status: "mapped" },
  { pidTag: "12-PU-201", assetNumber: "TAL-THK01-PMP01", description: "Thickener Hydraulic Pump", status: "mapped" },
  { pidTag: "12-PU-201M", assetNumber: "TAL-THK01-PMP01-MTR01", description: "Thickener Hydraulic Pump Motor", status: "mapped" },
  { pidTag: "12-PU-201LCS", assetNumber: "TAL-THK01-PMP01-LCS01", description: "Thickener Hydraulic Pump LCS", status: "mapped" },
  { pidTag: "12-HE-202", assetNumber: "TAL-THK01-HTR01", description: "Hydraulic Oil Heater", status: "mapped" },
  { pidTag: "12-FN-203", assetNumber: "TAL-THK01-FAN01", description: "Hydraulic Oil Cooling Fan", status: "mapped" },
  { pidTag: "12-PN-205", assetNumber: "TAL-THK01-PNL01", description: "Thickener Hydraulic Pack Panel", status: "mapped" },
  { pidTag: "12-PN-205IN", assetNumber: "TAL-THK01-INS01", description: "Thickener Hydraulic Pack Instruments", status: "mapped" },
  
  // Floc System
  { pidTag: "12-PN-206", assetNumber: "TAL-FLC01", description: "Flocc Panel 1", status: "mapped" },
  { pidTag: "12-PN-207", assetNumber: "TAL-FLC02", description: "Flocc Panel 2", status: "mapped" },
  { pidTag: "12-PN-208", assetNumber: "TAL-CLR01", description: "Clarometer Panel", status: "mapped" },
  
  // Filter Press Area
  { pidTag: "13-FP-300", assetNumber: "FLT-FP00", description: "Tails Filter Press Area", status: "mapped" },
  { pidTag: "13-CP-133", assetNumber: "FLT-CMP01", description: "Filter Area HP Air Compressor", status: "mapped" },
  { pidTag: "13-CP-133P", assetNumber: "FLT-CMP01-PIP01", description: "HP Air Compressor Piping", status: "mapped" },
  { pidTag: "13-CP-133MC", assetNumber: "FLT-CMP01-MCC01", description: "HP Air Compressor MCC Cell", status: "mapped" },
  { pidTag: "13-AR-139", assetNumber: "FLT-AR01", description: "HP Air Receiver 1", status: "mapped" },
  { pidTag: "13-AR-140", assetNumber: "FLT-AR02", description: "HP Air Receiver 2", status: "mapped" },
  
  // Filter Press 1
  { pidTag: "13-FP-301", assetNumber: "FLT-FP01", description: "Filter Press 1", status: "mapped" },
  { pidTag: "13-PU-301", assetNumber: "FLT-FP01-PMP01", description: "Filter 1 Feed Pump", status: "mapped" },
  { pidTag: "13-PU-301M", assetNumber: "FLT-FP01-PMP01-MTR01", description: "Filter 1 Feed Pump Motor", status: "mapped" },
  { pidTag: "13-PU-301VFD", assetNumber: "FLT-FP01-PMP01-VFD01", description: "Filter 1 Feed Pump VFD", status: "mapped" },
  { pidTag: "13-PU-301MC", assetNumber: "FLT-FP01-PMP01-MCC01", description: "Filter 1 Feed Pump MCC Cell", status: "mapped" },
  { pidTag: "13-CV-301", assetNumber: "FLT-FP01-CV01", description: "Filter 1 Extraction Conveyor", status: "mapped" },
  { pidTag: "13-CV-301M", assetNumber: "FLT-FP01-CV01-MTR01", description: "Filter 1 Extraction Motor", status: "mapped" },
  { pidTag: "13-CV-301GB", assetNumber: "FLT-FP01-CV01-GBX01", description: "Filter 1 Extraction Gearbox", status: "mapped" },
  { pidTag: "13-CV-301VFD", assetNumber: "FLT-FP01-CV01-VFD01", description: "Filter 1 Extraction Conveyor VFD", status: "mapped" },
  { pidTag: "13-CV-301MC", assetNumber: "FLT-FP01-CV01-MCC01", description: "Filter 1 Extraction Conveyor MCC Cell", status: "mapped" },
  { pidTag: "13-TK-301", assetNumber: "FLT-FP01-TK01", description: "Filter 1 Stock Tank", status: "mapped" },
  { pidTag: "13-AG-301", assetNumber: "FLT-FP01-AGT01", description: "Filter 1 Stock Tank Agitator", status: "mapped" },
  { pidTag: "13-AG-301M", assetNumber: "FLT-FP01-AGT01-MTR01", description: "Filter 1 Stock Tank Agitator Motor", status: "mapped" },
  { pidTag: "13-AG-301GB", assetNumber: "FLT-FP01-AGT01-GBX01", description: "Filter 1 Stock Tank Agitator Gearbox", status: "mapped" },
  { pidTag: "13-AG-301MC", assetNumber: "FLT-FP01-AGT01-MCC01", description: "Filter 1 Stock Tank Agitator MCC Cell", status: "mapped" },
  { pidTag: "13-PN-301PLC", assetNumber: "FLT-FP01-PLC01", description: "Filter 1 PLC", status: "mapped" },
  { pidTag: "13-FP-301IN", assetNumber: "FLT-FP01-INS01", description: "Filter 1 Instruments", status: "mapped" },
  { pidTag: "13-FP-301P", assetNumber: "FLT-FP01-PIP01", description: "Filter 1 Piping and Valves", status: "mapped" },
  { pidTag: "13-PN-301", assetNumber: "FLT-FP01-PNL01", description: "Filter Press 1 Panel", status: "mapped" },
  { pidTag: "13-HY-301", assetNumber: "FLT-FP01-HPU01", description: "Filter Press 1 Hydraulic Pack", status: "mapped" },
  { pidTag: "13-HP-301", assetNumber: "FLT-FP01-HPU01-PMP01", description: "Filter Press 1 Hydraulic Plate Pack Pump", status: "mapped" },
  { pidTag: "13-HP-301M", assetNumber: "FLT-FP01-HPU01-MTR01", description: "Filter Press 1 Hydraulic Plate Pack Motor", status: "mapped" },
  { pidTag: "13-HP-301MC", assetNumber: "FLT-FP01-HPU01-MCC01", description: "Filter Press 1 Hydraulic Plate Pack MCC Cell", status: "mapped" },
  { pidTag: "13-HP-301B", assetNumber: "FLT-FP01-HPU01-PMP02", description: "Filter Press 1 Hydraulic TT Plate Pump", status: "mapped" },
  { pidTag: "13-HP-301BM", assetNumber: "FLT-FP01-HPU01-MTR02", description: "Filter Press 1 Hydraulic TT Plate Motor", status: "mapped" },
  { pidTag: "13-HP-301BMC", assetNumber: "FLT-FP01-HPU01-MCC02", description: "Filter Press 1 Hydraulic TT Plate MCC Cell", status: "mapped" },
  
  // Filter Press 2
  { pidTag: "13-FP-302", assetNumber: "FLT-FP02", description: "Filter Press 2", status: "mapped" },
  { pidTag: "13-PU-302", assetNumber: "FLT-FP02-PMP01", description: "Filter 2 Feed Pump", status: "mapped" },
  { pidTag: "13-PU-302M", assetNumber: "FLT-FP02-PMP01-MTR01", description: "Filter 2 Feed Pump Motor", status: "mapped" },
  { pidTag: "13-PU-302VFD", assetNumber: "FLT-FP02-PMP01-VFD01", description: "Filter 2 Feed Pump VFD", status: "mapped" },
  { pidTag: "13-PU-302MC", assetNumber: "FLT-FP02-PMP01-MCC01", description: "Filter 2 Feed Pump MCC Cell", status: "mapped" },
  { pidTag: "13-CV-302", assetNumber: "FLT-FP02-CV01", description: "Filter 2 Extraction Conveyor", status: "mapped" },
  { pidTag: "13-CV-302M", assetNumber: "FLT-FP02-CV01-MTR01", description: "Filter 2 Extraction Motor", status: "mapped" },
  { pidTag: "13-CV-302GB", assetNumber: "FLT-FP02-CV01-GBX01", description: "Filter 2 Extraction Gearbox", status: "mapped" },
  { pidTag: "13-CV-302VFD", assetNumber: "FLT-FP02-CV01-VFD01", description: "Filter 2 Extraction Conveyor VFD", status: "mapped" },
  { pidTag: "13-CV-302MC", assetNumber: "FLT-FP02-CV01-MCC01", description: "Filter 2 Extraction Conveyor MCC Cell", status: "mapped" },
  { pidTag: "13-TK-302", assetNumber: "FLT-FP02-TK01", description: "Filter 2 Stock Tank", status: "mapped" },
  { pidTag: "13-AG-302", assetNumber: "FLT-FP02-AGT01", description: "Filter 2 Stock Tank Agitator", status: "mapped" },
  { pidTag: "13-AG-302M", assetNumber: "FLT-FP02-AGT01-MTR01", description: "Filter 2 Stock Tank Agitator Motor", status: "mapped" },
  { pidTag: "13-AG-302GB", assetNumber: "FLT-FP02-AGT01-GBX01", description: "Filter 2 Stock Tank Agitator Gearbox", status: "mapped" },
  { pidTag: "13-AG-302MC", assetNumber: "FLT-FP02-AGT01-MCC01", description: "Filter 2 Stock Tank Agitator MCC Cell", status: "mapped" },
  { pidTag: "13-PN-302PLC", assetNumber: "FLT-FP02-PLC01", description: "Filter 2 PLC", status: "mapped" },
  { pidTag: "13-FP-302IN", assetNumber: "FLT-FP02-INS01", description: "Filter 2 Instruments", status: "mapped" },
  { pidTag: "13-FP-302P", assetNumber: "FLT-FP02-PIP01", description: "Filter 2 Piping and Valves", status: "mapped" },
  { pidTag: "13-PN-302", assetNumber: "FLT-FP02-PNL01", description: "Filter Press 2 Panel", status: "mapped" },
  { pidTag: "13-HY-302", assetNumber: "FLT-FP02-HPU01", description: "Filter Press 2 Hydraulic Pack", status: "mapped" },
  { pidTag: "13-HP-302", assetNumber: "FLT-FP02-HPU01-PMP01", description: "Filter Press 2 Hydraulic Plate Pack Pump", status: "mapped" },
  { pidTag: "13-HP-302M", assetNumber: "FLT-FP02-HPU01-MTR01", description: "Filter Press 2 Hydraulic Plate Pack Motor", status: "mapped" },
  { pidTag: "13-HP-3012MC", assetNumber: "FLT-FP02-HPU01-MCC01", description: "Filter Press 2 Hydraulic Plate Pack MCC Cell", status: "mapped" },
  { pidTag: "13-HP-302B", assetNumber: "FLT-FP02-HPU01-PMP02", description: "Filter Press 2 Hydraulic TT Plate Pump", status: "mapped" },
  { pidTag: "13-HP-302BM", assetNumber: "FLT-FP02-HPU01-MTR02", description: "Filter Press 2 Hydraulic TT Plate Motor", status: "mapped" },
  { pidTag: "13-HP-302BMC", assetNumber: "FLT-FP02-HPU01-MCC02", description: "Filter Press 2 Hydraulic TT Plate MCC Cell", status: "mapped" },
  
  // Collection & Stacker Conveyors
  { pidTag: "13-CV-303", assetNumber: "FLT-CV01", description: "Tails Filter Press Collection Conveyor", status: "mapped" },
  { pidTag: "13-CV-303M", assetNumber: "FLT-CV01-MTR01", description: "Tails Filter Press Collection Conveyor Motor", status: "mapped" },
  { pidTag: "13-CV-303GB", assetNumber: "FLT-CV01-GBX01", description: "Tails Filter Press Collection Conveyor Gearbox", status: "mapped" },
  { pidTag: "13-CV-303MC", assetNumber: "FLT-CV01-MCC01", description: "Tails Filter Press Collection Conveyor MCC Cell", status: "mapped" },
  { pidTag: "13-CV-303VFD", assetNumber: "FLT-CV01-VFD01", description: "Tails Filter Press Collection Conveyor VFD", status: "mapped" },
  { pidTag: "13-CV-304", assetNumber: "FLT-CV02", description: "Tails Filter Press Radial Stacker Conveyor", status: "mapped" },
  { pidTag: "13-CV-304DAM", assetNumber: "FLT-CV02-MTR01", description: "Radial Stacker Conveyor Drive Motor A", status: "mapped" },
  { pidTag: "13-CV-304DBM", assetNumber: "FLT-CV02-MTR02", description: "Radial Stacker Conveyor Drive Motor B", status: "mapped" },
  { pidTag: "13-CV-304WDAM", assetNumber: "FLT-CV02-MTR03", description: "Radial Stacker Conveyor Wheel Drive Motor A", status: "mapped" },
  { pidTag: "13-CV-304WDBM", assetNumber: "FLT-CV02-MTR04", description: "Radial Stacker Conveyor Wheel Drive Motor B", status: "mapped" },
  { pidTag: "13-CV-304DGBA", assetNumber: "FLT-CV02-GBX01", description: "Radial Stacker Conveyor Drive Gear Box A", status: "mapped" },
  { pidTag: "13-CV-304DGBB", assetNumber: "FLT-CV02-GBX02", description: "Radial Stacker Conveyor Drive Gear Box B", status: "mapped" },
  { pidTag: "13-CV-304WDGBA", assetNumber: "FLT-CV02-GBX03", description: "Radial Stacker Conveyor Wheel Drive Gearbox A", status: "mapped" },
  { pidTag: "13-CV-304WDGBB", assetNumber: "FLT-CV02-GBX04", description: "Radial Stacker Conveyor Wheel Drive Gearbox B", status: "mapped" },
  { pidTag: "13-CV-304DAMC", assetNumber: "FLT-CV02-MCC01", description: "Radial Stacker Conveyor Drive A MCC Cell", status: "mapped" },
  { pidTag: "13-CV-304DBMC", assetNumber: "FLT-CV02-MCC02", description: "Radial Stacker Conveyor Drive B MCC Cell", status: "mapped" },
  { pidTag: "13-CV-304WDAMC", assetNumber: "FLT-CV02-MCC03", description: "Radial Stacker Conveyor Wheel Drive A MCC Cell", status: "mapped" },
  { pidTag: "13-CV-304WDBMC", assetNumber: "FLT-CV02-MCC04", description: "Radial Stacker Conveyor Wheel Drive B MCC Cell", status: "mapped" },
  { pidTag: "13-PU-330", assetNumber: "FLT-SPMP01", description: "Filter Area Sump Pump", status: "mapped" },
  { pidTag: "13-PU-330M", assetNumber: "FLT-SPMP01-MTR01", description: "Filter Area Sump Pump Motor", status: "mapped" },
  { pidTag: "13-PU-330LCS", assetNumber: "FLT-SPMP01-LCS01", description: "Filter Area Sump Pump LCS", status: "mapped" },
  { pidTag: "13-PU-330MC", assetNumber: "FLT-SPMP01-MCC01", description: "Filter Area Sump Pump MCC Cell", status: "mapped" },
  
  // ============ POWER GENERATION ============
  { pidTag: "17-Sub-100", assetNumber: "MSUB01", description: "Main Sub Station", status: "mapped" },
  { pidTag: "17-GN-001", assetNumber: "GEN01", description: "Power Station Generator 1 500kVA", status: "mapped" },
  { pidTag: "17-GN-002", assetNumber: "GEN02", description: "Power Station Generator 2 500kVA", status: "mapped" },
  { pidTag: "17-GN-003", assetNumber: "GEN03", description: "Power Station Generator 3 500kVA", status: "mapped" },
  { pidTag: "17-GN-004", assetNumber: "GEN04", description: "Power Station Generator 4 500kVA", status: "mapped" },
  { pidTag: "17-GN-005", assetNumber: "GEN05", description: "Power Station Generator 5 500kVA", status: "mapped" },
  { pidTag: "17-GN-006", assetNumber: "GEN06", description: "Power Station Generator 6 500kVA", status: "mapped" },
  { pidTag: "17-GN-007", assetNumber: "GEN07", description: "Power Station Generator 7 500kVA", status: "mapped" },
  { pidTag: "17-GN-008", assetNumber: "GEN08", description: "Power Station Generator 8 500kVA", status: "mapped" },
  { pidTag: "17-GN-009", assetNumber: "GEN-ADM01", description: "Admin Generator 50kVA", status: "mapped" },
  { pidTag: "17-GN-010", assetNumber: "GEN-SPR01", description: "Spare Generator", status: "mapped" },
  { pidTag: "17-GN-012", assetNumber: "GEN-LAB01", description: "Lab Generator 30kVA", status: "mapped" },
  { pidTag: "17-GN-016", assetNumber: "GEN-JUNO01", description: "Juno Bore Generator 200kVA", status: "mapped" },
  { pidTag: "17-GN-017", assetNumber: "GEN-WRK01", description: "Mining Workshop 75kVA", status: "mapped" },
  
  // ============ FIELD MCCs ============
  { pidTag: "18-MCC-110", assetNumber: "MFC01-MCC02", description: "Mill Feed Conveyor Field MCC", status: "mapped" },
  { pidTag: "18-MCC-111", assetNumber: "BM01-MCC01", description: "Mill Area Field MCC", status: "mapped" },
  { pidTag: "18-MCC-112", assetNumber: "GRAV-MCC01", description: "Gravity Field MCC", status: "mapped" },
  { pidTag: "18-MCC-113", assetNumber: "CIP-MCC01", description: "Tanks Field MCC 1", status: "mapped" },
  { pidTag: "18-MCC-114", assetNumber: "CIP-MCC02", description: "Tanks Field MCC 2", status: "mapped" },
  { pidTag: "18-MCC-116", assetNumber: "CIP-MCC03", description: "Tanks Field MCC 3", status: "mapped" },
  { pidTag: "18-MCC-117", assetNumber: "CIP-MCC04", description: "Tanks Field MCC 4", status: "mapped" },
  { pidTag: "18-MCC-118", assetNumber: "THK-MCC01", description: "Thickener Field MCC", status: "mapped" },
  { pidTag: "18-MCC-120", assetNumber: "REAG-MCC01", description: "Reagents Field MCC", status: "mapped" },
  { pidTag: "18-MCC-121", assetNumber: "SVC-MCC01", description: "Services Field MCC", status: "mapped" },
  { pidTag: "18-MCC-122", assetNumber: "PWP01-MCC01", description: "Process Water Field MCC", status: "mapped" },
  { pidTag: "18-MCC-125", assetNumber: "FLT-MCC01", description: "Filter Press Field MCC", status: "mapped" },
  { pidTag: "18-MCC-130", assetNumber: "ELU-MCC01", description: "Elution Area Field MCC", status: "mapped" },
  
  // ============ DISTRIBUTION BOARDS ============
  { pidTag: "DB-102", assetNumber: "SDB01-LP01", description: "Sub-100 L&P", status: "mapped" },
  { pidTag: "DB-105", assetNumber: "LAB-DB01", description: "Main DB Lab", status: "mapped" },
  { pidTag: "DB-101", assetNumber: "SDB01-ESS01", description: "Sub-100 Essential Board", status: "mapped" },
  { pidTag: "DB-103", assetNumber: "MSUB01-DB01", description: "RO Plant Main Board", status: "mapped" },
  { pidTag: "DB-104", assetNumber: "FDISP01-DB01", description: "Fuel Dispensing Control Board", status: "mapped" },
  { pidTag: "SB-003B", assetNumber: "MDB01-DB01", description: "Ice Machine Room DB", status: "mapped" },
  { pidTag: "DB-003", assetNumber: "WSP-DB01", description: "Workshop DB", status: "mapped" },
  { pidTag: "SB-003A", assetNumber: "SVC02-DB01", description: "Lath Container L&P", status: "mapped" },
  { pidTag: "SB-002E", assetNumber: "SVC02-DB02", description: "Crib Room L&P DB", status: "mapped" },
  { pidTag: "SB-002F", assetNumber: "SVC02-DB03", description: "Conference Building L&P", status: "mapped" },
  { pidTag: "SB-002G", assetNumber: "SVC02-DB04", description: "First Aid Room L&P DB", status: "mapped" },
  { pidTag: "DB-001", assetNumber: "MDB01-DB02", description: "Main DB 1", status: "mapped" },
  { pidTag: "DB-002", assetNumber: "MDB01-DB03", description: "Main DB 2", status: "mapped" },
  { pidTag: "SB-001A", assetNumber: "SINF07-DB01", description: "Male Toilet L&P DB", status: "mapped" },
  { pidTag: "SB-002A", assetNumber: "SINF03-DB01", description: "Admin Office L&P DB 1", status: "mapped" },
  { pidTag: "SB-002B", assetNumber: "SINF03-DB02", description: "Admin Office L&P DB 2", status: "mapped" },
  { pidTag: "SB-002C", assetNumber: "SINF03-DB03", description: "Admin Office L&P DB 3", status: "mapped" },
  { pidTag: "SB-002D", assetNumber: "SINF03-DB04", description: "Admin Office L&P DB 4", status: "mapped" },
  { pidTag: "SB-105A", assetNumber: "LAB-DB02", description: "Lab L&P DB", status: "mapped" },
  { pidTag: "MCC-125-SB-001A", assetNumber: "MDB01-LP01", description: "MCC-125 L&P", status: "mapped" },
  { pidTag: "MCC-110-SB-001A", assetNumber: "MDB01-LP02", description: "MCC-110 L&P", status: "mapped" },
  { pidTag: "MCC-111-SB-001A", assetNumber: "MDB01-LP03", description: "MCC-111 L&P", status: "mapped" },
  { pidTag: "MCC-113-SB-001A", assetNumber: "MDB01-LP04", description: "MCC-113 L&P", status: "mapped" },
  { pidTag: "MCC-114-SB-001A", assetNumber: "MDB01-LP05", description: "MCC-114 L&P", status: "mapped" },
  { pidTag: "MCC-115-SB-001A", assetNumber: "MDB01-LP06", description: "MCC-115 L&P", status: "mapped" },
  { pidTag: "MCC-116-SB-001A", assetNumber: "MDB01-LP07", description: "MCC-116 L&P", status: "mapped" },
  { pidTag: "MCC-117-SB-001A", assetNumber: "MDB01-LP08", description: "MCC-117 L&P", status: "mapped" },
  { pidTag: "MCC-118-SB-001A", assetNumber: "MDB01-LP09", description: "MCC-118 L&P", status: "mapped" },
  { pidTag: "MCC-120-SB-001A", assetNumber: "MDB01-LP10", description: "MCC-120 L&P", status: "mapped" },
  { pidTag: "MCC-121-SB-001A", assetNumber: "MDB01-LP11", description: "MCC-121 L&P", status: "mapped" },
  { pidTag: "MCC-122-SB-001A", assetNumber: "MDB01-LP12", description: "MCC-122 L&P", status: "mapped" },
  { pidTag: "MCC-130-SB-001A", assetNumber: "MDB01-LP13", description: "MCC-130 L&P", status: "mapped" },
  { pidTag: "SB-102A", assetNumber: "CR01-DB01", description: "Control Room L&P DB", status: "mapped" },
  { pidTag: "MCC-XXX-SB-001B", assetNumber: "MDB01-LP14", description: "Titration Hut L&P DB", status: "mapped" },
  
  // ============ BUILDINGS ============
  { pidTag: "16-BU-001", assetNumber: "SINF03", description: "Admin Building", status: "mapped" },
  { pidTag: "16-BU-002", assetNumber: "WSP01", description: "Workshop", status: "mapped" },
  { pidTag: "16-BU-003", assetNumber: "SINF04", description: "Crib", status: "mapped" },
  { pidTag: "16-BU-004", assetNumber: "SINF05", description: "Conference", status: "mapped" },
  { pidTag: "16-BU-005", assetNumber: "SINF06", description: "First Aid Room", status: "mapped" },
  { pidTag: "16-BU-006", assetNumber: "SINF07", description: "Male Toilet", status: "mapped" },
  { pidTag: "16-BU-007", assetNumber: "SINF08", description: "Female Toilet", status: "mapped" },
  { pidTag: "16-BU-008", assetNumber: "CR01", description: "Control Room", status: "mapped" },
  { pidTag: "16-BU-009", assetNumber: "SDB01", description: "Sub-100", status: "mapped" },
  { pidTag: "16-BU-010", assetNumber: "LAB01", description: "Lab", status: "mapped" },
  { pidTag: "16-BU-011", assetNumber: "TTR01", description: "Titration Hut", status: "mapped" },
  { pidTag: "16-BU-012", assetNumber: "CDH01", description: "Cyanide Dosing Hut", status: "mapped" },
  
  // ============ LIGHT VEHICLES ============
  { pidTag: "14-LV-005", assetNumber: "LV-005", description: "LC Military", status: "mapped" },
  { pidTag: "14-LV-011", assetNumber: "LV-011", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-012", assetNumber: "LV-012", description: "Ford Ranger XL dual Cab", status: "mapped" },
  { pidTag: "14-LV-014", assetNumber: "LV-014", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-015", assetNumber: "LV-015", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-016", assetNumber: "LV-016", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-017", assetNumber: "LV-017", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-018", assetNumber: "LV-018", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-019", assetNumber: "LV-019", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-020", assetNumber: "LV-020", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-021", assetNumber: "LV-021", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-022", assetNumber: "LV-022", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-023", assetNumber: "LV-023", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-024", assetNumber: "LV-024", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-026", assetNumber: "LV-026", description: "Ranger single Cab", status: "mapped" },
  { pidTag: "14-LV-027", assetNumber: "LV-027", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-028", assetNumber: "LV-028", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-029", assetNumber: "LV-029", description: "Kia", status: "mapped" },
  { pidTag: "14-LV-030", assetNumber: "LV-030", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-BUS-01", assetNumber: "BUS-01", description: "Toyota Hiace", status: "mapped" },
  { pidTag: "14-BUS-02", assetNumber: "BUS-02", description: "Toyota Hiace", status: "mapped" },
  { pidTag: "14-BUS-03", assetNumber: "BUS-03", description: "LDV Discovery 9", status: "mapped" },
  { pidTag: "14-BUS-04", assetNumber: "BUS-04", description: "LDV Discovery 9", status: "mapped" },
  { pidTag: "14-LV-013", assetNumber: "LV-013", description: "Fuso TF Canter Flat Top Truck", status: "mapped" },
  
  // ============ MOBILE EQUIPMENT & LIGHTING TOWERS ============
  { pidTag: "15-PR-002", assetNumber: "CRN01", description: "25t Franner crane", status: "mapped" },
  { pidTag: "15-PR-003", assetNumber: "FLT01", description: "Forklift", status: "mapped" },
  { pidTag: "15-PR-004", assetNumber: "TLH01", description: "Telehandler", status: "mapped" },
  { pidTag: "15-PR-001", assetNumber: "BCT01", description: "Bob Cat", status: "mapped" },
  { pidTag: "15-WC-001", assetNumber: "WTK01", description: "Water Truck", status: "mapped" },
  { pidTag: "15-ST-001", assetNumber: "STK01", description: "Service Truck", status: "mapped" },
  { pidTag: "15-PR-005", assetNumber: "EWP01", description: "Sino EWP", status: "mapped" },
  { pidTag: "15-PR-006", assetNumber: "EWP02", description: "Hire EWP", status: "mapped" },
  { pidTag: "15-PR-007", assetNumber: "SL01", description: "Sino Scissor Lift 1", status: "mapped" },
  { pidTag: "15-PR-008", assetNumber: "SL02", description: "Sino Scissor Lift 2", status: "mapped" },
  { pidTag: "15-WL-001", assetNumber: "LDR01", description: "Cat 980 Loader 1", status: "mapped" },
  { pidTag: "15-WL-002", assetNumber: "LDR02", description: "Cat 980 Loader 2", status: "mapped" },
  { pidTag: "15-WL-003", assetNumber: "LDR03", description: "Cat 980 Loader 3", status: "mapped" },
  { pidTag: "15-WL-004", assetNumber: "LDR04", description: "Cat 980 Loader 4", status: "mapped" },
  { pidTag: "15-EX-001", assetNumber: "EXC01", description: "Cat 30t Excavator", status: "mapped" },
  { pidTag: "15-EX-002", assetNumber: "EXC02", description: "Case Excavator", status: "mapped" },
  { pidTag: "15-DT-001", assetNumber: "MXY01", description: "Cat Moxy 1", status: "mapped" },
  { pidTag: "15-DT-002", assetNumber: "MXY02", description: "Cat Moxy 2", status: "mapped" },
  { pidTag: "15-DT-003", assetNumber: "MXY03", description: "Cat Moxy 3", status: "mapped" },
  { pidTag: "15-LT-001", assetNumber: "LTW01", description: "Lighting Tower 1", status: "mapped" },
  { pidTag: "15-LT-002", assetNumber: "LTW02", description: "Lighting Tower 2", status: "mapped" },
  { pidTag: "15-LT-003", assetNumber: "LTW03", description: "Lighting Tower 3", status: "mapped" },
  { pidTag: "15-LT-004", assetNumber: "LTW04", description: "Lighting Tower 4", status: "mapped" },
  { pidTag: "15-LT-005", assetNumber: "LTW05", description: "Lighting Tower 5", status: "mapped" },
];

// Helper function to get P&ID tag by asset number
export const getPidTagByAssetNumber = (assetNumber: string): string => {
  const mapping = pidTagMappings.find(m => m.assetNumber === assetNumber);
  return mapping?.pidTag || "";
};

// Helper function to get asset number by P&ID tag
export const getAssetNumberByPidTag = (pidTag: string): string => {
  const mapping = pidTagMappings.find(m => m.pidTag === pidTag);
  return mapping?.assetNumber || "";
};
