// Legacy P&ID Tag to Asset Number Mappings
// These tags are stored as searchable metadata only - they do not appear in asset names/numbers

export interface PidTagMapping {
  pidTag: string;
  assetNumber: string;
  description: string;
  status: "mapped" | "unmapped";
}

// Comprehensive P&ID tag mappings organized by area
export const pidTagMappings: PidTagMapping[] = [
  // ============ GRINDING / COMMINUTION ============
  // Reclaim / Feed System
  { pidTag: "FE-100", assetNumber: "APRN001", description: "Reclaim Feeder", status: "mapped" },
  { pidTag: "04-PB-099", assetNumber: "RHOP001", description: "Reclaim Hopper", status: "mapped" },
  { pidTag: "04-FE-100LCS", assetNumber: "APRN001-LCS001", description: "Reclaim Feeder LCS", status: "mapped" },
  { pidTag: "04-FE-100M", assetNumber: "APRN001-MTR001", description: "Reclaim Feeder Motor", status: "mapped" },
  { pidTag: "04-FE-100MC", assetNumber: "APRN001-MCC001", description: "Reclaim Feeder MCC Cell", status: "mapped" },
  { pidTag: "04-FE-100GB", assetNumber: "APRN001-GBX001", description: "Reclaim Feeder Gearbox", status: "mapped" },
  { pidTag: "04-FE-100-PWS", assetNumber: "APRN001-PWS001", description: "Reclaim Feeder Pullwire switch", status: "mapped" },
  { pidTag: "04-SIT-500", assetNumber: "APRN001-TX001", description: "Reclaim Feeder Speed Transmitter", status: "mapped" },
  
  // Transfer Conveyor
  { pidTag: "04-FE-101", assetNumber: "CV01", description: "Transfer Conveyor", status: "mapped" },
  { pidTag: "04-CH-100", assetNumber: "CV01-CHU001", description: "Transfer Conveyor Discharge Chute", status: "mapped" },
  { pidTag: "04-FE-101LCS", assetNumber: "CV01-LCS001", description: "Transfer Conveyor Local Control Station", status: "mapped" },
  { pidTag: "04-FE-101M", assetNumber: "CV01-MTR001", description: "Transfer Conveyor Motor", status: "mapped" },
  { pidTag: "04-FE-101MC", assetNumber: "CV01-MCC001", description: "Transfer Conveyor MCC Cell", status: "mapped" },
  { pidTag: "04-FE-101GB", assetNumber: "CV01-GBX001", description: "Transfer Conveyor Gearbox", status: "mapped" },
  { pidTag: "04-FE-101PWS", assetNumber: "CV01-PWS001", description: "Transfer Conveyor Pull Wire Switch", status: "mapped" },
  
  // Mill Feed Conveyor
  { pidTag: "04-BC-100", assetNumber: "MFC001", description: "Mill Feed Conveyor", status: "mapped" },
  { pidTag: "04-BC-100LCS", assetNumber: "MFC001-LCS001", description: "Mill Feed Conveyor Local Control station", status: "mapped" },
  { pidTag: "04-BC-100M", assetNumber: "MFC001-MTR001", description: "Mill Feed Conveyor Motor", status: "mapped" },
  { pidTag: "04-BC-100MC", assetNumber: "MFC001-MCC001", description: "Mill Feed Conveyor MCC Cell", status: "mapped" },
  { pidTag: "04-BC-100GB", assetNumber: "MFC001-GBX001", description: "Mill Feed Conveyor Gearbox", status: "mapped" },
  { pidTag: "04-SS-506", assetNumber: "MFC001-USS001", description: "Feed Conveyor Underspeed Switch", status: "mapped" },
  { pidTag: "04-WE-506", assetNumber: "MFC001-WTM001", description: "Ball Mill Feed Conveyor Weightometer Loadcells", status: "mapped" },
  { pidTag: "04-WQIT-506", assetNumber: "MFC001-WTM002", description: "Ball Mill Feed Conveyor Weightometer Transmitter", status: "mapped" },
  { pidTag: "04-XS-507A", assetNumber: "MFC001-PWS001", description: "Feed Conveyor Pull Wire Switch 1", status: "mapped" },
  { pidTag: "04-XS-507B", assetNumber: "MFC001-PWS002", description: "Feed Conveyor Pull Wire Switch 2", status: "mapped" },
  { pidTag: "04-XS-507C", assetNumber: "MFC001-PWS003", description: "Feed Conveyor Pull Wire Switch 3", status: "mapped" },
  { pidTag: "04-XS-507D", assetNumber: "MFC001-PWS004", description: "Feed Conveyor Pull Wire Switch 4", status: "mapped" },
  { pidTag: "04-ZS-508A", assetNumber: "MFC001-BAS001", description: "Feed Conveyor Belt Alignment Switch 1", status: "mapped" },
  { pidTag: "04-ZS-508B", assetNumber: "MFC001-BAS002", description: "Feed Conveyor Belt Alignment Switch 2", status: "mapped" },
  { pidTag: "04-ZS-508C", assetNumber: "MFC001-BAS003", description: "Feed Conveyor Belt Alignment Switch 3", status: "mapped" },
  { pidTag: "04-ZS-508D", assetNumber: "MFC001-BAS004", description: "Feed Conveyor Belt Alignment Switch 4", status: "mapped" },
  { pidTag: "04-LSH-510", assetNumber: "FHOP001-HLS001", description: "Ball Mill Feed Chute High Level Switch", status: "mapped" },
  { pidTag: "04-CH-101", assetNumber: "MFC001-CHU001", description: "Mill Feed Conveyor Discharge Chute", status: "mapped" },
  { pidTag: "04-CH-102", assetNumber: "FHOP001-CHU001", description: "Mill Feed Chute", status: "mapped" },
  { pidTag: "04-CH-010", assetNumber: "FHOP001-CHU002", description: "Ball Loading Chute", status: "mapped" },
  
  // Lime System
  { pidTag: "04-TK-100", assetNumber: "LSILO001", description: "Lime Storage Silo", status: "mapped" },
  { pidTag: "04-FE-102", assetNumber: "APRN001-VLV001", description: "Lime Feeder Rotary Valve", status: "mapped" },
  { pidTag: "-BA-103", assetNumber: "LSILO001-VIB001", description: "Lime Silo Vibrator", status: "mapped" },
  
  // Primary Ball Mill
  { pidTag: "04-ML-100", assetNumber: "BM001", description: "Primary Ball Mill", status: "mapped" },
  { pidTag: "04-ML-100M", assetNumber: "BM001-MTR001", description: "Primary Ball Mill Motor", status: "mapped" },
  { pidTag: "04-ML-100GB", assetNumber: "BM001-GBX001", description: "Primary Ball Mill Gearbox", status: "mapped" },
  { pidTag: "04-ML-100P", assetNumber: "BM001-PIN001", description: "Primary Ball Mill Pinion", status: "mapped" },
  { pidTag: "04-ML-100MC", assetNumber: "BM001-MCC001", description: "Primary Ball Mill MCC Cell", status: "mapped" },
  { pidTag: "04-ML-100VSD", assetNumber: "BM001-VSD001", description: "Primary Ball Mill VSD", status: "mapped" },
  { pidTag: "04-ML-100I", assetNumber: "BM001-LUB003", description: "Primary Ball mill Instruments", status: "mapped" },
  { pidTag: "04-TIT-536", assetNumber: "MFC001-TX001", description: "Feed End Trunnion Bearing Temperature Transmitter", status: "mapped" },
  { pidTag: "04-TE-536X", assetNumber: "MFC001-SEN001", description: "Feed End Trunnion Bearing Temperature Sensor 1", status: "mapped" },
  { pidTag: "04-TE-536Y", assetNumber: "MFC001-SEN002", description: "Feed End Trunnion Bearing Temperature Sensor 2", status: "mapped" },
  { pidTag: "04-TE-536Z", assetNumber: "MFC001-SEN003", description: "Feed End Trunnion Bearing Temperature Sensor 3", status: "mapped" },
  { pidTag: "04-TIT-537", assetNumber: "MFC001-TX002", description: "Dis End Trunnion Bearing Temperature Transmitter", status: "mapped" },
  { pidTag: "04-TE-537X", assetNumber: "MFC001-SEN004", description: "Dis End Trunnion Bearing Temperature Sensor 1", status: "mapped" },
  { pidTag: "04-TE-537Y", assetNumber: "MFC001-SEN005", description: "Dis End Trunnion Bearing Temperature Sensor 2", status: "mapped" },
  { pidTag: "04-TE-537Z", assetNumber: "MFC001-SEN006", description: "Dis End Trunnion Bearing Temperature Sensor 3", status: "mapped" },
  { pidTag: "04-TE-538", assetNumber: "BM001-RED001-INS001", description: "Mill Gear Reducer Temperature", status: "mapped" },
  { pidTag: "04-FCV-545", assetNumber: "BM001-VLV001", description: "Mill Discharge End Water Addition Control Valve", status: "mapped" },
  { pidTag: "04-FIT-545", assetNumber: "BM001-TX001", description: "Mill Discharge End Water Addition Flow Transmitter", status: "mapped" },
  { pidTag: "-LE-550", assetNumber: "BM001-TX002", description: "Mill Discharge Hopper Level Transmitter", status: "mapped" },
  { pidTag: "04-PB-105", assetNumber: "FHOP001-BOX001", description: "Primary Mill Feed Boiler Box", status: "mapped" },
  { pidTag: "04-GR-100", assetNumber: "BM001-RED001", description: "Primary Ball Mill Gear Reducer", status: "mapped" },
  { pidTag: "04-MR-100", assetNumber: "BM001-MNR001", description: "Ball Mill Loading Monorail", status: "mapped" },
  { pidTag: "04-CV-011", assetNumber: "CV02", description: "Ball Mill Scatts Conveyor", status: "mapped" },
  { pidTag: "04-SS-01", assetNumber: "MILL-SHW01", description: "Mill Area Safety Shower 1", status: "mapped" },
  { pidTag: "04-SS-02", assetNumber: "MILL-SHW02", description: "Mill Area Safety Shower 2", status: "mapped" },
  
  // Ball Mill Lube System
  { pidTag: "04-PU-016", assetNumber: "BM001-PMP001", description: "Primary Ball Mill Lube Recirculating Pump", status: "mapped" },
  { pidTag: "04-PU-016M", assetNumber: "BM001-MTR002", description: "Primary Ball Mill Lube Recirculating Pump Motor", status: "mapped" },
  { pidTag: "04-PU-016MC", assetNumber: "BM001-MCC002", description: "Primary Ball Mill Lube Recirculating Pump MCC Cell", status: "mapped" },
  { pidTag: "04-PU-016LCS", assetNumber: "BM001-LCS001", description: "Primary Ball Mill Lube Recirculating Pump LCS", status: "mapped" },
  { pidTag: "04-LS-100", assetNumber: "BM001-LUB001", description: "Primary Ball Mill Lube System", status: "mapped" },
  { pidTag: "04-FA-006", assetNumber: "BM001-LUB002", description: "Primary Ball Mill Lube Air Blast Oil Cooler", status: "mapped" },
  { pidTag: "04-FA-006M", assetNumber: "BM001-MTR003", description: "Primary Ball Mill Lube Air Blast Oil Cooler Motor", status: "mapped" },
  { pidTag: "04-FA-006MC", assetNumber: "BM001-MCC003", description: "Primary Ball Mill Lube Air Blast Oil Cooler MCC Cell", status: "mapped" },
  { pidTag: "04-FA-06LCS", assetNumber: "BM001-LCS002", description: "Primary Ball Mill Lube Air Blast Oil Cooler LCS", status: "mapped" },
  { pidTag: "04-PU-100A", assetNumber: "BM001-PMP002", description: "Primary Ball Mill Low Pressure Lube Pump A", status: "mapped" },
  { pidTag: "04-PU-100AM", assetNumber: "BM001-MTR004", description: "Primary Ball Mill Low Pressure Lube Pump A Motor", status: "mapped" },
  { pidTag: "04-PU-100AMC", assetNumber: "BM001-MCC004", description: "Primary Ball Mill Low Pressure Lube Pump A MCC Cell", status: "mapped" },
  { pidTag: "04-PU-100ALCS", assetNumber: "BM001-LCS003", description: "Primary Ball Mill Low Pressure Lube Pump A LCS", status: "mapped" },
  { pidTag: "04-PU-100B", assetNumber: "BM001-PMP003", description: "Primary Ball Mill Low Pressure Lube Pump B", status: "mapped" },
  { pidTag: "04-PU-100BM", assetNumber: "BM001-MTR005", description: "Primary Ball Mill Low Pressure Lube Pump B Motor", status: "mapped" },
  { pidTag: "04-PU-100BMC", assetNumber: "BM001-MCC005", description: "Primary Ball Mill Low Pressure Lube Pump B MCC Cell", status: "mapped" },
  { pidTag: "04-PU-100BLCS", assetNumber: "BM001-LCS004", description: "Primary Ball Mill Low Pressure Lube Pump B LCS", status: "mapped" },
  
  // Grinding Sump
  { pidTag: "04-PU-120", assetNumber: "GSPMP001-PMP001", description: "Grinding Area Sump Pump", status: "mapped" },
  { pidTag: "04-PU-120M", assetNumber: "GSPMP001-MTR001", description: "Grinding Area Sump Pump Motor", status: "mapped" },
  { pidTag: "04-PU-120MC", assetNumber: "GSPMP001-MCC001", description: "Grinding Area Sump Pump MCC Cell", status: "mapped" },
  { pidTag: "04-PU-120LCS", assetNumber: "GSPMP001-LCS001", description: "Grinding Area Sump Pump LCS", status: "mapped" },
  
  // High Pressure Lube
  { pidTag: "04-PU-101", assetNumber: "BM001-PMP004", description: "Primary Ball Mill High Pressure Lube Pump", status: "mapped" },
  { pidTag: "04-PU-101M", assetNumber: "BM001-MTR006", description: "Primary Ball Mill High Pressure Lube Pump Motor", status: "mapped" },
  { pidTag: "04-PU-101MC", assetNumber: "BM001-MCC006", description: "Primary Ball Mill High Pressure Lube Pump MCC Cell", status: "mapped" },
  { pidTag: "04-LS-100I", assetNumber: "BM001-LUB003", description: "Primary Mill Lube System Instruments", status: "mapped" },
  { pidTag: "04-PIT-520", assetNumber: "BM001-TX003", description: "Mill Low Pressure Lube Oil Pressure Transmitter", status: "mapped" },
  { pidTag: "04-FIT-521", assetNumber: "BM001-TX004", description: "Mill Low Pressure Lube Oil Flow Transmitter", status: "mapped" },
  { pidTag: "04-PIT-525", assetNumber: "BM001-TX005", description: "Mill High Pressure Lift Lube Oil Pressure Transmitter", status: "mapped" },
  { pidTag: "04-FE-526", assetNumber: "BM001-LUB004", description: "Mill High Pressure Lift Lube Oil Flow", status: "mapped" },
  { pidTag: "04-FIT-526", assetNumber: "BM001-TX006", description: "Mill High Pressure Lift Lube Oil Flow Transmitter", status: "mapped" },
  { pidTag: "04-LIT-528", assetNumber: "BM001-LUB005", description: "Mill Lube System Oil Level", status: "mapped" },
  { pidTag: "04-TIT-529", assetNumber: "BM001-LUB006", description: "Mill Lube System Oil Temperature", status: "mapped" },
  { pidTag: "04-PU-101LCS", assetNumber: "BM001-LCS005", description: "Primary Ball Mill High Pressure Lube Pump LCS", status: "mapped" },
  { pidTag: "04-LS-101", assetNumber: "BM001-LUB007", description: "Primary Ball Mill Girth Gear Lube System", status: "mapped" },
  { pidTag: "04-LS-101P", assetNumber: "BM001-PMP005", description: "Primary Ball Mill Girth Gear Lube System Pump", status: "mapped" },
  { pidTag: "04-LS-101CP", assetNumber: "BM001-LUB008", description: "Primary Ball Mill Girth Gear Lube System Control Panel", status: "mapped" },
  { pidTag: "04-FL-100A", assetNumber: "BM001-LUB009", description: "Primary Ball Mill Lube System Filter A", status: "mapped" },
  { pidTag: "04-FL-100B", assetNumber: "BM001-LUB010", description: "Primary Ball Mill Lube System Filter B", status: "mapped" },
  { pidTag: "04-PB-100", assetNumber: "BM001-HOP001", description: "Primary Mill Discharge Hopper", status: "mapped" },
  
  // Primary Cyclone Feed Pumps
  { pidTag: "04-PU-102A", assetNumber: "PCFPA001", description: "Primary Cyclone Feed Pump A", status: "mapped" },
  { pidTag: "04-PU-102AM", assetNumber: "PCFPA001-MTR001", description: "Primary Cyclone Feed Pump A Motor", status: "mapped" },
  { pidTag: "04-PU-102AMC", assetNumber: "PCFPA001-MCC001", description: "Primary Cyclone Feed Pump A MCC Cell", status: "mapped" },
  { pidTag: "04-PU-102ALCS", assetNumber: "PCFPA001-LCS001", description: "Primary Cyclone Feed Pump A LCS", status: "mapped" },
  { pidTag: "04-PU-102B", assetNumber: "PCFPB001", description: "Primary Cyclone Feed Pump B", status: "mapped" },
  { pidTag: "04-PU-102BM", assetNumber: "PCFPB001-MTR001", description: "Primary Cyclone Feed Pump B Motor", status: "mapped" },
  { pidTag: "04-PU-102BMC", assetNumber: "PCFPB001-MCC001", description: "Primary Cyclone Feed Pump B MCC Cell", status: "mapped" },
  { pidTag: "04-PU-102BLCS", assetNumber: "PCFPB001-LCS001", description: "Primary Cyclone Feed Pump B LCS", status: "mapped" },
  { pidTag: "04-XV-", assetNumber: "PCFI001-VLV001", description: "Primary Cyclone Feed TechTaylor Valve", status: "mapped" },
  
  // Primary Cyclone Cluster
  { pidTag: "04-CY-100", assetNumber: "CYC001", description: "Primary Cyclone Cluster", status: "mapped" },
  { pidTag: "04-CY-100I", assetNumber: "CYC001-INS001", description: "Primary Cyclone Cluster Instruments", status: "mapped" },
  { pidTag: "04-FIT-551", assetNumber: "PCFI001-TX001", description: "Primary Cyclone Feed Flow Transmitter", status: "mapped" },
  { pidTag: "04-PIT-552", assetNumber: "CYC001-TX001", description: "Primary Cyclone Pressure Transmitter", status: "mapped" },
  { pidTag: "04-PI-552A", assetNumber: "CYC001-PG001", description: "Primary Cyclone Pressure Gauge", status: "mapped" },
  { pidTag: "04-PB-101", assetNumber: "CYC001-SPL001", description: "Primary Cyclone Underflow Splitter Box", status: "mapped" },
  
  // ============ CIP AREA ============
  { pidTag: "05-CIP-01", assetNumber: "CIP-TK01", description: "CIP Area", status: "mapped" },
  { pidTag: "05-CH-001", assetNumber: "CPTS001-FBX001", description: "CIP Trash Screen Feed Box", status: "mapped" },
  { pidTag: "05-SC-001", assetNumber: "CPTS001", description: "CIP Feed Trash Screen", status: "mapped" },
  { pidTag: "05-SC-001EXA", assetNumber: "CPTS001-EXC001", description: "CIP Feed Trash Screen Exciter A", status: "mapped" },
  { pidTag: "05-SC-001EXALCS", assetNumber: "CPTS001-LCS001", description: "CIP Feed Trash Screen Exciter A LCS", status: "mapped" },
  { pidTag: "05-SC-001EXAMC", assetNumber: "CPTS001-MCC001", description: "CIP Feed Trash Screen Exciter A MCC Cell", status: "mapped" },
  { pidTag: "05-SC-001EXB", assetNumber: "CPTS001-EXC002", description: "CIP Feed Trash Screen Exciter B", status: "mapped" },
  { pidTag: "05-SC-001EXBLCS", assetNumber: "CPTS001-LCS002", description: "CIP Feed Trash Screen Exciter B LCS", status: "mapped" },
  { pidTag: "05-SC-001EXBMC", assetNumber: "CPTS001-MCC002", description: "CIP Feed Trash Screen Exciter B MCC Cell", status: "mapped" },
  { pidTag: "05-SC-001SB", assetNumber: "CPTS001-SPR001", description: "CIP Feed Trash Screen Spray Bars", status: "mapped" },
  { pidTag: "05-CH-002", assetNumber: "CPTS001-CHU001", description: "CIP Trash Screen Oversize Chute", status: "mapped" },
  
  // CIP Sump
  { pidTag: "05-PU-005", assetNumber: "CIP-PMP001", description: "CIP Leach Area Sump Pump", status: "mapped" },
  { pidTag: "05-PU-005M", assetNumber: "CIP-PMP001", description: "CIP Leach Area Sump Pump Motor", status: "mapped" },
  { pidTag: "05-PU-005MC", assetNumber: "CIP-PMP001", description: "CIP Leach Area Sump Pump MCC Cell", status: "mapped" },
  { pidTag: "05-PU-005LCS", assetNumber: "CIP-PMP001", description: "CIP Leach Area Sump Pump LCS", status: "mapped" },
  
  // CIP Safety Showers
  { pidTag: "05-SS", assetNumber: "CIP-SHW01", description: "CIP Area Safety Showers", status: "mapped" },
  { pidTag: "05-SS-001", assetNumber: "CIP-SHW01", description: "CIP Area Safety Shower 1", status: "mapped" },
  { pidTag: "05-SS-002", assetNumber: "CIP-SHW02", description: "CIP Area Safety Shower 2", status: "mapped" },
  { pidTag: "05-SS-003", assetNumber: "CIP-SHW04", description: "CIP Tails Area Safety Shower", status: "mapped" },
  
  // CIP Tank 1
  { pidTag: "05-TK-001", assetNumber: "CIP-TK01", description: "CIP Leach Tank 1", status: "mapped" },
  { pidTag: "05-AG-001", assetNumber: "CIP-TK01-AGT001", description: "CIP Leach Tank 1 Agitator", status: "mapped" },
  { pidTag: "05-AG-001M", assetNumber: "CIP-TK01-MTR001", description: "CIP Leach Tank 1 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-001MC", assetNumber: "CIP-TK01-MCC001", description: "CIP Leach Tank 1 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-001GB", assetNumber: "CIP-TK01-GBX001", description: "CIP Leach Tank 1 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-001LCS", assetNumber: "CIP-TK01-LCS001", description: "CIP Leach Tank 1 Agitator LCS", status: "mapped" },
  { pidTag: "05-AIT-933", assetNumber: "CIP-TK01", description: "CIP Leach Tank 1 PH Probe", status: "mapped" },
  { pidTag: "05-XM-001", assetNumber: "CIP-NZL01", description: "Leach Tank 1 Air Sparge Nozzles", status: "mapped" },
  
  // CIP Tank 2
  { pidTag: "05-TK-002", assetNumber: "CIP-TK02", description: "CIP Leach Tank 2", status: "mapped" },
  { pidTag: "05-AG-002", assetNumber: "CIP-TK02-AGT001", description: "CIP Leach Tank 2 Agitator", status: "mapped" },
  { pidTag: "05-AG-002M", assetNumber: "CIP-TK02-MTR001", description: "CIP Leach Tank 2 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-002MC", assetNumber: "CIP-TK02-MCC001", description: "CIP Leach Tank 2 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-00GB", assetNumber: "CIP-TK02-GBX001", description: "CIP Leach Tank 2 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-002LCS", assetNumber: "CIP-TK02-LCS001", description: "CIP Leach Tank 2 Agitator LCS", status: "mapped" },
  { pidTag: "05-XM-002", assetNumber: "CIP-NZL02", description: "Leach Tank 2 Air Sparge Nozzles", status: "mapped" },
  
  // Loaded Carbon Screen
  { pidTag: "05-CH-7", assetNumber: "LDCS001-FBX001", description: "Loaded Carbon Screen Feedbox", status: "mapped" },
  { pidTag: "05-SC-010", assetNumber: "LDCS001", description: "Loaded Carbon Screen", status: "mapped" },
  { pidTag: "05-SC-010EX", assetNumber: "LDCS001-EXC001", description: "Loaded Carbon Screen Exciter A", status: "mapped" },
  { pidTag: "05-SC-010EXALCS", assetNumber: "LDCS001-LCS001", description: "Loaded Carbon Screen Exciter A LCS", status: "mapped" },
  { pidTag: "05-SC-010EXAMC", assetNumber: "LDCS001-MCC001", description: "Loaded Carbon Screen Exciter A MCC Cell", status: "mapped" },
  { pidTag: "05-SC-010EXB", assetNumber: "LDCS001-EXC002", description: "Loaded Carbon Screen Exciter B", status: "mapped" },
  { pidTag: "05-SC-010EXBLCS", assetNumber: "LDCS001-LCS002", description: "Loaded Carbon Screen Exciter B LCS", status: "mapped" },
  { pidTag: "05-SC-010EXBMC", assetNumber: "LDCS001-MCC002", description: "Loaded Carbon Screen Exciter B MCC Cell", status: "mapped" },
  { pidTag: "05-SC-010EXSB", assetNumber: "LDCS001-SPR001", description: "Loaded Carbon Screen Spray Bars", status: "mapped" },
  { pidTag: "05-CH-009", assetNumber: "LDCS001-PAN001", description: "Loaded Carbon Screen Underpan", status: "mapped" },
  { pidTag: "05-CH-008", assetNumber: "LDCS001-CHU001", description: "Loaded Carbon Screen Oversize Chute", status: "mapped" },
  
  // CIP Tanks 3-8
  { pidTag: "05-TK-003", assetNumber: "CIP-TK03", description: "CIP Tank 3", status: "mapped" },
  { pidTag: "05-AG-003", assetNumber: "CIP-TK03-AGT001", description: "CIP Tank 3 Agitator", status: "mapped" },
  { pidTag: "05-AG-003M", assetNumber: "CIP-TK03-MTR001", description: "CIP Tank 3 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-003MC", assetNumber: "CIP-TK03-MCC001", description: "CIP Tank 3 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-003GB", assetNumber: "CIP-TK03-GBX001", description: "CIP Tank 3 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-003LCS", assetNumber: "CIP-TK03-LCS001", description: "CIP Tank 3 Agitator LCS", status: "mapped" },
  
  { pidTag: "05-TK-004", assetNumber: "CIP-TK04", description: "CIP Tank 4", status: "mapped" },
  { pidTag: "05-AG-004", assetNumber: "CIP-TK04-AGT001", description: "CIP Tank 4 Agitator", status: "mapped" },
  { pidTag: "05-AG-004M", assetNumber: "CIP-TK04-MTR001", description: "CIP Tank 4 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-004MC", assetNumber: "CIP-TK04-MCC001", description: "CIP Tank 4 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-004GB", assetNumber: "CIP-TK04-GBX001", description: "CIP Tank 4 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-004LCS", assetNumber: "CIP-TK04-LCS001", description: "CIP Tank 4 Agitator LCS", status: "mapped" },
  
  { pidTag: "05-TK-005", assetNumber: "CIP-TK05", description: "CIP Tank 5", status: "mapped" },
  { pidTag: "05-AG-005", assetNumber: "CIP-TK05-AGT001", description: "CIP Tank 5 Agitator", status: "mapped" },
  { pidTag: "05-AG-005M", assetNumber: "CIP-TK05-MTR001", description: "CIP Tank 5 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-005MC", assetNumber: "CIP-TK05-MCC001", description: "CIP Tank 5 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-005GB", assetNumber: "CIP-TK05-GBX001", description: "CIP Tank 5 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-005LCS", assetNumber: "CIP-TK05-LCS001", description: "CIP Tank 5 Agitator LCS", status: "mapped" },
  
  { pidTag: "05-TK-006", assetNumber: "CIP-TK06", description: "CIP Tank 6", status: "mapped" },
  { pidTag: "05-AG-006", assetNumber: "CIP-TK06-AGT001", description: "CIP Tank 6 Agitator", status: "mapped" },
  { pidTag: "05-AG-006M", assetNumber: "CIP-TK06-MTR001", description: "CIP Tank 6 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-006MC", assetNumber: "CIP-TK06-MCC001", description: "CIP Tank 6 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-006GB", assetNumber: "CIP-TK06-GBX001", description: "CIP Tank 6 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-006LCS", assetNumber: "CIP-TK06-LCS001", description: "CIP Tank 6 Agitator LCS", status: "mapped" },
  
  { pidTag: "05-TK-007", assetNumber: "CIP-TK07", description: "CIP Tank 7", status: "mapped" },
  { pidTag: "05-AG-007", assetNumber: "CIP-TK07-AGT001", description: "CIP Tank 7 Agitator", status: "mapped" },
  { pidTag: "05-AG-007M", assetNumber: "CIP-TK07-MTR001", description: "CIP Tank 7 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-007MC", assetNumber: "CIP-TK07-MCC001", description: "CIP Tank 7 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-007GB", assetNumber: "CIP-TK07-GBX001", description: "CIP Tank 7 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-007LCS", assetNumber: "CIP-TK07-LCS001", description: "CIP Tank 7 Agitator LCS", status: "mapped" },
  
  { pidTag: "05-TK-008", assetNumber: "CIP-TK08", description: "CIP Tank 8", status: "mapped" },
  { pidTag: "05-AG-008", assetNumber: "CIP-TK08-AGT001", description: "CIP Tank 8 Agitator", status: "mapped" },
  { pidTag: "05-AG-008M", assetNumber: "CIP-TK08-MTR001", description: "CIP Tank 8 Agitator Motor", status: "mapped" },
  { pidTag: "05-AG-008MC", assetNumber: "CIP-TK08-MCC001", description: "CIP Tank 8 Agitator MCC Cell", status: "mapped" },
  { pidTag: "05-AG-008GB", assetNumber: "CIP-TK08-GBX001", description: "CIP Tank 8 Agitator Gear Box", status: "mapped" },
  { pidTag: "05-AG-008LCS", assetNumber: "CIP-TK08-LCS001", description: "CIP Tank 8 Agitator LCS", status: "mapped" },
  
  // Carbon Transfer Air Lifts
  { pidTag: "05-AL-002", assetNumber: "CIP-ALF02", description: "Carbon Transfer Air Lift 2", status: "mapped" },
  { pidTag: "05-AL-003", assetNumber: "CIP-ALF03", description: "Carbon Transfer Air Lift 3", status: "mapped" },
  { pidTag: "05-AL-004", assetNumber: "CIP-ALF04", description: "Carbon Transfer Air Lift 4", status: "mapped" },
  { pidTag: "05-AL-005", assetNumber: "CIP-ALF05", description: "Carbon Transfer Air Lift 5", status: "mapped" },
  { pidTag: "05-AL-006", assetNumber: "CIP-ALF06", description: "Carbon Transfer Air Lift 6", status: "mapped" },
  
  // CIP Inter Tank Screens
  { pidTag: "05-SC-002", assetNumber: "CITS001", description: "CIP Inter Tank Screen 1", status: "mapped" },
  { pidTag: "05-SC-002M", assetNumber: "CITS001-MTR001", description: "CIP Inter Tank Screen 1 Motor", status: "mapped" },
  { pidTag: "05-SC-002MC", assetNumber: "CITS001-MCC001", description: "CIP Inter Tank Screen 1 MCC Cell", status: "mapped" },
  { pidTag: "05-SC-00GB", assetNumber: "CITS001-GBX001", description: "CIP Inter Tank Screen 1 Gearbox", status: "mapped" },
  { pidTag: "05-SC-002LCS", assetNumber: "CITS001-LCS001", description: "CIP Inter Tank Screen 1 LCS", status: "mapped" },
  
  { pidTag: "05-SC-003", assetNumber: "CITS002", description: "CIP Inter Tank Screen 2", status: "mapped" },
  { pidTag: "05-SC-003M", assetNumber: "CITS002-MTR001", description: "CIP Inter Tank Screen 2 Motor", status: "mapped" },
  { pidTag: "05-SC-003MC", assetNumber: "CITS002-MCC001", description: "CIP Inter Tank Screen 2 MCC Cell", status: "mapped" },
  { pidTag: "05-SC-003GB", assetNumber: "CITS002-GBX001", description: "CIP Inter Tank Screen 2 Gearbox", status: "mapped" },
  { pidTag: "05-SC-003LCS", assetNumber: "CITS002-LCS001", description: "CIP Inter Tank Screen 2 LCS", status: "mapped" },
  
  { pidTag: "05-SC-004", assetNumber: "CITS005", description: "CIP Inter Tank Screen 5", status: "mapped" },
  { pidTag: "05-SC-007", assetNumber: "CITS006", description: "CIP Inter Tank Screen 6", status: "mapped" },
  
  // CIP Tails
  { pidTag: "05-PU-004", assetNumber: "CIPSMP001", description: "CIP Tails Area Sump Pump", status: "mapped" },
  { pidTag: "05-PU-004M", assetNumber: "CIPSMP001-MTR001", description: "CIP Tails Area Sump Pump Motor", status: "mapped" },
  { pidTag: "05-PU-004MC", assetNumber: "CIPSMP001-MCC001", description: "CIP Tails Area Sump Pump MCC Cell", status: "mapped" },
  { pidTag: "05-PU-004LCS", assetNumber: "CIPSMP001-LCS001", description: "CIP Tails Area Sump Pump LCS", status: "mapped" },
  { pidTag: "05-HP-001", assetNumber: "TAILHOP001", description: "CIP Tailings Hopper", status: "mapped" },
  
  // Carbon Safety Screen
  { pidTag: "05-CH-004", assetNumber: "CSS001", description: "Carbon Safety Screen Feed Box", status: "mapped" },
  { pidTag: "05-SC-005", assetNumber: "CSS001-SCR001", description: "Carbon Safety Screen", status: "mapped" },
  { pidTag: "05-CH-005", assetNumber: "CSS001-CHU001", description: "Carbon Safety Screen Underpan Chute", status: "mapped" },
  { pidTag: "05-CH-006", assetNumber: "CSS001-CHU002", description: "Carbon Safety Screen Oversize Chute", status: "mapped" },
  
  // CIP Tailings Pumps
  { pidTag: "05-PU-108A", assetNumber: "CIPPMP-A", description: "CIP Tailings Pump A", status: "mapped" },
  { pidTag: "05-PU-108AM", assetNumber: "CIPPMP-A-MTR001", description: "CIP Tailings Pump A Motor", status: "mapped" },
  { pidTag: "05-PU-108AMC", assetNumber: "CIPPMP-A-MCC001", description: "CIP Tailings Pump A MCC Cell", status: "mapped" },
  { pidTag: "05-PU-108ALCS", assetNumber: "CIPPMP-A-LCS001", description: "CIP Tailings Pump A LCS", status: "mapped" },
  { pidTag: "05-PU-108AVFD", assetNumber: "CIPPMP-A-VSD001", description: "CIP Tailings Pump A VSD", status: "mapped" },
  { pidTag: "05-PU-108B", assetNumber: "CIPPMP-B", description: "CIP Tailings Pump B", status: "mapped" },
  { pidTag: "05-PU-108BM", assetNumber: "CIPPMP-B-MTR001", description: "CIP Tailings Pump B Motor", status: "mapped" },
  { pidTag: "05-PU-108BMC", assetNumber: "CIPPMP-B-MCC001", description: "CIP Tailings Pump B MCC Cell", status: "mapped" },
  { pidTag: "05-PU-108BLCS", assetNumber: "CIPPMP-B-LCS001", description: "CIP Tailings Pump B LCS", status: "mapped" },
  { pidTag: "05-PU-108BVFD", assetNumber: "CIPPMP-B-VSD001", description: "CIP Tailings Pump B VSD", status: "mapped" },
  
  // Tails Instruments
  { pidTag: "05-FIT-930", assetNumber: "THK001-FM001", description: "Tails Flow Meter", status: "mapped" },
  { pidTag: "05-LIT-925", assetNumber: "TAILHOP001-LT001", description: "CIP Tailings Hopper Level Transmitter", status: "mapped" },
  
  // CIP Crane
  { pidTag: "05-HT-001", assetNumber: "CRN001", description: "CIP Area Gantry Crane", status: "mapped" },
  
  // ============ REAGENTS / CYANIDE ============
  { pidTag: "06-MR-101", assetNumber: "CMNR001", description: "Cyanide Monorail", status: "mapped" },
  { pidTag: "06-XM-001", assetNumber: "CBB001", description: "Cyanide Bag Breaker", status: "mapped" },
  { pidTag: "06-XM-002", assetNumber: "CABB001", description: "Caustic Bag Breaker", status: "mapped" },
  { pidTag: "06-TK-001", assetNumber: "CMIX001-TK001", description: "Cyanide Mixing Tank", status: "mapped" },
  { pidTag: "06-AG-001", assetNumber: "CMIX001-AGT001", description: "Cyanide Mixing Tank Agitator", status: "mapped" },
  { pidTag: "06-AG-001M", assetNumber: "CMIX001-MTR001", description: "Cyanide Mixing Tank Agitator Motor", status: "mapped" },
  { pidTag: "06-AG-001MC", assetNumber: "CMIX001-MCC001", description: "Cyanide Mixing Tank Agitator MCC Cell", status: "mapped" },
  { pidTag: "06-AG-001GB", assetNumber: "CMIX001-GBX001", description: "Cyanide Mixing Tank Agitator Gearbox", status: "mapped" },
  { pidTag: "06-AG-001LCS", assetNumber: "CMIX001-LCS001", description: "Cyanide Mixing Tank Agitator LCS", status: "mapped" },
  { pidTag: "06-LT-938", assetNumber: "CMIX001-TX001", description: "Cyanide Mixing Tank Level Transmitter", status: "mapped" },
  { pidTag: "06-LT-940", assetNumber: "CSTR001-TX001", description: "Cyanide Storage Tank Level Transmitter", status: "mapped" },
  { pidTag: "06-PU-001", assetNumber: "CXFR001-PMP001", description: "Cyanide Transfer Pump", status: "mapped" },
  { pidTag: "06-PU-001M", assetNumber: "CXFR001-MTR001", description: "Cyanide Transfer Pump Motor", status: "mapped" },
  { pidTag: "06-PU-001MC", assetNumber: "CXFR001-MCC001", description: "Cyanide Transfer Pump MCC", status: "mapped" },
  { pidTag: "06-PU-001LCS", assetNumber: "CXFR001-LCS001", description: "Cyanide Transfer Pump LCS", status: "mapped" },
  { pidTag: "06-TK-002", assetNumber: "CSTR001", description: "Cyanide Solution Storage Tank", status: "mapped" },
  { pidTag: "06-PU-002A", assetNumber: "CDOS001-PMP001", description: "Cyanide Dosing Pump Duty", status: "mapped" },
  { pidTag: "06-PU-002AM", assetNumber: "CXFR001-MTR001", description: "Cyanide Transfer Pump Motor", status: "mapped" },
  { pidTag: "06-PU-002AMC", assetNumber: "CXFR001-MCC001", description: "Cyanide Transfer Pump MCC", status: "mapped" },
  { pidTag: "06-PU-002ALCS", assetNumber: "CXFR001-LCS001", description: "Cyanide Transfer Pump LCS", status: "mapped" },
  { pidTag: "06-PU-002B", assetNumber: "CDOS001-PMP002", description: "Cyanide Dosing Pump Stand-by", status: "mapped" },
  { pidTag: "06-PU-002BM", assetNumber: "CDOS001-MTR001", description: "Cyanide Dosing Pump Stand-by Motor", status: "mapped" },
  { pidTag: "06-PU-002BMC", assetNumber: "CDOS001-MCC001", description: "Cyanide Dosing Pump Stand-by MCC Cell", status: "mapped" },
  { pidTag: "06-PU-002BLCS", assetNumber: "CDOS001-LCS001", description: "Cyanide Dosing Pump Stand-by LCS", status: "mapped" },
  { pidTag: "06-PU-003", assetNumber: "CSMP001-PMP001", description: "Cyanide Area Sump Pump", status: "mapped" },
  { pidTag: "06-PU-003M", assetNumber: "CSMP001-MTR001", description: "Cyanide Area Sump Pump Motor", status: "mapped" },
  { pidTag: "06-PU-003MC", assetNumber: "CSMP001-MCC001", description: "Cyanide Area Sump Pump MCC Cell", status: "mapped" },
  { pidTag: "06-PU-003MLCS", assetNumber: "CSMP001-LCS001", description: "Cyanide Area Sump Pump LCS", status: "mapped" },
  { pidTag: "06-SS-001", assetNumber: "REAG-SHW001", description: "Reagent Area Safety Shower 1", status: "mapped" },
  { pidTag: "06-SS-002", assetNumber: "REAG-SHW002", description: "Reagent Area Safety Shower 2", status: "mapped" },
  { pidTag: "06-PU-006", assetNumber: "CAUS001-PMP001", description: "Caustic Dosing Pump", status: "mapped" },
  { pidTag: "06-PU-004M", assetNumber: "CAUS001-MTR001", description: "Caustic Dosing Pump Motor", status: "mapped" },
  { pidTag: "06-PU-004MC", assetNumber: "CAUS001-MCC001", description: "Caustic Dosing Pump MCC Cell", status: "mapped" },
  { pidTag: "06-PU-004LCS", assetNumber: "CAUS001-LCS001", description: "Caustic Dosing Pump LCS", status: "mapped" },
  { pidTag: "06-SV-7554", assetNumber: "HDOS001-VLV001", description: "HCL Dosing Pump Solenoid Valve", status: "mapped" },
  
  // ============ ELUTION ============
  { pidTag: "08-PU-003", assetNumber: "DSL001-PMP001", description: "Diesel Pump", status: "mapped" },
  { pidTag: "08-TK-002", assetNumber: "DSL001-TK001", description: "Diesel Day Tank", status: "mapped" },
  { pidTag: "08-PU-003HCL", assetNumber: "HDOS001-PMP001", description: "HCL Acid Dosing Pump", status: "mapped" },
  { pidTag: "08-PU-004", assetNumber: "HSMP001-PMP001", description: "HCL Area Sump Pump", status: "mapped" },
  { pidTag: "08-HX-001", assetNumber: "HEXC001", description: "Elution Recovery Heat Exchange", status: "mapped" },
  { pidTag: "08-CM-002", assetNumber: "ELU-COL001", description: "Elution Column", status: "mapped" },
  { pidTag: "08-FL-02", assetNumber: "ELU-COL001-FLT001", description: "Elution Column Filters", status: "mapped" },
  
  // Elution Instruments
  { pidTag: "08-PSHH-7501", assetNumber: "ELUT001-SWT001", description: "Eluate Pump Discharge High High Pressure Switch", status: "mapped" },
  { pidTag: "08-DPSH-7502", assetNumber: "HEXC001-DPS001", description: "Elution Heater Differential Pressure High Switch", status: "mapped" },
  { pidTag: "08-PI-7503", assetNumber: "ELUT001-INS001", description: "Eluate Pump Discharge Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7504", assetNumber: "HEXC001-PG001", description: "Elution Heater Inlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7505", assetNumber: "HEXC001-PG002", description: "Elution Heater Outlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7506", assetNumber: "ELU-COL001-INS001", description: "Elution Column Outlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7507", assetNumber: "ELU-COL001-INS002", description: "Elution Column Inlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7509", assetNumber: "ACOL001-INS001", description: "Acid Wash Column Inlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-PI-7510", assetNumber: "ACOL001-INS002", description: "Acid Wash Column Discharge Pressure Gauge", status: "mapped" },
  { pidTag: "08-TI-7512", assetNumber: "HEXC001-TG001", description: "Elution Heat Exchange Inlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-PI-7513", assetNumber: "HEXC001-PG003", description: "Elution Heat Exchange Outlet Pressure Gauge", status: "mapped" },
  { pidTag: "08-TI-7514", assetNumber: "HEXC001-TG002", description: "Elution Heat Exchange Outlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-TI-7515", assetNumber: "ELUT001-INS002", description: "Eluate Pump Discharge Temperature Gauge", status: "mapped" },
  { pidTag: "08-TI-7516", assetNumber: "HEXC001-TG003", description: "Elution Heater Inlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-TI-7517", assetNumber: "HEXC001-TG004", description: "Elution Heater Outlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-TI-7518", assetNumber: "ELU-COL001-INS003", description: "Elution Column Outlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-TI-7519", assetNumber: "ELU-COL001-INS004", description: "Elution Column Inlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-TIC-7521", assetNumber: "HEXC001-CTRL001", description: "Elution Heater Burner Controller", status: "mapped" },
  { pidTag: "08-TE-7522", assetNumber: "HEXC001-TS001", description: "Elution Heater Outlet Temperature Sensor", status: "mapped" },
  { pidTag: "08-TE-7524", assetNumber: "HEXC001-TS002", description: "Elution Heater Flue Temperature Sensor", status: "mapped" },
  { pidTag: "08-FE-7529", assetNumber: "HEXC001-FS001", description: "Elution Heater Inlet Flow Sensor", status: "mapped" },
  { pidTag: "08-FE-7531", assetNumber: "ACOL001-SEN001", description: "Acid Wash Column HCL Flow Sensor", status: "mapped" },
  { pidTag: "08-FE-7532", assetNumber: "ELUT001-SEN001", description: "Eluate Tank Cyanide Feed Flow Sensor", status: "mapped" },
  { pidTag: "08-SV-7533", assetNumber: "ELUT001-VLV001", description: "Eluate Tank Cyanide Feed Solenoid Valve", status: "mapped" },
  { pidTag: "08-LE-7541", assetNumber: "ELUT001-SEN002", description: "Eluate Tank Level Sensor", status: "mapped" },
  { pidTag: "08-LSHH-7542", assetNumber: "ACOL001-SWT001", description: "Acid Wash Column High High Level Switch", status: "mapped" },
  
  // Elution Area
  { pidTag: "08-SS-001", assetNumber: "ELU-SHW01", description: "Elution Area Safety Shower 1", status: "mapped" },
  { pidTag: "08-PU-005", assetNumber: "ELU-PMP001", description: "Elution Area Sump Pump", status: "mapped" },
  { pidTag: "08-PU-005M", assetNumber: "ELU-PMP001-MTR001", description: "Elution Area Sump Pump Motor", status: "mapped" },
  { pidTag: "08-PU-005MC", assetNumber: "ELU-PMP001-MCC001", description: "Elution Area Sump Pump MCC Cell", status: "mapped" },
  { pidTag: "08-PU-005LCS", assetNumber: "ELU-PMP001-LCS001", description: "Elution Area Sump Pump LCS", status: "mapped" },
  { pidTag: "08-CM-001", assetNumber: "ACOL001", description: "Acid Wash Column", status: "mapped" },
  { pidTag: "100-FL-001", assetNumber: "ACOL001-FLT001", description: "Acid Column Filters", status: "mapped" },
  { pidTag: "08-HE-001", assetNumber: "HEXC001-HTR001", description: "Elution Heater", status: "mapped" },
  { pidTag: "08-BU-001", assetNumber: "HEXC001-BRN001", description: "Elution Heater Burner", status: "mapped" },
  { pidTag: "08-SS-002", assetNumber: "ELU-SHW02", description: "Elution Area Safety Shower 2", status: "mapped" },
  
  // Gold Room
  { pidTag: "08-SS-003", assetNumber: "GR-SHW01", description: "Gold Room Safety Shower", status: "mapped" },
  { pidTag: "08-MR-001", assetNumber: "EWCL001-MNR001", description: "Electrowinning Monorail", status: "mapped" },
  { pidTag: "08-TK-001", assetNumber: "ELUT001-TK001", description: "Eluate Tank", status: "mapped" },
  { pidTag: "08-EW-001", assetNumber: "EWCL001", description: "Electrowinning Cell", status: "mapped" },
  { pidTag: "08-FA-001", assetNumber: "EWCL001-FAN001", description: "Electrowinning Fan", status: "mapped" },
  { pidTag: "08-FA-004", assetNumber: "GEW001-FAN001", description: "Gravity Electrowinning Fan", status: "mapped" },
  { pidTag: "08-EW-002", assetNumber: "GEW001", description: "Gravity Electrowinning", status: "mapped" },
  { pidTag: "08-TK-004", assetNumber: "EWCL001-TK001", description: "Electrowinning Solution Tank", status: "mapped" },
  { pidTag: "08-PU-015", assetNumber: "EWCL001-PMP001", description: "Electrowinning Feed Pump", status: "mapped" },
  { pidTag: "08-PU-015M", assetNumber: "EWCL001-MTR001", description: "Electrowinning Feed Pump Motor", status: "mapped" },
  { pidTag: "08-PU-015MC", assetNumber: "EWCL001-MCC001", description: "Electrowinning Feed Pump MCC Cell", status: "mapped" },
  { pidTag: "08-PU-015LCS", assetNumber: "EWCL001-LCS001", description: "Electrowinning Feed Pump LCS", status: "mapped" },
  { pidTag: "08-PU-001", assetNumber: "ELUT001-PMP001", description: "Eluate Pump", status: "mapped" },
  { pidTag: "08-PU-001M", assetNumber: "ELUT001-MTR001", description: "Eluate Pump Motor", status: "mapped" },
  { pidTag: "08-PU-001MC", assetNumber: "ELUT001-MCC001", description: "Eluate Pump MCC Cell", status: "mapped" },
  { pidTag: "08-PU-001LCS", assetNumber: "ELUT001-LCS001", description: "Eluate Pump LCS", status: "mapped" },
  
  // Carbon Regen
  { pidTag: "08-SC-001", assetNumber: "BCDS001", description: "Barren Carbon Dewatering Screen", status: "mapped" },
  { pidTag: "08-SC-001EX", assetNumber: "BCDS001-EXC001", description: "Barren Carbon Dewatering Screen Exciter", status: "mapped" },
  { pidTag: "08-SC-001MC", assetNumber: "BCDS001-MCC001", description: "Barren Carbon Dewatering Screen MCC Cell", status: "mapped" },
  { pidTag: "08-SC-001LCS", assetNumber: "BCDS001-LCS001", description: "Barren Carbon Dewatering Screen LCS", status: "mapped" },
  { pidTag: "08-HP-001", assetNumber: "RKHP001", description: "Regen Kiln Feed Hopper", status: "mapped" },
  { pidTag: "08-KN-001", assetNumber: "KLN001", description: "Carbon Regen Kiln", status: "mapped" },
  { pidTag: "08-FE-001", assetNumber: "RKHP001-FDR001", description: "Regen Kiln Screw Feeder", status: "mapped" },
  { pidTag: "08-BU-003", assetNumber: "KLN001-BRN001", description: "Regen Kiln Burners", status: "mapped" },
  { pidTag: "08-HP-002", assetNumber: "CREG001-HOP001", description: "Regenerated Carbon Quench Hopper", status: "mapped" },
  { pidTag: "08-PU-006", assetNumber: "RCTR001-PMP001", description: "Carbon Transfer Pump", status: "mapped" },
  { pidTag: "08-PU-006M", assetNumber: "RCTR001-MTR001", description: "Carbon Transfer Pump Motor", status: "mapped" },
  { pidTag: "08-PU-006MC", assetNumber: "RCTR001-MCC001", description: "Carbon Transfer Pump MCC Cell", status: "mapped" },
  { pidTag: "08-PU-006LCS", assetNumber: "RCTR001-LCS001", description: "Carbon Transfer Pump LCS", status: "mapped" },
  
  // Regen Instruments
  { pidTag: "08-LE-7550", assetNumber: "RKHP001-SEN001", description: "Regen Kiln Feed Screw Inlet Level Sensor", status: "mapped" },
  { pidTag: "08-TE-7561A", assetNumber: "KLN001-INS003", description: "Regen Kiln Zone 2 Temperature Gauge 1", status: "mapped" },
  { pidTag: "08-TE-7561B", assetNumber: "KLN001-INS004", description: "Regen Kiln Zone 2 Temperature Gauge 2", status: "mapped" },
  { pidTag: "08-TE-7562A", assetNumber: "KLN001-INS005", description: "Regen Kiln Zone 3 Temperature Gauge 1", status: "mapped" },
  { pidTag: "08-TE-7562B", assetNumber: "KLN001-INS006", description: "Regen Kiln Zone 3 Temperature Gauge 2", status: "mapped" },
  { pidTag: "08-TE-7563", assetNumber: "KLN001-SEN001", description: "Regen Kiln Discharge Temperature Sensor", status: "mapped" },
  { pidTag: "08-TE-7575A", assetNumber: "KLN001-INS001", description: "Regen Kiln Zone 1 Temperature Gauge 1", status: "mapped" },
  { pidTag: "08-TE-7575B", assetNumber: "KLN001-INS002", description: "Regen Kiln Zone 1 Temperature Gauge 2", status: "mapped" },
  { pidTag: "08-TE-7575C", assetNumber: "KLN001-INS007", description: "Regen Kiln Feed End Temperature Gauge", status: "mapped" },
  { pidTag: "08-LSLL-7576", assetNumber: "CREG001-SWT001", description: "Regenerated Carbon Quench Hopper Low Low Level Switch", status: "mapped" },
  
  // Cathode System
  { pidTag: "08-PU-011", assetNumber: "CWSH001", description: "High Pressure Cathode Washer", status: "mapped" },
  { pidTag: "08-TK-003", assetNumber: "CWSH001-BOX001", description: "Cathode Wash Box", status: "mapped" },
  { pidTag: "08-PU-009", assetNumber: "CWSH001-PMP001", description: "Cathode Wash Sludge Pump", status: "mapped" },
  { pidTag: "08-PU-009M", assetNumber: "CWSH001-MTR001", description: "Cathode Wash Sludge Pump Motor", status: "mapped" },
  { pidTag: "08-PU-009MC", assetNumber: "CWSH001-MCC001", description: "Cathode Wash Sludge Pump MCC Cell", status: "mapped" },
  { pidTag: "08-PU-009LCS", assetNumber: "CWSH001-LCS001", description: "Cathode Wash Sludge Pump LCS", status: "mapped" },
  { pidTag: "08-CW-001", assetNumber: "CWSH001-WND001", description: "Cathode Winder", status: "mapped" },
  { pidTag: "08-FL-003", assetNumber: "CWSH001-FP001", description: "Cathode Sludge Filter Press", status: "mapped" },
  
  // Calcine / Smelting
  { pidTag: "08-CO-001", assetNumber: "CALC001", description: "Calcine Oven", status: "mapped" },
  { pidTag: "08-HD-002", assetNumber: "CALC001-HOOD001", description: "Calcine Oven Hood", status: "mapped" },
  { pidTag: "08-FA-002", assetNumber: "CALC001-FAN001", description: "Calcine Oven Extraction Fan", status: "mapped" },
  { pidTag: "08-BF-001", assetNumber: "SMLT001", description: "Gold Room Barring Furnace", status: "mapped" },
  { pidTag: "08-TI-7520", assetNumber: "EWCL001-TG001", description: "Electrowinning Flashpot Inlet Temperature Gauge", status: "mapped" },
  { pidTag: "08-LSHH-7539", assetNumber: "EWCL001-LSH001", description: "Electrowinning Flashpot High High Level Switch", status: "mapped" },
  { pidTag: "08-BU-002", assetNumber: "SMLT001-FAN001", description: "Barring Furnace Extraction Fan", status: "mapped" },
  { pidTag: "08-HD-001", assetNumber: "SMLT001-HOOD001", description: "Barring Furnace Hood", status: "mapped" },
  { pidTag: "08-XM-007", assetNumber: "GR-BEN001", description: "Gold Room Work Bench", status: "mapped" },
  { pidTag: "08-XM-004", assetNumber: "BULL001-SCL001", description: "Gold Bullion Scale", status: "mapped" },
  { pidTag: "08-XM-003", assetNumber: "BULL001-BEN001", description: "Gold Bullion Scale Bench", status: "mapped" },
  { pidTag: "08-XM-005", assetNumber: "GR-SAFE001", description: "Gold Room Bullion Safe", status: "mapped" },
  
  // ============ GRAVITY ============
  { pidTag: "04-SC-100", assetNumber: "GSCR001", description: "Gravity Screen", status: "mapped" },
  { pidTag: "04-CH-103", assetNumber: "GSCR001-CHU001", description: "Gravity Screen Feed Chute", status: "mapped" },
  { pidTag: "04-CH-104", assetNumber: "GSCR001-PAN001", description: "Gravity Screen Under Pan", status: "mapped" },
  { pidTag: "04-CH-105", assetNumber: "GSCR001-CHU002", description: "Gravity Screen Discharge Chute", status: "mapped" },
  { pidTag: "04-GC-100", assetNumber: "KNLS001", description: "Knelson Concentrator", status: "mapped" },
  { pidTag: "04-GC-100CP", assetNumber: "KNLS001-PNL001", description: "Knelson Concentrator Control Panel", status: "mapped" },
  { pidTag: "04-PB-112", assetNumber: "KNLS001-CONE001", description: "Concentrate Collection Cone", status: "mapped" },
  { pidTag: "04-ST-100", assetNumber: "CST001", description: "Concentrate Shaking Table", status: "mapped" },
  { pidTag: "04-ST-100M", assetNumber: "CST001-MTR001", description: "Concentrate Shaking Table Motor", status: "mapped" },
  { pidTag: "04-ST-100MC", assetNumber: "CST001-MCC001", description: "Concentrate Shaking Table MCC Cell", status: "mapped" },
  { pidTag: "04-ST-100LCS", assetNumber: "CST001-LCS001", description: "Concentrate Shaking Table LCS", status: "mapped" },
  { pidTag: "04-ST-100GB", assetNumber: "CST001-GBX001", description: "Concentrate Shaking Table Gearbox", status: "mapped" },
  { pidTag: "04-PU-111", assetNumber: "GRVPMP001", description: "Gravity Tails Pump", status: "mapped" },
  { pidTag: "04-PU-111M", assetNumber: "GRVPMP001-MTR001", description: "Gravity Tails Pump Motor", status: "mapped" },
  { pidTag: "04-PU-111MC", assetNumber: "GRVPMP001-MCC001", description: "Gravity Tails Pump MCC Cell", status: "mapped" },
  { pidTag: "04-PU-111LCS", assetNumber: "GRVPMP001-LCS001", description: "Gravity Tails Pump LCS", status: "mapped" },
  { pidTag: "04-MR-101", assetNumber: "HST001", description: "Knelson Area Hoist", status: "mapped" },
  { pidTag: "04-MR-101CP", assetNumber: "CR001-PNL002", description: "Knelson Area Hoist Control Panel", status: "mapped" },
  
  // ============ SERVICES / WATER ============
  { pidTag: "11-TK-202", assetNumber: "PWT001", description: "Potable Water Tank", status: "mapped" },
  { pidTag: "11-TK-202P", assetNumber: "PWT001-PIPE001", description: "Potable Water Pipework", status: "mapped" },
  { pidTag: "11-PU-033B", assetNumber: "PWT001-PMP001", description: "Potable Water Pump Standby", status: "mapped" },
  { pidTag: "11-PU-33BMC", assetNumber: "PWT001-MCC001", description: "Potable Water Pump Standby MCC Cell", status: "mapped" },
  { pidTag: "11-PU-33BLCS", assetNumber: "PWT001-LCS001", description: "Potable Water Pump Standby LCS", status: "mapped" },
  { pidTag: "11-PU-033A", assetNumber: "PWT001-PMP002", description: "Potable Water Pump Duty", status: "mapped" },
  { pidTag: "11-TK-001", assetNumber: "RWT001", description: "Raw Water Storage Tank", status: "mapped" },
  { pidTag: "11-PU-26A", assetNumber: "RWT001-PMP001", description: "Raw Water Pump Duty", status: "mapped" },
  { pidTag: "11-PU-26AM", assetNumber: "RWT001-MTR001", description: "Raw Water Pump Duty Motor", status: "mapped" },
  { pidTag: "11-PU-26AMC", assetNumber: "RWT001-MCC001", description: "Raw Water Pump Duty MCC Cell", status: "mapped" },
  { pidTag: "11-PU-26ALCS", assetNumber: "RWT001-LCS001", description: "Raw Water Pump Duty LCS", status: "mapped" },
  { pidTag: "11-PU-26B", assetNumber: "RWT001-PMP002", description: "Raw Water Pump Stand-By", status: "mapped" },
  { pidTag: "11-PU-26BM", assetNumber: "RWT001-MTR002", description: "Raw Water Pump Stand-By Motor", status: "mapped" },
  { pidTag: "11-PU-26BMC", assetNumber: "RWT001-MCC002", description: "Raw Water Pump Stand-By MCC Cell", status: "mapped" },
  { pidTag: "11-PU-26BLCS", assetNumber: "RWT001-LCS002", description: "Raw Water Pump Stand-By LCS", status: "mapped" },
  { pidTag: "11-PD-03", assetNumber: "PWP001", description: "Process Water Pond", status: "mapped" },
  { pidTag: "11-PD-03P", assetNumber: "PWP001-PIPE001", description: "Process Water Piping", status: "mapped" },
  { pidTag: "11-PU-130A", assetNumber: "PWP001-PMP001", description: "Process Water Pump Duty", status: "mapped" },
  { pidTag: "11-PU-130AM", assetNumber: "PWP001-MTR001", description: "Process Water Pump Duty Motor", status: "mapped" },
  { pidTag: "11-PU-130AMC", assetNumber: "PWP001-MCC001", description: "Process Water Pump Duty MCC Cell", status: "mapped" },
  { pidTag: "11-PU-130ALCS", assetNumber: "PWP001-LCS001", description: "Process Water Pump Duty LCS", status: "mapped" },
  { pidTag: "11-PU-130AVFD", assetNumber: "PWP001-VSD001", description: "Process Water Pump Duty VSD", status: "mapped" },
  { pidTag: "11-PU-130B", assetNumber: "PWP001-PMP002", description: "Process Water Pump Stand-By", status: "mapped" },
  { pidTag: "11-PU-130BM", assetNumber: "PWP001-MTR002", description: "Process Water Pump Stand-By Motor", status: "mapped" },
  { pidTag: "11-PU-130BMC", assetNumber: "PWP001-MCC002", description: "Process Water Pump Stand-By MCC Cell", status: "mapped" },
  { pidTag: "11-PU-130BLCS", assetNumber: "PWP001-LCS002", description: "Process Water Pump Stand-By LCS", status: "mapped" },
  { pidTag: "11-PU-130BVFD", assetNumber: "PWP001-VSD002", description: "Process Water Pump Stand-By VSD", status: "mapped" },
  
  // HP Air Compressors
  { pidTag: "05-CP-132", assetNumber: "HPCP001", description: "HP Air Compressor 1", status: "mapped" },
  { pidTag: "05-CP-132P", assetNumber: "HPCP001-PIPE001", description: "HP Air Compressor 1 Piping", status: "mapped" },
  { pidTag: "05-CP-132MC", assetNumber: "HPCP001-MCC001", description: "HP Air Compressor 1 MCC Cell", status: "mapped" },
  { pidTag: "05-AR-137", assetNumber: "HPCP001-RCVR001", description: "HP Air Receiver 1", status: "mapped" },
  { pidTag: "05-CP-133", assetNumber: "HPCP002", description: "HP Air Compressor 2", status: "mapped" },
  { pidTag: "05-CP-133P", assetNumber: "HPCP002-PIPE001", description: "HP Air Compressor 2 Piping", status: "mapped" },
  { pidTag: "05-CP-133MC", assetNumber: "HPCP002-MCC001", description: "HP Air Compressor 2 MCC Cell", status: "mapped" },
  { pidTag: "05-AR-138", assetNumber: "HPCP002-RCVR001", description: "HP Air Receiver 2", status: "mapped" },
  
  // ============ TAILS ============
  { pidTag: "12-TM-001", assetNumber: "THK001", description: "Tails Thickener", status: "mapped" },
  { pidTag: "12-TM-001P", assetNumber: "THK001-PIPE001", description: "Tails Thickener Piping and Valves", status: "mapped" },
  { pidTag: "PU-200A", assetNumber: "THKUFP-A", description: "Thickener Underflow Pump A", status: "mapped" },
  { pidTag: "PU-200AM", assetNumber: "THKUFP-A-MTR001", description: "Thickener Underflow Pump Duty Motor", status: "mapped" },
  { pidTag: "PU-200AMC", assetNumber: "THKUFP-A-MCC001", description: "Thickener Underflow Pump Duty MCC Cell", status: "mapped" },
  { pidTag: "PU-200ALCS", assetNumber: "THKUFP-A-LCS001", description: "Thickener Underflow Pump Duty LCS", status: "mapped" },
  { pidTag: "PU-200AVFD", assetNumber: "THKUFP-A-VSD001", description: "Thickener Underflow Duty VSD", status: "mapped" },
  { pidTag: "12-PU-200B", assetNumber: "THKUFP-B", description: "Thickener Underflow Pump B", status: "mapped" },
  { pidTag: "12-PU-200BM", assetNumber: "THKUFP-B-MTR001", description: "Thickener Underflow Standby Pump Motor", status: "mapped" },
  { pidTag: "12-PU-200BMC", assetNumber: "THKUFP-B-MCC001", description: "Thickener Underflow Standby Pump MCC", status: "mapped" },
  { pidTag: "12-PU-200BLCS", assetNumber: "THKUFP-B-LCS001", description: "Thickener Underflow Standby Pump LCS", status: "mapped" },
  { pidTag: "12-PU-200BVFD", assetNumber: "THKUFP-B-VFD001", description: "Thickener Underflow Standby Pump VFD", status: "mapped" },
  { pidTag: "12-PU-210", assetNumber: "TAILSMP001", description: "Tails Area Sump Pump", status: "mapped" },
  { pidTag: "12-PU-210M", assetNumber: "TAILSMP001-MTR001", description: "Tails Area Sump Pump Motor", status: "mapped" },
  { pidTag: "12-PU-210MC", assetNumber: "TAILSMP001-MCC001", description: "Tails Area Sump Pump MCC", status: "mapped" },
  { pidTag: "12-PU-210LCS", assetNumber: "TAILSMP001-LCS001", description: "Tails Area Sump Pump LCS", status: "mapped" },
  { pidTag: "12-HY-201", assetNumber: "THK001-HYD001", description: "Thickener Hydraulic Pack", status: "mapped" },
  { pidTag: "12-PU-201", assetNumber: "THKHYD001", description: "Thickener Hydraulic Pump", status: "mapped" },
  { pidTag: "12-PU-201M", assetNumber: "THKHYD001-MTR001", description: "Thickener Hydraulic Pump Motor", status: "mapped" },
  { pidTag: "12-PU-201LCS", assetNumber: "THKHYD001-LCS001", description: "Thickener Hydraulic Pump LCS", status: "mapped" },
  { pidTag: "12-HE-202", assetNumber: "HOIL001-HTR001", description: "Hydraulic Oil Heater", status: "mapped" },
  { pidTag: "12-FN-203", assetNumber: "HOIL001-FAN001", description: "Hydraulic Oil Cooling Fan", status: "mapped" },
  { pidTag: "12-PN-205", assetNumber: "THK001-PG001", description: "Thickener Hydraulic Pack Instruments", status: "mapped" },
  { pidTag: "12-PN-205IN", assetNumber: "THK001-PG002", description: "Thickener Hydraulic Pack Instruments", status: "mapped" },
  { pidTag: "12-PN-206", assetNumber: "THK001-PNL001", description: "Flocc Panel 1", status: "mapped" },
  { pidTag: "12-PN-207", assetNumber: "THK001-PNL002", description: "Flocc Panel 2", status: "mapped" },
  { pidTag: "12-PN-208", assetNumber: "THK001-PNL003", description: "Clarometer Panel", status: "mapped" },
  
  // Filter Press Area
  { pidTag: "13-FP-300", assetNumber: "FP001", description: "Tails Filter Press", status: "mapped" },
  { pidTag: "13-CP-133", assetNumber: "HPCP003", description: "Filter Area HP Air Compressor", status: "mapped" },
  { pidTag: "13-CP-133P", assetNumber: "HPCP003-PIPE001", description: "HP Air Compressor Piping", status: "mapped" },
  { pidTag: "13-CP-133MC", assetNumber: "HPCP003-MCC001", description: "HP Air Compressor MCC Cell", status: "mapped" },
  { pidTag: "13-AR-139", assetNumber: "HPCP003-RCVR001", description: "HP Air Receiver", status: "mapped" },
  { pidTag: "13-AR-140", assetNumber: "HPCP004-RCVR001", description: "HP Air Receiver 4", status: "mapped" },
  
  // Filter 1
  { pidTag: "13-FP-301", assetNumber: "FP001", description: "Filter Press 1", status: "mapped" },
  { pidTag: "13-PU-301", assetNumber: "FILT001-PMP001", description: "Filter 1 Feed Pump", status: "mapped" },
  { pidTag: "13-PU-301M", assetNumber: "FILT001-MTR001", description: "Filter 1 Feed Pump Motor", status: "mapped" },
  { pidTag: "13-CV-301", assetNumber: "F1EC001", description: "Filter 1 Extraction Conveyor", status: "mapped" },
  { pidTag: "13-CV-301M", assetNumber: "F1EC001-MTR001", description: "Filter 1 Extraction Motor", status: "mapped" },
  { pidTag: "13-CV-301GB", assetNumber: "F1EC001-GBX001", description: "Filter 1 Extraction Gearbox", status: "mapped" },
  { pidTag: "13-CV-301VFD", assetNumber: "F1EC001-VFD001", description: "Filter 1 Extraction Conveyor VFD", status: "mapped" },
  { pidTag: "13-CV-301MC", assetNumber: "F1EC001-MCC001", description: "Filter 1 Extraction Conveyor MCC Cell", status: "mapped" },
  { pidTag: "13-TK-301", assetNumber: "FP001-TK001", description: "Filter 1 Stock Tank", status: "mapped" },
  { pidTag: "13-AG-301", assetNumber: "FP001-AGT001", description: "Filter 1 Stock Tank Agitator", status: "mapped" },
  { pidTag: "13-AG-301M", assetNumber: "FP001-MTR001", description: "Filter 1 Stock Tank Agitator Motor", status: "mapped" },
  { pidTag: "13-AG-301GB", assetNumber: "FP001-GBX001", description: "Filter 1 Stock Tank Agitator Gearbox", status: "mapped" },
  { pidTag: "13-AG-301MC", assetNumber: "FP001-MCC001", description: "Filter 1 Stock Tank Agitator MCC Cell", status: "mapped" },
  { pidTag: "13-PN-301PLC", assetNumber: "FP001-PLC001", description: "Filter 1 PLC", status: "mapped" },
  { pidTag: "13-FP-301IN", assetNumber: "FP001-INST001", description: "Filter 1 Instruments", status: "mapped" },
  { pidTag: "13-FP-301P", assetNumber: "FP001-VLV001", description: "Filter 1 Piping and Valves", status: "mapped" },
  { pidTag: "13-PN-301", assetNumber: "FP001-PNL001", description: "Filter Press 1 Panel", status: "mapped" },
  { pidTag: "13-HY-301", assetNumber: "FP001-HYD001", description: "Filter Press 1 Hydraulic Pack", status: "mapped" },
  { pidTag: "13-HP-301", assetNumber: "FP001-MTR002", description: "Filter Press 1 Hydraulic Plate Pack Pump", status: "mapped" },
  { pidTag: "13-HP-301M", assetNumber: "FP001-MTR002", description: "Filter Press 1 Hydraulic Plate Pack Motor", status: "mapped" },
  { pidTag: "13-HP-301MC", assetNumber: "FP001-MCC002", description: "Filter Press 1 Hydraulic Plate Pack MCC Cell", status: "mapped" },
  { pidTag: "13-HP-301B", assetNumber: "FP001-MTR003", description: "Filter Press 1 Hydraulic TT Plate Pump", status: "mapped" },
  { pidTag: "13-HP-301BM", assetNumber: "FP001-MTR003", description: "Filter Press 1 Hydraulic TT Plate Motor", status: "mapped" },
  { pidTag: "13-HP-301BMC", assetNumber: "FP001-MCC003", description: "Filter Press 1 Hydraulic TT Plate MCC Cell", status: "mapped" },
  
  // Filter 2
  { pidTag: "13-FP-302", assetNumber: "FP002", description: "Filter Press 2", status: "mapped" },
  { pidTag: "13-CV-302", assetNumber: "F2EC001", description: "Filter 2 Extraction Conveyor", status: "mapped" },
  { pidTag: "13-CV-302M", assetNumber: "F2EC001-MTR001", description: "Filter 2 Extraction Motor", status: "mapped" },
  { pidTag: "13-CV-302GB", assetNumber: "F2EC001-GBX001", description: "Filter 2 Extraction Gearbox", status: "mapped" },
  { pidTag: "13-CV-302VFD", assetNumber: "F2EC001-VFD001", description: "Filter 2 Extraction Conveyor VFD", status: "mapped" },
  { pidTag: "13-CV-302MC", assetNumber: "F2EC001-MCC001", description: "Filter 2 Extraction Conveyor MCC Cell", status: "mapped" },
  { pidTag: "13-TK-302", assetNumber: "FP002-TK001", description: "Filter 2 Stock Tank", status: "mapped" },
  { pidTag: "13-AG-302", assetNumber: "FP002-AGT001", description: "Filter 2 Stock Tank Agitator", status: "mapped" },
  { pidTag: "13-AG-302M", assetNumber: "FP002-MTR001", description: "Filter 2 Stock Tank Agitator Motor", status: "mapped" },
  { pidTag: "13-AG-302GB", assetNumber: "FP002-GBX001", description: "Filter 2 Stock Tank Agitator Gearbox", status: "mapped" },
  { pidTag: "13-AG-302MC", assetNumber: "FP002-MCC001", description: "Filter 2 Stock Tank Agitator MCC Cell", status: "mapped" },
  { pidTag: "13-PN-302PLC", assetNumber: "FP002-PLC001", description: "Filter 2 PLC", status: "mapped" },
  { pidTag: "13-FP-302IN", assetNumber: "FP002-INST001", description: "Filter 2 Instruments", status: "mapped" },
  { pidTag: "13-FP-302P", assetNumber: "FP002-VLV001", description: "Filter 2 Piping and Valves", status: "mapped" },
  { pidTag: "13-PN-302", assetNumber: "FP002-PNL001", description: "Filter Press 2 Panel", status: "mapped" },
  { pidTag: "13-HY-302", assetNumber: "FP002-HYD001", description: "Filter Press 2 Hydraulic Pack", status: "mapped" },
  
  // Collection Conveyor
  { pidTag: "13-CV-303", assetNumber: "TFPC001", description: "Tails Filter Press Collection Conveyor", status: "mapped" },
  { pidTag: "13-CV-303M", assetNumber: "TFPC001-MTR001", description: "Tails Filter Press Collection Conveyor Motor", status: "mapped" },
  { pidTag: "13-CV-303GB", assetNumber: "TFPC001-GBX001", description: "Tails Filter Press Collection Conveyor Gearbox", status: "mapped" },
  { pidTag: "13-CV-303MC", assetNumber: "TFPC001-MCC001", description: "Tails Filter Press Collection Conveyor MCC Cell", status: "mapped" },
  { pidTag: "13-CV-303VFD", assetNumber: "TFPC001-VFD001", description: "Tails Filter Press Collection Conveyor VFD", status: "mapped" },
  
  // Radial Stacker
  { pidTag: "13-CV-304", assetNumber: "TFRS001", description: "Tails Filter Press Radial Stacker Conveyor", status: "mapped" },
  { pidTag: "13-CV-304DAM", assetNumber: "TFRS001-MTR001", description: "Tails Filter Press Radial Stacker Drive Motor A", status: "mapped" },
  { pidTag: "13-CV-304DBM", assetNumber: "TFRS001-MTR002", description: "Tails Filter Press Radial Stacker Drive Motor B", status: "mapped" },
  { pidTag: "13-CV-304WDAM", assetNumber: "TFRS001-MTR003", description: "Tails Filter Press Radial Stacker Wheel Drive Motor A", status: "mapped" },
  { pidTag: "13-CV-304WDBM", assetNumber: "TFRS001-MTR004", description: "Tails Filter Press Radial Stacker Wheel Drive Motor B", status: "mapped" },
  { pidTag: "13-CV-304DGBA", assetNumber: "TFRS001-GBX001", description: "Tails Filter Press Radial Stacker Drive Gearbox A", status: "mapped" },
  { pidTag: "13-CV-304DGBB", assetNumber: "TFRS001-GBX002", description: "Tails Filter Press Radial Stacker Drive Gearbox B", status: "mapped" },
  { pidTag: "13-CV-304WDGBA", assetNumber: "TFRS001-GBX003", description: "Tails Filter Press Radial Stacker Wheel Drive Gearbox A", status: "mapped" },
  { pidTag: "13-CV-304WDGBB", assetNumber: "TFRS001-GBX004", description: "Tails Filter Press Radial Stacker Wheel Drive Gearbox B", status: "mapped" },
  { pidTag: "13-CV-304DAMC", assetNumber: "TFRS001-MCC001", description: "Tails Filter Press Radial Stacker Drive A MCC Cell", status: "mapped" },
  { pidTag: "13-CV-304DBMC", assetNumber: "TFRS001-MCC002", description: "Tails Filter Press Radial Stacker Drive B MCC Cell", status: "mapped" },
  { pidTag: "13-CV-304WDAMC", assetNumber: "TFRS001-MCC003", description: "Tails Filter Press Radial Stacker Wheel Drive A MCC Cell", status: "mapped" },
  { pidTag: "13-CV-304WDBMC", assetNumber: "TFRS001-MCC004", description: "Tails Filter Press Radial Stacker Wheel Drive B MCC Cell", status: "mapped" },
  
  // ============ GENERATORS ============
  { pidTag: "17-Sub-100", assetNumber: "MSUB001", description: "Main Sub Station", status: "mapped" },
  { pidTag: "17-GN-001", assetNumber: "GEN001", description: "Power Station Generator 1 500kVA", status: "mapped" },
  { pidTag: "17-GN-002", assetNumber: "GEN002", description: "Power Station Generator 2 500kVA", status: "mapped" },
  { pidTag: "17-GN-003", assetNumber: "GEN003", description: "Power Station Generator 3 500kVA", status: "mapped" },
  { pidTag: "17-GN-004", assetNumber: "GEN004", description: "Power Station Generator 4 500kVA", status: "mapped" },
  { pidTag: "17-GN-005", assetNumber: "GEN005", description: "Power Station Generator 5 500kVA", status: "mapped" },
  { pidTag: "17-GN-006", assetNumber: "GEN006", description: "Power Station Generator 6 500kVA", status: "mapped" },
  { pidTag: "17-GN-007", assetNumber: "GEN007", description: "Power Station Generator 7 500kVA", status: "mapped" },
  { pidTag: "17-GN-008", assetNumber: "GEN008", description: "Power Station Generator 8 500kVA", status: "mapped" },
  { pidTag: "17-GN-009", assetNumber: "GEN-ADM001", description: "Admin Generator 50kVA", status: "mapped" },
  { pidTag: "17-GN-010", assetNumber: "GEN-SPR001", description: "Spare", status: "mapped" },
  { pidTag: "17-GN-012", assetNumber: "GEN-LAB001", description: "Lab Generator 30kVA", status: "mapped" },
  { pidTag: "17-GN-016", assetNumber: "GEN-JUNO001", description: "Juno Bore Generator 200kVA", status: "mapped" },
  { pidTag: "17-GN-017", assetNumber: "GEN-WRK001", description: "Mining Workshop 75kVA", status: "mapped" },
  
  // ============ FIELD MCCs ============
  { pidTag: "18-MCC-110", assetNumber: "MFC001-MCC002", description: "Mill Feed Conveyor Field MCC", status: "mapped" },
  { pidTag: "18-MCC-111", assetNumber: "MILL-MCC001", description: "Mill Area Field MCC", status: "mapped" },
  { pidTag: "18-MCC-113", assetNumber: "CIP-TK03", description: "Tanks Field MCC", status: "mapped" },
  { pidTag: "18-MCC-118", assetNumber: "THK001-MCC001", description: "Thickener Field MCC", status: "mapped" },
  { pidTag: "18-MCC-120", assetNumber: "REAG-MCC001", description: "Reagents Field MCC", status: "mapped" },
  { pidTag: "18-MCC-130", assetNumber: "ELU-MCC001", description: "Elution Area Field MCC", status: "mapped" },
  
  // ============ DISTRIBUTION BOARDS ============
  { pidTag: "DB-102", assetNumber: "SDB001-LP001", description: "Sub-100 L&P", status: "mapped" },
  { pidTag: "DB-105", assetNumber: "LAB001-DB001", description: "Main DB Lab", status: "mapped" },
  { pidTag: "DB-101", assetNumber: "SDB001-ESS001", description: "Sub-100 Essential Board", status: "mapped" },
  { pidTag: "DB-103", assetNumber: "MSUB001-DB001", description: "RO Plant Main Board", status: "mapped" },
  { pidTag: "DB-104", assetNumber: "FDISP001-DB001", description: "Fuel Dispensing control Board", status: "mapped" },
  { pidTag: "SB-003B", assetNumber: "MDB001-DB001", description: "Ice Machine Room DB", status: "mapped" },
  { pidTag: "DB-003", assetNumber: "WKSHP001-DB001", description: "Workshop DB", status: "mapped" },
  { pidTag: "SB-003A", assetNumber: "SVC002-DB001", description: "Lath Container L&P", status: "mapped" },
  { pidTag: "SB-002E", assetNumber: "SVC002-DB002", description: "Crib Room L&P DB", status: "mapped" },
  { pidTag: "SB-002F", assetNumber: "SVC002-DB003", description: "Conference Building L&P", status: "mapped" },
  { pidTag: "SB-002G", assetNumber: "SVC002-DB004", description: "First Aid Room L&P DB", status: "mapped" },
  { pidTag: "DB-001", assetNumber: "MDB001-DB002", description: "Main DB 1", status: "mapped" },
  { pidTag: "DB-002", assetNumber: "MDB001-DB003", description: "Main DB 2", status: "mapped" },
  { pidTag: "SB-001A", assetNumber: "SINF007-DB001", description: "Male Toilet L&P DB", status: "mapped" },
  { pidTag: "SB-002A", assetNumber: "SINF003-DB001", description: "Admin Office L&P DB 1", status: "mapped" },
  { pidTag: "SB-002B", assetNumber: "SINF003-DB002", description: "Admin Office L&P DB 2", status: "mapped" },
  { pidTag: "SB-002C", assetNumber: "SINF003-DB003", description: "Admin Office L&P DB 3", status: "mapped" },
  { pidTag: "SB-002D", assetNumber: "SINF003-DB004", description: "Admin Office L&P DB 4", status: "mapped" },
  { pidTag: "SB-105A", assetNumber: "LAB001-DB002", description: "Lab L&P DB", status: "mapped" },
  { pidTag: "MCC-125-SB-001A", assetNumber: "MDB001-LP001", description: "MCC-125 L&P", status: "mapped" },
  { pidTag: "MCC-110-SB-001A", assetNumber: "MDB001-LP002", description: "MCC-110 L&P", status: "mapped" },
  { pidTag: "MCC-111-SB-001A", assetNumber: "MDB001-LP003", description: "MCC-111 L&P", status: "mapped" },
  { pidTag: "MCC-113-SB-001A", assetNumber: "MDB001-LP004", description: "MCC-113 L&P", status: "mapped" },
  { pidTag: "MCC-114-SB-001A", assetNumber: "MDB001-LP005", description: "MCC-114 L&P", status: "mapped" },
  { pidTag: "MCC-115-SB-001A", assetNumber: "MDB001-LP006", description: "MCC-115 L&P", status: "mapped" },
  { pidTag: "MCC-116-SB-001A", assetNumber: "MDB001-LP007", description: "MCC-116 L&P", status: "mapped" },
  { pidTag: "MCC-117-SB-001A", assetNumber: "MDB001-LP008", description: "MCC-117 L&P", status: "mapped" },
  { pidTag: "MCC-118-SB-001A", assetNumber: "MDB001-LP009", description: "MCC-118 L&P", status: "mapped" },
  { pidTag: "MCC-120-SB-001A", assetNumber: "MDB001-LP010", description: "MCC-120 L&P", status: "mapped" },
  { pidTag: "MCC-121-SB-001A", assetNumber: "MDB001-LP011", description: "MCC-121 L&P", status: "mapped" },
  { pidTag: "MCC-122-SB-001A", assetNumber: "MDB001-LP012", description: "MCC-122 L&P", status: "mapped" },
  { pidTag: "MCC-130-SB-001A", assetNumber: "MDB001-LP013", description: "MCC-130 L&P", status: "mapped" },
  { pidTag: "SB-102A", assetNumber: "CR001-DB001", description: "Control Room L&P DB", status: "mapped" },
  { pidTag: "MCC-XXX-SB-001B", assetNumber: "MDB001-LP014", description: "Titration Hut L&P DB", status: "mapped" },
  
  // ============ BUILDINGS ============
  { pidTag: "16-BU-001", assetNumber: "SINF003", description: "Admin", status: "mapped" },
  { pidTag: "16-BU-002", assetNumber: "WKSHP001", description: "Workshop", status: "mapped" },
  { pidTag: "16-BU-003", assetNumber: "SINF004", description: "Crib", status: "mapped" },
  { pidTag: "16-BU-004", assetNumber: "SINF005", description: "Conference", status: "mapped" },
  { pidTag: "16-BU-005", assetNumber: "SINF006", description: "First Aid Room", status: "mapped" },
  { pidTag: "16-BU-006", assetNumber: "SINF007", description: "Male Toilet", status: "mapped" },
  { pidTag: "16-BU-007", assetNumber: "SINF008", description: "Female Toilet", status: "mapped" },
  { pidTag: "16-BU-008", assetNumber: "CR001", description: "Control Room", status: "mapped" },
  { pidTag: "16-BU-009", assetNumber: "SDB001", description: "Sub-100", status: "mapped" },
  { pidTag: "16-BU-010", assetNumber: "LAB001", description: "Lab", status: "mapped" },
  { pidTag: "16-BU-011", assetNumber: "THUT001", description: "Titration Hut", status: "mapped" },
  { pidTag: "16-BU-012", assetNumber: "CDOS001", description: "Cyanide Dosing Hut", status: "mapped" },
  
  // ============ LIGHT VEHICLES ============
  { pidTag: "14-LV-005", assetNumber: "LV-LC001", description: "LC Military", status: "mapped" },
  { pidTag: "14-LV-011", assetNumber: "LV-HILUX001", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-012", assetNumber: "LV-RANGER001", description: "Ford Ranger XL dual Cab", status: "mapped" },
  { pidTag: "14-LV-014", assetNumber: "LV-HILUX002", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-015", assetNumber: "LV-HILUX003", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-016", assetNumber: "LV-HILUX004", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-017", assetNumber: "LV-HILUX005", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-018", assetNumber: "LV-HILUX006", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-019", assetNumber: "LV-HILUX007", description: "Toyota Hilux", status: "mapped" },
  { pidTag: "14-LV-020", assetNumber: "LV-RANGER002", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-021", assetNumber: "LV-RANGER003", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-022", assetNumber: "LV-RANGER004", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-023", assetNumber: "LV-RANGER005", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-024", assetNumber: "LV-RANGER006", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-026", assetNumber: "LV-RANGER010", description: "Ranger single Cab", status: "mapped" },
  { pidTag: "14-LV-027", assetNumber: "LV-RANGER007", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-028", assetNumber: "LV-RANGER008", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-LV-029", assetNumber: "LV-KIA001", description: "Kia", status: "mapped" },
  { pidTag: "14-LV-030", assetNumber: "LV-RANGER009", description: "Ford Ranger XL dual cab", status: "mapped" },
  { pidTag: "14-BUS-01", assetNumber: "LV-HIACE001", description: "Toyota Hiace", status: "mapped" },
  { pidTag: "14-BUS-02", assetNumber: "LV-HIACE002", description: "Toyota Hiace", status: "mapped" },
  { pidTag: "14-BUS-03", assetNumber: "LV-LDV001", description: "LDV Discovery 9", status: "mapped" },
  { pidTag: "14-BUS-04", assetNumber: "LV-LDV002", description: "LDV Discovery 9", status: "mapped" },
  { pidTag: "14-LV-013", assetNumber: "LV-FUSO001", description: "Fuso TF Canter Flat Top Truck", status: "mapped" },
  
  // ============ MOBILE EQUIPMENT ============
  { pidTag: "15-PR-002", assetNumber: "CRN002", description: "25t Franner crane", status: "mapped" },
  { pidTag: "15-PR-003", assetNumber: "FLT001", description: "Forklift", status: "mapped" },
  { pidTag: "15-PR-004", assetNumber: "TLH001", description: "Telehandler", status: "mapped" },
  { pidTag: "15-PR-001", assetNumber: "BOBCAT001", description: "Bob Cat", status: "mapped" },
  { pidTag: "15-WC-001", assetNumber: "WTRTK001", description: "Water Truck", status: "mapped" },
  { pidTag: "15-ST-001", assetNumber: "SVCTK001", description: "Service Truck", status: "mapped" },
  { pidTag: "15-PR-005", assetNumber: "EWP001", description: "Sino EWP", status: "mapped" },
  { pidTag: "15-PR-006", assetNumber: "EWP002", description: "Hire EWP", status: "mapped" },
  { pidTag: "15-PR-007", assetNumber: "SCLFT001", description: "Sino Scissor Lift", status: "mapped" },
  { pidTag: "15-PR-008", assetNumber: "SCLFT002", description: "Sino Scissor Lift", status: "mapped" },
  { pidTag: "15-WL-001", assetNumber: "LDR001", description: "Cat 980 Loader", status: "mapped" },
  { pidTag: "15-WL-002", assetNumber: "LDR002", description: "Cat 980 Loader", status: "mapped" },
  { pidTag: "15-WL-003", assetNumber: "LDR003", description: "Cat 980 Loader", status: "mapped" },
  { pidTag: "15-WL-004", assetNumber: "LDR004", description: "Cat 980 Loader", status: "mapped" },
  { pidTag: "15-EX-001", assetNumber: "EXC001", description: "Cat 30t Excavator", status: "mapped" },
  { pidTag: "15-EX-002", assetNumber: "EXC002", description: "Case Excavator", status: "mapped" },
  { pidTag: "15-DT-001", assetNumber: "MOXY001", description: "Cat Moxy", status: "mapped" },
  { pidTag: "15-DT-003", assetNumber: "MOXY002", description: "Cat Moxy", status: "mapped" },
  { pidTag: "15-LT-001", assetNumber: "LTW001", description: "Lighting Tower 1", status: "mapped" },
  { pidTag: "15-LT-002", assetNumber: "LTW002", description: "Lighting Tower 2", status: "mapped" },
  { pidTag: "15-LT-003", assetNumber: "LTW003", description: "Lighting Tower 3", status: "mapped" },
  { pidTag: "15-LT-004", assetNumber: "LTW004", description: "Lighting Tower 4", status: "mapped" },
  { pidTag: "15-LT-005", assetNumber: "LTW005", description: "Lighting Tower 5", status: "mapped" },
];

// Helper function to get P&ID tags for a given asset number
export function getPidTagsForAsset(assetNumber: string): string[] {
  return pidTagMappings
    .filter(m => m.assetNumber === assetNumber && m.status === "mapped")
    .map(m => m.pidTag);
}

// Helper function to get asset number for a given P&ID tag
export function getAssetForPidTag(pidTag: string): string | null {
  const mapping = pidTagMappings.find(m => m.pidTag === pidTag && m.status === "mapped");
  return mapping ? mapping.assetNumber : null;
}
