// Critical Spares Register Data
// IMPORTANT: All quantities are PROVISIONAL - Pending P&ID Walkdown & Engineering Review
// Data populated ONLY from user-provided documents. TBC = To Be Confirmed
// Criticality marked as "Assumed" until user explicitly confirms

export interface SpareItem {
  id: string;
  // Hierarchy linkage
  area: string;
  subArea: string;
  system: string;
  parentAsset: string;
  // Component details
  componentName: string;
  componentType: string;
  sparePartDescription: string;
  oemPartNumber: string;
  // Criticality
  spareCriticality: "High" | "Medium" | "Low" | "";
  criticalitySource: "Confirmed" | "Assumed" | "";
  reasonCritical: string;
  // Provisional quantities
  minQtyProvisional: string;
  maxQtyProvisional: string;
  quantityConfidence: "Low" | "Medium" | "High" | "";
  // Other fields
  leadTime: string;
  storageRequirement: string;
  notes: string;
  status: "Provisional" | "Confirmed" | "TBC";
}

// Spares data - Criticality is ASSUMED until user confirms
export const sparesData: SpareItem[] = [
  // === GRINDING AREA ===
  {
    id: "CS-001",
    area: "COM",
    subArea: "Grinding",
    system: "Ball Mill",
    parentAsset: "BM01 Primary Ball Mill",
    componentName: "Mill Motor",
    componentType: "Motor",
    sparePartDescription: "Ball Mill Main Drive Motor",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Plant stoppage if fails",
    minQtyProvisional: "1",
    maxQtyProvisional: "1",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-002",
    area: "COM",
    subArea: "Grinding",
    system: "Ball Mill",
    parentAsset: "BM01 Primary Ball Mill",
    componentName: "Mill Liners",
    componentType: "Liner",
    sparePartDescription: "Ball Mill Shell Liners",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Wear item - scheduled replacement",
    minQtyProvisional: "1",
    maxQtyProvisional: "2",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-003",
    area: "COM",
    subArea: "Grinding",
    system: "Ball Mill",
    parentAsset: "BM01 Primary Ball Mill",
    componentName: "Gearbox",
    componentType: "Gearbox",
    sparePartDescription: "Mill Main Gearbox",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Plant stoppage if fails",
    minQtyProvisional: "TBC",
    maxQtyProvisional: "TBC",
    quantityConfidence: "",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "TBC",
  },
  {
    id: "CS-004",
    area: "COM",
    subArea: "Grinding",
    system: "Ball Mill",
    parentAsset: "BM01 Primary Ball Mill",
    componentName: "Pinion",
    componentType: "Gear",
    sparePartDescription: "Mill Pinion",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Long lead time critical component",
    minQtyProvisional: "1",
    maxQtyProvisional: "1",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-005",
    area: "COM",
    subArea: "Grinding",
    system: "Ball Mill",
    parentAsset: "BM01 Primary Ball Mill",
    componentName: "Trunnion Bearings",
    componentType: "Bearing",
    sparePartDescription: "Mill Trunnion Bearing Set",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Plant stoppage if fails",
    minQtyProvisional: "1",
    maxQtyProvisional: "2",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  // === PUMPS ===
  {
    id: "CS-006",
    area: "COM",
    subArea: "Process",
    system: "Slurry Pumps",
    parentAsset: "PP01 Process Pumps",
    componentName: "Slurry Pump Impeller",
    componentType: "Impeller",
    sparePartDescription: "Slurry Pump Impeller",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Wear item - frequent replacement",
    minQtyProvisional: "2",
    maxQtyProvisional: "4",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-007",
    area: "COM",
    subArea: "Process",
    system: "Slurry Pumps",
    parentAsset: "PP01 Process Pumps",
    componentName: "Pump Liner",
    componentType: "Liner",
    sparePartDescription: "Slurry Pump Liner Set",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Wear item - scheduled replacement",
    minQtyProvisional: "2",
    maxQtyProvisional: "4",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-008",
    area: "COM",
    subArea: "Process",
    system: "Slurry Pumps",
    parentAsset: "PP01 Process Pumps",
    componentName: "Mechanical Seal",
    componentType: "Seal",
    sparePartDescription: "Pump Mechanical Seal Kit",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Wear item - frequent replacement",
    minQtyProvisional: "2",
    maxQtyProvisional: "6",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-009",
    area: "COM",
    subArea: "Process",
    system: "Slurry Pumps",
    parentAsset: "PP01 Process Pumps",
    componentName: "Pump Bearing Assembly",
    componentType: "Bearing",
    sparePartDescription: "Pump Bearing Housing Assembly",
    oemPartNumber: "TBC",
    spareCriticality: "Medium",
    criticalitySource: "Assumed",
    reasonCritical: "Reduces capacity if standby unavailable",
    minQtyProvisional: "1",
    maxQtyProvisional: "2",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  // === CONVEYORS ===
  {
    id: "CS-010",
    area: "COM",
    subArea: "Materials Handling",
    system: "Conveyors",
    parentAsset: "CV01 Transfer Conveyor",
    componentName: "Drive Motor",
    componentType: "Motor",
    sparePartDescription: "Conveyor Drive Motor",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Plant stoppage if fails",
    minQtyProvisional: "1",
    maxQtyProvisional: "1",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-011",
    area: "COM",
    subArea: "Materials Handling",
    system: "Conveyors",
    parentAsset: "CV01 Transfer Conveyor",
    componentName: "Gearbox",
    componentType: "Gearbox",
    sparePartDescription: "Conveyor Drive Gearbox",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Plant stoppage if fails",
    minQtyProvisional: "TBC",
    maxQtyProvisional: "TBC",
    quantityConfidence: "",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "TBC",
  },
  {
    id: "CS-012",
    area: "COM",
    subArea: "Materials Handling",
    system: "Conveyors",
    parentAsset: "CV01 Transfer Conveyor",
    componentName: "Head Pulley",
    componentType: "Pulley",
    sparePartDescription: "Conveyor Head Pulley Assembly",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Long lead time",
    minQtyProvisional: "1",
    maxQtyProvisional: "1",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-013",
    area: "COM",
    subArea: "Materials Handling",
    system: "Conveyors",
    parentAsset: "CV01 Transfer Conveyor",
    componentName: "Tail Pulley",
    componentType: "Pulley",
    sparePartDescription: "Conveyor Tail Pulley Assembly",
    oemPartNumber: "TBC",
    spareCriticality: "Medium",
    criticalitySource: "Assumed",
    reasonCritical: "Reduces capacity",
    minQtyProvisional: "1",
    maxQtyProvisional: "1",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-014",
    area: "COM",
    subArea: "Materials Handling",
    system: "Conveyors",
    parentAsset: "CV01 Transfer Conveyor",
    componentName: "Belt",
    componentType: "Belt",
    sparePartDescription: "Conveyor Belt Section",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Plant stoppage if fails",
    minQtyProvisional: "TBC",
    maxQtyProvisional: "TBC",
    quantityConfidence: "",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "TBC",
  },
  // === FILTER PRESS ===
  {
    id: "CS-015",
    area: "TAIL",
    subArea: "Tailings Filtration",
    system: "Filter Press",
    parentAsset: "FP01 Filter Press",
    componentName: "Filter Cloth",
    componentType: "Consumable",
    sparePartDescription: "Filter Press Cloth Set",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Wear item - scheduled replacement",
    minQtyProvisional: "1",
    maxQtyProvisional: "2",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-016",
    area: "TAIL",
    subArea: "Tailings Filtration",
    system: "Filter Press",
    parentAsset: "FP01 Filter Press",
    componentName: "Hydraulic Pump",
    componentType: "Pump",
    sparePartDescription: "Hydraulic Power Unit Pump",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Plant stoppage if fails",
    minQtyProvisional: "1",
    maxQtyProvisional: "1",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-017",
    area: "TAIL",
    subArea: "Tailings Filtration",
    system: "Filter Press",
    parentAsset: "FP01 Filter Press",
    componentName: "Hydraulic Cylinder Seal Kit",
    componentType: "Seal",
    sparePartDescription: "Main Cylinder Seal Kit",
    oemPartNumber: "TBC",
    spareCriticality: "Medium",
    criticalitySource: "Assumed",
    reasonCritical: "Reduced capacity",
    minQtyProvisional: "2",
    maxQtyProvisional: "4",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  // === THICKENER ===
  {
    id: "CS-018",
    area: "TAIL",
    subArea: "Tailings",
    system: "Thickener",
    parentAsset: "TH01 Thickener",
    componentName: "Drive Motor",
    componentType: "Motor",
    sparePartDescription: "Thickener Drive Motor",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Plant stoppage if fails",
    minQtyProvisional: "TBC",
    maxQtyProvisional: "TBC",
    quantityConfidence: "",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "TBC",
  },
  {
    id: "CS-019",
    area: "TAIL",
    subArea: "Tailings",
    system: "Thickener",
    parentAsset: "TH01 Thickener",
    componentName: "Gearbox",
    componentType: "Gearbox",
    sparePartDescription: "Thickener Rake Drive Gearbox",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Long lead time critical",
    minQtyProvisional: "TBC",
    maxQtyProvisional: "TBC",
    quantityConfidence: "",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "TBC",
  },
  // === CIP / GOLD RECOVERY ===
  {
    id: "CS-020",
    area: "REC",
    subArea: "CIP",
    system: "Carbon Circuit",
    parentAsset: "CIP01 CIP Tanks",
    componentName: "Interstage Screen",
    componentType: "Screen",
    sparePartDescription: "CIP Interstage Screen Panel",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Gold losses if fails",
    minQtyProvisional: "2",
    maxQtyProvisional: "4",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-021",
    area: "REC",
    subArea: "CIP",
    system: "Carbon Circuit",
    parentAsset: "CIP01 CIP Tanks",
    componentName: "Agitator Motor",
    componentType: "Motor",
    sparePartDescription: "CIP Tank Agitator Motor",
    oemPartNumber: "TBC",
    spareCriticality: "Medium",
    criticalitySource: "Assumed",
    reasonCritical: "Reduced recovery",
    minQtyProvisional: "1",
    maxQtyProvisional: "1",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-022",
    area: "REC",
    subArea: "Elution",
    system: "Elution Circuit",
    parentAsset: "EL01 Elution Column",
    componentName: "Heater Element",
    componentType: "Heater",
    sparePartDescription: "Elution Heater Element",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Gold production loss",
    minQtyProvisional: "1",
    maxQtyProvisional: "2",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  // === REAGENTS ===
  {
    id: "CS-023",
    area: "COM",
    subArea: "Reagents",
    system: "Reagent Dosing",
    parentAsset: "RG01 Reagent System",
    componentName: "Dosing Pump",
    componentType: "Pump",
    sparePartDescription: "Reagent Dosing Pump",
    oemPartNumber: "TBC",
    spareCriticality: "Medium",
    criticalitySource: "Assumed",
    reasonCritical: "Reduced recovery efficiency",
    minQtyProvisional: "1",
    maxQtyProvisional: "2",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-024",
    area: "COM",
    subArea: "Reagents",
    system: "Reagent Dosing",
    parentAsset: "RG01 Reagent System",
    componentName: "Dosing Pump Diaphragm",
    componentType: "Consumable",
    sparePartDescription: "Dosing Pump Diaphragm Kit",
    oemPartNumber: "TBC",
    spareCriticality: "Medium",
    criticalitySource: "Assumed",
    reasonCritical: "Wear item",
    minQtyProvisional: "2",
    maxQtyProvisional: "6",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  // === POWER GENERATION ===
  {
    id: "CS-025",
    area: "UTL",
    subArea: "Power Generation",
    system: "Generators",
    parentAsset: "GEN01 Main Generator",
    componentName: "Injector Set",
    componentType: "Injector",
    sparePartDescription: "Diesel Injector Set",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Site power loss",
    minQtyProvisional: "1",
    maxQtyProvisional: "2",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-026",
    area: "UTL",
    subArea: "Power Generation",
    system: "Generators",
    parentAsset: "GEN01 Main Generator",
    componentName: "Alternator Bearings",
    componentType: "Bearing",
    sparePartDescription: "Alternator Bearing Set",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Site power loss",
    minQtyProvisional: "1",
    maxQtyProvisional: "1",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-027",
    area: "UTL",
    subArea: "Power Generation",
    system: "Generators",
    parentAsset: "GEN01 Main Generator",
    componentName: "Turbocharger",
    componentType: "Turbo",
    sparePartDescription: "Engine Turbocharger",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Site power loss",
    minQtyProvisional: "TBC",
    maxQtyProvisional: "TBC",
    quantityConfidence: "",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "TBC",
  },
  // === WATER SERVICES ===
  {
    id: "CS-028",
    area: "UTL",
    subArea: "Water Services",
    system: "Water Treatment",
    parentAsset: "RO01 RO Plant",
    componentName: "RO Membranes",
    componentType: "Membrane",
    sparePartDescription: "RO Membrane Elements",
    oemPartNumber: "TBC",
    spareCriticality: "Medium",
    criticalitySource: "Assumed",
    reasonCritical: "Camp water supply",
    minQtyProvisional: "2",
    maxQtyProvisional: "4",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-029",
    area: "UTL",
    subArea: "Water Services",
    system: "Water Treatment",
    parentAsset: "RO01 RO Plant",
    componentName: "HP Pump",
    componentType: "Pump",
    sparePartDescription: "RO High Pressure Pump",
    oemPartNumber: "TBC",
    spareCriticality: "Medium",
    criticalitySource: "Assumed",
    reasonCritical: "Camp water supply",
    minQtyProvisional: "TBC",
    maxQtyProvisional: "TBC",
    quantityConfidence: "",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "TBC",
  },
  // === VALVES ===
  {
    id: "CS-030",
    area: "COM",
    subArea: "Process",
    system: "Valves",
    parentAsset: "VLV01 Process Valves",
    componentName: "Knife Gate Valve",
    componentType: "Valve",
    sparePartDescription: "Slurry Knife Gate Valve",
    oemPartNumber: "TBC",
    spareCriticality: "Medium",
    criticalitySource: "Assumed",
    reasonCritical: "Isolation capability",
    minQtyProvisional: "2",
    maxQtyProvisional: "4",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
  {
    id: "CS-031",
    area: "COM",
    subArea: "Process",
    system: "Valves",
    parentAsset: "VLV01 Process Valves",
    componentName: "Pinch Valve Sleeve",
    componentType: "Consumable",
    sparePartDescription: "Pinch Valve Rubber Sleeve",
    oemPartNumber: "TBC",
    spareCriticality: "High",
    criticalitySource: "Assumed",
    reasonCritical: "Wear item - frequent replacement",
    minQtyProvisional: "4",
    maxQtyProvisional: "8",
    quantityConfidence: "Low",
    leadTime: "TBC",
    storageRequirement: "TBC",
    notes: "Provisional – Pending P&ID Walkdown & Engineering Review",
    status: "Provisional",
  },
];

// Component types for filtering
export const componentTypes = [
  "Motor",
  "Gearbox",
  "Pump",
  "Valve",
  "Roller",
  "Bearing",
  "Seal",
  "Coupling",
  "Belt",
  "Chain",
  "Sprocket",
  "Impeller",
  "Liner",
  "Screen",
  "Sensor",
  "Actuator",
  "Pulley",
  "Consumable",
  "Heater",
  "Injector",
  "Turbo",
  "Membrane",
  "Gear",
];

// Criticality colors
export const criticalityColors: Record<string, string> = {
  "High": "bg-destructive/20 text-destructive",
  "Medium": "bg-amber-500/20 text-amber-700",
  "Low": "bg-muted text-muted-foreground",
  "": "",
};

// Status colors
export const statusColors: Record<string, string> = {
  "Provisional": "bg-amber-500/20 text-amber-700",
  "Confirmed": "bg-green-500/20 text-green-700",
  "TBC": "bg-muted text-muted-foreground",
};

// Confidence colors
export const confidenceColors: Record<string, string> = {
  "High": "bg-green-500/20 text-green-700",
  "Medium": "bg-amber-500/20 text-amber-700",
  "Low": "bg-red-500/20 text-red-700",
  "": "bg-muted text-muted-foreground",
};

// Criticality source colors
export const criticalitySourceColors: Record<string, string> = {
  "Confirmed": "bg-green-500/20 text-green-700",
  "Assumed": "bg-amber-500/20 text-amber-700",
  "": "",
};
