// Critical Spares Register Data
// Contains HIGH PRIORITY items from the Site Spares Catalogue
// These are items that would cause plant stoppage or have long lead times
// Area/SubArea/System values are pulled DIRECTLY from assetData.ts (Asset Tree)

export interface SpareItem {
  id: string;
  // Hierarchy linkage - matches assetData.ts exactly
  area: string;          // e.g., "COM" or "REC" - matches Area.code
  areaLabel: string;     // e.g., "Comminution / Process" - matches Area.label
  subArea: string;       // e.g., "Feed / Reclaim" - matches SubArea.label
  system: string;        // e.g., "APN01 Apron Feeder" - matches ParentAsset.label
  parentAsset: string;   // Legacy P&ID reference
  assetNumber: string;   // Modern asset number from tree (e.g., APN01-GMR01)
  pidTag: string;
  // Component details
  componentName: string;
  componentType: string;
  sparePartDescription: string;
  oemPartNumber: string;
  manufacturer: string;
  vendor: string;
  assetManufacturer: string;
  assetModel: string;
  // Criticality
  spareCriticality: "High" | "Medium" | "Low" | "";
  criticalitySource: "Confirmed" | "Assumed" | "";
  reasonCritical: string;
  // Quantities
  minQty: string;
  maxQty: string;
  qtyPerSystem: string;
  unitPrice: string;
  uom: string;
  // Other fields
  notes: string;
  status: "Provisional" | "Confirmed" | "TBC";
}

// Critical Spares data - Populated from HIGH priority items in Site Spares Catalogue
// All data is from the attached document - NO invented or assumed data
// Area/SubArea/System values match assetData.ts EXACTLY
export const sparesData: SpareItem[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // COM - COMMINUTION / PROCESS
  // ═══════════════════════════════════════════════════════════════════════════

  // --- Feed / Reclaim > APN01 Apron Feeder ---
  { id: "CS-001", area: "COM", areaLabel: "Comminution / Process", subArea: "Feed / Reclaim", system: "APN01 Apron Feeder", parentAsset: "4-FE-100", assetNumber: "APN01-GMR01", pidTag: "04-FE-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Apron Feeder Gearmotor", oemPartNumber: "SEW-EURODRIVE KA107R77 DRN112M4/V", manufacturer: "SEW", vendor: "SEW", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$16,450.00", uom: "EA", notes: "", status: "Provisional" },

  // --- Feed / Reclaim > MFC01 Mill Feed Conveyor ---
  { id: "CS-002", area: "COM", areaLabel: "Comminution / Process", subArea: "Feed / Reclaim", system: "MFC01 Mill Feed Conveyor", parentAsset: "4-BC-100", assetNumber: "MFC01-MTR01", pidTag: "04-BC-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Mill Feed Conveyor Motor", oemPartNumber: "KTE30 PHEM", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-003", area: "COM", areaLabel: "Comminution / Process", subArea: "Feed / Reclaim", system: "MFC01 Mill Feed Conveyor", parentAsset: "4-BC-100", assetNumber: "MFC01-GBX01", pidTag: "04-BC-100", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Mill Feed Conveyor Gearbox", oemPartNumber: "TBC", manufacturer: "", vendor: "CBC", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-004", area: "COM", areaLabel: "Comminution / Process", subArea: "Feed / Reclaim", system: "MFC01 Mill Feed Conveyor", parentAsset: "4-WE-506", assetNumber: "MFC01-WTM01", pidTag: "04-WE-506", componentName: "Weightometer", componentType: "Mechanical", sparePartDescription: "Weightometer replacement", oemPartNumber: "WF16-600-4000", manufacturer: "Tecweigh", vendor: "Tecweigh", assetManufacturer: "Tecweigh", assetModel: "WF16-600-4000", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Instrumentation - production monitoring", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$65,000.00", uom: "EA", notes: "", status: "Provisional" },

  // --- Conveying > CV01 Transfer Conveyor ---
  { id: "CS-005", area: "COM", areaLabel: "Comminution / Process", subArea: "Conveying", system: "CV01 Transfer Conveyor", parentAsset: "4-FE-101", assetNumber: "CV01-MTR01", pidTag: "04-FE-101", componentName: "Motor", componentType: "Motor", sparePartDescription: "Transfer Conveyor Motor", oemPartNumber: "SEW-EURODRIVE KA77/T.DRE132M4/RS", manufacturer: "SEW", vendor: "SEW", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-006", area: "COM", areaLabel: "Comminution / Process", subArea: "Conveying", system: "CV01 Transfer Conveyor", parentAsset: "4-FE-101", assetNumber: "CV01-GBX01", pidTag: "04-FE-101", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Transfer Conveyor Gearbox", oemPartNumber: "SEW-EURODRIVE KA77/T.DRE132M4/RS", manufacturer: "SEW", vendor: "SEW", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // --- Grinding > BM01 Primary Ball Mill ---
  { id: "CS-007", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "4-ML-100", assetNumber: "BM01-MTR01", pidTag: "04-ML-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Primary Ball Mill Motor 1000kW", oemPartNumber: "1LA4 454-4AN70-Z (1000kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-008", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "4-ML-100", assetNumber: "BM01-PIN01", pidTag: "04-ML-100", componentName: "Pinion Assembly", componentType: "Mechanical", sparePartDescription: "Pinion assembly (2 bearings, 2 pillow block, 1 pinion)", oemPartNumber: "TBC", manufacturer: "", vendor: "BLA", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Mill pinion - plant stoppage", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "", notes: "", status: "TBC" },
  { id: "CS-009", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "4-GR-100", assetNumber: "GRD-BM-GBX", pidTag: "04-GR-100", componentName: "Gear Box Replacement", componentType: "Gearbox", sparePartDescription: "Mill Main Gear Reducer", oemPartNumber: "JKD 4504150638.01.001 / H1 SH 15 B", manufacturer: "Siemens", vendor: "Flender", assetManufacturer: "Flender", assetModel: "H1 SH 15B", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "$70,000.00", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-010", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "4-LS-100", assetNumber: "GRD-LP-LPUMP-D", pidTag: "04-LS-100", componentName: "Main Lube Pump", componentType: "Pump", sparePartDescription: "Low Pressure Lube Pump (Duty)", oemPartNumber: "P/N: 3G55 AT10V A6O0 0036 00", manufacturer: "Rexroth", vendor: "Southern Cross", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - process critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-011", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "4-LS-100", assetNumber: "GRD-LP-LPUMP-S", pidTag: "04-LS-100", componentName: "Standby Lube Pump", componentType: "Pump", sparePartDescription: "Low Pressure Lube Pump (Standby)", oemPartNumber: "P/N: 3G55 AT10V A6O0 0036 00", manufacturer: "Rexroth", vendor: "Southern Cross", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - process critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-012", area: "COM", areaLabel: "Comminution / Process", subArea: "Grinding", system: "BM01 Primary Ball Mill", parentAsset: "4-LS-100", assetNumber: "OCL01", pidTag: "04-LS-100", componentName: "Air Cooler Replacement", componentType: "Air Cooler", sparePartDescription: "Lube Water Oil Cooler", oemPartNumber: "P/N: AKG LA-80-4-LN / Motor 0.09kW 230/400V 50Hz IE2 4P B14/1", manufacturer: "AKG", vendor: "", assetManufacturer: "DYNACOOL", assetModel: "50EK4/2", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Air cooler - lube system critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // --- Classification > CYC01 Cyclone Cluster ---
  { id: "CS-013", area: "COM", areaLabel: "Comminution / Process", subArea: "Classification", system: "CYC01 Cyclone Cluster", parentAsset: "4-CY-100", assetNumber: "CFP01-A", pidTag: "04-CY-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Cyclone Feed Pump Motor – Duty", oemPartNumber: "Weg W22 185kW 2P 3Ph", manufacturer: "Weg", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-014", area: "COM", areaLabel: "Comminution / Process", subArea: "Classification", system: "CYC01 Cyclone Cluster", parentAsset: "4-CY-100", assetNumber: "CFP01-B", pidTag: "04-CY-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Cyclone Feed Pump Motor – Standby", oemPartNumber: "Weg W22 185kW 2P 3Ph", manufacturer: "Weg", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // REC - GOLD RECOVERY
  // ═══════════════════════════════════════════════════════════════════════════

  // --- Gravity Circuit > SCR01 Gravity Concentrator ---
  { id: "CS-015", area: "REC", areaLabel: "Gold Recovery", subArea: "Gravity Circuit", system: "SCR01 Gravity Concentrator", parentAsset: "SCR01", assetNumber: "SCR01", pidTag: "", componentName: "Gravity Screen", componentType: "Screen", sparePartDescription: "Vibrating Screen Unit", oemPartNumber: "OF-HS-09/24-24", manufacturer: "OVERFLOW", vendor: "OVERFLOW", assetManufacturer: "OVERFLOW", assetModel: "OF-HS-09/24-24", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Screen - gravity circuit critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // --- CIP > CIP-TK01 CIP Tanks ---
  { id: "CS-016", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK01", assetNumber: "CIP-TK01-MTR01", pidTag: "05-AT-200", componentName: "Motor", componentType: "Motor", sparePartDescription: "CIP Leach Tank 1 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-017", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK01", assetNumber: "CIP-TK01-GBX01", pidTag: "05-AT-200", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "CIP Leach Tank 1 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-018", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK02", assetNumber: "CIP-TK02-MTR01", pidTag: "05-AT-201", componentName: "Motor", componentType: "Motor", sparePartDescription: "CIP Leach Tank 2 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-019", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK02", assetNumber: "CIP-TK02-GBX01", pidTag: "05-AT-201", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "CIP Leach Tank 2 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-020", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK03", assetNumber: "CIP-TK03-MTR01", pidTag: "05-AT-202", componentName: "Motor", componentType: "Motor", sparePartDescription: "CIP Tank 3 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-021", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK03", assetNumber: "CIP-TK03-GBX01", pidTag: "05-AT-202", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "CIP Tank 3 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-022", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK04", assetNumber: "CIP-TK04-MTR01", pidTag: "05-AT-203", componentName: "Motor", componentType: "Motor", sparePartDescription: "CIP Tank 4 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-023", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK04", assetNumber: "CIP-TK04-GBX01", pidTag: "05-AT-203", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "CIP Tank 4 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-024", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK05", assetNumber: "CIP-TK05-MTR01", pidTag: "05-AT-204", componentName: "Motor", componentType: "Motor", sparePartDescription: "CIP Tank 5 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-025", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK05", assetNumber: "CIP-TK05-GBX01", pidTag: "05-AT-204", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "CIP Tank 5 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-026", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK06", assetNumber: "CIP-TK06-MTR01", pidTag: "05-AT-205", componentName: "Motor", componentType: "Motor", sparePartDescription: "CIP Tank 6 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-027", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK06", assetNumber: "CIP-TK06-GBX01", pidTag: "05-AT-205", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "CIP Tank 6 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-028", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK07", assetNumber: "CIP-TK07-MTR01", pidTag: "05-AT-206", componentName: "Motor", componentType: "Motor", sparePartDescription: "CIP Tank 7 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-029", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK07", assetNumber: "CIP-TK07-GBX01", pidTag: "05-AT-206", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "CIP Tank 7 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-030", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK08", assetNumber: "CIP-TK08-MTR01", pidTag: "05-AT-207", componentName: "Motor", componentType: "Motor", sparePartDescription: "CIP Tank 8 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-031", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK08", assetNumber: "CIP-TK08-GBX01", pidTag: "05-AT-207", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "CIP Tank 8 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-032", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-SUMP", assetNumber: "CIP-SUMP-PMP-D", pidTag: "", componentName: "Pump", componentType: "Pump", sparePartDescription: "CIP Area Sump Pump (Duty)", oemPartNumber: "65QV-SPR1200", manufacturer: "WARMAN", vendor: "Weir", assetManufacturer: "WARMAN", assetModel: "65QV-SPR1200", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Process pump - critical to operations", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-033", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-SCR-INT", assetNumber: "CIP-SCR-INT", pidTag: "", componentName: "Intertank Screen", componentType: "Screen", sparePartDescription: "Intertank Screen", oemPartNumber: "TBC", manufacturer: "ALLOYTECH", vendor: "ALLOYTECH", assetManufacturer: "ALLOYTECH", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Screen - CIP circuit critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- Elution > COL01 Elution Column ---
  { id: "CS-034", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "COL01 Elution Column", parentAsset: "HTR01", assetNumber: "HTR01", pidTag: "08-HX-100", componentName: "Elution Heater", componentType: "Heater", sparePartDescription: "Elution Heater Unit", oemPartNumber: "500KW-SS", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "500kW SS Coil Direct Heater", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Heater unit - elution critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-035", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "COL01 Elution Column", parentAsset: "BRN01", assetNumber: "BRN01", pidTag: "08-HX-100", componentName: "Burner Unit", componentType: "Burner", sparePartDescription: "Elution Heater Burner", oemPartNumber: "GX 5/2 TL", manufacturer: "FBR", vendor: "", assetManufacturer: "FBR", assetModel: "GX 5/2 TL", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Burner unit - elution critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // --- Carbon Regeneration > CREG01 Carbon Regeneration System ---
  { id: "CS-036", area: "REC", areaLabel: "Gold Recovery", subArea: "Carbon Regeneration", system: "CREG01 Carbon Regeneration System", parentAsset: "CREG01", assetNumber: "CREG01-KLN01", pidTag: "08-KN-001", componentName: "Kiln Motor", componentType: "Motor", sparePartDescription: "Regeneration Kiln Motor", oemPartNumber: "TBC", manufacturer: "", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-037", area: "REC", areaLabel: "Gold Recovery", subArea: "Carbon Regeneration", system: "CREG01 Carbon Regeneration System", parentAsset: "CREG01", assetNumber: "CREG01-BRN01", pidTag: "08-KN-001", componentName: "Burner Unit", componentType: "Burner", sparePartDescription: "Regeneration Kiln Burner", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Burner unit - regeneration critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- Gold Room > EWCL01 Electrowinning Cell ---
  { id: "CS-038", area: "REC", areaLabel: "Gold Recovery", subArea: "Gold Room", system: "EWCL01 Electrowinning Cell", parentAsset: "REC01", assetNumber: "REC01", pidTag: "08-EW-100", componentName: "Rectifier Unit", componentType: "Rectifier", sparePartDescription: "Electrowinning Rectifier", oemPartNumber: "pe3000-6", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "pe3000-6", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Critical instrumentation - electrowinning", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // ═══════════════════════════════════════════════════════════════════════════
  // TAIL - TAILINGS
  // ═══════════════════════════════════════════════════════════════════════════

  // --- Thickening > THK01 Thickener ---
  { id: "CS-039", area: "TAIL", areaLabel: "Tailings", subArea: "Thickening", system: "THK01 Thickener", parentAsset: "THK01", assetNumber: "THK01-HYD01", pidTag: "12-TH-100", componentName: "Hydraulic Pack", componentType: "Hydraulic", sparePartDescription: "Thickener Hydraulic Power Unit", oemPartNumber: "AEU8-4P-11KW FR160M", manufacturer: "PARKER", vendor: "PARKER", assetManufacturer: "PARKER", assetModel: "AEU8-4P-11KW FR160M", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Hydraulic - thickener critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // --- Thickening > THKUFP-A Thickener Underflow Pump ---
  { id: "CS-040", area: "TAIL", areaLabel: "Tailings", subArea: "Thickening", system: "THKUFP-A Thickener Underflow Pump", parentAsset: "THKUFP-A", assetNumber: "THKUFP-A", pidTag: "12-PP-100", componentName: "Pump Full", componentType: "Pump", sparePartDescription: "Thickener Underflow Pump A", oemPartNumber: "75kW / 4P / 1485RPM", manufacturer: "WARMAN", vendor: "Weir", assetManufacturer: "WARMAN", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Process pump - critical to operations", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-041", area: "TAIL", areaLabel: "Tailings", subArea: "Thickening", system: "THKUFP-A Thickener Underflow Pump", parentAsset: "THKUFP-A", assetNumber: "THKUFP-A-MTR01", pidTag: "12-PP-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Thickener Underflow Pump A Motor", oemPartNumber: "Weg W22 90kW 4P", manufacturer: "Weg", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-042", area: "TAIL", areaLabel: "Tailings", subArea: "Thickening", system: "THKUFP-A Thickener Underflow Pump", parentAsset: "THKUFP-B", assetNumber: "THKUFP-B", pidTag: "12-PP-101", componentName: "Pump Full", componentType: "Pump", sparePartDescription: "Thickener Underflow Pump B", oemPartNumber: "75kW / 4P / 1485RPM", manufacturer: "WARMAN", vendor: "Weir", assetManufacturer: "WARMAN", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Process pump - critical to operations", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-043", area: "TAIL", areaLabel: "Tailings", subArea: "Thickening", system: "THKUFP-A Thickener Underflow Pump", parentAsset: "THKUFP-B", assetNumber: "THKUFP-B-MTR01", pidTag: "12-PP-101", componentName: "Motor", componentType: "Motor", sparePartDescription: "Thickener Underflow Pump B Motor", oemPartNumber: "Weg W22 90kW 4P", manufacturer: "Weg", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // --- Filtering > FP01 Filter Press ---
  { id: "CS-044", area: "TAIL", areaLabel: "Tailings", subArea: "Filtering", system: "FP01 Filter Press", parentAsset: "FP01", assetNumber: "FP01-MTR01", pidTag: "13-FP-100", componentName: "HPU Motor", componentType: "Motor", sparePartDescription: "Filter Press HPU Motor", oemPartNumber: "TBC", manufacturer: "", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-045", area: "TAIL", areaLabel: "Tailings", subArea: "Filtering", system: "FP01 Filter Press", parentAsset: "FP01", assetNumber: "FP01-HPU01", pidTag: "13-FP-100", componentName: "Hydraulic Pump", componentType: "Pump", sparePartDescription: "Filter Press Hydraulic Pump", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - process critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- Filtering > FFD01 Filter Feed Pump ---
  { id: "CS-046", area: "TAIL", areaLabel: "Tailings", subArea: "Filtering", system: "FFD01 Filter Feed Pump", parentAsset: "FFD01-PMP01", assetNumber: "FFD01-PMP01", pidTag: "13-PP-100", componentName: "Pump Full", componentType: "Pump", sparePartDescription: "Filter Feed Pump Duty", oemPartNumber: "PSH2100 V/A/A400 (DLT1050-2H)", manufacturer: "ALFA POMPE", vendor: "ALFA POMPE", assetManufacturer: "ALFA POMPE", assetModel: "PSH2100", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Process pump - critical to operations", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-047", area: "TAIL", areaLabel: "Tailings", subArea: "Filtering", system: "FFD01 Filter Feed Pump", parentAsset: "FFD01-MTR01", assetNumber: "FFD01-MTR01", pidTag: "13-PP-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Filter Feed Pump Duty Motor", oemPartNumber: "280M4", manufacturer: "ELVEM", vendor: "NEWMAN", assetManufacturer: "ELVEM", assetModel: "280M4", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-048", area: "TAIL", areaLabel: "Tailings", subArea: "Filtering", system: "FFD01 Filter Feed Pump", parentAsset: "FFD01-PMP02", assetNumber: "FFD01-PMP02", pidTag: "13-PP-101", componentName: "Pump Full", componentType: "Pump", sparePartDescription: "Filter Feed Pump Standby", oemPartNumber: "PSH2100 V/A/A400 (DLT1050-2H)", manufacturer: "ALFA POMPE", vendor: "ALFA POMPE", assetManufacturer: "ALFA POMPE", assetModel: "PSH2100", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Process pump - critical to operations", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-049", area: "TAIL", areaLabel: "Tailings", subArea: "Filtering", system: "FFD01 Filter Feed Pump", parentAsset: "FFD01-MTR02", assetNumber: "FFD01-MTR02", pidTag: "13-PP-101", componentName: "Motor", componentType: "Motor", sparePartDescription: "Filter Feed Pump Standby Motor", oemPartNumber: "280M4", manufacturer: "ELVEM", vendor: "NEWMAN", assetManufacturer: "ELVEM", assetModel: "280M4", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // ═══════════════════════════════════════════════════════════════════════════
  // UTL - UTILITIES & POWER
  // ═══════════════════════════════════════════════════════════════════════════

  // --- Reagents > CMIX01 Cyanide Mixing System ---
  { id: "CS-050", area: "UTL", areaLabel: "Utilities & Power", subArea: "Reagents", system: "CMIX01 Cyanide Mixing System", parentAsset: "CYN-MIX-AGT-01", assetNumber: "CYN-MIX-AGT-01", pidTag: "06-AT-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Cyanide Mixing Tank Agitator Motor", oemPartNumber: "MTE8 W22M", manufacturer: "Weg", vendor: "NEWMAN", assetManufacturer: "WEG", assetModel: "MTE8 W22M", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-051", area: "UTL", areaLabel: "Utilities & Power", subArea: "Reagents", system: "CMIX01 Cyanide Mixing System", parentAsset: "CYN-MIX-AGT-01", assetNumber: "CYN-MIX-GBX-01", pidTag: "06-AT-100", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Cyanide Mixing Tank Agitator Gearbox", oemPartNumber: "MC4350", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time, plant impact", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-052", area: "UTL", areaLabel: "Utilities & Power", subArea: "Reagents", system: "CMIX01 Cyanide Mixing System", parentAsset: "PMP09", assetNumber: "PMP09", pidTag: "06-PP-100", componentName: "Pump Full", componentType: "Pump", sparePartDescription: "Cyanide Solution Transfer Pump", oemPartNumber: "CRN20-01 A FGI-G-V-HQQV", manufacturer: "GRUNDFOS", vendor: "GRUNDFOS", assetManufacturer: "GRUNDFOS", assetModel: "CRN20-01", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Process pump - critical to operations", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // --- Reagents > CDOS01 Cyanide Dosing System ---
  { id: "CS-053", area: "UTL", areaLabel: "Utilities & Power", subArea: "Reagents", system: "CDOS01 Cyanide Dosing System", parentAsset: "CDOS01-PMP01", assetNumber: "CDOS01-PMP01", pidTag: "06-PP-100", componentName: "Pump", componentType: "Pump", sparePartDescription: "Cyanide Dosing Pump Duty", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Process pump - critical to operations", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- Reagents > CAUS01 Caustic Dosing System ---
  { id: "CS-054", area: "UTL", areaLabel: "Utilities & Power", subArea: "Reagents", system: "CAUS01 Caustic Dosing System", parentAsset: "CAUS01-PMP01", assetNumber: "CAUS01-PMP01", pidTag: "06-DS-100", componentName: "Pump", componentType: "Pump", sparePartDescription: "Caustic Dosing Pump", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Process pump - critical to operations", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-055", area: "UTL", areaLabel: "Utilities & Power", subArea: "Reagents", system: "CAUS01 Caustic Dosing System", parentAsset: "CAUS01-MTR01", assetNumber: "CAUS01-MTR01", pidTag: "06-DS-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Caustic Dosing Pump Motor", oemPartNumber: "TBC", manufacturer: "", vendor: "NEWMAN", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- Reagents > FLOC01 Floc System ---
  { id: "CS-056", area: "UTL", areaLabel: "Utilities & Power", subArea: "Reagents", system: "FLOC01 Floc System", parentAsset: "FLOC01-PMP01", assetNumber: "FLOC01-PMP01", pidTag: "12-DS-100", componentName: "Pump", componentType: "Pump", sparePartDescription: "Floc Dosing Pump", oemPartNumber: "BN1-6L", manufacturer: "SEEPEX", vendor: "SEEPEX", assetManufacturer: "SEEPEX", assetModel: "BN1-6L", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Process pump - critical to operations", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // --- Water > PWP01 Process Water System ---
  { id: "CS-057", area: "UTL", areaLabel: "Utilities & Power", subArea: "Water", system: "PWP01 Process Water System", parentAsset: "UTL-PW-PMP-D", assetNumber: "UTL-PW-PMP-D", pidTag: "15-PP-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Process Water Pump Motor (Duty)", oemPartNumber: "KTE44 W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "WEG", assetModel: "KTE44 W22M", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-058", area: "UTL", areaLabel: "Utilities & Power", subArea: "Water", system: "PWP01 Process Water System", parentAsset: "UTL-PW-PMP-S", assetNumber: "UTL-PW-PMP-S", pidTag: "15-PP-101", componentName: "Motor", componentType: "Motor", sparePartDescription: "Process Water Pump Motor (Standby)", oemPartNumber: "KTE44 W22M", manufacturer: "WEG", vendor: "NEWMAN", assetManufacturer: "WEG", assetModel: "KTE44 W22M", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // --- Compressed Air > HPCP01 HP Air Compressor ---
  { id: "CS-059", area: "UTL", areaLabel: "Utilities & Power", subArea: "Compressed Air", system: "HPCP01 HP Air Compressor", parentAsset: "HPCP01", assetNumber: "HPCP01", pidTag: "16-AC-100", componentName: "Compressor", componentType: "Compressor", sparePartDescription: "HP Air Compressor 1", oemPartNumber: "C-201", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Compressor - plant air critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-060", area: "UTL", areaLabel: "Utilities & Power", subArea: "Compressed Air", system: "HPCP01 HP Air Compressor", parentAsset: "HPCP02", assetNumber: "HPCP02", pidTag: "16-AC-101", componentName: "Compressor", componentType: "Compressor", sparePartDescription: "HP Air Compressor 2", oemPartNumber: "C-202", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Compressor - plant air critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- Power Generation > GEN01 Generators ---
  { id: "CS-061", area: "UTL", areaLabel: "Utilities & Power", subArea: "Power Generation", system: "GEN01 Generators", parentAsset: "GEN01", assetNumber: "GEN01", pidTag: "", componentName: "Generator", componentType: "Generator", sparePartDescription: "Power Station Generator 1 (500kVA)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Generator - power critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // ═══════════════════════════════════════════════════════════════════════════
  // ADDITIONAL HIGH PRIORITY ITEMS (CS-062 to CS-093) - RESTORED
  // ═══════════════════════════════════════════════════════════════════════════

  // --- REC > Leaching > Leach Tanks ---
  { id: "CS-062", area: "REC", areaLabel: "Gold Recovery", subArea: "Leaching", system: "LCH01 Leach Tank 1", parentAsset: "LCH01", assetNumber: "LCH01-MTR01", pidTag: "05-AG-001", componentName: "Motor", componentType: "Motor", sparePartDescription: "Leach Tank 1 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-063", area: "REC", areaLabel: "Gold Recovery", subArea: "Leaching", system: "LCH01 Leach Tank 1", parentAsset: "LCH01", assetNumber: "LCH01-GBX01", pidTag: "05-AG-001", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Leach Tank 1 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-064", area: "REC", areaLabel: "Gold Recovery", subArea: "Leaching", system: "LCH02 Leach Tank 2", parentAsset: "LCH02", assetNumber: "LCH02-MTR01", pidTag: "05-AG-002", componentName: "Motor", componentType: "Motor", sparePartDescription: "Leach Tank 2 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-065", area: "REC", areaLabel: "Gold Recovery", subArea: "Leaching", system: "LCH02 Leach Tank 2", parentAsset: "LCH02", assetNumber: "LCH02-GBX01", pidTag: "05-AG-002", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Leach Tank 2 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-066", area: "REC", areaLabel: "Gold Recovery", subArea: "Leaching", system: "LCH03 Leach Tank 3", parentAsset: "LCH03", assetNumber: "LCH03-MTR01", pidTag: "05-AG-003", componentName: "Motor", componentType: "Motor", sparePartDescription: "Leach Tank 3 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-067", area: "REC", areaLabel: "Gold Recovery", subArea: "Leaching", system: "LCH03 Leach Tank 3", parentAsset: "LCH03", assetNumber: "LCH03-GBX01", pidTag: "05-AG-003", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Leach Tank 3 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // --- REC > CIP > Intertank Screen ---
  { id: "CS-068", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-SCR-INT Intertank Screen", parentAsset: "CIP-SCR-INT", assetNumber: "CIP-SCR-INT-MTR01", pidTag: "", componentName: "Motor", componentType: "Motor", sparePartDescription: "Intertank Screen Motor", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "Alloytec", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - CIP circuit critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-069", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-SCR-INT Intertank Screen", parentAsset: "CIP-SCR-INT", assetNumber: "CIP-SCR-INT-EXC01", pidTag: "", componentName: "Exciter", componentType: "Mechanical", sparePartDescription: "Intertank Screen Exciter", oemPartNumber: "Bonfiglioli", manufacturer: "Bonfiglioli", vendor: "", assetManufacturer: "Alloytec", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Exciter - screen critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- REC > CIP > Additional CIP Tanks (6-8) ---
  { id: "CS-070", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK06", assetNumber: "CIP-TK06-MTR01", pidTag: "05-AT-205", componentName: "Motor", componentType: "Motor", sparePartDescription: "CIP Tank 6 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-071", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK06", assetNumber: "CIP-TK06-GBX01", pidTag: "05-AT-205", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "CIP Tank 6 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-072", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK07", assetNumber: "CIP-TK07-MTR01", pidTag: "05-AT-206", componentName: "Motor", componentType: "Motor", sparePartDescription: "CIP Tank 7 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-073", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK07", assetNumber: "CIP-TK07-GBX01", pidTag: "05-AT-206", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "CIP Tank 7 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-074", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK08", assetNumber: "CIP-TK08-MTR01", pidTag: "05-AT-207", componentName: "Motor", componentType: "Motor", sparePartDescription: "CIP Tank 8 Agitator Motor", oemPartNumber: "Siemens 1LA7163-2AA70 (15kW)", manufacturer: "Siemens", vendor: "NEWMAN", assetManufacturer: "MIXTEC", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - plant stoppage risk", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },
  { id: "CS-075", area: "REC", areaLabel: "Gold Recovery", subArea: "CIP", system: "CIP-TK01 CIP Tanks", parentAsset: "CIP-TK08", assetNumber: "CIP-TK08-GBX01", pidTag: "05-AT-207", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "CIP Tank 8 Agitator Gearbox", oemPartNumber: "MC4350/01/1167", manufacturer: "MIXTEC", vendor: "MIXTEC", assetManufacturer: "MIXTEC", assetModel: "MC4350", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - long lead time", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "Provisional" },

  // --- REC > Elution > Elution System ---
  { id: "CS-076", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "ELU01 Elution Column", parentAsset: "ELU01", assetNumber: "ELU-PMP-D", pidTag: "06-PP-100", componentName: "Pump", componentType: "Pump", sparePartDescription: "Elution Pump (Duty)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - elution critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-077", area: "REC", areaLabel: "Gold Recovery", subArea: "Elution", system: "ELU01 Elution Column", parentAsset: "ELU01", assetNumber: "ELU-PMP-S", pidTag: "06-PP-101", componentName: "Pump", componentType: "Pump", sparePartDescription: "Elution Pump (Standby)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - elution critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- REC > Carbon Regen > Kiln ---
  { id: "CS-078", area: "REC", areaLabel: "Gold Recovery", subArea: "Carbon Regen", system: "KLN01 Regen Kiln", parentAsset: "KLN01", assetNumber: "KLN01-BRN01", pidTag: "07-KL-100", componentName: "Burner", componentType: "Burner", sparePartDescription: "Kiln Burner", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Burner - carbon regen critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-079", area: "REC", areaLabel: "Gold Recovery", subArea: "Carbon Regen", system: "KLN01 Regen Kiln", parentAsset: "KLN01", assetNumber: "KLN01-MTR01", pidTag: "07-KL-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Kiln Drive Motor", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - carbon regen critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- REC > Gold Room ---
  { id: "CS-080", area: "REC", areaLabel: "Gold Recovery", subArea: "Gold Room", system: "GR01 Gold Room", parentAsset: "EWCL01", assetNumber: "EWCL01-REC01", pidTag: "08-EW-100", componentName: "Rectifier", componentType: "Rectifier", sparePartDescription: "Electrowinning Rectifier", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Rectifier - gold room critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-081", area: "REC", areaLabel: "Gold Recovery", subArea: "Gold Room", system: "GR01 Gold Room", parentAsset: "CALC01", assetNumber: "CALC01-HTR01", pidTag: "08-FN-100", componentName: "Heater", componentType: "Heater", sparePartDescription: "Calcine Oven Heater", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Heater - gold room critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- TAIL > Tailings Thickener ---
  { id: "CS-082", area: "TAIL", areaLabel: "Tailings", subArea: "Tailings", system: "THK01 Tailings Thickener", parentAsset: "THK01", assetNumber: "THK01-MTR01", pidTag: "09-TH-100", componentName: "Motor", componentType: "Motor", sparePartDescription: "Thickener Drive Motor", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Motor - tailings critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-083", area: "TAIL", areaLabel: "Tailings", subArea: "Tailings", system: "THK01 Tailings Thickener", parentAsset: "THK01", assetNumber: "THK01-GBX01", pidTag: "09-TH-100", componentName: "Gearbox", componentType: "Gearbox", sparePartDescription: "Thickener Drive Gearbox", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Gearbox - tailings critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-084", area: "TAIL", areaLabel: "Tailings", subArea: "Tailings", system: "THK01 Tailings Thickener", parentAsset: "THK-UFP-A", assetNumber: "THK-UFP-A", pidTag: "09-PP-100", componentName: "Pump", componentType: "Pump", sparePartDescription: "Thickener Underflow Pump A", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - tailings critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-085", area: "TAIL", areaLabel: "Tailings", subArea: "Tailings", system: "THK01 Tailings Thickener", parentAsset: "THK-UFP-B", assetNumber: "THK-UFP-B", pidTag: "09-PP-101", componentName: "Pump", componentType: "Pump", sparePartDescription: "Thickener Underflow Pump B", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - tailings critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- TAIL > Filter Press ---
  { id: "CS-086", area: "TAIL", areaLabel: "Tailings", subArea: "Tailings Filtration", system: "FP01 Filter Press 1", parentAsset: "FP01", assetNumber: "FP01-HPU01", pidTag: "10-FP-100", componentName: "Hydraulic Power Unit", componentType: "Hydraulic", sparePartDescription: "Filter Press 1 HPU", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "HPU - filter press critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-087", area: "TAIL", areaLabel: "Tailings", subArea: "Tailings Filtration", system: "FP01 Filter Press 1", parentAsset: "FP01", assetNumber: "FP01-PLC01", pidTag: "10-FP-100", componentName: "PLC", componentType: "Electrical", sparePartDescription: "Filter Press 1 PLC", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "PLC - filter press critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-088", area: "TAIL", areaLabel: "Tailings", subArea: "Tailings Filtration", system: "FP02 Filter Press 2", parentAsset: "FP02", assetNumber: "FP02-HPU01", pidTag: "10-FP-101", componentName: "Hydraulic Power Unit", componentType: "Hydraulic", sparePartDescription: "Filter Press 2 HPU", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "HPU - filter press critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-089", area: "TAIL", areaLabel: "Tailings", subArea: "Tailings Filtration", system: "FP02 Filter Press 2", parentAsset: "FP02", assetNumber: "FP02-PLC01", pidTag: "10-FP-101", componentName: "PLC", componentType: "Electrical", sparePartDescription: "Filter Press 2 PLC", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "PLC - filter press critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- TAIL > Tailings Feed Pumps ---
  { id: "CS-090", area: "TAIL", areaLabel: "Tailings", subArea: "Tailings Filtration", system: "FP01 Filter Press 1", parentAsset: "FP-FP-A", assetNumber: "FP-FP-A", pidTag: "10-PP-100", componentName: "Pump", componentType: "Pump", sparePartDescription: "Filter Press Feed Pump A", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - filter press critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-091", area: "TAIL", areaLabel: "Tailings", subArea: "Tailings Filtration", system: "FP01 Filter Press 1", parentAsset: "FP-FP-B", assetNumber: "FP-FP-B", pidTag: "10-PP-101", componentName: "Pump", componentType: "Pump", sparePartDescription: "Filter Press Feed Pump B", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Pump - filter press critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },

  // --- UTL > Additional Generators ---
  { id: "CS-092", area: "UTL", areaLabel: "Utilities & Power", subArea: "Power Generation", system: "GEN01 Generators", parentAsset: "GEN02", assetNumber: "GEN02", pidTag: "", componentName: "Generator", componentType: "Generator", sparePartDescription: "Power Station Generator 2 (500kVA)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Generator - power critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
  { id: "CS-093", area: "UTL", areaLabel: "Utilities & Power", subArea: "Power Generation", system: "GEN01 Generators", parentAsset: "GEN03", assetNumber: "GEN03", pidTag: "", componentName: "Generator", componentType: "Generator", sparePartDescription: "Power Station Generator 3 (500kVA)", oemPartNumber: "TBC", manufacturer: "", vendor: "", assetManufacturer: "", assetModel: "", spareCriticality: "High", criticalitySource: "Confirmed", reasonCritical: "Generator - power critical", minQty: "0", maxQty: "1", qtyPerSystem: "1", unitPrice: "", uom: "EA", notes: "", status: "TBC" },
];

// Component types for filtering
export const componentTypes = [
  "Motor",
  "Gearbox",
  "Pump",
  "Valve",
  "Roller",
  "Bearing",
  "Seal",
  "Coupling",
  "Belt",
  "Impeller",
  "Liner",
  "Screen",
  "Sensor",
  "Actuator",
  "Pulley",
  "Consumable",
  "Heater",
  "Filter",
  "Electrical",
  "Mechanical",
  "Wear Items",
  "Pillow Block",
  "Burner",
  "Rectifier",
  "Air Cooler",
  "Agitator",
  "Pinion",
  "Hydraulic",
  "Compressor",
  "Generator",
];

// Area codes for filtering - matches assetData.ts Area.code
export const areaCodes = [
  { code: "SITE", label: "Site" },
  { code: "UTL", label: "Utilities & Power" },
  { code: "COM", label: "Comminution / Process" },
  { code: "REC", label: "Gold Recovery" },
  { code: "TAIL", label: "Tailings" },
  { code: "SUP", label: "Support Services" },
];

// Criticality colors
export const criticalityColors: Record<string, string> = {
  "High": "bg-destructive/20 text-destructive",
  "Medium": "bg-amber-500/20 text-amber-700",
  "Low": "bg-muted text-muted-foreground",
  "": "",
};

// Status colors
export const statusColors: Record<string, string> = {
  "Provisional": "bg-amber-500/20 text-amber-700",
  "Confirmed": "bg-green-500/20 text-green-700",
  "TBC": "bg-muted text-muted-foreground",
};

// Criticality source colors
export const criticalitySourceColors: Record<string, string> = {
  "Confirmed": "bg-green-500/20 text-green-700",
  "Assumed": "bg-amber-500/20 text-amber-700",
  "": "",
};
