// Critical Spares Register Data
// IMPORTANT: Data populated from user-provided Excel spreadsheet (Book1.xlsx)
// Source document is the authoritative master for this data
// criticalitySource = "Confirmed" as user explicitly stated all items in the spreadsheet are critical

export interface SpareItem {
  id: string;
  // Hierarchy linkage
  area: string;
  subArea: string;
  system: string;
  parentAsset: string;
  pidTag: string;
  // Component details
  componentName: string;
  componentType: string;
  sparePartDescription: string;
  oemPartNumber: string;
  manufacturer: string;
  vendor: string;
  assetManufacturer: string;
  assetModel: string;
  // Criticality
  spareCriticality: "High" | "Medium" | "Low" | "";
  criticalitySource: "Confirmed" | "Assumed" | "";
  reasonCritical: string;
  // Quantities
  minQty: string;
  maxQty: string;
  qtyPerSystem: string;
  unitPrice: string;
  uom: string;
  // Other fields
  notes: string;
  status: "Provisional" | "Confirmed" | "TBC";
}

// Critical Spares data - Populated from site OEM spreadsheet
export const sparesData: SpareItem[] = [
  // === GRINDING AREA (04) ===
  // 4-FE-100 Reclaim Feeder
  {
    id: "CS-001",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Reclaim Feeder",
    parentAsset: "4-FE-100",
    pidTag: "04-FE-100",
    componentName: "Motor",
    componentType: "Motor",
    sparePartDescription: "Reclaim Feeder Motor",
    oemPartNumber: "SEW-EURODRIVE KA107R77 DRN112M4/V",
    manufacturer: "SEW",
    vendor: "SEW",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant feed critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$16,450.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-002",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Reclaim Feeder",
    parentAsset: "4-FE-100",
    pidTag: "04-FE-100",
    componentName: "Gearbox",
    componentType: "Gearbox",
    sparePartDescription: "Reclaim Feeder Gearbox",
    oemPartNumber: "SEW-EURODRIVE KA107R77 DRN112M4/V",
    manufacturer: "SEW",
    vendor: "SEW",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant feed critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-003",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Reclaim Feeder",
    parentAsset: "4-FE-100",
    pidTag: "04-FE-100",
    componentName: "Head Pulley Pillow Block",
    componentType: "Pillow Block",
    sparePartDescription: "Head pulley Pillow Block",
    oemPartNumber: "TBC - Robbie please advise",
    manufacturer: "",
    vendor: "CBC",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant feed critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "2",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "TBC",
  },
  {
    id: "CS-004",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Reclaim Feeder",
    parentAsset: "4-FE-100",
    pidTag: "04-FE-100",
    componentName: "Head Pulley Bearing",
    componentType: "Bearing",
    sparePartDescription: "Head pulley Bearing",
    oemPartNumber: "TBC - Robbie please advise",
    manufacturer: "",
    vendor: "CBC",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant feed critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "2",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "TBC",
  },
  {
    id: "CS-005",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Reclaim Feeder",
    parentAsset: "4-FE-100",
    pidTag: "04-FE-100",
    componentName: "Tail Pulley Pillow Block",
    componentType: "Pillow Block",
    sparePartDescription: "Tail pulley Pillow Block",
    oemPartNumber: "TBC - Robbie please advise",
    manufacturer: "",
    vendor: "CBC",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant feed critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "2",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "TBC",
  },
  {
    id: "CS-006",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Reclaim Feeder",
    parentAsset: "4-FE-100",
    pidTag: "04-FE-100",
    componentName: "Tail Pulley Bearing",
    componentType: "Bearing",
    sparePartDescription: "Tail pulley Bearings",
    oemPartNumber: "TBC - Robbie please advise",
    manufacturer: "",
    vendor: "CBC",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant feed critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "2",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "TBC",
  },
  {
    id: "CS-007",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Reclaim Feeder",
    parentAsset: "4-FE-100",
    pidTag: "04-FE-100",
    componentName: "Conveyor Belt",
    componentType: "Belt",
    sparePartDescription: "Conveyor belt",
    oemPartNumber: "TBC - Robbie please advise",
    manufacturer: "",
    vendor: "",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant feed critical",
    minQty: "0",
    maxQty: "0",
    qtyPerSystem: "1",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "TBC",
  },
  {
    id: "CS-008",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Reclaim Feeder",
    parentAsset: "4-FE-100",
    pidTag: "04-FE-100",
    componentName: "Roller - Steel Trough",
    componentType: "Roller",
    sparePartDescription: "Roller - Steel Trough",
    oemPartNumber: "P/N: K-ROL-STR-600B25",
    manufacturer: "Britac",
    vendor: "Britac",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "3",
    maxQty: "5",
    qtyPerSystem: "",
    unitPrice: "$70.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-009",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Reclaim Feeder",
    parentAsset: "4-FE-100",
    pidTag: "04-FE-100",
    componentName: "Roller - Steel Return",
    componentType: "Roller",
    sparePartDescription: "Roller - Steel Return",
    oemPartNumber: "P/N: K-ROL-SRR-1200B25",
    manufacturer: "Britac",
    vendor: "Britac",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "1",
    maxQty: "3",
    qtyPerSystem: "",
    unitPrice: "$167.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-010",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Reclaim Feeder",
    parentAsset: "4-FE-100",
    pidTag: "04-FE-100",
    componentName: "Hard Skirt",
    componentType: "Wear Items",
    sparePartDescription: "Hard Skirt - 3750 x 100mm, Thickness: 12mm, Material: Bisalloy",
    oemPartNumber: "Dimensions: 3750 x 100mm, Thickness: 12mm, Material: Bisalloy",
    manufacturer: "Fenner",
    vendor: "Fenner",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "0",
    maxQty: "0",
    qtyPerSystem: "",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  // 4-FE-101 Transfer Conveyor
  {
    id: "CS-011",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Transfer Conveyor",
    parentAsset: "4-FE-101",
    pidTag: "04-FE-101",
    componentName: "Motor",
    componentType: "Motor",
    sparePartDescription: "Transfer Conveyor Motor",
    oemPartNumber: "SEW-EURODRIVE KA77/T.DRE132M4/RS",
    manufacturer: "SEW",
    vendor: "SEW",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant feed critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$-",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-012",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Transfer Conveyor",
    parentAsset: "4-FE-101",
    pidTag: "04-FE-101",
    componentName: "Gearbox",
    componentType: "Gearbox",
    sparePartDescription: "Transfer Conveyor Gearbox",
    oemPartNumber: "SEW-EURODRIVE KA77/T.DRE132M4/RS",
    manufacturer: "SEW",
    vendor: "SEW",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant feed critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-013",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Transfer Conveyor",
    parentAsset: "4-FE-101",
    pidTag: "04-FE-101",
    componentName: "Roller - Steel Trough",
    componentType: "Roller",
    sparePartDescription: "Roller - Steel Trough",
    oemPartNumber: "P/N: K-ROL-STR-600B25",
    manufacturer: "Britac",
    vendor: "Britac",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "3",
    maxQty: "5",
    qtyPerSystem: "",
    unitPrice: "$167.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-014",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Transfer Conveyor",
    parentAsset: "4-FE-101",
    pidTag: "04-FE-101",
    componentName: "Roller - Steel Return",
    componentType: "Roller",
    sparePartDescription: "Roller - Steel Return",
    oemPartNumber: "P/N: K-ROL-STR-600B25",
    manufacturer: "Britac",
    vendor: "Britac",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "1",
    maxQty: "3",
    qtyPerSystem: "",
    unitPrice: "$167.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  // 4-BC-100 Mill Feed Conveyor
  {
    id: "CS-015",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Mill Feed Conveyor",
    parentAsset: "4-BC-100",
    pidTag: "04-BC-100",
    componentName: "Motor",
    componentType: "Motor",
    sparePartDescription: "Mill Feed Conveyor Motor",
    oemPartNumber: "KTE30 PHEM",
    manufacturer: "WEG",
    vendor: "NEWMAN",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill feed critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$-",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-016",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Mill Feed Conveyor",
    parentAsset: "4-BC-100",
    pidTag: "04-BC-100",
    componentName: "Drive Belt",
    componentType: "Belt",
    sparePartDescription: "Drive Belt",
    oemPartNumber: "TBC - Robbie please advise",
    manufacturer: "",
    vendor: "CBC",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill feed critical",
    minQty: "2",
    maxQty: "4",
    qtyPerSystem: "2",
    unitPrice: "$-",
    uom: "EA",
    notes: "",
    status: "TBC",
  },
  {
    id: "CS-017",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Mill Feed Conveyor",
    parentAsset: "4-BC-100",
    pidTag: "04-BC-100",
    componentName: "Side Guide Roller",
    componentType: "Roller",
    sparePartDescription: "Side Guide Roller",
    oemPartNumber: "P/N: K-ROL-SG-60x125-B",
    manufacturer: "Britac",
    vendor: "Britac",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "3",
    maxQty: "5",
    qtyPerSystem: "",
    unitPrice: "$82.40",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-018",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Mill Feed Conveyor",
    parentAsset: "4-BC-100",
    pidTag: "04-BC-100",
    componentName: "Roller - Steel Trough",
    componentType: "Roller",
    sparePartDescription: "Roller - Steel Trough",
    oemPartNumber: "P/N: K-ROL-STR-600B25",
    manufacturer: "Britac",
    vendor: "Britac",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "3",
    maxQty: "5",
    qtyPerSystem: "",
    unitPrice: "$56.90",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-019",
    area: "Grinding",
    subArea: "Materials Handling",
    system: "Mill Feed Conveyor",
    parentAsset: "4-BC-100",
    pidTag: "04-BC-100",
    componentName: "Roller - Steel Return",
    componentType: "Roller",
    sparePartDescription: "Roller - Steel Return",
    oemPartNumber: "P/N: K-ROL-SRR-600B25",
    manufacturer: "Britac",
    vendor: "Britac",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "1",
    maxQty: "3",
    qtyPerSystem: "",
    unitPrice: "$105.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  // 4-WE-506 Weightometer
  {
    id: "CS-020",
    area: "Grinding",
    subArea: "Instrumentation",
    system: "Weightometer",
    parentAsset: "4-WE-506",
    pidTag: "04-WE-506",
    componentName: "Weightometer Replacement",
    componentType: "Mechanical",
    sparePartDescription: "Weightometer replacement",
    oemPartNumber: "WF16-600-4000",
    manufacturer: "Tecweigh",
    vendor: "Tecweigh",
    assetManufacturer: "Tecweigh",
    assetModel: "WF16-600-4000",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Process control critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$65,000.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-021",
    area: "Grinding",
    subArea: "Instrumentation",
    system: "Weightometer",
    parentAsset: "4-WE-506",
    pidTag: "04-WE-506",
    componentName: "Load Cells",
    componentType: "Electrical",
    sparePartDescription: "Load cells",
    oemPartNumber: "TBC - Robbie please advise",
    manufacturer: "",
    vendor: "MCE",
    assetManufacturer: "Tecweigh",
    assetModel: "WF16-600-4000",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Process control critical",
    minQty: "0",
    maxQty: "4",
    qtyPerSystem: "",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "TBC",
  },
  // 4-FE-102 Lime Rotary Valve
  {
    id: "CS-022",
    area: "Grinding",
    subArea: "Reagents",
    system: "Lime Rotary Valve",
    parentAsset: "4-FE-102",
    pidTag: "04-FE-102",
    componentName: "Motor and Gearbox",
    componentType: "Motor and Gearbox",
    sparePartDescription: "Lime Rotary Valve Motor and Gearbox",
    oemPartNumber: "MD67-M1 / Ratio 34.29 / 1.5kW",
    manufacturer: "Melbourne Machinery Co",
    vendor: "",
    assetManufacturer: "Melbourne Machinery Co",
    assetModel: "MD67-M1",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Reagent dosing critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$1,390.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  // 4-ML-100 Primary Ball Mill
  {
    id: "CS-023",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill",
    parentAsset: "4-ML-100",
    pidTag: "04-ML-100",
    componentName: "Motor",
    componentType: "Motor",
    sparePartDescription: "Primary Ball Mill Motor 1000kW",
    oemPartNumber: "1LA4 454-4AN70-Z (1000kW)",
    manufacturer: "Siemens",
    vendor: "NEWMAN",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant stoppage if fails",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-024",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill",
    parentAsset: "4-ML-100",
    pidTag: "04-ML-100",
    componentName: "Pinion Assembly",
    componentType: "Mechanical",
    sparePartDescription: "Pinion assembly (2 bearings, 2 pillow block, 1 pinion)",
    oemPartNumber: "TBC",
    manufacturer: "",
    vendor: "BLA",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant stoppage if fails",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "",
    uom: "",
    notes: "",
    status: "TBC",
  },
  {
    id: "CS-025",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill",
    parentAsset: "4-ML-100",
    pidTag: "04-ML-100",
    componentName: "Mill Liners",
    componentType: "Liner",
    sparePartDescription: "Set of liners (Ops to advise)",
    oemPartNumber: "TBC - Ops to advise",
    manufacturer: "",
    vendor: "",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item - scheduled replacement",
    minQty: "0",
    maxQty: "0",
    qtyPerSystem: "1",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "TBC",
  },
  {
    id: "CS-026",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill",
    parentAsset: "4-ML-100",
    pidTag: "04-ML-100",
    componentName: "Trunnion Mats",
    componentType: "Wear Items",
    sparePartDescription: "Trunnion mats",
    oemPartNumber: "TBC - Robbie please advise",
    manufacturer: "",
    vendor: "",
    assetManufacturer: "",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill protection",
    minQty: "1",
    maxQty: "3",
    qtyPerSystem: "",
    unitPrice: "",
    uom: "",
    notes: "",
    status: "TBC",
  },
  // 4-GR-100 Primary Ball Mill Gear Reducer
  {
    id: "CS-027",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Gear Reducer",
    parentAsset: "4-GR-100",
    pidTag: "04-GR-100",
    componentName: "Gear Box Replacement",
    componentType: "Gearbox",
    sparePartDescription: "Primary Ball Mill Gear Reducer - Full Unit",
    oemPartNumber: "JKD 4504150638.01.001 / H1 SH 15 B",
    manufacturer: "Siemens",
    vendor: "Flender",
    assetManufacturer: "Flender",
    assetModel: "H1 SH 15B",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Plant stoppage if fails",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$70,000.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-028",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Gear Reducer",
    parentAsset: "4-GR-100",
    pidTag: "04-GR-100",
    componentName: "Coupling Motor Side (High Speed)",
    componentType: "Coupling",
    sparePartDescription: "Coupling motor side (high speed)",
    oemPartNumber: "Rupex RWN 450 Coupling",
    manufacturer: "",
    vendor: "",
    assetManufacturer: "Flender",
    assetModel: "H1 SH 15B",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-029",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Gear Reducer",
    parentAsset: "4-GR-100",
    pidTag: "04-GR-100",
    componentName: "Coupling Pinion Side (Low Speed)",
    componentType: "Coupling",
    sparePartDescription: "Coupling pinion side (low speed)",
    oemPartNumber: "Zapex ZWN 415 Coupling",
    manufacturer: "",
    vendor: "",
    assetManufacturer: "Flender",
    assetModel: "H1 SH 15B",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill critical",
    minQty: "0",
    maxQty: "0",
    qtyPerSystem: "1",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  // 4-LS-100 Primary Ball Mill Lube System
  {
    id: "CS-030",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube System",
    parentAsset: "4-LS-100",
    pidTag: "04-LS-100",
    componentName: "Reservoir Breather (Desiccant)",
    componentType: "Mechanical",
    sparePartDescription: "Reservoir Breather (Desiccant) (Rep. 43)",
    oemPartNumber: "934330TX1",
    manufacturer: "Parker",
    vendor: "Ausdraulics",
    assetManufacturer: "Parker / Isadraulics",
    assetModel: "AU-35395",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Lube system protection",
    minQty: "1",
    maxQty: "2",
    qtyPerSystem: "",
    unitPrice: "$180.60",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-031",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube System",
    parentAsset: "4-LS-100",
    pidTag: "04-LS-100",
    componentName: "Reservoir Refill Element",
    componentType: "Mechanical",
    sparePartDescription: "Reservoir Refill Element (Rep. 41)",
    oemPartNumber: "FTBE2A10Q",
    manufacturer: "Parker",
    vendor: "Ausdraulics",
    assetManufacturer: "Parker / Isadraulics",
    assetModel: "AU-35395",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Lube system protection",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "",
    unitPrice: "$298.20",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-032",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube System",
    parentAsset: "4-LS-100",
    pidTag: "04-LS-100",
    componentName: "Oil Level / Temperature Controller",
    componentType: "Electrical",
    sparePartDescription: "Oil Level / Temperature Controller (Rep. 40)",
    oemPartNumber: "SCLTSD-520-10-05",
    manufacturer: "Parker",
    vendor: "Ausdraulics",
    assetManufacturer: "Parker / Isadraulics",
    assetModel: "AU-35395",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill protection",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "",
    unitPrice: "$1,776.74",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-033",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube System",
    parentAsset: "4-LS-100",
    pidTag: "04-LS-100",
    componentName: "Pressure Sensor & Switch",
    componentType: "Electrical",
    sparePartDescription: "Pressure Sensor & Switch (Rep. 54)",
    oemPartNumber: "SCPSD-400-14-25",
    manufacturer: "Parker",
    vendor: "Ausdraulics",
    assetManufacturer: "Parker / Isadraulics",
    assetModel: "AU-35395",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill protection",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "",
    unitPrice: "$932.96",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-034",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube System",
    parentAsset: "4-LS-100",
    pidTag: "04-LS-100",
    componentName: "Filter Element (Medium Pressure)",
    componentType: "Filter",
    sparePartDescription: "Filter Element (Medium Pressure Filter) (Rep. 12)",
    oemPartNumber: "932667Q",
    manufacturer: "Parker",
    vendor: "Ausdraulics",
    assetManufacturer: "Parker / Isadraulics",
    assetModel: "AU-35395",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "2",
    maxQty: "4",
    qtyPerSystem: "",
    unitPrice: "$540.96",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-035",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube System",
    parentAsset: "4-LS-100",
    pidTag: "04-LS-100",
    componentName: "Filter Element (Low Pressure)",
    componentType: "Filter",
    sparePartDescription: "Filter Element (Low Pressure Filter) (Rep. 37)",
    oemPartNumber: "937399Q",
    manufacturer: "Parker",
    vendor: "Ausdraulics",
    assetManufacturer: "Parker / Isadraulics",
    assetModel: "AU-35395",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "2",
    maxQty: "4",
    qtyPerSystem: "",
    unitPrice: "$445.20",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-036",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube System",
    parentAsset: "4-LS-100",
    pidTag: "04-LS-100",
    componentName: "Relief Valve (Low Pressure)",
    componentType: "Valve",
    sparePartDescription: "Relief Valve (Low Pressure) (Rep. 11)",
    oemPartNumber: "RAH201S10",
    manufacturer: "Parker",
    vendor: "Ausdraulics",
    assetManufacturer: "Parker / Isadraulics",
    assetModel: "AU-35395",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Lube system protection",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "",
    unitPrice: "$660.66",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-037",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube System",
    parentAsset: "4-LS-100",
    pidTag: "04-LS-100",
    componentName: "Flow Divider Coupling",
    componentType: "Coupling",
    sparePartDescription: "Coupling (Flow Divider) (Rep. 19)",
    oemPartNumber: "A4-31169",
    manufacturer: "Parker",
    vendor: "Ausdraulics",
    assetManufacturer: "Parker / Isadraulics",
    assetModel: "AU-35395",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Lube system critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "",
    unitPrice: "$5,629.40",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  // 4-FA-006 Primary Ball Mill Lube Air Blast Oil Cooler
  {
    id: "CS-038",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube Air Blast Oil Cooler",
    parentAsset: "4-FA-006",
    pidTag: "04-FA-006",
    componentName: "Air Cooler Replacement Unit",
    componentType: "Air Cooler",
    sparePartDescription: "AC-LN7S/1.0/F/A/BP3 - Full Unit",
    oemPartNumber: "4028981",
    manufacturer: "HYDAC",
    vendor: "HYDAC",
    assetManufacturer: "Hydac",
    assetModel: "AC-LN7S/1.O/F/A/1/IBP3",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill lube cooling critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$5,664.20",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-039",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube Air Blast Oil Cooler",
    parentAsset: "4-FA-006",
    pidTag: "04-FA-006",
    componentName: "Motor",
    componentType: "Motor",
    sparePartDescription: "E-Motor IMB14 100M 3.0kW 4P 3Ph",
    oemPartNumber: "2355748",
    manufacturer: "HYDAC",
    vendor: "HYDAC",
    assetManufacturer: "Hydac",
    assetModel: "AC-LN7S/1.O/F/A/1/IBP3",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill lube cooling critical",
    minQty: "0",
    maxQty: "0",
    qtyPerSystem: "1",
    unitPrice: "$2,187.70",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-040",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube Air Blast Oil Cooler",
    parentAsset: "4-FA-006",
    pidTag: "04-FA-006",
    componentName: "Cooler Core Assembly Kit",
    componentType: "Mechanical",
    sparePartDescription: "KIT Cooler Core Assembly",
    oemPartNumber: "2355914",
    manufacturer: "HYDAC",
    vendor: "HYDAC",
    assetManufacturer: "Hydac",
    assetModel: "AC-LN7S/1.O/F/A/1/IBP3",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill lube cooling critical",
    minQty: "0",
    maxQty: "0",
    qtyPerSystem: "1",
    unitPrice: "$1,441.70",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  // 4-PU-16 Primary Ball Mill Lube Cooling Recirculating Pump
  {
    id: "CS-041",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Lube Cooling Pump",
    parentAsset: "4-PU-16",
    pidTag: "04-PU-016",
    componentName: "Full Pump Unit",
    componentType: "Pump",
    sparePartDescription: "Full Pump Unit",
    oemPartNumber: "3339111496",
    manufacturer: "Parker",
    vendor: "Powerdraulics",
    assetManufacturer: "Parker",
    assetModel: "3339111496",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill lube cooling critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$1,857.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  // 4-PU-100A Primary Ball Mill Low Pressure Lube Pump - Duty
  {
    id: "CS-042",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Low Pressure Lube Pump - Duty",
    parentAsset: "4-PU-100A",
    pidTag: "04-PU-100A",
    componentName: "Motor",
    componentType: "Motor",
    sparePartDescription: "Full Motor Assembly",
    oemPartNumber: "L194 W22",
    manufacturer: "WEG",
    vendor: "NEWMAN",
    assetManufacturer: "Motor: WEG, Pump: PARKER",
    assetModel: "L194 W22",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill lube critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$-",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-043",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Low Pressure Lube Pump - Duty",
    parentAsset: "4-PU-100A",
    pidTag: "04-PU-100A",
    componentName: "Pump",
    componentType: "Pump",
    sparePartDescription: "Pump",
    oemPartNumber: "3339111192",
    manufacturer: "PARKER",
    vendor: "Powerdraulics",
    assetManufacturer: "Motor: WEG, Pump: PARKER",
    assetModel: "",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill lube critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$1,857.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-044",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Low Pressure Lube Pump - Duty",
    parentAsset: "4-PU-100A",
    pidTag: "04-PU-100A",
    componentName: "Seals Kit",
    componentType: "Seal",
    sparePartDescription: "Seals Kit - Wet end",
    oemPartNumber: "3911822071",
    manufacturer: "PARKER",
    vendor: "Powerdraulics",
    assetManufacturer: "Motor: WEG, Pump: PARKER",
    assetModel: "",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "0",
    maxQty: "0",
    qtyPerSystem: "1",
    unitPrice: "$81.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  // 4-PU-101 Primary Ball Mill High Pressure Lube Pump
  {
    id: "CS-045",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill High Pressure Lube Pump",
    parentAsset: "4-PU-101",
    pidTag: "04-PU-101",
    componentName: "Motor",
    componentType: "Motor",
    sparePartDescription: "Motor",
    oemPartNumber: "L30 STDE2",
    manufacturer: "WEG",
    vendor: "NEWMAN",
    assetManufacturer: "Motor: WEG, Pump: PARKER",
    assetModel: "Motor: L30 STDE2",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill lube critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "",
    uom: "",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-046",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill High Pressure Lube Pump",
    parentAsset: "4-PU-101",
    pidTag: "04-PU-101",
    componentName: "Pump (High Pressure)",
    componentType: "Pump",
    sparePartDescription: "Pump (High Pressure) (Rep. 20)",
    oemPartNumber: "3706030",
    manufacturer: "PARKER",
    vendor: "Ausdraulics",
    assetManufacturer: "Motor: WEG, Pump: PARKER",
    assetModel: "F11 010 MB CV K 000 000 0",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Mill lube critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$4,286.59",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  // 4-LS-101 Primary Ball Mill Girth Gear Lube System
  {
    id: "CS-047",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Ball Mill Girth Gear Lube System",
    parentAsset: "4-LS-101",
    pidTag: "04-LS-101",
    componentName: "Grease Pump",
    componentType: "Pump",
    sparePartDescription: "Pneumatic Grease Pump",
    oemPartNumber: "239888",
    manufacturer: "Graco",
    vendor: "",
    assetManufacturer: "Graco",
    assetModel: "239888 K434021",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Girth gear lubrication",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$1,670.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  // 4-PU-102A Primary Mill Cyclone Feed Pump - Duty
  {
    id: "CS-048",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Mill Cyclone Feed Pump - Duty",
    parentAsset: "4-PU-102A",
    pidTag: "04-PU-102A",
    componentName: "Motor",
    componentType: "Motor",
    sparePartDescription: "Full Motor Assembly",
    oemPartNumber: "KTE50 W22M",
    manufacturer: "WEG",
    vendor: "NEWMAN",
    assetManufacturer: "Motor: WEG, Pump: Austral Pump",
    assetModel: "Motor: KTE50 W22M",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Cyclone feed critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$10,041.00",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-049",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Mill Cyclone Feed Pump - Duty",
    parentAsset: "4-PU-102A",
    pidTag: "04-PU-102A",
    componentName: "Bearing",
    componentType: "Bearing",
    sparePartDescription: "Bearing Assembly",
    oemPartNumber: "EAM005M / 1811005",
    manufacturer: "M&Q equipment",
    vendor: "CBC",
    assetManufacturer: "Motor: WEG, Pump: Austral Pump",
    assetModel: "EAM005M",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Cyclone feed critical",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-050",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Mill Cyclone Feed Pump - Duty",
    parentAsset: "4-PU-102A",
    pidTag: "04-PU-102A",
    componentName: "Belts",
    componentType: "Belt",
    sparePartDescription: "Drive Belts",
    oemPartNumber: "SPC 2360",
    manufacturer: "",
    vendor: "CBC",
    assetManufacturer: "Motor: WEG, Pump: Austral Pump",
    assetModel: "",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "2",
    maxQty: "4",
    qtyPerSystem: "4",
    unitPrice: "$43.40",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-051",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Mill Cyclone Feed Pump - Duty",
    parentAsset: "4-PU-102A",
    pidTag: "04-PU-102A",
    componentName: "Impeller",
    componentType: "Impeller",
    sparePartDescription: "Impeller",
    oemPartNumber: "F6147A05",
    manufacturer: "Austral Pump",
    vendor: "PPS",
    assetManufacturer: "Motor: WEG, Pump: Austral Pump",
    assetModel: "8/6 AH Metal",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item - frequent replacement",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$13,459.66",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-052",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Mill Cyclone Feed Pump - Duty",
    parentAsset: "4-PU-102A",
    pidTag: "04-PU-102A",
    componentName: "Volute Liner",
    componentType: "Liner",
    sparePartDescription: "Volute Liner",
    oemPartNumber: "F6110A05",
    manufacturer: "Austral Pump",
    vendor: "PPS",
    assetManufacturer: "Motor: WEG, Pump: Austral Pump",
    assetModel: "8/6 AH Metal",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$14,659.66",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-053",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Mill Cyclone Feed Pump - Duty",
    parentAsset: "4-PU-102A",
    pidTag: "04-PU-102A",
    componentName: "Frame Plate Liner Insert",
    componentType: "Liner",
    sparePartDescription: "Frame Plate Liner Insert",
    oemPartNumber: "F6041MA05",
    manufacturer: "Austral Pump",
    vendor: "PPS",
    assetManufacturer: "Motor: WEG, Pump: Austral Pump",
    assetModel: "8/6 AH Metal",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$3,424.29",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-054",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Mill Cyclone Feed Pump - Duty",
    parentAsset: "4-PU-102A",
    pidTag: "04-PU-102A",
    componentName: "Throat Bush",
    componentType: "Wear Items",
    sparePartDescription: "Throat Bush",
    oemPartNumber: "F6083A05",
    manufacturer: "Austral Pump",
    vendor: "PPS",
    assetManufacturer: "Motor: WEG, Pump: Austral Pump",
    assetModel: "8/6 AH Metal",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "0",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$6,893.22",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-055",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Mill Cyclone Feed Pump - Duty",
    parentAsset: "4-PU-102A",
    pidTag: "04-PU-102A",
    componentName: "Shaft Sleeve",
    componentType: "Wear Items",
    sparePartDescription: "Shaft Sleeve",
    oemPartNumber: "EAM076C21",
    manufacturer: "Austral Pump",
    vendor: "PPS",
    assetManufacturer: "Motor: WEG, Pump: Austral Pump",
    assetModel: "8/6 AH Metal",
    spareCriticality: "High",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "1",
    maxQty: "1",
    qtyPerSystem: "1",
    unitPrice: "$1,491.66",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-056",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Mill Cyclone Feed Pump - Duty",
    parentAsset: "4-PU-102A",
    pidTag: "04-PU-102A",
    componentName: "Lantern Restrictor",
    componentType: "Wear Items",
    sparePartDescription: "Lantern Restrictor",
    oemPartNumber: "E118C73",
    manufacturer: "Austral Pump",
    vendor: "PPS",
    assetManufacturer: "Motor: WEG, Pump: Austral Pump",
    assetModel: "8/6 AH Metal",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "1",
    maxQty: "2",
    qtyPerSystem: "1",
    unitPrice: "$905.67",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
  {
    id: "CS-057",
    area: "Grinding",
    subArea: "Comminution",
    system: "Primary Mill Cyclone Feed Pump - Duty",
    parentAsset: "4-PU-102A",
    pidTag: "04-PU-102A",
    componentName: "Packing",
    componentType: "Gland Packing",
    sparePartDescription: "Gland Packing Set",
    oemPartNumber: "E111Q20-set",
    manufacturer: "Austral Pump",
    vendor: "PPS",
    assetManufacturer: "Motor: WEG, Pump: Austral Pump",
    assetModel: "8/6 AH Metal",
    spareCriticality: "Medium",
    criticalitySource: "Confirmed",
    reasonCritical: "Wear item",
    minQty: "1",
    maxQty: "0",
    qtyPerSystem: "1",
    unitPrice: "$519.93",
    uom: "EA",
    notes: "",
    status: "Confirmed",
  },
];

// Component types for filtering
export const componentTypes = [
  "Motor",
  "Gearbox",
  "Pump",
  "Valve",
  "Roller",
  "Bearing",
  "Seal",
  "Coupling",
  "Belt",
  "Chain",
  "Sprocket",
  "Impeller",
  "Liner",
  "Screen",
  "Sensor",
  "Actuator",
  "Pulley",
  "Consumable",
  "Heater",
  "Injector",
  "Turbo",
  "Membrane",
  "Gear",
  "Filter",
  "Electrical",
  "Mechanical",
  "Wear Items",
  "Pillow Block",
  "Air Cooler",
  "Gland Packing",
  "Service Kit",
  "Wet End",
];

// Area codes for filtering
export const areaCodes = [
  "Grinding",
  "Leaching",
  "Adsorption",
  "Reagents",
  "Gold System",
  "Thickener",
  "Filter Press",
  "Water Services",
  "Power Generation",
];

// Criticality colors
export const criticalityColors: Record<string, string> = {
  "High": "bg-destructive/20 text-destructive",
  "Medium": "bg-amber-500/20 text-amber-700",
  "Low": "bg-muted text-muted-foreground",
  "": "",
};

// Status colors
export const statusColors: Record<string, string> = {
  "Provisional": "bg-amber-500/20 text-amber-700",
  "Confirmed": "bg-green-500/20 text-green-700",
  "TBC": "bg-muted text-muted-foreground",
};

// Criticality source colors
export const criticalitySourceColors: Record<string, string> = {
  "Confirmed": "bg-green-500/20 text-green-700",
  "Assumed": "bg-amber-500/20 text-amber-700",
  "": "",
};
