
-- Step 1: Reset all to not critical
UPDATE site_spares SET is_critical = false;

-- Step 2: Set HIGH criticality items to is_critical = true
-- EXCLUDING items that match LOW patterns (pump parts, motor parts, fittings, consumables, hose clamps)
UPDATE site_spares SET is_critical = true
WHERE (
  -- Motors
  description ILIKE '%motor%'
  OR description ILIKE '%gearbox%'
  OR description ILIKE '%gear box%'
  OR description ILIKE '%gear reducer%'
  OR description ILIKE '%speed reducer%'
  -- Pumps (generic + brands)
  OR description ILIKE '%pump%'
  OR description ILIKE '%pumpset%'
  OR description ILIKE '%warman%'
  OR description ILIKE '%metso%'
  OR description ILIKE '%weir%'
  OR description ILIKE '%krebs%'
  OR description ILIKE '%grundfos%'
  OR description ILIKE '%lowara%'
  OR description ILIKE '%keto%'
  OR description ILIKE '%wilden%'
  OR description ILIKE '%ebara%'
  OR description ILIKE '%matec%'
  -- Hoses
  OR description ILIKE '%hose%'
  OR description ILIKE '%tubing%'
  OR description ILIKE '%bellows%'
  -- Mill / Crusher
  OR description ILIKE '%pinion%'
  OR description ILIKE '%girth gear%'
  OR description ILIKE '%ball mill%'
  OR description ILIKE '%mill liner set%'
  OR description ILIKE '%mill drive%'
  OR description ILIKE '%trunnion%'
  OR description ILIKE '%ring gear%'
  OR description ILIKE '%crusher%'
  OR description ILIKE '%apron feeder%'
  OR description ILIKE '%vibrating feeder%'
  OR description ILIKE '%feeder drive%'
  -- PLC / Control
  OR description ILIKE '%plc%'
  OR description ILIKE '%hmi%'
  OR description ILIKE '%scada%'
  OR description ILIKE '%vfd%'
  OR description ILIKE '%vsd%'
  OR description ILIKE '%inverter%'
  OR description ILIKE '%soft starter%'
  OR description ILIKE '%allen bradley%'
  OR description ILIKE '%siemens s7%'
  -- Major Equipment
  OR description ILIKE '%agitator%'
  OR description ILIKE '%thickener%'
  OR description ILIKE '%filter press%'
  OR description ILIKE '%centrifuge%'
  OR description ILIKE '%cyclone%'
  OR description ILIKE '%hydrocyclone%'
  OR description ILIKE '%compressor%'
  OR description ILIKE '%blower%'
  OR description ILIKE '%concentrator%'
  OR description ILIKE '%knelson%'
  -- Electrical Critical
  OR description ILIKE '%transformer%'
  OR description ILIKE '%switchgear%'
  OR description ILIKE '%mcc panel%'
  OR description ILIKE '%mcc bucket%'
  OR description ILIKE '%generator%'
  OR description ILIKE '%genset%'
  OR description ILIKE '%ups %'
  -- OEM drives
  OR description ILIKE '%hydraulic drive%'
  OR description ILIKE '%kiln drive%'
  OR description ILIKE '%mixer%'
  OR description ILIKE '%mixing%'
  OR description ILIKE '%mill feed%'
)
-- EXCLUDE LOW items (pump parts, motor parts, fittings, consumables)
AND NOT (
  description ILIKE '%pump sleeve%'
  OR description ILIKE '%pump shaft sleeve%'
  OR description ILIKE '%pump clamp%'
  OR description ILIKE '%pump tubing%'
  OR description ILIKE '%pump parts%'
  OR description ILIKE '%pump rebuild kit%'
  OR description ILIKE '%pump repair kit%'
  OR description ILIKE '%pump kit%'
  OR description ILIKE '%pump casing%'
  OR description ILIKE '%pump component%'
  OR description ILIKE '%pump drive coupling%'
  OR description ILIKE '%pump shaft%'
  OR description ILIKE '%impeller%'
  OR description ILIKE '%volute%'
  OR description ILIKE '%wear ring%'
  OR description ILIKE '%throat bush%'
  OR description ILIKE '%suction liner%'
  OR description ILIKE '%frame plate%'
  OR description ILIKE '%stuffing box%'
  OR description ILIKE '%lantern ring%'
  OR description ILIKE '%flinger%'
  OR description ILIKE '%cotter%'
  OR description ILIKE '%flexibore%'
  OR description ILIKE '%motor hub%'
  OR description ILIKE '%motor starter%'
  OR description ILIKE '%motor circuit breaker%'
  OR description ILIKE '%motor protection%'
  OR description ILIKE '%motor protector%'
  OR description ILIKE '%motor coupling%'
  OR description ILIKE '%coupling insert%'
  OR description ILIKE '%coupling element%'
  OR description ILIKE '%filter element%'
  OR description ILIKE '%filter cartridge%'
  OR description ILIKE '%filter sock%'
  OR description ILIKE '%filter bag%'
  OR description ILIKE '%hose clamp%'
  OR description ILIKE '%hose barb%'
  OR description ILIKE '%hose fitting%'
  OR description ILIKE '%crusher liner%'
  OR description ILIKE '%crusher wear%'
  OR description ILIKE '%fan blade%'
  OR description ILIKE '%fan part%'
  OR description ILIKE '%hand pump%'
  OR description ILIKE '%oil transfer pump%'
  OR description ILIKE '%drum pump%'
  OR description ILIKE '%grease gun%'
  OR description ILIKE '%manual pump%'
  OR description ILIKE '%gland packing%'
  OR description ILIKE '%packing ring%'
  OR description ILIKE '%bolt%'
  OR description ILIKE '%nut %'
  OR description ILIKE '%washer%'
  OR description ILIKE '%screw%'
  OR description ILIKE '%clamp%'
  OR description ILIKE '%nipple%'
  OR description ILIKE '%elbow%'
  OR description ILIKE '%rubber cord%'
  OR description ILIKE '%pipe float%'
);
